### ISSUE TITLE
cannot open file 'ikuyadeu.r-2.3.6/R/session/init.R' when open R prompt

### ISSUE THREAD

**Issue by ddzhang3** [REditorSupport/vscode-R#1004]
Everything worked well before Feb, until suddenly today I open R prompt on the remote linux server.  The R prompt showed as following:

> Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/home/users/***/.vscode-server/extensions/ikuyadeu.r-**2.3.6**/R/session/init.R': No such file or directory

I suspected that the ikuyadeu.r has been updated automatically, as the following file exists:

> /home/users/***/.vscode-server/extensions/ikuyadeu.r-**2.3.8**/R/session/init.R

when I send R codes to R terminal, the 'r.RunSelection' command not found, even I have open the directory containing my R codes file.

What I felt strange was that, have the vscode-R changed the action of `typing R and click enter on the linux command line`?
By the way, I also wander how to fix this

**Comment by ddzhang3** [comment]
I have fixed it out.
But, I still want to know how vscode-R changes the default action of `typing R and click enter on the linux command line`

**Comment by renkun-ken** [comment]
Looks like you are starting R from terminal manually instead of using "R: Create R terminal"?

In this case, when vscode-R is upgraded, make sure that vscode-R is activated before starting an R session.
