### ISSUE TITLE
Editor not respecting rmarkdown with automatic formatting

### ISSUE THREAD

**Issue by py9mrg** [REditorSupport/vscode-R#1006]
Hello,

I'm not sure this isn't a vscode issue rather than vscode-R, but...

When I'm writing an rmarkdown file the text parts experience some automatic formatting. I mean within the editor, not the preview. For example, if I type `some text in *italic*` then the word "italic" is italicised. But it seems to be using a different flavour of markdown because when I use rmarkdown's subscript (e.g.  if I type `this is H~2~O`) it puts a strikethrough the 2 as though it's a different markdown (e.g. I see "this is H~2~O"). As far as I can tell the editor knows its an rmarkdown file because all the chunks are syntax highlighted correctly, and the chunk options are present.

Here's a more elaborate example:

![image](https://user-images.githubusercontent.com/12600721/154510206-66852821-e039-4e87-a75e-6a25bbda264e.png)

I disabled all other markdown extensions so I don't *think* it's a conflict with one of those, and they don't pick up .Rmd files anyway. Maybe something built into vscode? Everything else in vscode / vscode-r are in default settings (except I'm using radian but I think that's irrelevant).

It's not the end of the world because the knitted document comes out with subscripts correctly, but it can be a bit jarring as you're writing.

Is there a way to either get the editor to respect rmarkdown flavour instead of whatever other flavour it's using, when the file is an .Rmd, or is there a way to turn off this formatting entirely?

Thanks.

- OS: Windows 10
- VSCode Version: 1.64.2
- R Version: 4.1.2
- vscode-R version: 2.3.8

**Comment by renkun-ken** [comment]
I only see the formatting of `*hello*` but not `H~2~O`. What if you start vscode with all extensions disabled?

**Comment by py9mrg** [comment]
If I turn them all off then I get no formatting at all. I turned back on only this extension and I see the same problem of H~2~O with a strikethrough. Weird!
