### ISSUE TITLE
command for other extensions to execute interactive R code

### ISSUE THREAD

**Issue by jjallaire** [REditorSupport/vscode-R#1015]
We are working on a VS Code extension for Quarto (http://quarto.org) documents. Quarto is similar to R Markdown but has a multi-language architecture (so supports Jupyter, Knitr, and potentially other execution engines). 

For embedded languages, we currently delegate completion, hover, and signature tips to native language extensions (Python, vscode-R, LaTeX Workshop, etc.). We'd also like to be able to delegate code execution. We currently do that for Python using the Jupyter Interactive Console: https://github.com/quarto-dev/quarto-vscode#code-cells. We do this using the `jupyter.execSelectionInteractive` command, which was recently enhanced to take a string argument (https://github.com/microsoft/vscode-jupyter/pull/5053). 

It would be great if vscode-R has a similar command that allowed us to send R code to its interactive console from within `.qmd` files.

**Comment by renkun-ken** [comment]
Currently, we only provide send code to terminal via https://github.com/REditorSupport/vscode-R/blob/4ba871c7d18d63ffe4800aa37f6b3ce1e10ab9a8/src/rTerminal.ts#L229. I'd be glad to know if we need to add anything to make it work for you?

**Comment by jjallaire** [comment]
PR is here: https://github.com/REditorSupport/vscode-R/pull/1017

Let me know if this looks okay. If it does and once you release to the marketplace ping me back and I'll do another release of the Quarto extension that makes use of this command.

**Comment by eitsupi** [comment]
@jjallaire Now that the latest version of vscode-R is available in the marketplace, I think you can release a version that enables the ability to execute R code blocks in quarto.

I've been enjoying creating qmd files on VSCode the last few days and this is so great!
(For now I only need to temporarily change the file format from Quarto to Rmd to execute the code in the code block).
Thanks for all the work you guys do, it is much appreciated.
