### ISSUE TITLE
collaborate on embedded R code for quarto documents

### ISSUE THREAD

**Issue by jjallaire** [REditorSupport/vscode-R#1016]
The Quarto VS Code extension (https://marketplace.visualstudio.com/items?itemName=quarto.quarto) delegates completion, hover, and signature tips to other extensions for embedded code. This is working well for Python (via the Microsoft Python extension), LaTeX (via LaTeX workshop), as well as HTML, CSS, and JavaScript (via built-in extensions). However, we haven't yet gotten this to work correctly w/ vscode-R.

By way of additional background, we have two different methods of delegating editor features. 

- The first is based on the [lsp-embedded-request-forwarding](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-embedded-request-forwarding) example, which uses virtual content documents as the target for completion, etc. This method works well for built-in languages (e.g. JS, TS, HTML) however does not work for Python, LaTeX, and, R.

- The second method is based on creating a per-language temporary file which we target requests to. We open this document via `workspace.openTextDocument` here (https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-embedded-request-forwarding) and then execute intellisense commands against it. 
 
The second method works well for Python and LaTeX, however works unevenly with vscode-R. One potential clue is that explicit completion requests (e.g. triggered by `Ctrl+Space`) seem to work, but completions as you type don't (there is a crash of the R LSP that occurs in this case). Perhaps an issue w/ concurrent LSP requests? Here is what we see in the Debug Console:

```
Process 59219 spawned
[LiveSessionListener] started
Initialize session watcher
[deploySessionWatcher] extensionPath: /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8
Create sessionStatusBarItem
[startRequestWatcher] Starting
[startRequestWatcher] Done
Start language server for file:///var/folders/_7/h09fb1n572g4071vt5d8ks1r0000gn/T/tmp-59171-rwlcCn6vvt1P/r/intellisense.r
Process 59297 spawned
R process connected
Start language server for file:///var/folders/_7/h09fb1n572g4071vt5d8ks1r0000gn/T/tmp-59171-rwlcCn6vvt1P/r/intellisense.r
Process 59393 spawned
Start language server for file:///var/folders/_7/h09fb1n572g4071vt5d8ks1r0000gn/T/tmp-59171-rwlcCn6vvt1P/r/intellisense.r
Process 59434 spawned
R process connected
Process 59297 exited
R process disconnected
R process error: This socket has been ended by the other party
R process error: This socket has been ended by the other party
R process error: This socket has been ended by the other party
R process error: This socket has been ended by the other party
R process connected
rejected promise not handled within 1 second: Error: This socket has been ended by the other party
stack trace: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:456:14)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854414
	at new Promise (<anonymous>)
	at c.write (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854332)
	at h.doWrite (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843916)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843811
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
rejected promise not handled within 1 second: Error: This socket has been ended by the other party
stack trace: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:456:14)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854414
	at new Promise (<anonymous>)
	at c.write (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854332)
	at h.doWrite (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843916)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843811
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
rejected promise not handled within 1 second: Error: This socket has been ended by the other party
stack trace: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:456:14)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854414
	at new Promise (<anonymous>)
	at c.write (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854332)
	at h.doWrite (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843916)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843811
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
rejected promise not handled within 1 second: Error: This socket has been ended by the other party
stack trace: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:456:14)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854414
	at new Promise (<anonymous>)
	at c.write (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854332)
	at h.doWrite (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843916)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843811
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at process.callbackTrampoline (internal/async_hooks.js:131:14)
R process error: read ECONNRESET
Process 59393 exited
rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at Socket.write (internal/streams/writable.js:292:11)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854414
	at new Promise (<anonymous>)
	at c.write (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1854332)
	at h.doWrite (/Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843916)
	at /Users/jjallaire/.vscode/extensions/ikuyadeu.r-2.3.8/dist/extension.js:2:1843811
```

It looks like the R language server is stopping and starting a few times. This might be caused by our opening and closing the temporary document when it changes? We are happy to make changes to the way we handle delegation to get this to work better if that ends up being the solution. Let us know if you are able to experiment and have any speculation about what is going wrong.

One other note: for hover we are sending requests but don't seem to get the same content as when using vscode-R in an R script (hover just shows the name of the symbol and the package its in rather than full help).

**Comment by jjallaire** [comment]
I discovered that the issue is indeed the opening and closing of the temporary R document when it changes (which causes the LSP to load and unload). I can definitely work around this. Let me see what I can do and then will report back.

**Comment by renkun-ken** [comment]
Looks like the language client just opens and closes the document, sending requests and closing the socket before the language server could handle it.

**Comment by jjallaire** [comment]
It looks like the problem is that calling the `vscode.executeHoverProvider` command returns the first hover, but doesn't see the one from the LSP. If I set `r.helpPanel.enableHoverLinks: false` then I do see the hovers as expected. I wonder if it would be reasonable for the Quarto extension to default that setting to `false` when it is loaded?

**Comment by jjallaire** [comment]
I could also see if I can default that to `false` for _only_ Quarto docs. Will report back on what I find soon.

**Comment by renkun-ken** [comment]
From the documentation, 

> `vscode.executeHoverProvider` - Execute all hover providers.
> 
>     uri - Uri of a text document
>     position - A position in a text document
>     (returns) - A promise that resolves to an array of Hover-instances.

Looks like it should resolve the results from all hover providers registered.

**Comment by jjallaire** [comment]
You are correct! There were actually two Hover instances returned (am now showing the second one which is the one from the LSP)
