### ISSUE TITLE
Show Environment Package Stack

### ISSUE THREAD

**Issue by kalaschnik** [REditorSupport/vscode-R#1018]
I know there is `View(globalenv())` or `R: Preview Environment` from the command pallette.
Is there any way to show the loaded packages in the environment; I am referring to this fly-out from R Studio:
<img src="https://user-images.githubusercontent.com/9831678/156040889-079749a7-5aa7-4161-b468-176783b1ac34.png" width="256">

**Comment by renkun-ken** [comment]
It is perfectly possible. We could output `search()` in a task callback and present it in the sidebar, just like the workspace viewer.
