### ISSUE TITLE
Httpgd plot viewer not working with LiveShare

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#1023]
Currently, httpgd plot viewer does not seems to work with LiveShare. Not sure if it is possible to support this.

**Comment by renkun-ken** [comment]
@ElianHugh do you think if there is a handy way to forward a httpgd plot to the client session?

**Comment by ElianHugh** [comment]
Hmm, this was definitely working before. It may be there was a regression at some point.  I'll have a look to see where the issue is

**Comment by renkun-ken** [comment]
`httpgd::hgd_browse()` that creates a WebView works with LiveShare.

I tried rolling back to previous versions but the built-in httpgd plot viewer never worked.

**Comment by renkun-ken** [comment]
However, if I start debugging and join a LiveShare session, then the httpgd plot viewer works.

**Comment by renkun-ken** [comment]
Looks like all features that depend on a http server on localhost do not work as we don't have a mechanism of port forwarding from host to guest, then visiting the URL by httpgd plot viewer and all browser requests simply get nothing.

**Comment by renkun-ken** [comment]
When I manually use "Share Server" to share the localhost url, then the viewer works as supposed.

**Comment by renkun-ken** [comment]
Just notice that I didn't enable "Auto forward ports. Now just httpgd does not work as we don't share port before notifying guest the httpgd request.

**Comment by ElianHugh** [comment]
Thanks for digging into that. I suspect we didn't run into this issue because of it working during debugging. As an aside, "auto forward ports" was (from memory) untoggled due to security concerns
