### ISSUE TITLE
Support for new shorthand function syntax

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#1024]
As of v4.1.0 R has a new shorthand function syntax:

```
x <- \(y) y + 1
x(5)
```

It would be good if we could support this in terms of letting vscodeR know that objects created in this way are functions (i.e. for syntax highlighting etc)

**Comment by renkun-ken** [comment]
It is already supported in languageserver via https://github.com/REditorSupport/languageserver/pull/428.

**Comment by renkun-ken** [comment]
The syntax highlighting support is still missing. Are you interested in filing a PR?

**Comment by gowerc** [comment]
I'm happy to attempt one but realistically it wont be for 3 weeks due to busyness :(

**Comment by gowerc** [comment]
ty !
