### ISSUE TITLE
R Help Panel commands in command palettes

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#1035]
Most commands of category `R Help Panel` in `packages.json` are used to provide functionality of the little buttons on the  R Help Viewer nodes. However, they also appear in the command palettes as shown below:

![image](https://user-images.githubusercontent.com/4662568/157617096-e07dce60-5c00-4294-8da3-2b6cbcbcb92b.png)

User might expect some of these commands to work, e.g. `Install multiple packages` but when they are chosen, nothing happens.

Is there a good way to make such commands work from the command palettes?

Could we hide those commands from the command palettes that should only appear as little buttons?

**Comment by Fred-Wu** [comment]
For the R help panel, may I ask how to adjust font size as well?

**Comment by ManuelHentschel** [comment]
> Is there a good way to make such commands work from the command palettes?
> 

Yes, for example most of the R plot related commands work from the command palette, as well. Implementing something similar for the help related commands shouldn't be too hard.

> Could we hide those commands from the command palettes that should only appear as little buttons?

Yes that's also possible in `package.json`, I'll have to look up the details, though.

I can take care of this, hopefully soon.

**Comment by renkun-ken** [comment]
unstale

**Comment by renkun-ken** [comment]
<https://code.visualstudio.com/api/extension-guides/command#controlling-when-a-command-shows-up-in-the-command-palette> should be helpful.
