### ISSUE TITLE
Option to enable/disable "prompt to install `languageserver`"

### ISSUE THREAD

**Issue by mcanouil** [REditorSupport/vscode-R#1037]
**Is your feature request related to a problem? Please describe.**
The feature from #965 asks to install "languageserver" when switching projects.
(I am using a lot of projects on remote containers (with R installed) and a shared "home", it is annoying to have to discard the prompt on every projects not really using R and get spammed by the prompt until you do install the package.)

**Describe the solution you'd like**
In the extension settings, an option to enable (default) / disable #965

---

PS: how packages are installed by `vscode-R` in a `renv` setup?
EDIT: I found the answer https://github.com/REditorSupport/vscode-R/blob/master/src/util.ts#L511
It uses either `base::install.packages` or `renv::install.packages` in a `renv` project with an `.Rprofile` (if the R process is spawned properly at project's root).

**Comment by mcanouil** [comment]
Related to this, maybe a similar check for `httpg`?

**Comment by mcanouil** [comment]
https://github.com/REditorSupport/vscode-R/blob/dc9b33a5f2922be6ab2108b7ad2f900b9ddcac91/src/languageService.ts#L28-L32

I am assuming this could be replaced by the following:

``` ts
    const installed = await isRPkgIntalled(
      'languageserver', cwd, config.get<boolean>('lsp.checkLanguageServerInstall'),
      'R package {languageserver} is required to enable R language service features such as code completion, function signature, find references, etc. Do you want to install it?',
      'You may need to reopen an R file to start the language service after the package is installed.'
    );
```

With `r.lsp.checkLanguageServerInstall`, the new boolean setting to add to [`package.json`](package.json)

**Comment by ElianHugh** [comment]
Just to add to this, we can make use of the "Don't show again" design pattern

**Comment by mcanouil** [comment]
The only downside with this feature is it cannot be reset easily by user (yet) https://github.com/Microsoft/vscode/issues/24815
