### ISSUE TITLE
R markdown code chunk not executable after saving

### ISSUE THREAD

**Issue by aachener** [REditorSupport/vscode-R#1043]
**Describe the bug**

The code chunk works perfectly before I named and saved the file. The following code, without naming and saving, can be linted and produce the right plot in vs code plot pane. But the same chunk will be no longer executable, and not linted, after I gave the file a name (such as test.Rmd) and saved the file.

**To Reproduce**

1. press ctrl+N, choose file type as .Rmd
2. type in the following code 
```{r}
test <- rnorm(1000)
plot(test)
```

3. the code chunk was linted and if you run the code chunk, it works perfectly with a plot pane shows up
4. save the file with name "test.Rmd"
5. the lint disappeared,  and the code chunk was no longer executable.

## Do you want to fix by self? (We hope your help!)

 No

**Expected behavior**
I would like the code executable after the .Rmd file is named and saved.

**Screenshots**
when unsaved, everything works fine.

![problem1-1](https://user-images.githubusercontent.com/56262926/158040440-135a589b-b5dc-42b9-85a6-c245eead2481.png)

after naming and saving, the code chunk is not executable

![problem2](https://user-images.githubusercontent.com/56262926/158040443-adeeab48-c1f9-43ce-92db-a02fab9aa992.png)

**Environment (please complete the following information):**

- OS: Windows 10
- VSCode Version: 1.65.2
- R Version: 4.1.2
- vscode-R version: 2.4.0

**additional information**

This is my first time raising an issue, please let me know if there is anything improper in my request.

**Comment by renkun-ken** [comment]
Looks like the file language is misspecified. What if you choose `rmd` language explicitly?

**Comment by aachener** [comment]
Mr. Ren, thanks for your reply! And I love your book `Learning R Programming`.

I did specified the file language as `r markdown`, and vs code automatically assign the file name `untitled.rmd` to the file. I made another screenshot to show my problem as following. 

The left editor pane shows the file named as `test.Rmd`, the middle pane is file `Untitled` with no suffix, the right pane is what I did as in the original post: Ctrl +N, click "select a language", chose `r markdown`, and vs code automatically name the file as`Untitled-2.Rmd`. And again, once I saved the file in the right pane, the linting and executability disapeared.

![problem3](https://user-images.githubusercontent.com/56262926/158048955-d0738aed-3016-4632-aec5-d26effafe453.png)


I do think there may be some configuration problems on my side, but I searched the whole web without finding a solution. Please help me.

Thanks!


> Looks like the file language is misspecified. What if you choose `rmd` language explicitly?

**Comment by eitsupi** [comment]
Is there anything set in settings.json regarding RMarkdown?

**Comment by aachener** [comment]
Thanks eitsupi. Yes, there are.  I made a minor change and solve the problem partly.

I think the relative settings are as following:

```
{
    "files.associations": {
        "*.rmd": "markdown"
    },
    "[markdown]": {
        "editor.defaultFormatter": "yzhang.markdown-all-in-one"
    "markdown-preview-enhanced.pandocPath": "C:\\Program Files\\Pandoc\\pandoc.exe",
    "r.rmarkdown.chunkBackgroundColor": "rgba(128, 128, 128, 0.1)",
    "r.rmarkdown.knit.defaults.knitWorkingDirectory": "workspace root",
    "r.rmarkdown.knit.openOutputFile": true,
}
```

I changed the above settings into this:

```
{
    "files.associations": {
        "*.rmd": "rmarkdown"  # I changed it to "rmarkdown"
    },
    "[markdown]": {
        "editor.defaultFormatter": "yzhang.markdown-all-in-one"
    "markdown-preview-enhanced.pandocPath": "C:\\Program Files\\Pandoc\\pandoc.exe",
    "r.rmarkdown.chunkBackgroundColor": "rgba(128, 128, 128, 0.1)",
    "r.rmarkdown.knit.defaults.knitWorkingDirectory": "workspace root",
    "r.rmarkdown.knit.openOutputFile": true,
}
```

And some good things happened that I can run the code chunk after naming and saving the `.Rmd` file! as following screenshot shows.

![problem4](https://user-images.githubusercontent.com/56262926/158050558-13f4346f-7074-4076-822f-9ce08a483ed9.png)


However, another problem still exists. After I save and close the editor pane and reopen the same rmarkdown file, the linting and executability are gone, as following.

![problem5](https://user-images.githubusercontent.com/56262926/158050567-00e6cc0d-15ad-4a0a-9c24-11c5592310a0.png)

**Comment by eitsupi** [comment]
> ```json
>     "files.associations": {
>         "*.rmd": "markdown"
>     },
> ```

> ```json
>     "files.associations": {
>         "*.rmd": "rmarkdown"  # I changed it to "rmarkdown"
>     },
> ```

Undoubtedly the problem is these lines. These lines are unnecessary.

**Comment by aachener** [comment]
Confirmed! It worked on my PC. 

Actually I did not touch the .jason files, I have no idea where they came from....

Many thanks!

**Comment by eitsupi** [comment]
The problem was caused by opening an R Markdown file as a Markdown file.
If you remove the offending setting, the default setting will be applied and it should work as normal.

**Comment by tomlue** [comment]
Rmd rendering and codelens only works for me with the below 1 line settings.json. 
```json
{ "files.associations": {  "*.Rmd":"rmd"  }}
```
Rendering/odelens does not work with empty settings.json. Rmd associates w/ `R Markdown` in both cases.  This setting seems to fix everything, maybe add it to docs?

**Comment by renkun-ken** [comment]
@tomule https://github.com/REditorSupport/vscode-R/wiki/R-Markdown#file-association is added to the wiki.
