### ISSUE TITLE
R Markdown: New Draft` does not work for some templates

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#1044]
CC @renkun-ken 

I've found that `R Markdown: New Draft` does not work for some templates.

## Reprex

1. `install.packages("ghclass")`
1. Launch `R Markdown: New Draft`
1. Type `ghclass`
1. See if either "Reviewer feedback form, {ghclass}" or "Author rating form, {ghclass}" works: cannot make any draft out of them

**Comment by renkun-ken** [comment]
We use `rmarkdown::draft(...)` to create new drafts.

In this case, it looks like `ghclass` does not comply with rmarkdown template.

```
> rmarkdown::draft(file = "test-ghclass.Rmd", template = "review", package = "ghclass")                                          
Error in rmarkdown::draft(file = "test-ghclass.Rmd", template = "review",  : 
  template.yaml must contain name and description fields
Backtrace:
1: stop("template.yaml must contain name and description fields")
2: rmarkdown::draft(file = "test-ghclass.Rmd", template = "review",
```

**Comment by renkun-ken** [comment]
I tried adding a `description` field to `template.yaml` and it works.

In RStudio, looks like it does not rely on `rmarkdown::draft()` but directly uses `skeleton/skeleton.Rmd` instead.

**Comment by jooyoungseo** [comment]
Aw, I see. Thank you so much for investigating this issue, @renkun-ken! I have seen that you opened an issue in the ghclass repo. Thank you very much!

**Comment by renkun-ken** [comment]
unstale
