### ISSUE TITLE
Session watcher doesn't work for self-managed environment

### ISSUE THREAD

**Issue by elliothershberg** [REditorSupport/vscode-R#1047]
**Describe the bug**

I am using the vscode-r extension in combination with the Remote-SSH extension to develop on a university cluster.
I initially connect to the login node, which shouldn't be used for anything compute intensive.
Unfortunately, using `R: create R terminal` starts the terminal on the login node as well (but the session watcher does work!).

To get around this, I'm trying to use a self-managed R terminal.
I've set `Always Use Active Terminal` to true, and added the necessary snippet to my `.Rprofile`.
The session watcher still doesn't work, and `.vsc` is undefined, so something has gone wrong

## Do you want to fix by self? (We hope your help!)

Yes! I'd like to fix this, but would appreciate recommendations on what to check in order to make progress.

**Comment by renkun-ken** [comment]
See https://github.com/REditorSupport/vscode-R/issues/1019#issuecomment-1056616224.

It is a known limitation at the moment.

**Comment by renkun-ken** [comment]
On remote scenario, the session watcher relies on direct filesystem access to create file watcher on several files that will be updated by interactive user R session. On each user input, the R session file is updated to reflect the latest information, and the file watcher notifies the file change and let session watcher read the file and present the latest information.

If the remote vscode-R extension cannot access the files created by the R session, e.g. vscode-R is running on login node, yet R session is running on compute node, then there is no way to communicate between R session and sessio watcher at the moment.
