### ISSUE TITLE
unexpected numeric constant in "00~library(data.table)01"

### ISSUE THREAD

**Issue by rrchai** [REditorSupport/vscode-R#1051]
I just followed the [instruction](https://code.visualstudio.com/docs/languages/r) and install the `languageserver`, as well as its requirements.

When I hit "cmd + Enter" (mac) on `library(data.table)`,  I get this error:
```
unexpected numeric constant in "00~library(data.table)01"
```

Basically, all lines do not work with similar errors. I am not sure if it is because of languageserver or other settings in vscode.

**Comment by rrchai** [comment]
yes, I added these two lines on my settings, but still not worked:
```
"r.bracketedPaste": true,
"r.rterm.linux": "/Users/rchai/opt/anaconda3/bin/radian",
```

```
which pip
-> /Users/rchai/opt/anaconda3/bin/pip
pip list | grep 'radian'
-> radian                                            0.6.0
```

**Comment by katiepress** [comment]
I have a similar problem I think? I'm on an M1 Mac, have the latest version of R (4.2), have installed the languages package, r.bracketedPaste is toggled on. 

If I use the console "R interactive", the code evaluates just fine. However, if I have a regular .r file with the same code in the editor, it doesn't matter if I click the arrow to run the code line or if I hit command-enter, I still get this weird error. The red box below is where I tried to use command enter, and the yellow box is where I tried using the arrow button with that line of code selected. I tried to use radian, but it keeps going to an "R interactive" terminal. Even if I kill it and open up a radian terminal it will pop up with a new R interactive. 

![Screen Shot 2022-04-26 at 3 12 08 PM](https://user-images.githubusercontent.com/44142983/165384481-19bc4c01-508a-4ad2-ad06-0c7cf6f0a36d.png)

**Comment by renkun-ken** [comment]
@katiepress Looks like you are running official `R` console instead of `radian`.

To make "R: Create R terminal" start `radian`, you need to know the path to `radian` and set it in the vscode settings `r.rterm.*`.

**Comment by rrchai** [comment]
ugh, I used wrong OS for `r.rterm.*`. Solved my issue by adding these two lines to `setting.json`:

```json
"r.bracketedPaste": true,
"r.rterm.mac": "/Users/rchai/opt/anaconda3/bin/radian",
```
Thanks for the help!

**Comment by bdoyisca** [comment]
I am having the same problem and I followed every part of set up but I am still getting this

> 00~h <- c(1, 2, 3, 4, 5, 6)
Error in 0 ~ h <- c(1, 2, 3, 4, 5, 6) : 
  target of assignment expands to non-language object
> m <- c("A", "B", "C", "D", "E", "F")
> barplot(h,
+     names.arg = m, xlab = "X", ylab = "Y",
+     col = "#00cec9", main = "Chart", border = "#fdcb6e"
+ )01~
Error: unexpected numeric constant in:
"    col = "#00cec9", main = "Chart", border = "#fdcb6e"
)01"

and it runs perfectly if I copy the codes and paste directly in the r terminal

What am I supposed to do now

**Comment by DrLuong** [comment]
Hi all

My vscode had same situation.  I added:

"r.bracketedPaste": true,
"r.rterm.mac": "/Users/rchai/opt/anaconda3/bin/radian"
<img width="1255" alt="Screenshot 2023-07-07 at 20 50 01" src="https://github.com/REditorSupport/vscode-R/assets/86107838/5ed00430-fea1-472f-aff6-328f59d08533">


Pls, help me

**Comment by jfulponi** [comment]
In my case, installing `radian` again did the trick. 

In the terminal, just put:

```
pip install -U radian
```

And I didn't even have to reload vscode. Hope this helps someone.

**Comment by OrangeAoo** [comment]
> You can try to disable Bracketed Paste in settings, which works for me
Gracias - this did the trick for me :p
