### ISSUE TITLE
Consider becoming a verified VS Code extension publisher

### ISSUE THREAD

**Issue by gregvanl** [REditorSupport/vscode-R#1052]
Verifying your publisher will demonstrate your authenticity and add a verified badge to your extensions.

You can learn about the process at https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

**Comment by renkun-ken** [comment]
Thanks for the information!

Looks like it requires an eligible domain of some kind yet we don't have one at the moment.

Also, we have an open issue #690  about changing the publisher name (not necessarily publisherId) but does not hear anything from the vscode marktetplace yet. Do you have any idea how we could do it?

**Comment by isidorn** [comment]
Hi my name is Isidor and I am a PM on the VS Code side 👋 

Then I suggest that you become verified once you get an eligible domain. Or you could contact https://www.r-project.org/ and ask them if they would like to partner with you. They could officially support your extension, and if they want they can help you get verified using their domain.

For the publisher name change I will comment on the other issue.

**Comment by mcanouil** [comment]
Hi,

probably better to partner with the [R Consortium](https://www.r-consortium.org/) as a "project" (https://www.r-consortium.org/projects).
This could also allow vscode-r to get fundings if needed.

**Comment by mcanouil** [comment]
The R Consortium just announced:

> ISC Call for Proposals is now open! We are looking to provide grants for technical projects that will have a significant impact on the R Community. Deadline is May 1, 2022. Apply now!
> https://www.r-consortium.org/blog/2022/04/01/isc-call-for-proposals-2
