### ISSUE TITLE
  Could not find tools necessary to compile a package Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

### ISSUE THREAD

**Issue by zdlspace0528** [REditorSupport/vscode-R#1059]
When I install R packages in vscode radian,it always gets an error,for example,

r$> remotes::install_github("REditorSupport/languageserver")
Downloading GitHub repo REditorSupport/languageserver@HEAD
Error: Failed to install 'languageserver' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

but when I run the same codes in iterm2 radian,it can install the package successfully.
<img width="922" alt="截屏2022-04-04 06 32 16" src="https://user-images.githubusercontent.com/75175622/161453449-6766e060-2aff-4b84-974e-5ebc820a2758.png">

**Environment (please complete the following information):**

- OS: [macOS M1]
- VSCode Version: [1.66.0]
- R Version: [4.1.3]
- vscode-R version: [2.4.0]

**Additional context**

**Comment by renkun-ken** [comment]
Does it still occur?
