### ISSUE TITLE
Code/Text in View Window can't be copied

### ISSUE THREAD

**Issue by XiangyunHuang** [REditorSupport/vscode-R#1062]
**Describe the bug**
Text/Code in View Window can't be copied and pasted.

**To Reproduce**

A [personal website](https://github.com/rbind/xiangyun) built on [blogdown](https://github.com/rstudio/blogdown), then in R Terminal, and run

```r
blogdown::serve_site()
```

## Do you want to fix by self? (We hope your help!)

No

**Expected behavior**

We can Copy text/code From View Window instead of R Help View Window and Paste in Source Code Document

**Screenshots**

![](https://user-images.githubusercontent.com/12031874/159469997-69f34770-3d89-428d-9cb1-cca8199ab7d2.png)

**Environment (please complete the following information):**

- OS: macOS
- VSCode Version: 1.65.2
- R Version: 4.1.3
- vscode-R version: v2.4.0

```
版本: 1.65.2
提交: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
日期: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

**Additional context**
no

**Comment by renkun-ken** [comment]
Thanks for reporting. I can reproduce it.

Looks like it is reported at https://github.com/platformio/platformio-vscode-ide/commit/a1acff8436b4e12dd947141afceb0986e9c9528b and https://github.com/platformio/platformio-vscode-ide/commit/a1acff8436b4e12dd947141afceb0986e9c9528b fixed it. Let me try if it works.

**Comment by renkun-ken** [comment]
There are some sugguested fixes:

* https://github.com/tamuratak/LaTeX-Workshop/commit/e204b0848d0f62cb13175e8e804566e5e1b318b7
* https://github.com/tamuratak/LaTeX-Workshop/commit/e204b0848d0f62cb13175e8e804566e5e1b318b7

I tried but it does not seem to work in our case where we cannot control the content of the `iframe`.
