### ISSUE TITLE
Feature request: Allow jump to function to open in different panel

### ISSUE THREAD

**Issue by joelnitta** [REditorSupport/vscode-R#1063]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I command-click on a function name to jump to its source code, and the source code pops up in the same panel **on top of the code I was working on.**

**Describe the solution you'd like**
I'd like the source code to show up in a side panel.

**Describe alternatives you've considered**
Manually clicking on the tab and selecting "split right".

**Additional context**

<img width="1710" alt="request" src="https://user-images.githubusercontent.com/13459362/161483289-1688801b-ebf0-4fb5-8c69-8137490acb59.png">

**Comment by renkun-ken** [comment]
Does "Peak definition" work for you?

<img width="530" alt="image" src="https://user-images.githubusercontent.com/4662568/161483979-6c477b4b-adbb-4ed1-bc43-73bc9074ac12.png">

Also, you could use option+cmd+click to open the definition side-by-side.

**Comment by joelnitta** [comment]
option+cmd+click command click does exactly what I want! Thank you!
