### ISSUE TITLE
Autocompletion of session variables and suggestion in vscode-Jupyter

### ISSUE THREAD

**Issue by olivedv** [REditorSupport/vscode-R#1074]
**Describe the bug**
I have run R scripts in vscode-Jupyter for some time. Recently after upgrading the extensions, there is somthing wrong with it. The autocompletion suggestions and the names of variables defined previously disappear in `.ipynb` files even though the appropriate IRkernel have been installed in Jupyter. But it still works well in `.R` files. 

**To Reproduce**

1. Create a `.ipynb`/`.R` file
2. Type some R scripts  such as `a <- c(1, 2)`
3. Start new line with `a` - in the `.R` file you'll see variable suggestions, in `.ipynb` you won't.

**Setting.json**

```jsonc

"r.rterm.windows": "C:\\Users\\myusername\\anaconda3\\Scripts\\radian.exe",
"r.rpath.windows": "C:\\Program Files\\R\\R-4.1.3\\bin\\x64\\R.exe"
"r.bracketedPaste": true,
"r.sessionWatcher": true

```

**Screenshot**

Autocompletion doesn't see the session variables and suggestions in `.ipynb`:
<img src="https://user-images.githubusercontent.com/66551904/162892379-010cbad8-d3b9-4bd1-8d32-0879447b39be.png" width="600" height="300" /><br/>
But autocompletion works in `.R`:
<img src="https://user-images.githubusercontent.com/66551904/162895610-c106f3c8-d694-4c2d-96b2-f4a5d7c49a1f.png" width="600" height="400" /><br/>
The log of Extension Host:
<img src="https://user-images.githubusercontent.com/66551904/162896744-e3faff90-c27e-4c77-88c6-0be5be3e3296.png" width="600" height="600" /><br/>

**Environment:**

- OS: Windows 10 x64 (build 22000)
- VSCode Version: 1.66.1
- R Version: 4.1.3 (2022-03-10)
- vscode-R version: v2.4.0
- vscode-Jupyter version: v2022.3.1000901801

**Comment by olivedv** [comment]
> ```r
> ```r
> remotes::install_github("REditorSupport/languageserver")
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

**Comment by olivedv** [comment]
Yes, I have tried the latest version/build of them. It doesn't work.

**Comment by renkun-ken** [comment]
I could reproduce the problem.

It looks like the language server only receives document open/save/change events. It never receives anything else such as completion and hover requests. Looks like these providers are somehow not registered or the notebook does not redirect those requests to R language server.

**Comment by olivedv** [comment]
Thanks for your help.
The bug is likely from a change in VS code core. I just tried an old version of vscode. It worked fine.

<img src="https://user-images.githubusercontent.com/66551904/163088677-ea4761bf-293c-4469-a379-9ba2c224282f.png" width="50%" ></img>

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

But I still would like to use the latest version of vscode. Hope someone could fix it.

**Comment by renkun-ken** [comment]
Thanks for confirming it worked in older vscode versions. Looks like I need to change something in the language client or server to adapt to the latest changes in notebooks api which is broken in this case.

**Comment by rchiodo** [comment]
We had to make a similar change for python in the Jupyter extension here:
https://github.com/microsoft/vscode-jupyter/commit/362ca2fd842adfe5ce8e78686d5874dd0e085de5

**Comment by renkun-ken** [comment]
@rchiodo Thanks for the information!

I take a look at the fix. It looks like we are just missing a document filter like the following:

```typescript
    { language: 'r', notebookType: 'jupyter-notebook' },
```

Maybe it is a stupid question, but I'm wondering what should be done to use `notebookType` here? Should I depend on proposed api or something?

**Comment by renkun-ken** [comment]
Looks like I need to depend on a newer [vscode.d.ts](https://github.com/microsoft/vscode/commit/afcebfa6ae642564d43165e1e72375361e2338ed#diff-0a75aed19c118603eb96332bc0b9c2d7867f4182346d16d18b7fc31b6ceeb321R2077) to include this.

**Comment by renkun-ken** [comment]
Also there is a mention of this at https://code.visualstudio.com/updates/v1_66#_notebookaware-document-selectors.

**Comment by renkun-ken** [comment]
I tried to make the fix at https://github.com/REditorSupport/vscode-R/compare/jupyter-notebook but it does not build with the following errors at https://github.com/REditorSupport/vscode-R/runs/6017891653?check_suite_focus=true:

```
ERROR in /github/workspace/src/languageService.ts
./src/languageService.ts 193:29-61
[tsl] ERROR in /github/workspace/src/languageService.ts(193,30)
      TS2322: Type '{ language: string; notebookType: string; pattern: string; }' is not assignable to type 'DocumentFilter'.
  Object literal may only specify known properties, and 'notebookType' does not exist in type 'DocumentFilter'.
```

If I debug anyway with errors, the language providers seem to work for notebooks.

**Comment by rchiodo** [comment]
Are you updating your vscode.d.ts in your build folder? We use this command to do so:

```
vscode-dts main
```

This should download the vscode.d.ts that is the most up to date. The latest one does have the 'notebookType' in the DocumentFilter type.

**Comment by renkun-ken** [comment]
Yes, `vscode.d.ts` contains a definition of `DocumentFilter` but we import it from `vscode-languageclient/node`, otherwise `LanguageClientOptions.documentSelector` does not seem to accept it.

Am I missing something?

**Comment by renkun-ken** [comment]
Looks like I need to use a newer version of the language client`"vscode-languageclient": "^8.0.0-next.14"`.

**Comment by renkun-ken** [comment]
Now the language server roughly works with notebooks but errors occur when I edit cells:

```

[2022-04-18 15:08:52.807] internal error: Error: key not found
Call: self$workspace$documents$get(uri)
Stack trace:
1: self$workspace$documents$get(uri)
2: dispatch(self, id, params)

[2022-04-18 15:08:52.808] token: {
  "full_token": "read.csv",
  "right_token": ".csv",
  "package": null,
  "accessor": "",
  "token": "read.csv"
}

[2022-04-18 15:08:52.809] deliver:  ["Response", "Response", "Message", "R6"]

[Error - 3:08:52 PM] Request textDocument/hover failed.
  Message: Error: key not found
Call: self$workspace$documents$get(uri)
Stack trace:
1: self$workspace$documents$get(uri)
2: dispatch(self, id, params)

  Code: -32603 
```

It looks like the document open requests are not sent before other requests.

**Comment by rchiodo** [comment]
I don't think so as I don't see this for Python. If you upgrade the language client the API is different I think though. @dbaumer would be a good person to ask. He's in the middle of changing the language client API to work better for notebooks, so maybe it's too early to switch the language client module?

**Comment by pehkawn** [comment]
I'm been having this issue for some time. Have there been any new developments?

**Comment by carbocation** [comment]
As far as I can see, this is still happening with VS Code 1.73.0:

```
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:33:40.745Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```
