### ISSUE TITLE
`no_tab_linter` error in one R script, but not in others with unequal indent. 

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#1079]
I was reading someone else's codes, and in one of the scripts, a linter error appeared in the entire script and suggested not to use tab. The auto indent space is 4. 

So I started to test it with the following codes in 3 files. 

Simple test on one script with lots of `no_tab_linter` error.
<img width="158" alt="image" src="https://user-images.githubusercontent.com/4111978/163582023-26c2aaa8-b4a1-4c20-a5b5-35ef5301b7ab.png">

In another file without `no_tab_linter` error, and the auto indent space is 2. 
<img width="158" alt="image" src="https://user-images.githubusercontent.com/4111978/163582125-4db27a5f-c146-466b-85a1-c01227a1a9cd.png">

I also used a completely new script,  and this time the auto indent space is 4 without linter error. 
<img width="158" alt="image" src="https://user-images.githubusercontent.com/4111978/163582172-6926b6ff-d8fb-4026-a903-889a8af860d4.png">

This is the first time I encounter this. What could be the possible reason?

**Comment by eitsupi** [comment]
Could it be a problem of the `lintr` package?
https://github.com/r-lib/lintr#available-linters

**Comment by AshesITR** [comment]
Does the last file contain tabs or 4 spaces?
If it's 4 spaces, you'll probably want r-lib/lintr#497 to be merged so a new `indentation_linter()` allows you to control indentation style.
