### ISSUE TITLE
When I use the radian in vscode to open a new R terminal , the first line code always run "conda activate base" , then pop up an error

### ISSUE THREAD

**Issue by ZHULOO** [REditorSupport/vscode-R#1080]
I know how to use conda to set the python's envs, But here I can't find out how to set to cancel running this line of code "conda activate base", when I run the select line in the Radian terminal.

**Comment by ZHULOO** [comment]
How to set to cancel running the code "conda activate base"? Thanks a lot.

**Comment by mcanouil** [comment]
This issue seems to be more a python/conda/vscode issue and possibly has nothing to do with vscode-r.

See microsoft/vscode-python#13464
