### ISSUE TITLE
shiny and httpgd package conflict

### ISSUE THREAD

**Issue by pholck** [REditorSupport/vscode-R#1083]
I suspect this is not a bug, but rather my lack of understanding.

Regardless if I use vsc viewer to display plots/shiny output, or an external browser, creating (say) a plot with:
  library(httpggd)
  hgd()
  hgd_browse()
  x=c(1,2,3)
  plot(x)

and THEN trying to run a shiny app (open/listening in a different browser window or vsc viewer pane) causes the terminal to hang (using radian). I assume because somehow the terminal is listening to different locations (hgd and shiny) or some such. The terminal becomes unresponsive, and Control-C, esc, etc do nothing. Only option is to kill the terminal.

Likely you can tell me I am doing something basic wrong! Thanks.

**Comment by renkun-ken** [comment]
Looks like it has nothing to do with vscode or radian but httpgd. I could reproduce it with vanilla R. As long as I create an httpgd device before running a shiny app, I cannot use control-c to suspend the shiny app.

Will report to httpgd.

**Comment by renkun-ken** [comment]
See https://github.com/nx10/httpgd/issues/108.
