### ISSUE TITLE
Help provider not working with renv projects without required packages

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#1091]
In renv projects, it is often a good practice only to include necessary packages. However, vscode-R help provider (e.g. `getAliases.R`) requires `jsonlite` to write the info. If the package is not installed in the renv project, then it won't work.

#1071 implements a vscode setting `r.lsp.libPaths` to support extra `.libPaths()` for the language server to start with. Maybe we should do similar in `getAliases.R` or eliminate the dependency on `jsonlite`?

**Comment by mcanouil** [comment]
Installing `jsonlite` or even `languageserver` causes no harm, since within a `renv` project only explicit use of packages (i.e., a call to `library()` or `require()`) are part of a default snapshot (i.e., `renv.lock`).

**Comment by renkun-ken** [comment]
What if languageserver requires something that has a version conflict with those installed in renv?

For example, if the project renv requires an older version of a package but languageserver depends on a newer one?

**Comment by mcanouil** [comment]
In that case, you have a problem indeed.
Define a new lib path in which you have the right to write/install new packages can help.
Then for this kind of edges cases and in a more general point of view, maybe vscode-r should rely on its own independent library path entirely 🤷‍♂️

**Comment by renkun-ken** [comment]
Closed via #1098.
