### ISSUE TITLE
Switch the "Knit Rmd" button from `render()` to `run()` for documents with "runtime: shiny"

### ISSUE THREAD

**Issue by tarensanders** [REditorSupport/vscode-R#1099]
**Is your feature request related to a problem? Please describe.**
In RStudio, when you have an interactive document (i.e., the YAML contains `runtime: shiny`), the knit button changes from knitting to HTML to "Run document" (as [described in their docs](https://shiny.rstudio.com/articles/interactive-docs.html)). Under the hood, it seems like the difference is that it switches from `rmarkdown::render()` to `rmarkdown::run()`. 

If you click the render button in vscode, vscode-R trys to render the document regardless of if it should actually be run, which just results in an error. I get the same error if I run `rmarkdown::render()` in the terminal (and everything runs fine if I switch that call to `rmarkdown::run()`).

**Describe the solution you'd like**
It would be great if either 1) the button could change the call dynamically (i.e., if "runtime: shiny" is detected) or 2) a default keyboard shortcut existed for `rmarkdown::run()`.

**Comment by ElianHugh** [comment]
Agreed that this could be better. I had a look at extending document types in #794, but admittedly haven't had a chance to revisit
