### ISSUE TITLE
When `{jsonlite}` is missing, the extension does not suggest to install it

### ISSUE THREAD

**Issue by CGMossa** [REditorSupport/vscode-R#1100]
When `{languageserver}` is missing, the extension provides a button to install it.
This doesn't happen with `{jsonlite}` is missing.
Instead this happens:

```
Fejl i loadNamespace("jsonlite") : der er ingen pakke med navn 'jsonlite' Kald: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart Kørsel stoppet
```

**Comment by renkun-ken** [comment]
Thanks for reporting! We'll probably have a unified approach to check required packages and prompt to install.
