### ISSUE TITLE
Control + enter within a Pipe does not execute the entire code block

### ISSUE THREAD

**Issue by brianmsm** [REditorSupport/vscode-R#1104]
If inside a flow with pipe, I have a function of more than 1 line and I execute it (control + enter) while the course is inside the parenthesis, only that particular line of code is executed.

![image](https://user-images.githubusercontent.com/28207224/168984628-682f1785-9a62-4e6e-a507-213f38b70ced.png)

Here the operation in Rstudio with the same cursor position.

![image](https://user-images.githubusercontent.com/28207224/168984360-4f9d4a03-d2b2-4d15-a39f-2444493d54a2.png)

**Comment by eitsupi** [comment]
This is currently the expected behavior. See https://github.com/REditorSupport/vscode-R/issues/437#issuecomment-1003074628.

**Comment by andycraig** [comment]
Closing as currently expected behaviour. Thanks @eitsupi!

**Comment by andycraig** [comment]
It is currently expected behaviour, but I've reopened in case there should be discussion about whether to change the expected behaviour.
