### ISSUE TITLE
Using pipe after mutate automatically suggests the newly created variable

### ISSUE THREAD

**Issue by brianmsm** [REditorSupport/vscode-R#1105]
When mutate is used within a pipe flow (%>%), the newly created variable is automatically suggested without opening any new function.

![image](https://user-images.githubusercontent.com/28207224/168983353-0d43fed1-5463-4b82-952c-f09736436b17.png)

Every time I exit a mutate and hit enter hastily (to go to the next line), the newly created variable name is inserted and I have to go back to the previous line to remove the erroneously autocompleted (by the enter) name.

![image](https://user-images.githubusercontent.com/28207224/168983601-5b584979-147e-4cab-97be-3fbd14e7b718.png)

**Comment by elsherbini** [comment]
Similar issue here. Pressing enter after a pipe rarely creates a newline for me and instead either suggests a variable or performs a find on a variable in my file. This is on https://github.com/coder /
[code-server](https://github.com/coder/code-server) running the vscode-R extension, in both rmarkdown files and .R files.
