### ISSUE TITLE
Allow passing arguments to `r.check` shortcut

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/vscode-R#1115]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Currently it seems that the invokation of `r.check` executes `devtools::check()` without the possibility to hand over user arguments.

**Describe alternatives you've considered**
Allow setting default arguments for `r.check`.

**Additional context**
I usually invoke `devtools::check()` without tests (i.e. `--no-tests`) (and other options) and invoke the tests only manually if needed.

I am using a custom keybinding for this right now. However, this has the downside that it is executed in the main R session and not in a new terminal - and by this it is blocking the main R session.
Would be great if `r.check` command would be modifiable by users :)

(Maybe it's already possible and I just overlooked it?)

**Comment by renkun-ken** [comment]
You could go to "Run Task" and customize existing R tasks.

**Comment by pat-s** [comment]
Nice! Worked flawlessly!
