### ISSUE TITLE
Error in httpgd_(host, port, bg, width, height, pointsize, aliases, cors, : Graphics API version mismatch

### ISSUE THREAD

**Issue by a-shihai** [REditorSupport/vscode-R#1118]
When i setting r.sessionWatcher to True, I get an error while drawing
Error in httpgd_(host, port, bg, width, height, pointsize, aliases, cors, :Graphics API version mismatch
All my packages are up to date
R：4.2.0
Plugins ：2.5.0
![image](https://user-images.githubusercontent.com/70144885/171408601-9c73f030-59e4-4780-b069-239240e59092.png)

**Comment by renkun-ken** [comment]
Does it still occur if you install the latest httpgd from CRAN or github?

**Comment by a-shihai** [comment]
Sure，my httpgd is 1.3.0

发件人: Kun Ren
发送时间: 2022年6月1日 21:01
收件人: REditorSupport/vscode-R
抄送: a_shihai; Author
主题: Re: [REditorSupport/vscode-R] Error in httpgd_(host, port, bg, width,height, pointsize, aliases, cors, : Graphics API version mismatch (Issue#1118)

Does it still occur if you install the latest httpgd from CRAN or github?

**Comment by nx10** [comment]
This should be fixed in the development version on GitHub. `remotes::install_github("nx10/httpgd")`
