### ISSUE TITLE
cannot display calculated value in data viewer

### ISSUE THREAD

**Issue by toorukt** [REditorSupport/vscode-R#1120]
**Describe the bug**
Hey everyone, I'm new to vscode-R and I'm so appreciate for making such excellent plugin.
The problem I found out is that the data viewer only display original value after read a dataset.
For example, 
say I have a 75-columns dataset "aaa", I used "read_csv" to load it then calculated a new "mean" column.
When I view it only the original 75 columns displayed, and the "mean"column were somehow "hidden".
If I want to see the calculated value I need to drag it.
Is this an issue?

**To Reproduce**

[aaa.csv](https://github.com/REditorSupport/vscode-R/files/8829197/aaa.csv)
aaa <- read_csv("aaa.csv", na = c("999", "NA"))
aaa$mean <- mean(aaa$o8)
<img width="572" alt="スクリーンショット 2022-06-03 11 54 19" src="https://user-images.githubusercontent.com/92703225/171777791-75677607-f3de-423a-ac5a-208b13a03412.png">
<img width="559" alt="スクリーンショット 2022-06-03 11 56 22" src="https://user-images.githubusercontent.com/92703225/171777797-bc9a88f1-4960-4f1c-94c4-43c3da947768.png">

Thanks in advance!

**Comment by ElianHugh** [comment]
I haven't been able to replicate this from the steps described:

![image](https://user-images.githubusercontent.com/60372411/171840170-7241ee5e-1568-4c7b-b2ca-9e841be516c7.png)

Just to double check, are you viewing the dataframe *before* creating the mean column?

**Comment by toorukt** [comment]
Thanks for the promptly reply!
Sorry I've deleted some columns when exporting the dataset so probably that why it not replicated.
It seems when the number of columns more than 84 then the rest will be hidden.
Could you try this please?

library(readr)
aaa <- read_csv("aaa.csv")
aaa$mean1 <- mean(aaa$o8)
aaa$mean2 <- mean(aaa$o8)
aaa$mean3 <- mean(aaa$o8)
aaa$mean4 <- mean(aaa$o8)
aaa$mean5 <- mean(aaa$o8)
aaa$mean6 <- mean(aaa$o8)
aaa$mean7 <- mean(aaa$o8)
aaa$mean8 <- mean(aaa$o8)
aaa$mean9 <- mean(aaa$o8)
aaa$mean10 <- mean(aaa$o8)
aaa$mean11 <- mean(aaa$o8)
aaa$mean12 <- mean(aaa$o8)
aaa$mean13 <- mean(aaa$o8)
aaa$mean14 <- mean(aaa$o8)

In my case, the column mean10~mean14 is hidden (see the screenshot).
 
<img width="1288" alt="スクリーンショット 2022-06-03 20 44 51" src="https://user-images.githubusercontent.com/92703225/171847569-50deca34-cd02-4132-a171-f1e551a88159.png">

**Comment by eitsupi** [comment]
I had also found this phenomenon but forgot to create an issue.
It seems that the collapsing of columns is affected by window size.
Conversely, creating a data frame with many columns in a given window size will always result in columns being collapsed from somewhere.

**Comment by ElianHugh** [comment]
Interesting, thank you for the information. As suggested by @eitsupi , I can replicate this by squishing my window:

![image](https://user-images.githubusercontent.com/60372411/171868195-3534766a-d294-4515-90bd-5b6a966120c7.png)

**Comment by ElianHugh** [comment]
Looks like this might be useful https://www.ag-grid.com/angular-data-grid/column-sizing/#sizing-columns-by-default=
I'll have a quick look if it's an easy fix

**Comment by ElianHugh** [comment]
Alright, the trick seems to be setting `suppressColumnVirtualisation` to true.  I'm not sure of the performance ramifications though: 

> Column Virtualisation is the technique the grid uses to render large amounts of columns without degrading performance by only rendering columns that are visible due to the horizontal scroll positions. For example, the grid can have 1,000 columns with only 10 rendered if the horizontal scroll is only showing 10 columns.

**Comment by ElianHugh** [comment]
Sorry, it's not (currently) a user-facing setting. @renkun-ken do you think this should be user-toggleable?

**Comment by renkun-ken** [comment]
I cannot reproduce it under macOS. Do you reproduce it all under Windows?

**Comment by toorukt** [comment]
Mine is macOS though😅

**Comment by renkun-ken** [comment]
@ElianHugh Maybe we should do the following:

* Add `minWidth` to each columns so that no column could be too thin?
* Add a button to the data viewer web view to resize all columns to fit the width of the webview

**Comment by renkun-ken** [comment]
I could reproduce it now if I add `minWidth: 20` to `defaultColDef` at https://github.com/REditorSupport/vscode-R/blob/master/src/session.ts#L506-L513.

**Comment by renkun-ken** [comment]
Looks like `suppressColumnVirtualisation: false` indeed could resolve the problem but as the number of columns get larger, I could observe significant performance problem when I scroll down the grid with 100 columns.

**Comment by renkun-ken** [comment]
@toorukt Would you like to try the [build](https://github.com/REditorSupport/vscode-R/suites/6792139407/artifacts/260520392) of #1121?

**Comment by toorukt** [comment]
@renkun-ken It's all good now! Brilliant!
