### ISSUE TITLE
Global Environment issue in workspace 

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#1128]
I am on a Macbook M1 with latest R, VScode and VScode-R. 

Some strange behaviour with `Global Environment` in workspace. 

There were 4 numeric values, and a data.table in the environment. However, somehow the folding with data.table became related to three of those values. When I clicked on the arrow beside data.table, it did not change direction, but three values just disappeared from it. 

In a more extreme case, the entire `Global Environment` would disappear with nothing inside even I have loaded the data.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/4111978/173367165-345971ec-4153-4fbc-850c-e9238f88bbcf.png">

<img width="259" alt="image" src="https://user-images.githubusercontent.com/4111978/173367255-2a61a091-64e4-4eaf-8bf1-27b13e6ed00e.png">

**Comment by MrJGao** [comment]
Confirmed, I'm having the same issue here.

**Comment by EvoLandEco** [comment]
Confirmed with latest extension version.

**Comment by renkun-ken** [comment]
Looks like the workspace viewer is broken for some reason. Let me take a closer look.

**Comment by renkun-ken** [comment]
@ElianHugh Does the workspace viewer work for you?

**Comment by ElianHugh** [comment]
Confirmed, having an issue as well. Occurs with a logged error:

```
 ERR Cannot read properties of null (reading 'value'): TypeError: Cannot read properties of null (reading 'value')
    at T (vscode-file://vscode-app/e:/Windows/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:82:72)
```

**Comment by ElianHugh** [comment]
This is very weird considering there hasn't been any major changes to the workspace viewer since the extended functionality PR. I wonder if it is due to a change in VSCode api or a regression of some kind?

**Comment by ManuelHentschel** [comment]
> ERR Cannot read properties of null

General tip for avoiding this type of error is to temporarily enable [strict null checks](https://github.com/REditorSupport/vscode-R/blob/e5b8f0c983496e4a0d74d336327f3e37bcc6fe2e/tsconfig.json#L11) and fix the resulting errors in your files. IMO we should have this enabled permanently, but that would require changes to almost the entire code base.
