### ISSUE TITLE
Use of R Projects in the extension

### ISSUE THREAD

**Issue by Pentaonia** [REditorSupport/vscode-R#1131]
**Is your feature request related to a problem? Please describe.**
I am really missing the feature of RProjects in VS code. For some things I need work arounds, that's sad. :(

**Describe the solution you'd like**
Working with projects makes a lot of stuff easier. For example sharing data or the use of relative paths.

**Additional context**
I have seen that the project file only contains a few lines of text and then R itself and a few packages can use that. So I don't know exactly if its easy but because there is so less information in the project file, that should not be a big problem?
It would be great if you bring it to work! <3

**Comment by renkun-ken** [comment]
In VS Code, you could open a folder and everything should work as a project.

**Comment by Pentaonia** [comment]
Thank you for your fast reply. Perfekt. I didn't knew that!
