### ISSUE TITLE
Handling roxygen imports

### ISSUE THREAD

**Issue by Wazarr** [REditorSupport/vscode-R#1133]
**Is your feature request related to a problem? Please describe.**
The linter indicates an object_user_linter issue for functions that have been imported using roxygen import statements. This doesn't happen on RStudio. For context, I am working on a golem project.
![image](https://user-images.githubusercontent.com/25822124/175288449-1a0197da-cf48-46fb-a929-eb2e1b983045.png)

**Describe the solution you'd like**
Either using the namespace file or treating the roxygen comments as regular imports.

**Comment by renkun-ken** [comment]
This should be a lintr issue. Please report at <https://github.com/r-lib/lintr/issues>.
