### ISSUE TITLE
Shortcut to view an object

### ISSUE THREAD

**Issue by Wazarr** [REditorSupport/vscode-R#1134]
Something that I use a lot in RStudio is the Ctrl+Click shortcut on a variable which opens its View tab without needing to have the workspace pane open.

Would it be possible to implement a similar functionality in VSCode? Thanks

**Comment by stefanopagliari** [comment]
I would also find this functionality very helpful

**Comment by andycraig** [comment]
I believe this would require VS Code to allow customisation of mouse shortcuts. There's an open feature request (with 1138 upvotes!): https://github.com/microsoft/vscode/issues/3130
