### ISSUE TITLE
Code/Text in Help Window can't be copied

### ISSUE THREAD

**Issue by iago-pssjd** [REditorSupport/vscode-R#1137]
**Describe the bug**
Text/Code in Help Window can't be copied and pasted.

**To Reproduce**
1. Search the help of any function, e.g., `?t.test`
2. On the help for the function, try to copy something, e.g., `t.test(1:10, y = c(7 : 20))`
3. Try to paste it in the terminal, in the editor or in any other place.

## Do you want to fix by self? (We hope your help!)

No

**Expected behavior**
We can Copy text/code From R Help View Window and Paste in Source Code Document

**Screenshots**
![scs](https://user-images.githubusercontent.com/40892925/175891600-a3d15cbf-99d5-4077-aed4-6523aaa4ebe7.png)

**Environment (please complete the following information):**

- OS:  Windows 10
- VSCode Version: 1.68.1
- R Version: 4.2.0
- vscode-R version: v2.5.0

**Additional context**
Related issues: 
- Very similar to https://github.com/REditorSupport/vscode-R/issues/1062
- Actually, I would prefer to apply feature requested in https://github.com/REditorSupport/vscode-R/issues/459, but don't having it, I have to copy and paste.

**Comment by ManuelHentschel** [comment]
I can't reproduce this bug on windows 10, vscode 1.68.1, vscode-R 2.5.0. Are you aware of any other settings etc. that might influence this?

**Comment by iago-pssjd** [comment]
I am not aware of that. I only modified the next settings to use `radian`:
```
 "r.bracketedPaste": true,
  "r.rterm.windows": ...
```
