### ISSUE TITLE
When calling plot or help, nothing happens (no display, no message, no error)

### ISSUE THREAD

**Issue by lz01** [REditorSupport/vscode-R#1140]
**Describe the bug**
Plotting or calling R help normally displays the resulting plot or help doc in a panel on the top right of the editor. Plotting and help display all work fine in my IDE, but sometimes, and it has happened already 5 or 6 times, this functionality stops working out of the blue, and nothing happens when calling plot or help, no display, no message, no error. I am not able to reproduce the error, but it has happened multiple times. Restarting the app doesn't solve the issue. The odd thing is that every time that functionality has stopped working, the issue was only solved the next time VSCode had an update and installing it, even though the update had nothing to do with the issue or R. 

**To Reproduce**
Impossible to reproduce. It seems to happen without an event preceding it.

## Do you want to fix by self? (We hope your help!)

 No

(If related)setting.json

```jsonc





// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**
Plot or help are displayed.

**Environment (please complete the following information):**

- OS: macOS 10.15.7
- VSCode Version: 1.68.1 
- R Version: 4.1.1
- vscode-R version: 2.5.0

**Comment by renkun-ken** [comment]
Did you close vscode and reopen it so that the session watcher did not attach to the session where you create plots?

It should work again if you attach the session, or call `dev.off()` to close the device and plot again.
