### ISSUE TITLE
Can render quarto doc in RStudio but not in VSCode

### ISSUE THREAD

**Issue by werkstattcodes** [REditorSupport/vscode-R#1146]
**Describe the bug**
In a .qmd (Quarto) document calling the library(treemapify) works. I can run the code chunk without problem. 
However, when rendering the document to html I get the prompt:

```
Error in library(treemapify) : there is no package called 'treemapify'
Calls: .main ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted
```
Rendering the same file in RStudio does not produce the error.

**To Reproduce**
Create the .qmd (Quarto) file with the content below.

```{r}
library(tidyverse)
library(treemapify)
find.package("tidyverse")
find.package("treemapify")
```
Assuming that treemapify has been already [installed](https://github.com/wilkox/treemapify), run the code chunk. (No issue).
Render the document. Error. Issue appears.

Open the same document in RStudio and render it. No error occurs.

## Do you want to fix by self? (We hope your help!)

Unfortunately, not qualified enough.

**Environment (please complete the following information):**

- OS:  Windows 10
- VSCode Version: 1.69
- R Version:  4.2.0
- vscode-R version: v.2.5.0.

**Additional context**
I use Quarto, R and VSCode without problem. Only with this package the strange error occurs.

**Comment by eitsupi** [comment]
I don't think this issue has anything to do with vscode-R.
I suggest you create an issue on https://github.com/quarto-dev/quarto-cli (or https://github.com/quarto-dev/quarto-vscode).

**Comment by werkstattcodes** [comment]
Ok. Many thank thanks. Feel free to close the issue.
