### ISSUE TITLE
Folder specific R path

### ISSUE THREAD

**Issue by fernandoroa** [REditorSupport/vscode-R#1148]
**Describe the solution you'd like**
In settings, related to a remote server, sometimes it is necessary to have a specific R path (version executable) in Rterm and Rpath depending on the working folder 

**Describe alternatives you've considered**
I tried, modifying the file in .vscode-R/settings.json without success, in addition this file is not specific for working folders

**Additional context**
I work connected by ssh.

**Comment by renkun-ken** [comment]
You might want to edit [workspace settings](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings) to achieve this, which creates a `.vscode/settings.json` in your workspace folder.

**Comment by ElianHugh** [comment]
Note that this will be implemented with #1143
