### ISSUE TITLE
Extension settings should be stored in default location

### ISSUE THREAD

**Issue by cbrnr** [REditorSupport/vscode-R#1149]
**Describe the bug**
Extension settings are usually located in `~/.vscode/extensions`. However, the settings for this extension are stored in `~/.vscode-R`.

**To Reproduce**
Here's an example of my setup, all extensions store their settings under `.vscode`:

```
~  ls ~/.vscode/extensions
adpyke.codesnap-1.3.4                     ms-python.python-2022.10.0            ms-toolsai.jupyter-renderers-1.0.8
github.vscode-pull-request-github-0.46.0  ms-python.vscode-pylance-2022.7.20    quarto.quarto-1.26.0
julialang.language-julia-1.6.24           ms-python.vscode-pylance-2022.7.30    reditorsupport.r-2.5.0
kevinrose.vsc-python-indent-1.17.0        ms-toolsai.jupyter-2022.6.1101950301
```

This does not include `vscode-R`, which has its own folder in my home:

```
~  ls ~/.vscode*           
/Users/clemens/.vscode:
extensions  argv.json

/Users/clemens/.vscode-R:
tmp  init.R  request.lock  request.log  settings.json
```

I could try to fix this if people agree this is a bug.

**Expected behavior**
I expected the settings of `vscode-R` to be in the standard location under `~/.vscode/extensions`.

**Environment (please complete the following information):**

- OS: macOS 11.6.7
- VSCode Version: 1.69.1
- R Version: 4.2.1
- vscode-R version: 2.5.0

**Comment by renkun-ken** [comment]
For [self-managed R sessions](https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions), it might not be very convenient to have the files located in the extension folder (e.g. `/home/user/.vscode-server/extensions/reditorsupport.r-2.5.0`) since it contains the version of the extension. I think this is a main reason we keep such a folder at the moment.

**Comment by cbrnr** [comment]
I see. Could this be solved in a different way (e.g. creating a symlink if someone wants a self-manages session)? The relevant code snippet could be updated as follows:

```
configdir = list.files(".vscode/extensions", pattern="reditorsupport*")
if (interactive() && Sys.getenv("RSTUDIO") == "") {
  source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), configdir, "init.R"))
}
```

**Comment by eitsupi** [comment]
I think VSCode Server has a different directory name (`.vscode` vs `.vscode-server`).
Is there any reason to change the storage location at the risk of it not working?

**Comment by cbrnr** [comment]
My reasons are (1) it's easier to find the settings when it's in the standard location, and (2) I don't like applications cluttering my home directory (I know it's a hidden folder, but still). Of course these reasons might not be enough to warrant the change.

**Comment by cbrnr** [comment]
Yes, #495 is very much related! Instead of `~/.vscode-R`, if within `~/.vscode/extensions` is not an option, you might want to consider using `~/.config/vscode-R` instead.

**Comment by renkun-ken** [comment]
`~/.config/vscode-R` seems to be a better place.

**Comment by benz0li** [comment]
Folder `~/.vscode-R` is according to [requirements](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s08.html#requirements4a) – at least for Unix-like operating systems. Nothing wrong with that.

Should this folder be abandoned, do not hard-code `~/.config/vscode-R` but follow the guidelines as outlined in https://github.com/REditorSupport/vscode-R/issues/495#issue-765236660 by @LiteracyFanatic.

**Comment by LucasFA** [comment]
A backwards compatible change would be to use the XDG locations if they exist (ie, use `XDG_CONFIG_HOME/vscode-R/` or fall back to  `~/.config/vscode-R/`). If neither of those exist, move  `~/.vscode-R` (if it exists) to `XDG_CONFIG_HOME/vscode-R`. Of course if the `XDG_CONFIG_HOME` variable is not set it would fall back to use `~/.config/vscode-R` as new default behaviour.

Regarding @benz0li's comment, it is worthy to note that the linked spec explicitly mentions and links to the [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and the [Glib conventions, here in the GNOME documentation](https://docs.gtk.org/glib/func.get_user_config_dir.html) which also use the XDG spec.
 
Somewhat related, the wakatime-cli family of extensions are trying to migrate, too. [Issue on the main project](https://github.com/wakatime/wakatime-cli/issues/558), the [jetbrains extension](https://github.com/wakatime/jetbrains-wakatime/issues/252) and the [vim extension](https://github.com/wakatime/vim-wakatime/issues/158)

Off-topic, but I do not see the value of auto-closing issues. That's like automically tagging it `wontfix`. An unhandled issue is not intrinsically less worthy than a new issue simply by nature of being older. If this does not reopen it, I will open another one to continue this conversation unless asked not to by a mantainer.

**Comment by mayurankv** [comment]
I also find this quite annoying and would love for XDG conventions to be respected. Ideally an environment variable would specify the path, followed by XDG conventions, followed by ~/.vscode-R. This would let those of use who manage our dotfiles carefully set the location explicitly.
