### ISSUE TITLE
Add date to rmarkdown file output name when clicking "knit"

### ISSUE THREAD

**Issue by jarbet** [REditorSupport/vscode-R#1153]
**Describe the bug**
I am using rmarkdown within VSCode, and would like to automatically add today's date to the output filename when clicking the 'knit' button.  I see that this feature was requested [here](https://github.com/REditorSupport/vscode-R/issues/753) and added in PR #765, however, I can't get it to work.

**To Reproduce**

1. Create file `test.Rmd` that contains the following code:
```
---
title: "hello world"
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(input), '-', Sys.Date(), '.html'
      ),
      envir = globalenv()
    )
  })
---

hello world
```
2. Click on Knit > Rmd button:
![image](https://user-images.githubusercontent.com/103967480/179795251-3c152108-ea42-418c-88c6-b7b527574ab0.png)

3. Unfortunately, the output filename is `test.html` and does not contain the date:
![image](https://user-images.githubusercontent.com/103967480/179795565-aa70c7bb-b34a-4b45-a878-485f25b2061c.png)

Note after clicking the knit button, the following command is automatically called (which I suspect is causing the date to be removed from the filename):

`rmarkdown::render("test.Rmd", encoding = "UTF-8")`

**Environment (please complete the following information):**

- OS: macOS but I am using VSCode to connect to a remote server where I am using Rmarkdown/R for analysis
- VSCode Version: 1.69.1 
- R Version: 4.1.3
- vscode-R version: v\2.5.2

**Comment by ElianHugh** [comment]
I can't replicate this locally -- I'd just like to double check that you have enabled the VSC setting `rmarkdown.knit.useBackgroundProcess` as otherwise vscode-R will default to standard knitting in the interactive terminal

**Comment by jarbet** [comment]
> I can't replicate this locally -- I'd just like to double check that you have enabled the VSC setting `rmarkdown.knit.useBackgroundProcess` as otherwise vscode-R will default to standard knitting in the interactive terminal

It works now after checking that box.  Thanks!
