### ISSUE TITLE
Not available for server version of vscode

### ISSUE THREAD

**Issue by david-cortes** [REditorSupport/vscode-R#1155]
This extension is currently not available in vscode-server version, only the LSP package is available there to install. Would be nice if the whole package could also be made available for vscode-server.

**Comment by eitsupi** [comment]
What does the "vscode-server version" mean?
Can you post the exact software name or a link to the official documentation?

**Comment by david-cortes** [comment]
This vscode server:
https://github.com/coder/code-server/releases
https://code.visualstudio.com/blogs/2022/07/07/vscode-server

**Comment by eitsupi** [comment]
> This vscode server:
> [coder/code-server/releases](https://github.com/coder/code-server/releases)
> [code.visualstudio.com/blogs/2022/07/07/vscode-server](https://code.visualstudio.com/blogs/2022/07/07/vscode-server)

I believe "coder/code-server" and "The Visual Studio Code Server"  are completely different products.
Which is it that you have tried?

**Comment by benz0li** [comment]
@david-cortes If this is about the latest version, see https://github.com/open-vsx/publish-extensions/issues/591.

**Comment by benz0li** [comment]
There is https://open-vsx.org/extension/Ikuyadeu/r (v2.4.0).

**Comment by benz0li** [comment]
@david-cortes See https://github.com/coder/code-server/blob/main/docs/FAQ.md#why-cant-code-server-use-microsofts-extension-marketplace for more information. 
👉 [Microsoft extension marketplace (Visual Studio Code)](https://marketplace.visualstudio.com/VSCode), [Open-VSX extension gallery](https://open-vsx.org/).
