### ISSUE TITLE
Consider taking out overlapping snippets that are supported by auto-completion

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#1156]
`snippets/r-snippets.json` contains lots of functions that are available in auto-completion/suggestion. Could you please consider taking out all these overlapping functions from the snippet? These are rather redundant and sometimes confusing. For example, `lib` triggers both auto-completion and snippet of `library()` function and this is not necessarily useful.

**Comment by gowerc** [comment]
@andycraig 

hmm, I don't use the snippets myself but are we sure we'd want to remove these as I see them serving to distinct purposes, autocomplete is just to finish the keyword whilst snippets provide boilerplate with tab functionality to focus on specific parts of the boiler plate

**Comment by andycraig** [comment]
Hi @gowerc, thanks for the feedback. I don't have a strong opinion either way. For now I'll remove the labels.
