### ISSUE TITLE
r.libPaths not respected

### ISSUE THREAD

**Issue by bizzinho** [REditorSupport/vscode-R#1163]
**Describe the bug**
Adding library paths in `r.libPaths` does not affect `.libPaths()` when sourcing a test file.

**To Reproduce**

1. Make new custom library folder <customfolder>
2. In R: `install.packages("vroom", lib=<customfolder>)`
1. Add custom Lib Path to r.LibPaths setting
3. Create new file `test.R` with content `print(libPaths())` -> only shows defaults of installation

## Do you want to fix by self? (We hope your help!)

No

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

(If related)setting.json

```jsonc
    "r.libPaths": [
        "<customfolder>"
    ]
```

**Expected behavior**
The custom folder should appear in the library path.

**Screenshots**
![image](https://user-images.githubusercontent.com/1315032/181769012-3abfaae4-d51a-4a76-b142-d798bd6b0d10.png)

**Environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.69.2
- R Version: 4.0.2
- vscode-R version: 2.5.2

**Additional context**
I'm facing the same issue with an attached linux remote. The R session in the terminal seems to ignore my libPaths setting.

Very possible that I'm doing something wrong. Thanks in advance!

**Comment by renkun-ken** [comment]
This `r.libPaths` was introduced in #1071 to tweak the lib paths of background R processes, e.g. help server and language server, and is not intended for user interactive sessions.

For your use case, you might want to tweak your libPaths in your `~/.Rprofile`.

**Comment by gowerc** [comment]
@bizzinho Does Renkun's above reply answer your issue? I think this can be closed now

**Comment by bizzinho** [comment]
Apologies for not replying sooner. I missed the notification.

Yes, this ticket can be closed, I appreciate the feedback. I _would_ suggest to expand/clarify the documentation on this item in an upcoming release, though, lest there be more users with similar expectations.
