### ISSUE TITLE
search option in data viewer is bugged?

### ISSUE THREAD

**Issue by kj-rea** [REditorSupport/vscode-R#1164]
**Describe the bug**
I'm currently often working with datasets that contain >200 columns and 3-10 thousand rows and mostly text data. Tried switching from RStudio to VSCode and I really appreciated that search includes column names as well, but I noticed that very often the search option fails to show any results when it definitely should. This is really breaking my experience using R in vscode so I hope I can get some support on this.

**To Reproduce**

1. Load a data frame (probably needs to contain large number of columns and text data)
2. Open the data viewer
3. Try searching for some text that should definitely be in the data frame
4. See if you find any results

## Do you want to fix by self? (We hope your help!)

No (i dont know JS)

**Expected behavior**
I expect the search function in the data viewer to properly find matching text.

**Screenshots**
![r_viewer screen](https://user-images.githubusercontent.com/108526862/181789696-52b833c1-eb99-4900-997b-7c5e5a8c4ebc.png)

**Environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.69.2
- R Version: 4.2.1
- vscode-R version: 2.5.2

__I have not changed any default vscode-r settings__

**Comment by albertosantini** [comment]
Hey.

If you need to search something in a column, please, hover on the column and click on the hamburger menu.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/328179/182013749-52e91ab8-5ca6-4451-84ea-998ed3261a80.png">

The component behind the scenes, is AG Grid Community: https://www.ag-grid.com/

Hope that helps.
