### ISSUE TITLE
Special character not sent to R console

### ISSUE THREAD

**Issue by sindribaldur** [REditorSupport/vscode-R#1169]
```r 
v = "yes–no"
```

Results in (when I use ctrl+enter to send to console):

```r 
v = "yesno"
```

I'm using Windows 10 and R 4.2.1.

**Comment by gowerc** [comment]
Works fine for me (though am using linux):
![image](https://user-images.githubusercontent.com/8447209/184500002-6274198e-08d2-4bb4-a74f-3cefb7a4e3b4.png)

Can you share more details of your setup e.g. vscode version, vscode-R version,  R or radian ?

Can you also try disabling your keyboard shortcuts and any other R extensions.
