### ISSUE TITLE
Multi-line statements are sent line-by-line to radian terminal

### ISSUE THREAD

**Issue by david-cortes** [REditorSupport/vscode-R#1171]
**Steps to reproduce:**
* Install [radian](https://github.com/randy3k/radian) and set it as your R console through the setting `R: Rterm: Linux` in vscode.
* Create an R file and write some multi-line statement on it, such as this:
```r
df <- data.frame(
    col1 = 1:3,
    col2 = c("a","b","c")
)
```
* Press Ctrl + Shift + P and select `R: Create R terminal`.
* Click on the first line of the multi-line statement in the R file so as to put the focus there.
* Press Ctrl + Enter.

**Expected behavior:** should send the whole multi-line statement as one command to the terminal.

**Actual behavior:** sends the multi-line statement line-by-line to the terminal, making each individual line fail to execute as they aren't meant to be executed separately.

**Comment by eitsupi** [comment]
duplicate of #437

**Comment by david-cortes** [comment]
> duplicate of #437

I think #437 describes a different issue which affects also the regular R terminal, while this only affects radian and has a different behavior when using the regular terminal.

**Comment by andycraig** [comment]
Hi, try enabling the setting `R: Bracketed Paste`. That should fix it.

**Comment by david-cortes** [comment]
> Hi, try enabling the setting `R: Bracketed Paste`. That should fix it.

Thanks, that solves it. Would be good to have it in the readme instructions.

**Comment by andycraig** [comment]
@david-cortes Thank you for the feedback. It's in the Wiki here: https://github.com/REditorSupport/vscode-R/wiki/Installation:-Windows#radian
But perhaps it could be made more discoverable.

**Comment by MrShadow0624** [comment]
i have enabled the setting R: Bracketed Paste = true, but it doesn't work. I wonder if anyone meet the same problem with me?

**Comment by MrShadow0624** [comment]
> i have enabled the setting R: Bracketed Paste = true, but it doesn't work. I wonder if anyone meet the same problem with me?我已经启用了设置 R: Bracketed Paste = true，但不起作用。我想知道是否有其他人遇到相同的问题？

问题解决了，参考https://github.com/REditorSupport/vscode-R/issues/1590
