### ISSUE TITLE
R terminal cannot be started after switching R versions

### ISSUE THREAD

**Issue by strengejacke** [REditorSupport/vscode-R#1181]
Hi, I'm using VS Code with R 4.2.1 on Windows 10. I temporarily installed R devel for checking packages, and after starting VS Code, the terminal loaded R 4.3.0 (devel) instead of R 4.2.1. After un-installing R-devel again, VS Code cannot open the R terminal any longer, with following error message:

```
PS D:\mail\Documents\Coding\R\easystats\parameters> .vsc.attach()
In Zeile:1 Zeichen:13
+ .vsc.attach()
+             ~
Nach "(" wurde ein Ausdruck erwartet.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression
 
PS D:\mail\Documents\Coding\R\easystats\parameters> ?.vsc.attach
?.vsc.attach : Die Benennung "?.vsc.attach" wurde nicht als Name eines Cmdlet, einer 
Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die  
Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen  
Sie den Vorgang.
In Zeile:1 Zeichen:1
+ ?.vsc.attach
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (?.vsc.attach:String) [], CommandNotFoundExc 
   eption
    + FullyQualifiedErrorId : CommandNotFoundException
```

And following message:

![image](https://user-images.githubusercontent.com/26301769/185875896-0982fbdd-ca6a-49e4-980d-c43d2ca3ca19.png)

The message suggests setting `r.rpath.windows`, however, before it worked without changing that setting. I'm hesitant to do so, because I work with VS Code on 3 different computer and settings/keybinds etc. are synced, and the paths to the R installation might be different.

Is there any possibility to fix this issue without "hardcoding" the path to the R installation in the settings? Like uninstalling and reinstalling the R extension?

**Comment by strengejacke** [comment]
Ok, it might be that `r.rpath.windows` was indeed hardcoded, but `r.rterm.windows` was not. R path should be identical across computer, though I'm pretty sure I did _not_ modify this settings.

Not sure if you consider this as an "issue" (regarding working with multiple R versions) or if you want to close this.

**Comment by andycraig** [comment]
This extension also looks for R on the PATH environment variable, and in the location set in the Windows registry (if it exists). (These are Windows settings, not vscode-R settings.) I'm wondering if installing/uninstalling R devel somehow modified one of those.

If you want to share settings between different PCs that may have R installed in different locations, adding those locations to the PATH environment variable would be one option.

**Comment by strengejacke** [comment]
> I'm wondering if installing/uninstalling R devel somehow modified one of those.

I think I also checked the environment variable of windows, including PATH, but I cannot say for sure. I would also guess that this is the most likely reason. That said, I don't think this is a vscode-R issue in first instance, so we might close this one.

**Comment by andycraig** [comment]
Thanks @strengejacke, I'll close it now.
