### ISSUE TITLE
Plots are not automatically opening in external browser

### ISSUE THREAD

**Issue by PMassicotte** [REditorSupport/vscode-R#1182]
I would like to open plots/graphs in an external web browser rather than directly in VSC. Per [documentatin](https://github.com/REditorSupport/vscode-R/wiki/Plot-viewer), I am using this in my `.Rprofile`:

```r
if (interactive() && Sys.getenv("RSTUDIO") == "") {
  Sys.setenv(TERM_PROGRAM = "vscode")
  if ("httpgd" %in% .packages(all.available = TRUE)) {
    options(vsc.plot = FALSE)
    options(device = function(...) {
      httpgd::hgd(silent = TRUE)
      .vsc.browser(httpgd::hgd_url(history = FALSE), viewer = "Beside")
    })
  }
}
```

As said in the documentation, this will pop the graphs inside VSC. Any possibility to open them in my web browser (externally)? I have also tried to use:

```r
.vsc.browser(httpgd::hgd_url(history = FALSE), viewer = FALSE)
```

![image](https://user-images.githubusercontent.com/4519221/186713038-719b1fcb-7811-43dc-9ea3-a3536b5338f0.png)

Anything I am missing out?

```r
r$> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 21

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1    cli_3.3.0         later_1.3.0      
[4] Rcpp_1.0.9        httpgd_1.3.0      jsonlite_1.8.0   
[7] systemfonts_1.0.4 rlang_1.0.4      
```

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- VSCode Version: 1.70.2
- R Version: 4.2.1
- vscode-R version: 2.5.2

**Comment by renkun-ken** [comment]
```r
.vsc.browser(httpgd::hgd_url(history = FALSE), viewer = FALSE)
```

should open the httpgd viewer in an external web browser. How does it behave differently?

**Comment by PMassicotte** [comment]
> should open the httpgd viewer in an external web browser. How does it behave differently?

It does nothing on my external browser (Firefox). The plot only appears inside VSC. I h ave tried to use it in my `.Rprofile` but also directly in a live session:

![Peek 2022-08-25 12-29](https://user-images.githubusercontent.com/4519221/186719981-b2fc54e3-5ab5-4f2a-a6a5-ca73acfe98f6.gif)
.

**Comment by renkun-ken** [comment]
What if you disable `r.plot.useHttpgd`?

**Comment by PMassicotte** [comment]
I set `"r.plot.useHttpgd": false,` in `settings.json`. The same thing happens, except it is a png file that opens inside VSC.

**Comment by PMassicotte** [comment]
I do not remember where, but I found a post from you somewhere with this keybinding.

```json
{
    "key": "ctrl+alt+p",
    "command": "r.runCommand",
    "when": "editorTextFocus && editorLangId == 'r'",
    "args": ".vsc.browser(httpgd::hgd_url(), viewer = FALSE)"
  }
```
If I use it, it will indeed open the plot in a web browser.

**Comment by PMassicotte** [comment]
I just found that it is working only if the following is defined in the **project** `.Rprofile` file. It is not working if used in the global `.Rprofile`.

```json

if (interactive() && Sys.getenv("RSTUDIO") == "") {
  Sys.setenv(TERM_PROGRAM = "vscode")
  if ("httpgd" %in% .packages(all.available = TRUE)) {
    options(vsc.plot = FALSE)
    options(device = function(...) {
      httpgd::hgd(silent = TRUE)
      .vsc.browser(httpgd::hgd_url(history = FALSE), viewer = FALSE)
    })
  }
}

```

**Comment by renkun-ken** [comment]
Do you have both project `.Rprofile` and global `~/.Rprofile`?

If it is the case, then only project `.Rprofile` will be sourced by R session started from the project directory.

**Comment by PMassicotte** [comment]
That was the problem. I had an empty `.Rprofile` inside my project. I never thought that although empty, it will prevent the global one to be loaded. Tx for your assistance.
