### ISSUE TITLE
R code not working when function call stacked across two lines with radian.

### ISSUE THREAD

**Issue by padpadpadpad** [REditorSupport/vscode-R#1187]
**Describe the bug**

When I send ggplot2 code from a script to a radian terminal on VSCode (v1.70.2), if the specific command is over two lines, it errors. It appears to be adding a random bracket at the end of each line, and this is after me unclicking Bracketed Paste mode (although I am not entirely sure what that was doing anyway). A screenshot of the output of the code is below.

I think this is something I am doing that is really stupid but I am only just starting out trying to use VSCode instead of RStudio on this machine.

**To Reproduce**

```{r}
library(ggplot2)

data(mpg)

ggplot(mpg, aes(hwy, cty)) +
    geom_point() +
    theme_bw() +
    labs(x = 'y',
    y = 'z')
# breaks

ggplot(mpg, aes(hwy, cty)) +
    geom_point() +
    theme_bw() +
    labs(x = 'y', y = 'z')
# works
```

## Do you want to fix by self? (We hope your help!)

Yes

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

(If related)setting.json

```jsonc
{
    "editor.wordWrap": "on",
    "workbench.colorTheme": "Default Dark+",
    "security.workspace.trust.untrustedFiles": "open",
    "window.autoDetectColorScheme": true,
    "window.zoomLevel": 1,
    "r.rterm.mac": "/Users/danpadfield/miniconda3/bin/radian",
    "r.lsp.debug": true,
    "r.lsp.diagnostics": true,
    "r.rterm.option": [
            "--no-save",
            "--no-restore",
            "radian"
        ],
        "quarto.mathjax.theme": "dark",
        "r.alwaysUseActiveTerminal": true,
        "r.plot.useHttpgd": true,
        "workbench.startupEditor": "none",
}
```

**Screenshots**

![Screen Shot 2022-08-30 at 10 20 52](https://user-images.githubusercontent.com/10220722/187400228-2ca3e77e-cf35-4f36-b905-b7fc96372816.png)

**Environment (please complete the following information):**

- OS: [MacOS 13.13.6]
- VSCode Version: [v1.70.2]
- R Version: [e.g. 4.1.2]
- vscode-R version: [v2.5.2]

**Comment by andycraig** [comment]
Try adding `options(radian.auto_match = FALSE)` to your [radian profile](https://github.com/randy3k/radian#settings).
