### ISSUE TITLE
Unable to open help documentation for functions

### ISSUE THREAD

**Issue by mdmanurung** [REditorSupport/vscode-R#1190]
Dear all,

Apologies in advance if this is a duplicate issue.

I am using R via SSH (so a self-managed R session). 
I have set the following settings: `r.alwaysUseActiveTerminal`, `r.rpath.linux`, and `r.rterm.linux`. However, I am still getting this error when trying to open help (e.g. `?plot`) or hovering my cursor over a function on the editor.

```
Failed to get list of R functions. Make sure that `jsonlite` is installed and r.rpath.linux points to a valid R executable.
```
as well as

```
The "file" argument must be of type string. Received undefined
```

Note that I have installed `jsonlite`. Can anyone give any advice? Much appreciated.

**Comment by ManuelHentschel** [comment]
Are you using the remote ssh extension (see [here](https://code.visualstudio.com/docs/remote/ssh)), or just a normal terminal and then SSH into your server?

In the latter case, many functions won't work, since the vscode-R extension cannot access the R process running on the server.

**Comment by renkun-ken** [comment]
As @ManuelHentschel points out, vscode-R cannot access a remote R terminal started by a user since it does not have direct file system access where the R process does.

It you are accessing remote R terminal, you need to use the Remote-SSH approach.

**Comment by mdmanurung** [comment]
Thanks for the advice! @ManuelHentschel @renkun-ken 
It works perfectly now after using the Remote-SSH approach :)
