### ISSUE TITLE
disable `Linting` and remove inline warnings

### ISSUE THREAD

**Issue by kongdd** [REditorSupport/vscode-R#1191]
I want to remove those inline warnings in vscode-R. 
Any solution?
![image](https://user-images.githubusercontent.com/9815742/189464223-98cbd20e-910c-4d63-8183-f9cafb899a51.png)

**Comment by renkun-ken** [comment]
To disable linting, turn off `r.lsp.diagnostics` in vscode settings.

**Comment by kongdd** [comment]
`r.lsp.diagnostics` has been turn off.
But still not work.
![image](https://user-images.githubusercontent.com/9815742/189464931-90191e3b-c78b-48c9-b5b5-ffc948b2b609.png)

**Comment by ManuelHentschel** [comment]
Not sure if I'm missing something, but this doesnt seem to work for me (i.e. I can't turn off the linter). I also could not find in the source code where the option `r.lsp.diagnostics` is handled. Any tips?

**Comment by renkun-ken** [comment]
lintr is called on languageserver side at

https://github.com/REditorSupport/languageserver/blob/f15957538d2ef82f4a5905e1a8b493dca2cc8deb/R/languageserver.R#L106-L115

**Comment by ManuelHentschel** [comment]
Ok, but how does the value of `r.lsp.diagnostics` get into `run_lintr && lsp_settings$get("diagnostics")`?

**Comment by renkun-ken** [comment]
The language server configuration

https://github.com/REditorSupport/vscode-R/blob/708004ab75a14f00146bf13bd397b20744ec40cb/src/languageService.ts#L129

still works at the moment and it sends `r.lsp.*` to language server on startup.

Then on language server side, it is handled by

https://github.com/REditorSupport/languageserver/blob/f15957538d2ef82f4a5905e1a8b493dca2cc8deb/R/handlers-workspace.R#L19

and <https://github.com/REditorSupport/languageserver/blob/master/R/settings.R> defines how settings are handled.
