### ISSUE TITLE
cat() function output removing first 2 characters

### ISSUE THREAD

**Issue by kanazuchijin** [REditorSupport/vscode-R#1193]
**Describe the bug**
The `cat()` function's output removes the first two characters in the terminal output. Here is an example:

```R
v=c(1:8)
cat(v,sep=":")
```

This should result in the following output to the console: `1:2:3:4:5:6`. Instead, in VS Code, it outputs `2:3:4:5:6`.

Another example:

```R
x = "It's finally Saturday!"
cat("I want to hear you shout", x)
```

This results in `want to hear you shout  It's finally Saturday!`. Two other people using their own computers can also confirm this.

**Screenshots**
Here is the output in VS Code:
![image](https://user-images.githubusercontent.com/57264954/189489686-1dcbe3d3-b98d-4151-9130-dfac52e8faff.png)

Here is the output in RStudio:
![image](https://user-images.githubusercontent.com/57264954/189489708-693ba7cb-8861-42b8-b271-2a9160b1b2d9.png)

**Environment:**
My system environment:
- OS: Windows 11 Education Build 22000.856
- VSCode Version: 1.71
- R Version: 4.1.2
- vscode-R version: 2.5.3

System environment of 2nd tester:
- OS: Windows 11 Home Build 22000
- VSCode Version: 1.71
- R Version: 4.2.1
- vscode-R version: 2.5.3

**Comment by ManuelHentschel** [comment]
That's the normal behaviour in plain R. To get the desired output you need to append '\n' manually:
``` R
cat("I want to hear you shout", x, "\n")
```

**Comment by kanazuchijin** [comment]
> That's the normal behaviour in plain R. To get the desired output you need to append '\n' manually:
> 
> ```r
> cat("I want to hear you shout", x, "\n")
> ```

I did not know. In all my years of using R (10+ years), I have never known that. Thank you!
