### ISSUE TITLE
"Run command in terminal" just runs "undefined"

### ISSUE THREAD

**Issue by multimeric** [REditorSupport/vscode-R#1197]
**Describe the bug**
When I try to use the "Run command in terminal" command, the extension just runs `undefined` in the associated R terminal.

**To Reproduce**

1. Start an R terminal with the "R: Create R terminal" command
2. Click on a line of R code. In my case it contains `library(tidyverse)`
3. Run the "R: Run Command in Terminal" command
4. In the R terminal, this now shows:
    ```
    r$> undefined
    Error: object 'undefined' not found
    ```

## Do you want to fix by self? (We hope your help!)

Not really

## setting.json

```jsonc
    "r.alwaysUseActiveTerminal": true,
    "r.bracketedPaste": true,
    "r.rterm.linux": "/home/migwell/miniconda3/envs/R42/bin/radian",
```

**Expected behavior**
The command on the current line of the editor should run

**Screenshots**
![image](https://user-images.githubusercontent.com/5019367/190049801-1abf277e-51e5-4f40-a663-53da7fdc97f1.png)

**Environment (please complete the following information):**

- OS: Linux (Ubuntu 22.04)
- VSCode Version: 1.70.2
- R Version: 4.2.1
- vscode-R version: v2.5.3
- 
## Extra Context

This also happens if I use the default (ie non-radian) terminal.

**Comment by andycraig** [comment]
Hi, `R: Run Command in Terminal` is intended for use via keybindings. Here's a section in the Wiki explaining it: https://github.com/REditorSupport/vscode-R/wiki/Keyboard-shortcuts#creating-keybindings-for-r-commands

To send code from the editor to the console, you want `R: Run Selection/Line`.

**Comment by multimeric** [comment]
Oh I see, so I would need to have set the `args` field for the command when attached to a keyboard shortcut. I'll try out the `Run Selection` command and see if that works.

**Comment by multimeric** [comment]
Yep, that was the correct command! Works well.
