### ISSUE TITLE
Equation rendering in HTML Help pages

### ISSUE THREAD

**Issue by bwiernik** [REditorSupport/vscode-R#1207]
**Is your feature request related to a problem? Please describe.**
R 4.2 added support for HTML5 in help pages: https://www.r-bloggers.com/2022/04/new-features-in-r-4-2-0/

Many of the features described above are working in VS Code (e.g., the Run Examples button, syntax highlighting), but equations are not being rendered correctly. R 4.2 supports either KaTeX or mathjaxr to render equations in help files such as in `?rnorm`.

**Describe the solution you'd like**
 Is it possible to make either katex (preferably) or mathjaxr available to render the equations in VS Code? VS Code ships with built-in KaTeX support for Markdown (https://code.visualstudio.com/updates/v1_58#_math-formula-rendering-in-the-markdown-preview), so it seems like it should be possible to enable for R help files.

**Comment by renkun-ken** [comment]
Thanks for bringing this up. It would be quite nice if we could make it work in help pages.

@ManuelHentschel It looks like katex resources are blocked in the webview.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/4662568/193055507-71c75379-baba-4f68-99fe-474c1ecca263.png">

Is it possible we could somehow make it work in the webview?
