### ISSUE TITLE
installation not possible

### ISSUE THREAD

**Issue by RichardCorbett** [REditorSupport/vscode-R#1212]
**Describe the bug**

VScode gives `'Failed to install 'reditorsupport.R'` error

**To Reproduce**

1. Go to Extensions in VScode menu
2. Search for REditorSupport
3. Click on 'install'
4. see "Failed to install 'reditorsupport.r'." error

**Can you fix this issue by yourself? (We appreciate the help)**

 No

However, I tried the following with no success:
After running 1-4 above, I accepted the suggestion to try and download it manually. The download is successful, getting a file named REditorSupport.r-2.5.3.vsix.

When i try and install using this downloaded package I don't get any errors, nor does any installation occur.

if I follow a link to the webpage for the extension: https://marketplace.visualstudio.com/items?itemName=REditorSupport.r and click on the green Install it opens vscode and asks me "Would you like to install the R extension?". When i click install I get a 'Server returned 404' error.

I should also note that I can install other extensions without error or warning through the extension manager.

NOTE:  I have the same question posted to stackoverflow here:
https://stackoverflow.com/questions/73821016/installing-reditorsupport-in-vscode-error

**Expected behavior**
Successful installation of the plugin

**Screenshots**
You can show the keyboard contents by pressing `F1` and `Developer: toggle screencast mode`

**Environment (please complete the following information):**

- OS:  Mac desktop, connected to a Linux machine through Remote-SSH
- VSCode Version: Version 1.36.1 (1.36.1)
- R Version: NA
- vscode-R version: NA

**Comment by andycraig** [comment]
Anyone have any ideas? It does seem specific to vscode-R since other extensions are installing normally. I haven't run into this problem before.

**Comment by andycraig** [comment]
@RichardCorbett Can you try checking the log, as described [here](https://stackoverflow.com/a/58241911/7785832)? (I don't think the solution described in that answer will help you since you can install most extensions, but the log might provide some useful information.)

**Comment by RichardCorbett** [comment]
Here's the log output (shared and window are the only ones creating output when i try to install)

Log (Shared)
```
[2022-10-14 14:02:48.887] [sharedprocess] [info] main {"machineId":"4ffbe14db8f5dd16ab4aea86dbb0f3da99be0ede2af0756cf8e120f5b8969a62"}
[2022-10-14 14:03:28.893] [sharedprocess] [info] Starting to clean up unused language packs.
[2022-10-14 14:03:30.382] [sharedprocess] [error] Failed to install extension: reditorsupport.r undefined
```

Log (Window)
```
[2022-10-14 14:06:57.964] [renderer1] [error] Server returned 404
```

**Comment by eitsupi** [comment]
> * VSCode Version: Version 1.36.1 (1.36.1)

Does it matter that vscode is too old? Does the problem occur in the latest vscode (Now 1.72)?

**Comment by renkun-ken** [comment]
Looks like the VS Code version is too old to install the extension.

**Comment by andycraig** [comment]
Thanks @eitsupi and @renkun-ken!

@RichardCorbett Did updating VS Code as suggested resolve the problem?

**Comment by RichardCorbett** [comment]
I finally got my VS code updated and now i'm able to install as expected.

**Comment by renkun-ken** [comment]
Glad to hear it works for you.
