### ISSUE TITLE
Error in knitting when spamming save

### ISSUE THREAD

**Issue by adriansletten** [REditorSupport/vscode-R#1214]
**Describe the bug**
I am working with RMarkdown in Vscode with preview window open to the side. When I press save the document is knitted, then the updated file is shown on the preview. 
My problem is that sometimes  an additional save is registered before knitting is finished, causing  a second knit to start. When the second one is done I get an error and the preview closes. The error is 

```
Error: pandoc document conversion failed with error 1
Execution halted
```

It is annoying that this causes the preview to close, and it is the reason I am filing this report.

**To Reproduce**

1. open a Rmd-file
2. Click on top right 'Open preview to the side'
3. Once the preview is open, 'ctrl+s' should trigger knitting  (message at bottom right) and  the preview to be updated.
4. To get error and cause preview to close, spam 'ctrl+s' until a second message saying "Knitting file to html preview" shows up

**Can you fix this issue by yourself? (We appreciate the help)**
No

**Expected behavior**
Triggering multiple knits should not result in preview being closed.

**Screenshots**
Here are the multiple messages that show up when spamming save.
![image](https://user-images.githubusercontent.com/70268798/194709031-d1c58ad3-6bbb-47e0-b377-8ee1a1546ad8.png)

**Environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.72
- R Version: 3.6.1
- vscode-R version: 2.5.3

**Comment by adriansletten** [comment]
seems to be the same issue as in #824

**Comment by renkun-ken** [comment]
Thanks for reporting!

@ElianHugh Looks like we need to keep a status for each `RMarkdownPreview` so that `fileWatcher` won't be triggered if a preview is still rendering.
