### ISSUE TITLE
Trouble Running R + Radian in VSCode for Mac M1

### ISSUE THREAD

**Issue by yepiserin** [REditorSupport/vscode-R#1220]
I've looked at various troubleshooting posts, I'm unable to run r code in VSCode

I've installed VSCode 1.72.0, and followed all of [these instructions](https://www.r-bloggers.com/2021/01/setup-visual-studio-code-to-run-r-on-vscode-2021/) which are referencing [this how-to](https://renkun.me/2019/12/11/writing-r-in-vscode-a-fresh-start/).  I installed the arm version of R 4.2.1 Patched and have Python 3.10 installed.

**To Reproduce**

1. Go to VS Code
2. Click on a test R file I saved on my desktop
3. Hit Command + Enter on the first line (just View(iris))
4. See error in screenshot (included settings.json file to show I have rterm and rpath set correctly with the radian bracketing option, as well.

<img width="1233" alt="Screen Shot 2022-10-10 at 1 09 51 PM" src="https://user-images.githubusercontent.com/114412799/194919998-86fc31c0-7778-4972-ba2e-72d6c8e2e0c3.png">

**Comment by psobolewskiPhD** [comment]
Wait, why is your R > Rterm not radian?
Also your RPath is strange. Can you try `which r`? For me it's `/usr/local/bin/r` which is my RPath in vscode

**Comment by psobolewskiPhD** [comment]
Can you try `which radian` as well, just to check that?
It's somehow related to text encodings I think, because when I use your snippet and do command-enter I get 
`r$> View(iris)     `
(But I've got radian in vs code)

**Comment by yepiserin** [comment]
I unchecked the bracketed setting and now it's working - should I be concerned that there is no "r$" in the terminal?  I wonder why this bracket step caused an issue:

![Screen Shot 2022-10-10 at 4 07 14 PM](https://user-images.githubusercontent.com/114412799/194944392-6cc5b983-7ac9-493a-a1ba-cec13379ce03.png)

**Comment by psobolewskiPhD** [comment]
You're not actually using radian for your R terminal in VS Code. You have just the vanilla R.
That's why you need to disable bracketed paste. That's needed for radian.
Try `which radian` from your terminal.

**Comment by yepiserin** [comment]
I'm not getting a result for "which radian" but do have rterm pointed to the correct (I think?) radian path:
![Screen Shot 2022-10-10 at 4 19 09 PM](https://user-images.githubusercontent.com/114412799/194945941-cf1e786f-2acd-47a9-b684-a504f6a7cab7.png)

**Comment by psobolewskiPhD** [comment]
> I'm not getting a result for "which radian" 

Can you elaborate? if you have radian installed properly, then `which radian` in the terminal should give you the path to it.
How did you install radian?

**Comment by yepiserin** [comment]
I installed radian using "pip3 install -U radian" in the terminal.  I get the expected results from that comman (i.e. "Requirement already satisified"), I get no response to commands "radian" or "which radian"

**Comment by psobolewskiPhD** [comment]
You must have some python environment issue then, where your radian isn't found.
What does `which pip3` say?

**Comment by yepiserin** [comment]
Results for which pip3 are "/usr/local/bin/pip3"

**Comment by psobolewskiPhD** [comment]
Ok, and `pip show radian`? or `pip list | grep radian`

**Comment by yepiserin** [comment]
Results below, is this confirming I had the wrong path for radian?

<img width="639" alt="Screen Shot 2022-10-10 at 4 32 48 PM" src="https://user-images.githubusercontent.com/114412799/194948194-7c353d24-91a2-4e4b-9827-3e685cbd345c.png">

**Comment by psobolewskiPhD** [comment]
Ok, so that shows that it is indeed installed into a python environment.
But you said `which radian` doesn't show it? and just `radian` at the terminal also doesn't work?

**Comment by yepiserin** [comment]
That's correct, radian and which radian return nothing in the terminal.  I updated the Rterm path, nothing has changed in VSCode yet - do I need to change Rpath or bracketing again?

![Screen Shot 2022-10-10 at 4 37 34 PM](https://user-images.githubusercontent.com/114412799/194948744-f1fcef5c-9fe9-4fbb-8c02-69e175dc8c34.png)

**Comment by psobolewskiPhD** [comment]
No, you need to get radian working first. If it's not working it doesn't matter what you do in the VS Code.

**Comment by yepiserin** [comment]
Ok I'll close this issue and re-open it in the radian github.  Thanks.

**Comment by psobolewskiPhD** [comment]
> Ok I'll close this issue and re-open it in the radian github. Thanks.

Once you can launch radian from the terminal (using `radian`), then you need to paste the path into `"r.rterm.mac":` and then set bracketed paste to true again.
