### ISSUE TITLE
Data/help viewer opening in a browser?

### ISSUE THREAD

**Issue by PMassicotte** [REditorSupport/vscode-R#1222]
**Is your feature request related to a problem? Please describe.**
Not an issue per se, but would it be possible to have the data/help viewer opening in a separate web browser, as it is already possible with graphics? I think it would be useful if you are working on a multi-monitor setup. 

**Describe the solution you'd like**
See my previous point.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thank you!

**Comment by ElianHugh** [comment]
Should be a simple change -- I can look into this  tonight

**Comment by ElianHugh** [comment]
Sorry -- didn't end up getting a chance to work on this. Had a closer look and it'll take a bit more effort than I anticipated, but should still be doable

**Comment by PMassicotte** [comment]
Looking forward it :)

**Comment by jooyoungseo** [comment]
There are already some related options that you can put in .Rprofile:

``` r
# Use an external browser for displaying html files, such as {gt} and {xaringan}
options(vsc.viewer = FALSE)
# External browser for web apps, such as {shiny}
options(vsc.browser = FALSE)
# View help page in an external browser
options(vsc.helpPanel = FALSE)
# Use original data viewer
options(vsc.view = FALSE)
```

**Comment by jooyoungseo** [comment]
@ElianHugh -- I think it would be easier for users to manage these options through extension settings instead of `.Rprofile` directly like we do for `httpgd` option.

**Comment by PMassicotte** [comment]
Just tried it and I noticed that the data viewer opens in a separate window where I can not filter, scroll the data. Any ways to make the view dynamics?

![image](https://user-images.githubusercontent.com/4519221/197335741-7a47d62f-2b56-425c-8847-1a215d677d9d.png)

**Comment by ElianHugh** [comment]
That is the default R viewer window (see https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/View). The vscode-R dataviewer doesn't currently support non-webview usecases
