### ISSUE TITLE
Outline and symbol recognition for R markdown

### ISSUE THREAD

**Issue by Babakfifoo** [REditorSupport/vscode-R#1223]
VScode has an outline panel that shows all sections of a markdown file. This feature is not working when a document is opened as R markdown file. Hence, in large notebooks or Rmd files, it is hard to navigate. 

Add the symbol recognition and outline feature of plain markdown to the R markdown interface

**Describe alternatives you've considered**
change the file type to markdown to find the section, then change it back to Rmd

**Comment by renkun-ken** [comment]
For the following rmd

````
---
title: new document
author: test
---

This is a test document.

## Hello

```{r}
rm(list = ls(all.names = TRUE))
x <- 1
y <- 2
```

Following is a test plot:

```{r}
plot(rnorm(100))
x <- list(a = 1)
```
````

The outline works like the following

<img width="294" alt="image" src="https://user-images.githubusercontent.com/4662568/196200349-a25cbf85-de5c-49ac-a445-4e80f461dc64.png">


Looks like your rmd file cannot be properly parsed in languageserver for some reason. Would you like to create a minimal example that does not work? Is there an error in "Output -> R Language Server"?
