### ISSUE TITLE
Rmd chunks don't run as one block with radian

### ISSUE THREAD

**Issue by derekschinke** [REditorSupport/vscode-R#1225]
**Describe the bug**
When running Rmd chunks with radian as the Rterm for mac, chunks are separated line by line, and thus multiline statements (like functions etc.) are split, and each line is run as if it is a separate statement.

**To Reproduce**

1. Create `.Rmd` file.
2. Create new chunk
3. Write a multiline statement, e.g.:
```
print(
  "hello"
)
```
5. Press "Run chunk"
6. `print(` is run, then `"hello"`, then `)`. Depending on the multiline expression, it typically results in an error.

**Can you fix this issue by yourself? (We appreciate the help)**

No

// R path for Mac OS X
"r.rterm.mac": "/opt/homebrew/Caskroom/miniforge/base/bin/radian",

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": false,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**
The chunk should run as one code block.

**Screenshots**
If applicable, add screenshots to help explain your problem.
You can show the keyboard contents by pressing `F1` and `Developer: toggle screencast mode`

**Environment (please complete the following information):**

- OS: macOS
- VSCode Version: 1.72.2
- R Version: 4.2.1
- vscode-R version: 2.6.0

**Comment by andycraig** [comment]
Changing `r.bracketedPaste` from `false` to `true` in your settings should fix it:

```json
"r.bracketedPaste": true,
```
