### ISSUE TITLE
Wrap lines longer than line_length_linter limit.

### ISSUE THREAD

**Issue by jackpeplinski** [REditorSupport/vscode-R#1226]
**Is your feature request related to a problem? Please describe.**
I get wavy line under my code when it is longer than 80 characters. For example:
<img width="942" alt="Screen Shot 2022-10-19 at 10 11 42 PM" src="https://user-images.githubusercontent.com/30737750/196839823-b249547a-3fe6-4c23-8206-0797b49bfab3.png">

**Describe the solution you'd like**
I wish the extension would break the line where possible. For example:
<img width="501" alt="Screen Shot 2022-10-19 at 10 12 08 PM" src="https://user-images.githubusercontent.com/30737750/196839868-618a9913-2912-4d36-aa9c-a4d0c65013ac.png">

**Comment by eitsupi** [comment]
See r-lib/styler#247
