### ISSUE TITLE
Plotting fails for `qgraph` when using a vertical layout

### ISSUE THREAD

**Issue by mihaiconstantin** [REditorSupport/vscode-R#1227]
**Describe the bug**

Plotting fails for `qgraph` when using a vertical layout (see below). However, using `layout(matrix(1:3, 1, 3))` seems to work.

**To reproduce**

```r
# Load library.
library(qgraph)

# Load data.
data(big5)

# Correlations.
graph <- cor(big5[, 1:10])

# Layout.
layout(matrix(1:3, 3, 1))

# Works.
layout.show(n = 3)

# Fails in Code.
qgraph(graph, title = "Plot 1")
qgraph(graph, title = "Plot 2")
qgraph(graph, title = "Plot 3")

# Reset.
layout(1:1)
```

**Screenshots**

https://user-images.githubusercontent.com/20051042/197187138-b96ece57-fb78-4fd3-a9ee-385a2c198e68.mp4

*works

**R version and OS:**

```txt
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          2.1                         
year           2022                        
month          06                          
day            23                          
svn rev        82513                       
language       R                           
version.string R version 4.2.1 (2022-06-23)
nickname       Funny-Looking Kid      
```

**VS Code version:**

```txt
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:55.763Z (1 wk ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

**vscode-R version:** `v2.6.0`

**Comment by renkun-ken** [comment]
Looks like it is a httpgd issue. @nx10 What do you think?

**Comment by nx10** [comment]
What version of httpgd are you using? Could you please try again with the current development version directly from GitHub? `remotes::install_github("nx10/httpgd")`

**Comment by mihaiconstantin** [comment]
@nx10, I was using version `1.3.0`, i.e., the one on [`CRAN`](https://cran.r-project.org/package=httpgd). I just tried with https://github.com/nx10/httpgd/commit/f44dae0885f60a7d04dab382c70191406690bf49 and it works. 

I'll make a note to remind myself to update packages next time... 😅

**Comment by nx10** [comment]
No problem at all, I want to make a new CRAN release for a while, but we're currently blocked by some issues with the new webserver library (https://github.com/CrowCpp/Crow/issues/546) nothing major, but until this is fixed CRAN will likely not accept it.

**Comment by mihaiconstantin** [comment]
I wasn't aware that CRAN also takes memory leaks into account. The [CrowCpp/Crow](https://github.com/CrowCpp/Crow) project looks very interesting&mdash;I'm happy you mentioned it!
