### ISSUE TITLE
Workspace garbles some objects in the global environment to make the object unreadable

### ISSUE THREAD

**Issue by davidnov** [REditorSupport/vscode-R#1229]
**Describe the bug**

The vscode-R Workspace garbles the appearance of some objects in the global environment to make the object unreadable. The object still exists in R, and behaves normally in the code otherwise.

**To Reproduce**

I can consistently produce this when I ``base::source()`` an R file I have with a bunch of proprietary utility functions that I can't share. I tried to make a reproducible example by guessing at what might be the cause, but was unsuccessful.

**Can you fix this issue by yourself?**

No

My only modifications to the default settings are below:

```jsonc
{
    "files.trimTrailingWhitespace": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.rulers": [
    
        {
            "column": 80,
            "color": "#ff00FF"
        },
        {
            "column": 120,
            "color": "#ff0000"
        },
    ],
    "editor.minimap.side": "left",
    "r.session.levelOfObjectDetail": "Detailed",
    "workbench.settings.useSplitJSON": true,
    "r.plot.useHttpgd": true,
    "r.bracketedPaste": true,
    "r.rterm.mac": "/Library/Frameworks/Python.framework/Versions/3.10/bin/radian",
    "r.session.emulateRStudioAPI": false,
    "editor.copyWithSyntaxHighlighting": false,
    "security.workspace.trust.untrustedFiles": "open"
}
```

**Expected behavior**
Clear, readable Global Environment entries.

**Screenshots**
<img width="321" alt="Screen Shot 2022-10-21 at 16 31 33PMEDT" src="https://user-images.githubusercontent.com/5544483/197288391-0278631e-00cf-412a-b86a-5c2598ecab40.png">

**Environment:**

- OS: macOS Catalina v10.15.7
- VSCode Version: 1.72.2
- R Version: 4.2.1
- vscode-R version: 2.6.0

**Additional context**
The Attached Namespaces and Loaded Namespaces both look fine, so only an issue for Global Environment.

**Comment by renkun-ken** [comment]
I could reproduce it with long function names and long function signature:

```r
long_function_names_with_something_to_be_done <- function(object1, object2, object3 = object1 + object2, object4 = findInterval(object1, object2)) {
  object1 + object2 + object3 + object4
}
```

<img width="318" alt="image" src="https://user-images.githubusercontent.com/4662568/197315873-88703d0c-16a0-406d-8d0f-c62b0a270025.png">

**Comment by davidnov** [comment]
Thank you for the quick reply! Now that you've drawn my attention to this (seems it is some sort of word wrapping-type behavior?) it seems to be purely about the function signature and not the function name per se.

For example, the following yields the same issue for me:

```
fun <- function(a, b, c, d, e){
    invisible(x)
}
```

but the following does not (one fewer parameter in the function)

```
fun <- function(a, b, c, d){
    invisible(x)
}
```

and the results don't change if, instead, name the function ```fun_really_really_really_really_ridiculously_long```
