### ISSUE TITLE
Plotting stars object crashes the R session

### ISSUE THREAD

**Issue by PMassicotte** [REditorSupport/vscode-R#1238]
**Describe the bug**

The R session crashes when I try to plot a `stars` [object](https://r-spatial.github.io/stars/articles/stars1.html) while it works fine inside RStudio IDE.

**To Reproduce**

```r
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)

plot(x)

Browsing http://127.0.0.1:44595/live?token=SpRPkKXU&sidebar=0

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: dev.capabilities()
 2: isTRUE(dev.capabilities()$rasterImage == "yes")
 3: image.default(dims[[dimx]], dims[[dimy]], ar, asp = asp, xlab = xlab,     ylab = ylab, xlim = xlim, ylim = ylim, axes = FALSE, useRaster = useRaster &&         !is_rectilinear(x), ...)
 4: image.stars(im, xlab = "", ylab = "", axes = axes, zlim = zlim,     breaks = br, col = col, key.pos = NULL, main = NULL, ...)
 5: image(im, xlab = "", ylab = "", axes = axes, zlim = zlim, breaks = br,     col = col, key.pos = NULL, main = NULL, ...)
 6: plot.stars(x)
 7: plot(x)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

Selection:
```

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- VSCode Version: 1.72.2
- R Version: 4.2.1
- vscode-R version: 2.6.0

**Comment by renkun-ken** [comment]
Does it occur if you don't use httpgd? Does it occur if you use the latest development version of httpgd?

Looks like an httpgd issue, @nx10, what do you think?

**Comment by nx10** [comment]
I can reproduce this error with the current CRAN version of httpgd.

It works as expected with the development version:

```R
remotes::install_github("nx10/httpgd")
```

**Comment by PMassicotte** [comment]
I confirm that the dev version works for me. Thank you for your work.
