### ISSUE TITLE
runSelection submits proceeding comments

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#1244]
Am wanting to re-open #438 as I was hoping to work on developing a PR for it. 

As far as I can see it there are 2 options to solve this

(1) Add a pre-processor that strips comments from the selected range
(2) Adjust `expandSelection` to not cover these lines

(1) is easier to implement but am thinking (2) is probably the more "proper" way of handling this. @renkun-ken any preference as to how to handle this ?

**Comment by gowerc** [comment]
My gut feeling is `expandSelection()` is very complex and potentially quite fragile to changes.  Currently white space is removed in post processing by the `trim()` method:

```
selection.selectedText = currentDocument.getText(selection.range).trim();
```

So would propose do post processing to remove header comments as well

**Comment by renkun-ken** [comment]
In a previous issue or PR (I forget which one), I find it useful to keep comments in the terminals so that when I scroll the terminal I could also read the comment to know about the code just like in the source code. But if the comment block has too many lines, it might be a bit annoying.

Maybe we could let user to opt-out removing leading comments if they find it annoying?

**Comment by gowerc** [comment]
Makes sense will add an argument flag to enable/disable the feature.   Any preferences on default? Personally I would argue that we should mirror rstudio which would be to have this enabled by default.

Likewise any thoughts on wether this should be for `expandselection()` only or for any submission to terminal ? I imagine the latter but I think I would need to re-do the implementation and it might also be more complicated :(

**Comment by renkun-ken** [comment]
The default behavior of RStudio is keeping the leading comments. I suggest we keep it as default too. User could opt-out the behavior by a setting.

I think `expandselection()` having this behavior is enough.

**Comment by gowerc** [comment]
I was thinking that I will re-work this so that it only applies to the automatic expansion. At the moment the current implementation also affects manually highlighted code sections which I don't think is desirable.

The Rstudio implementation seems to be space dependent i.e.

```
# l1
# l2
x <- c(
    2,
    3,
    4
)
```

Would include the comments whilst:

```
# l1
# l2

x <- c(
    2,
    3,
    4
)
```
Would not include the comments.... I don't think we should replicate this exactly, though it confuses me as to what our default should be.

**Comment by renkun-ken** [comment]
Closing.
