### ISSUE TITLE
`Error unexpected numeric constant` in the latest update on MacOS

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#1246]
Just updated `vscode-R` on my macbook.  

When I sent the code to the terminal, this happened

```
> 00~library(data.table)01~
Error: unexpected numeric constant in "00~library(data.table)01"
```

There is no such issue on the windows machine.

**Comment by renkun-ken** [comment]
If you are using radian, you need to turn on `r.bracketedPaste`. Otherwise, you need to turn if off.

**Comment by Fred-Wu** [comment]
> If you are using radian, you need to turn on `r.bracketedPaste`. Otherwise, you need to turn if off.

Thanks.  you are right. 

However, on my both Windows and MacOS, I disabled radian, but `r.bracketedPaste` are not turned off on both. 

The issue is only with MacOS, but not Windows.
