### ISSUE TITLE
Webview CSP blocks some htmlwidgets with web workers

### ISSUE THREAD

**Issue by anthonynorth** [REditorSupport/vscode-R#1260]
**Describe the bug**
Webview content security policy blocks web workers with blob urls. This prevents some htmlwidgets from rendering correctly (or at all) in the viewer.

**Can you fix this issue by yourself? (We appreciate the help)**
Yes. It's a 1-liner.

**(If yes,) can we assist you with anything?**
Let me know if you're ok with these directives for `worker-src` (which is currently not defined).
```
worker-src https: data: blob: filesystem:
```

**Comment by renkun-ken** [comment]
Thanks for reporting! WebView is known to have some limitation on certain usage of resources. Have you tried it and it actually works for you?

**Comment by anthonynorth** [comment]
The problem with webview in this instance is that the content-security-policy doesn't allow for blob sources. The linked PR addresses this.
