### ISSUE TITLE
Workspace does not reflect new variables in R session

### ISSUE THREAD

**Issue by soumyaray** [REditorSupport/vscode-R#1262]
**Describe the bug**
Workspace is not picking up any variables or activities run on my R terminal (opened using "R: Create R Terminal").

**To Reproduce**

1. Started VSCode in folder with R project.
2. Open R terminal using "R: Create R Terminal"
3. Enter "x <- 5" in terminal
4. Confirm in terminal that x is 5
5. Notice that no variables show in Workspace > Global Environment

**Can you fix this issue by yourself? (We appreciate the help)**

No

**Expected behavior**
Expected to see x value in Workspace > Global Environment when its uncollapsed.

**Environment (please complete the following information):**

- OS: MacOS
- VSCode Version: Version: 1.73.1 (Universal)
- R Version: 4.2.1
- vscode-R version: 2.6.1

**Comment by soumyaray** [comment]
I noticed that `r.sessionWatcher` was not in my settings so I added the following two settings:

```
"r.plot.useHttpgd": true,
"r.sessionWatcher": true
```

Restarted VSCode but still no changes.

**Comment by renkun-ken** [comment]
Looks like the session watcher does not successfully attach to the R terminal. Would you like to check out the output of `ls.str(.vsc)` in your terminal?

**Comment by soumyaray** [comment]
@renkun-ken 

Sadly:

```
> ls.str(.vsc)
Error in ls.str(.vsc) : object '.vsc' not found
```

**Comment by renkun-ken** [comment]
Looks like the terminal does not manage to start with `~/.vscode-R/init.R` sourced.

What happens if you manually run `source("~/.vscode-R/init.R")`?

**Comment by soumyaray** [comment]
@renkun-ken yes it works!  I now see variables I create in my global environment and plots also show (which they did not before).

If I reload my VSCode (Cmd-R) then it stops working and I have to close the R session, open a new R terminal, and source the init file again for it to get back to working.

Any thoughts on what/where I can make the script source automatically?

**Comment by renkun-ken** [comment]
The `R: Create R terminal` command should automatically do that, but not sure why it doesn't. Looks like you might need to follow the steps in <https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions> and put the init code in your `~/.Rprofile`.

**Comment by renkun-ken** [comment]
Do you have something already in your `~/.Rprofile`?

**Comment by soumyaray** [comment]
@renkun-ken I think you've nailed it.  I didn't have an `~/.Rprofile` to begin with, so perhaps any code the extension used to append it never worked.  I've manually created the file now and added the lines suggested in the (very helpful) wiki file you sent me. I can confirm that when I quit and reopen VSCode, the extension works beautifully!  Many thanks!  

I'll keep the issue open in case there is something to fix to handle missing `~/.Rprofile` files like my case. Please feel free to close it.

**Comment by renkun-ken** [comment]
"R: Create R terminal" should work without `~/.Rprofile` since it replaces enviornment variables like `R_PROFILE_USER` to make the session source the init file. Would you like to put the output of `Sys.getenv()` so that we might see what prevents the R session from sourcing the init script.

**Comment by soumyaray** [comment]
Understood.  Here is the results of `Sys.getenv()` – I've only redacted my local username with `<username>` to blind it from search engines:

```
__CF_USER_TEXT_ENCODING
                        0x1F5:0x0:0x0
__CFBundleIdentifier    com.microsoft.VSCode
COLORTERM               truecolor
COLUMNS                 68
COMMAND_MODE            unix2003
DISPLAY                 /private/tmp/com.apple.launchd.XWYVxY7LQB/org.xquartz:0
DYLD_FALLBACK_LIBRARY_PATH
                        /Library/Frameworks/R.framework/Resources/lib:/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server
EDITOR                  micro
GIT_ASKPASS             /Applications/Visual Studio
                        Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
HOME                    /Users/<username>
HOMEBREW_CELLAR         /opt/homebrew/Cellar
HOMEBREW_PREFIX         /opt/homebrew
HOMEBREW_REPOSITORY     /opt/homebrew
INFOPATH                /opt/homebrew/share/info:
LANG                    en_US.UTF-8
LC_CTYPE                UTF-8
LESS                    -R
LINES                   41
LN_S                    ln -s
LOGNAME                 <username>
LSCOLORS                Gxfxcxdxbxegedabagacad
MAKE                    make
MallocNanoZone          0
MANPATH                 /opt/homebrew/share/man::
ORIGINAL_XDG_CURRENT_DESKTOP
                        undefined
PAGER                   less
PATH                    /Users/<username>/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Users/<username>/.cargo/bin
PWD                     /Users/<username>/Sync/Dropbox/Research/My
                        Papers/Working Papers/Privacy Control Paper
                        Shared/Model Redesign/data-code
R_ARCH                  
R_BROWSER               /usr/bin/open
R_BZIPCMD               /usr/bin/bzip2
R_DOC_DIR               /Library/Frameworks/R.framework/Resources/doc
R_GZIPCMD               /usr/bin/gzip
R_HOME                  /Library/Frameworks/R.framework/Resources
R_INCLUDE_DIR           /Library/Frameworks/R.framework/Resources/include
R_LIBS_SITE             /Library/Frameworks/R.framework/Resources/site-library
R_LIBS_USER             /Users/<username>/Library/R/arm64/4.2/library
R_PAPERSIZE             a4
R_PDFVIEWER             /usr/bin/open
R_PLATFORM              aarch64-apple-darwin20
R_PRINTCMD              lpr
R_PROFILE_USER          
R_PROFILE_USER_OLD      
R_QPDF                  /Library/Frameworks/R.framework/Resources/bin/qpdf
R_RD4PDF                times,inconsolata,hyper
R_SESSION_TMPDIR        /var/folders/vn/gm5v6xsn65v5ct5nj1jl3n540000gn/T//RtmpXdyz8S
R_SHARE_DIR             /Library/Frameworks/R.framework/Resources/share
R_STRIP_SHARED_LIB      strip -x
R_STRIP_STATIC_LIB      strip -S
R_SYSTEM_ABI            macos,gcc,gxx,gfortran,gfortran
R_TEXI2DVICMD           /opt/R/arm64/bin/texi2dvi
R_UNZIPCMD              /usr/bin/unzip
R_ZIPCMD                /usr/bin/zip
RBENV_SHELL             zsh
SED                     /usr/bin/sed
SHELL                   /bin/zsh
SHLVL                   2
SSH_AUTH_SOCK           /private/tmp/com.apple.launchd.Z769J2Pj60/Listeners
TAR                     /usr/bin/tar
TERM                    xterm-256color
TERM_PROGRAM            vscode
TERM_PROGRAM_VERSION    1.73.1
TERM_SESSION_ID         17E6B2C7-C694-4BCB-9298-004BF89FA61C
TMPDIR                  /var/folders/vn/gm5v6xsn65v5ct5nj1jl3n540000gn/T/
TZDIR                   /var/db/timezone/zoneinfo
USER                    <username>
VSCODE_GIT_ASKPASS_EXTRA_ARGS
                        --ms-enable-electron-run-as-node
VSCODE_GIT_ASKPASS_MAIN
                        /Applications/Visual Studio
                        Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_ASKPASS_NODE
                        /Applications/Visual Studio
                        Code.app/Contents/Frameworks/Code
                        Helper.app/Contents/MacOS/Code Helper
VSCODE_GIT_IPC_HANDLE   /var/folders/vn/gm5v6xsn65v5ct5nj1jl3n540000gn/T/vscode-git-5ea11bbb05.sock
VSCODE_INIT_R           /Users/<username>/.vscode/extensions/reditorsupport.r-2.6.1/R/session/init.R
VSCODE_WATCHER_DIR      /Users/<username>/.vscode-R
XPC_FLAGS               0x0
XPC_SERVICE_NAME        application.com.microsoft.VSCode.263082433.263082439.DA537054-33A5-4E5E-BD03-1BB4A9B60B41
ZSH                     /Users/<username>/.oh-my-zsh
```

**Comment by soumyaray** [comment]
To be clear, the above is the env info from a working reditor session after I edited my `~/.Rprofile` and restarted vscode. If you want, I can also clear out my `~/.Rprofile`, restart vscode, and get this env info again.

**Comment by ElianHugh** [comment]
> @renkun-ken Quick question: Am I supposed to open R terminals using "R: Create R Terminal" or "R: Attach Active Terminal"?  The latter seems to work well to integrate into vscode-r whereas the former needs me to run the init file suggested above.

Both can be used. "attach" is for when you are using a self-managed R session, "create" just does the attaching for you.

**Comment by soumyaray** [comment]
Thanks so much. The Attach option is working for me while Create does not.
