### ISSUE TITLE
Upcoming changes in the knitr progress bar

### ISSUE THREAD

**Issue by yihui** [REditorSupport/vscode-R#1263]
**Is your feature request related to a problem? Please describe.**

We are currently working on condensing the knitr progress bar: https://github.com/yihui/knitr/issues/1880. I'm filing this issue to check if the changes would affect the progress tracking in this extension: https://github.com/REditorSupport/vscode-R/wiki/R-Markdown#progress-tracking

**Describe the solution you'd like**

The form of the progress bar will be changed from

```
  |...   | x%
label: foo (with options)
  str(options)
```

to

```
  |...   | x% chunk: foo
```

I don't know the assumptions of this extension when parsing the percentages. If it only looks for `x%` no matter where it appears, it's probably going to be okay. If it assumes that `x%` appears at the end of a line, it may be broken with a future version of **knitr**.

You can install the dev version of **knitr** to verify:

```r
remotes::install_github('yihui/knitr')
```

**Additional context**

In a future version of **knitr**, users may also be able to provide their custom progress bars (https://github.com/yihui/knitr/pull/2196). If they do, the progress tracking may not work, since we can't predict the form of the progress bars, but I guess that might be fine---if users customize the progress bar, that means they prefer their own style of progress tracking.

Thanks!

**Comment by renkun-ken** [comment]
Thanks for the information! Currently, we simply capture the percentage that appears in the log with

https://github.com/REditorSupport/vscode-R/blob/e7fcb1d85ff0425ac90f67f73979f2f2fa339bf4/src/rmarkdown/manager.ts#L125

As long as there is a percentage number in `x%` it should not be broken.

**Comment by renkun-ken** [comment]
I test with the latest knitr dev and the progress works as expected.

**Comment by yihui** [comment]
Great! Thank you for the confirmation! Then I'll close this issue.

BTW, the PR https://github.com/yihui/knitr/pull/2196 will make it possible to use a custom progress bar. Perhaps this vscode extension can also use this feature to create a native vscode progress bar directly.
