### ISSUE TITLE
bug in the R interpreter?!

### ISSUE THREAD

**Issue by carlosmandoz** [REditorSupport/vscode-R#1264]
Hi,

please see this issue: https://github.com/microsoft/vscode/issues/167221

I copy the text here:

I work on a MAC with newest R version and just switched from ATOM to VSCODE. I encountered a weird problem I hope you can help me solve: I have an R script that I can run through line by line using CMD + ENTER. No problems. However, if I mark all code and hit CMD + ENTER all code is run, too (as expected) but the script encounters several errors. This makes zero sense. The script is fine and there are no errors (I am very experienced in R + I can run the same code all at once in e.g. Rstudio). Thus, something is off with the system in vscode to run code. If I press CMD + ENTER too fast between the lines of codes, I also encounter this issue.

Any idea what this could be and how I can solve that?

even if I disable all extensions except the REditorSupport (which I think is necessary to run R code), the problem persists: I can run through the code line by line if I make sure not to go too fast but if I go too fast or all at once, I get errors that are no correct errors...

**Comment by renkun-ken** [comment]
Are you using radian or official R terminal?

**Comment by carlosmandoz** [comment]
official R terminal. I guess it should work with either terminal, right?

**Comment by renkun-ken** [comment]
Official R terminal has a known limitation of reading 4096 bytes per line. You might want to try [radian](https://github.com/randy3k/radian) and enable `r.bracketedPaste` in vscode settings.

**Comment by carlosmandoz** [comment]
thank you!! I will try it. I never experienced any issues when using the normal terminal (e.g. in ATOM, Rstudio or just in Mac terminal). I will report back if this will fix it!

**Comment by carlosmandoz** [comment]
fixed it
