### ISSUE TITLE
Add a command to focus on attached R terminal

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#1265]
This is a feature request. When interacting with multiple terminal instances (e.g., bash, Python, and R to name a few) in VSCode, users may want to quickly focus on attached R terminal. Adding this command would be instrumental.

**Comment by albertosantini** [comment]
Just to mitigate the scenario, you can switch from editor to the terminal typing ctrl+` (control + backquote).
Then you may switch between the terminals using ctrl+pgup or ctrl+pgdown (control + page up o control + page down).
