### ISSUE TITLE
View() opens pop-up window

### ISSUE THREAD

**Issue by werkstattcodes** [REditorSupport/vscode-R#1272]
I updated today REditor Support to v2.7.0 and noticed a new behavior which seems odd to me:

In the past when using View(my_dataframe), the dataframe would open in a new tab in VS Code. This was
very convenient, since I could filter etc. columns.

Now when I use View(my_dataframe), a pop-up window comes up, which looks like a crude html representation
of the dataframe. It's not attached as a tab to VS Code, but floating. It can't be filtered. Is there any way to get the previous 
behavior back? 

Many thanks.

- OS: Windows 10
- VSCode Version: 1.73.1
- R Version: 4.2
- vscode-R version: v2.7.0

**Comment by ratnanil** [comment]
Why did you close this issue? Did you find a solution? I have the same problem!


    OS: Ubuntu 22.04.2 LTS (64-Bit)
    VSCode Version: 1.78-2
    R Version: 4.2.2
    vscode-R version: v2.8.1

**Comment by renkun-ken** [comment]
Would you like to check if vscode-R session watcher is attached to your R session via `ls.str(.vsc)`?

**Comment by ratnanil** [comment]
I would! Is `ls.str(.vsc)` an R Command? If so, the object `.vsc` does not exist.
