### ISSUE TITLE
Better math support for R Markdown

### ISSUE THREAD

**Issue by brendanford24** [REditorSupport/vscode-R#1279]
I use R Markdown a lot for taking statistics/data science notes and a big part of this is writing math equations and R code chunks.  The R code chunk functionality of vscode-R is great (thanks so much for all your hard work), however, I really wish I could see my maths equations as I type. 

I think this may be achieved via either:
    - Inline math rendering; and/or
    - Real live preview for R markdown, i.e. markdown text and math is rendered as you type and r chunks only on save (not sure if possible). 

There are extensions which currently do both these things for markdown files, although I know markdown doesn't run any code. 

Currently I'm writing my math equations in a markdown file to use the inline math preview, but its a bit clumsy. Please help! 😅

**Comment by eitsupi** [comment]
Have you try the Quarto extension?
For uses like yours, I think you will most likely be able to migrate from R Markdown to Quarto.
https://quarto.org/docs/tools/vscode.html#live-preview

**Comment by brendanford24** [comment]
Hi thanks for you help. I have given quarto a go and it seems to do most of what I want. Thanks for you help.
