### ISSUE TITLE
After attaching R, some other (invalid) code is being sent into the R console by VScode.

### ISSUE THREAD

**Issue by jordantgh** [REditorSupport/vscode-R#1282]
**Describe the bug**
When I do not have an active R session attached in VS code, if I press the button at the bottom right to attach one (shown below)

![image](https://user-images.githubusercontent.com/56029559/208322629-b4d09002-0dae-4ad0-bce8-22ed6d68f747.png)
...it does the expected '.vsc.attach()' command in the R console, but it also adds an unexpected `conda activate` command:

![image](https://user-images.githubusercontent.com/56029559/208322579-814abec4-b315-486c-ae36-d51bb4515e9d.png)
This does not happen when I press the button again after the session is already attached, it just runs '.vsc.attach()' again.

**Environment (please complete the following information):**

- OS: [Windows 11 client SSH into Ubuntu 22.04 host]
- VSCode Version: [e.g. 1.74.1]
- R Version: [e.g. 4.2.2]
- vscode-R version: latest, just installed today

**Additional context**
When I was installing R, I may have been (mistakenly) in the conda "p110" environment. But AFAIK that shouldn't matter.

All I really need to know is where this command may be being stored so that I can remove it. Apart from looking ugly, it doesn't affect anything, since the command is not functional in Radian (obviously). 

I have tried restarting my client machine and this hasn't fixed it. I will not be able to restart the host in the next couple of days.

**Comment by andycraig** [comment]
This is almost certainly coming from the Python extension: https://github.com/microsoft/vscode-python/issues/11039

**Comment by s1349795** [comment]
Thanks. I found your issue on this from a couple of years ago. Setting `"python.terminal.activateEnvironment": false` seemed to do the trick.
