### ISSUE TITLE
Add support for the thematic package for Rshiny dynamic themes for plots

### ISSUE THREAD

**Issue by ml-koch** [REditorSupport/vscode-R#1283]
**Is your feature request related to a problem? Please describe.**
I switched from RStudio to VScode and am working on an Rshiny app that includes a ggplotly object as output. When loading the package `thematic` via `thematic_shiny()` the shiny app displays "Warning: Error in getThemeInfo: This {rstudioapi} function is not currently implemented for VSCode". 

It works fine without the dynamic theming but I would like users to be able to select themes that also change for plots. 

**Describe the solution you'd like**
If i understand the message correctly it could work but needs support from the rstudioapi in vscode. 

**Describe alternatives you've considered**
I considered adding theme arguments to the ggplot object but that would give them one static look. 
Its fine but its more convenient in Rstudio

**Additional context**

https://user-images.githubusercontent.com/120103502/208549373-93df0c6a-2040-4ed7-ba66-6a0638802620.mp4

**Comment by renkun-ken** [comment]
`rstudioapi::getThemeInfo()` is not yet implemented in VS Code. In RStudio, the function returns a list like the following:

```
$editor
[1] "Textmate (default)"

$global
[1] "Modern"

$dark
[1] FALSE

$foreground
[1] "rgb(0, 0, 0)"

$background
[1] "rgb(255, 255, 255)"
```

The information could be obtained via VS Code Extension API:

* https://code.visualstudio.com/api/references/vscode-api#ThemeColor
* https://code.visualstudio.com/api/references/theme-color
