### ISSUE TITLE
No clear way to configure which R version radian uses

### ISSUE THREAD

**Issue by jkroes** [REditorSupport/vscode-R#1284]
**Describe the bug**
`Rpath: Windows` has no effect on `Rterm: Windows`, at least when the latter is a path to a radian executable. 

**To Reproduce**
1. On Windows 10, install radian. 
2. Set `Rterm: Windows` to the radian executable path. E.g., C:\Users\USER\AppData\Roaming\Python\Python37\Scripts\radian.exe.
4. Set `Rpath: Windows` to some nonstandard (user?) location. E.g. C:\Users\USER\Documents\R\R-4.2.1\bin\R.exe.
5. Source an R script or execute some lines (Control-Enter) in the script. 
6. A radian console starts, using the executable installed on a standard (system?) location, ignoring `Rpath: Windows`. E.g. radian runs C:\Program Files\R\R-4.2.2\bin\R.exe.

**Can you fix this issue by yourself? (We appreciate the help)**

HACK: Edit `PATH` in the user environment variables window on Windows 10 to include your desired R path. E.g. C:\Users\USER\Documents\R\R-4.2.1\bin. 

**(If applicable) Please attach `setting.json`**

```jsonc
{
    "r.rpath.windows": "C:\\Users\\jkroes\\Documents\\R\\R-4.2.1\\bin\\R.exe",
    "r.rterm.windows": "C:\\Users\\jkroes\\AppData\\Roaming\\Python\\Python37\\Scripts\\radian.exe"
}
```

**Expected behavior**
There's no clear documentation of how to configure radian to use a specific R interpreter/executable. I surmised that `Rpath: Windows` might be the way to do so. I understand this might well be incorrect.

**Environment (please complete the following information):**

- OS: Windows 10
- VSCode Version: 1.74.0
- R Version: 4.2.1 (desired) and R-4.2.2 (actual)
- vscode-R version: 2.7.0

**Comment by andycraig** [comment]
Another way to do it is use the `--r-binary` argument to radian (https://github.com/randy3k/radian#how-to-switch-to-a-different-r-or-specify-the-version-of-r). This can be specified in your `settings.json` in the setting `r.rterm.option`.

**Comment by weir12** [comment]
@andycraig I have the same confusion .  in #1322
