### ISSUE TITLE
Extension messages: cannot register r.rpath.windows / r.path.mac /r.path.linux

### ISSUE THREAD

**Issue by mabuimo** [REditorSupport/vscode-R#1289]
![image](https://user-images.githubusercontent.com/20048041/212201593-4352e9db-70f7-46e7-9dae-249eab1ff13e.png)

**Comment by renkun-ken** [comment]
The [R Debugger](https://marketplace.visualstudio.com/items?itemName=RDebugger.r-debugger) extension and vscode-R share these settings. Not sure if there is a way to suppress these messages.

**Comment by yuliaUU** [comment]
worked for me:  uninstalled R Debugger, then installed R Extension for Visual Studio and set r.path there. only after that R Debugger- after that no more messages like that
