### ISSUE TITLE
Working with an *.Rmd file, I can't execute chunks that are set to use "python" or "bash", without setting  switching my active terminal to the required language.

### ISSUE THREAD

**Issue by simonleandergrimm** [REditorSupport/vscode-R#1294]
Working with an *.Rmd file, I can't execute chunks that are set to use "python" or "bash", without setting  switching my active terminal to the required language.

For instance, executing this chunk in Rstudio works: 
![image](https://user-images.githubusercontent.com/58591538/215527661-d6bfbbdb-a855-4c93-aad7-7cd83631cc53.png)

While in VSCode I get the following error, if I don't switch terminals away from R:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/58591538/215527634-62ab2aa6-df0c-4325-ac21-3a125e3c02a4.png">

My settings file can be found here:
[defaultSettings.txt](https://github.com/REditorSupport/vscode-R/files/10537420/defaultSettings.txt)
**Environment**

- OS: macOS
- VSCode Version: 1.72.2
- R Version: 4.2.1
- vscode-R version: 2.7.0

**Comment by eitsupi** [comment]
I don't think this is a bug, just that vscode-R does not support execution of anything other than R code chunks.

I recommend trying the Quarto extension, which supports execution of Julia, Python, and R code blocks.
https://quarto.org/docs/tools/vscode.html
