### ISSUE TITLE
No plot viewer shown in vscode 

### ISSUE THREAD

**Issue by EngineeringScholar** [REditorSupport/vscode-R#1297]
httpgd package was installed, and r.plot.useHttpgd is set to true. However running a simple plot command, plot(rnorm(100)) as an example, only outputs a Rplots.pdf file. I was expecting a plot viewer panel in the vscode, like in Rstudio. Is this a bug or I missed something? 
I have R4.2.2 installed and Radian, languageserver, vscDebugger all installed, along with R extension and R Debugger extension. Googling all day long, but no solution found on this. Thanks.

**Comment by renkun-ken** [comment]
Do you use `R: Create R terminal` to start a new R session?

Would you like to post the value of `ls.str(.vsc)` and `getOption("device")` from your R terminal?

**Comment by EngineeringScholar** [comment]
Thanks so much for responding! I got similar errors when running `ls.str(.vsc)` and `getOption("device")`. I'm new to vscode. Thanks.
`getOption : The term 'getOption' is not recognized as the name of a cmdlet, function, script file, or operable    
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ getOption("device")
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (getOption:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by EngineeringScholar** [comment]
This is probably a stupid question - how do you use R: Create R terminal to start a new R session? in vs code code, I simply typed `R: Create R terminal` in the terminal, and got error:
![image](https://user-images.githubusercontent.com/121742301/217014700-49d7f958-2654-4ca0-b3c4-a3ab9832a3be.png)

Then I tried to attach R session by clicking on the bottom "R: (not attached)", it also failed
![image](https://user-images.githubusercontent.com/121742301/217015155-0f7cb01f-9738-4d6c-9758-ec3d5e9af7c0.png)

**Comment by eitsupi** [comment]
@EngineeringScholar Have you checked the wiki?
https://github.com/REditorSupport/vscode-R/wiki/Interacting-with-R-terminals

**Comment by EngineeringScholar** [comment]
I read the wiki. It seems the problem is that my vs code could not find R client:
![image](https://user-images.githubusercontent.com/121742301/217017647-9a336a5f-2aa7-40ac-a99a-95566a8a1058.png)

I have R installed in C: for all user with the following paths set in windows:
![image](https://user-images.githubusercontent.com/121742301/217017991-444f0aa8-0318-4914-bcb1-601bd6d679b5.png), but Radian installed to Users AppData/Roaming/Python/Python311/Scripts/radian folder, which there was not a way I know of to change the installation path.

I wonder if this has to do with where

**Comment by EngineeringScholar** [comment]
Update: I disabled radian in Json settings, and it worked!! not sure why radian is causing the problem though.
