### ISSUE TITLE
Unable to access python objects in R through reticulate::py when editing Quarto qmd files.

### ISSUE THREAD

**Issue by marsiwiec** [REditorSupport/vscode-R#1299]
**Describe the bug**
When editing a Python/R qmd file in VSCode I can execute R and Python blocks but I cannot use reticulate to access objects made in Python.

Calling py$python_object returns empty and there are no matches after pressing tab in the repl. Seems like the contents from Python cells are not being exposed to calls from R cells?

The appropriate Python environment is activated in vscode and the same document works in RStudio.

**To Reproduce**

1. Open/Create a .qmd file in VSCode
2. Add a Python cell, create some Python objects.
3. Run Python cell.
4. Add an R cell, try to access Python objects through reticulate::py
5. py$<python_object> returns empty, with no available completions in the REPL for py$

**Can you fix this issue by yourself? (We appreciate the help)**
No

```jsonc
// R path for Mac OS X
"r.rterm.mac": "/usr/local/bin/R",

```

**Expected behavior**
Calling reticulate::py$<python_object> should return the object in the R environment. Tab-activated completion for reticulate::py$ in the REPL should result in a list of Python objects.

**Environment (please complete the following information):**

- OS: macOS Ventura 13.2
- VSCode Version: 1.75.0
- R Version: 4.2.2
- vscode-R version: 2.7.0

**Comment by eitsupi** [comment]
Unfortunately, this is not possible because Python and R run in separate sessions.

**Comment by marsiwiec** [comment]
I understand. Thanks for the reply, that is what I suspected. Perhaps it would be possible to somehow expose the Python objects to the R session by automatically copying them through reticulate::repl anytime the extension detects two languages in a qmd and reticulate being used?

**Comment by eitsupi** [comment]
> Perhaps it would be possible to somehow expose the Python objects to the R session by automatically copying them through reticulate::repl anytime the extension detects two languages in a qmd and reticulate being used?

That feature request probably needs to be made there https://github.com/quarto-dev/quarto.

**Comment by marsiwiec** [comment]
I understand, thank you.

**Comment by marsiwiec** [comment]
Although this feature works in RStudio and I've posted this issue on Quarto and got this reply:

              Completion within VS Code is actually delegated to the R extension. Not sure if it is reticulate aware. You can follow up by posting an issue there: https://github.com/REditorSupport/vscode-R

_Originally posted by @jjallaire in https://github.com/quarto-dev/quarto/issues/77#issuecomment-1424129778_

**Comment by ElianHugh** [comment]
Out of interest (away from a computer at the moment), does names(reticulate::py) return NULL as well? Like @eitsupi said, the R extension doesn't have access to python values (theoretically unless called through reticulate)

**Comment by eitsupi** [comment]
My understanding is that the Quarto VS Code extension sends code in python code blocks to ipython.
If we want to use reticulate for python code blocks, I think we need to modify the Quarto VS Code extension.

**Comment by marsiwiec** [comment]
Hi @ElianHugh, yeah, names(reticulate::py) returns NULL as well. RStudio supports python/R cell execution in the same session by automatically wrapping code from python cells in reticulate::repl_python(). That way we stay in the R session and python objects are available in R.

So @eitsupi is right and it has nothing to do with vscode-R and we need to modify the Quarto VC Code extension.

**Comment by eitsupi** [comment]
This feature was implemented in the VS Code Quarto extension, so we can close this.
See quarto-dev/quarto-cli#2313
