### ISSUE TITLE
Option to source with echo

### ISSUE THREAD

**Issue by Wazarr94** [REditorSupport/vscode-R#1301]
Would it be possible to add an option when you run a script? RStudio offers this functionality and it's important to me, I use the tidylog library that shows what the line you ran results in, and not having the lines that gives the logs makes it unreadable for my large script.

I was thinking that you could add an arrow that gives the additional option, just like the Python extension does:
![image](https://user-images.githubusercontent.com/39807740/218441998-6bb3299e-4d0f-47cc-bfef-dd3db365d86d.png)

Thanks

**Comment by renkun-ken** [comment]
Looks like you are looking for #1286.

**Comment by Wazarr94** [comment]
I wanted to elaborate and forgot about it. The point of the issue is to do something similar from RStudio: once you click the option source with echo, the default source setting would be echo=TRUE and inversely.
I was wondering if it would be possible to mimic this behavior if it is easy enough, otherwise using the shortcuts is just fine.

**Comment by Wazarr94** [comment]
closing as after more time, I think Ctrl+Shift+Enter and Ctrl+Enter is more than enough for me
