### ISSUE TITLE
TOC / Outline

### ISSUE THREAD

**Issue by royfrancis** [REditorSupport/vscode-R#1320]
Would it be possible to add a floating TOC/outline similar to RStudio for `.R`, `.Rmd` and `.qmd` filetypes?

![Screenshot from 2023-03-04 16-42-17](https://user-images.githubusercontent.com/5083500/222919266-7a301598-fb9a-4747-bba3-5e336f6ca2de.png)

**Comment by renkun-ken** [comment]
Code sections are already provided by languageserver for R and Rmd.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/4662568/222936887-a793b222-e854-47d9-8bad-1ccd657d7427.png">

**Comment by royfrancis** [comment]
Fantastic! Hadn't noticed that. Thanks!
