### ISSUE TITLE
What is the actual effect of the r.rpath variable?

### ISSUE THREAD

**Issue by weir12** [REditorSupport/vscode-R#1322]
Hi:

I'm a freshman of vscode-r.I found that the role of `r.rterm` is to specify the fore-end shell of R,when I clicked the `run source` button of an R script. However, I was dismayed to find that` r.rpath` could not provide the back-end interpreter for` r.rterm`. I had to use `-- r-binary `to specify the interpreter for` r.rterm`. So I am confused about the role of the `r.rpath` variable and the real time when it is called.

Many thanks！

**Comment by weir12** [comment]
For example:

```
"r.rterm.linux": "/cluster/home/anaconda3/envs/r/bin/radian",

"r.rpath.linux": "/cluster/home/anaconda3/envs/r/bin/R",
```



The above settings will only activate the `R `with higher priority in the environment variable and the specified `radian`, not the expected ` R` in r.rpath


```
    "r.rterm.linux": "/cluster/home/anaconda3/envs/r/bin/radian",
    "r.rterm.option": [
        "--no-site-file",
        "--r-binary=/cluster/home/anaconda3/envs/r/bin/R"
    ],
    "r.rpath.linux": "/cluster/home/anaconda3/envs/r/bin/R",
```
The method I found to specify the R interpreter path for radian.

**Comment by ElianHugh** [comment]
At the moment, this is how `r.rterm` and `r.rpath` work:

- r.rpath:
	- used for vscode-R background processes, such as linting, knitting, etc
	- is used *as a backup* when r.rterm is not specified
- r.rterm
	- used for the creation of terminals
	- does not use the path in r.rpath

if you would like to specify the binary for the rterm when using radian, you will have to rely on setting the env var as you suggested
