### ISSUE TITLE
R Language Server client: couldn't create connection to server

### ISSUE THREAD

**Issue by sahaavi** [REditorSupport/vscode-R#1326]
**Describe the bug**
R Language Server client: couldn't create connection to server.
  Message: write ECONNRESET
  Code: -32099 

**To Reproduce**
Open any .R file in vscode.

**Screenshots**
![image](https://user-images.githubusercontent.com/55613672/224522333-103f204c-e5dc-4933-a91f-2efa6800d8a3.png)
![image](https://user-images.githubusercontent.com/55613672/224522409-13e52c5a-8199-477b-a96e-5f868e030c6c.png)

**Environment (please complete the following information):**

- OS: Windows 11
- VSCode Version: 1.76.1
- R Version: [e.g. 3.6.2]
- vscode-R version: 4.2.2

**Additional context**
If I run the R file then it says 
`Error in library(dash) : there is no package called 'dash'`

**Comment by renkun-ken** [comment]
From the log, it looks like you don't have `callr` installed. Would you install all dependencies and see if the error still occurs?

**Comment by sahaavi** [comment]
I found the solution.

**Solution**
change setting for “r.rterm.windows” to “C:/Program Files/R/R-4.2.1/bin/R.exe”

Solution link: https://fanwangecon.github.io/R4Econ/development/install/htmlpdfr/fs_install_R.pdf
