### ISSUE TITLE
WebR

### ISSUE THREAD

**Issue by ElianHugh** [REditorSupport/vscode-R#1335]
**Is your feature request related to a problem? Please describe.**
An early version of WebR has recently been released on npm, and I think it brings with it some potential development avenues for vscode-R. It might be interesting to see how we could leverage WebR in a few ways:

- WebR as a terminal when an R executable isn't available
- WebR in place of R for web vscode
- WebR for LSP or session watcher behaviour

Many of these features will require WebR to mature a bit more (e.g., packages have to be manually compiled to wasm right now), but I think it's something worth look into in the long run

**Comment by renkun-ken** [comment]
Thanks for the summary of thoughts. Yes, I was thinking about this too. Looks like we could play around and try to embed it in vscode-R and see if it could work properly as a starting point.

**Comment by renkun-ken** [comment]
Following repos could be helpful:

* https://github.com/georgestagg/webr-webpack-example

**Comment by ElianHugh** [comment]
a WebR with pre-bundled LSP, lintr, jsonlite, etc would significantly ease the onboarding for the extension too!
