### ISSUE TITLE
no .RData after running the code

### ISSUE THREAD

**Issue by dfmjndm** [REditorSupport/vscode-R#1336]
Hello, this is a very convenient plugin. Thank you for your work. However, I have encountered some problems while using it. When I open an R file and run part of the code, I cannot see the variable results after running the code in the workspace. It seems that I need to open an RData file in the workspace, but I cannot find the RData file on my desktop (my R file is on my desktop). So I created a new.RData file, but the plugin prompted me that it was a blank RData and could not be used.

**Comment by dfmjndm** [comment]
here's part of my setting.json

  "r.rterm.windows": "D:\\Python310\\Scripts\\radian.exe",
  "r.rterm.option": [
    "–no-site-file"
  ],
  "r.rpath.windows": "D:\\R-4.2.3\\bin\\R.exe",
  "r.bracketedPaste": true,
  "r.session.levelOfObjectDetail": "Normal",
  "r.helpPanel.cacheIndexFiles": "Workspace",
  "r.lsp.debug": true,

**Comment by dfmjndm** [comment]
![image](https://user-images.githubusercontent.com/57401901/227690604-baec80af-5592-4138-b0f9-2833f1a5c99b.png)

**Comment by dfmjndm** [comment]
My Windows desktop used to be a OneDrive synced folder (but it has been uninstalled now).

**Comment by dfmjndm** [comment]
And in Rstudio, .Rhistory and .RData are generated normally.

**Comment by albertosantini** [comment]
It is not about .RData or .Rhistory.

That session is very strange beacuse the namespaces are empties. 
Below the workspace after just starting the session:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/328179/229338023-7f3e6bd8-8210-455a-b0c1-88cb8d9681e1.png">

It seems to me that workspace is not attached tothe  R process.
Please, try to remove radian and just use the "default" configuration, using only R console.

**Comment by albertosantini** [comment]
See also https://github.com/REditorSupport/vscode-R/issues/1284
