### ISSUE TITLE
Weird escape characters send to R interactive session along with the code in the terminal

### ISSUE THREAD

**Issue by yuw444** [REditorSupport/vscode-R#1338]
**Describe the bug**
Weird escape characters send to R interactive session along with the code in the terminal

**To Reproduce**
1. create an R script with one line only  `library(tools)`
2. open the terminal, type R and open an R interactive session 
3.  move the cursor into R script 
4.  hit `cmd+enter`, send `library(tools)` into terminal
5. see `>00~library(tools)01~`

**Can you fix this issue by yourself? (We appreciate the help)**
No

**Expected behavior**
`library(tools)` in the terminal

**Environment (please complete the following information):**

- OS: [macOS, Linux]
- VSCode Version: [Version: 1.76.2 (Universal)]
- R Version: [R 4.1.2]
- vscode-R version: [v2.7.2]

**Comment by albertosantini** [comment]
I cannot reproduce it, even if I tested with R 4.2.3, but I don't think it is relevant.

> 2. open the terminal, type R and open an R interactive session

Generally speaking, I use the command "R: Create R terminal" from command palette (ctrl+shift+P) to open an R console.
I cannot understand how to attach the R console to VSCode, once you started it from the (bash) terminal.

**Comment by the8thday** [comment]
i have the same problem!
when i run Rmarkdown chunk, like, `library(tidyverse)` the terminal shows `0 ~ library(tidyverse)`;
and even worse, some chunk will add 01 behind the code, like `head(speed)`, the console will run `head(speed)01~`, then an error `Error: unexpected numeric constant in "head(speed)01"` appear, i wonder how to fix this.

**Comment by yuw444** [comment]
@albertosantini @the8thday  I just had this problem recently. It was working fine previously. Good to know I'm not alone.

**Comment by ElianHugh** [comment]
Is this occuring with the bracketed paste setting?
