### ISSUE TITLE
Browse script sections indicated by # comments

### ISSUE THREAD

**Issue by KleinhansDa** [REditorSupport/vscode-R#1344]
In addition to 'workspace' and 'help pages' on the R tab, it would be great to have a 'document' or 'script' panel that displays script sections indicated by `# comment ----` / `# comment ####` analog to here https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/code.html#create-sections.

**Comment by Yunuuuu** [comment]
Use `ctrl+shift+o` to open the outline panel, Does this do what you want?
![image](https://user-images.githubusercontent.com/19575010/233540796-8ca357d5-8821-4edf-b34c-99f88275fa9b.png)

**Comment by KleinhansDa** [comment]
Yes! :)
Thanks
