### ISSUE TITLE
[Feature Request] Option to disable opening plots in vscode when using httpgd

### ISSUE THREAD

**Issue by tddschn** [REditorSupport/vscode-R#1353]
**Is your feature request related to a problem? Please describe.**

I strongly prefer viewing plots with httpgd in a (external) web browser than in vscode, I could view plots that way by using the `R Plot: Open in External Browser` command, but the plots would still be rendered in a vscode pane. 

**Describe the solution you'd like**
An settings option to disable opening plots in vscode (when using httpgd).

**Comment by eitsupi** [comment]
I think you can do that via https://github.com/REditorSupport/vscode-R/wiki/Plot-viewer#svg-in-httpgd-webpage
