### ISSUE TITLE
Latex rendering on helppages

### ISSUE THREAD

**Issue by LGraz** [REditorSupport/vscode-R#1356]
Thanks very much for this wonderful extension :heart: 

Latex-style equations appear on many help pages. Here I consider the example `?metafor::rma` help page:
![image](https://user-images.githubusercontent.com/79447750/236836746-863912fa-8e54-4ad0-b77b-f7895a22434c.png)

Even the R-Terminal does a better job (interpreting "\( ...  \)"  and "\[ .... \]" correctly and removing it):
![image](https://user-images.githubusercontent.com/79447750/236836666-ce711e98-1a48-441a-b536-9ee43df5d1a3.png)

R-Studio renders it nicely:
![image](https://user-images.githubusercontent.com/79447750/236836296-6df6910c-3a0d-4449-95e9-1abae30cb917.png)

I think many users will appreciate this :smile:

**Comment by renkun-ken** [comment]
Thanks for reporting. Does equations in `?rnorm` render properly?

<img width="548" alt="image" src="https://user-images.githubusercontent.com/4662568/236856391-80088c10-2583-45a2-ad1e-642ed119ad64.png">

**Comment by LGraz** [comment]
Thanks for your reproducing. 

`?rnorm` renders fine. 

looking at the [source](https://github.com/SurajGupta/r-source/blob/master/src/library/stats/man/Normal.Rd) of the man-page of `rnorm` one sees that the math is encoded with `\deqn{  ...math...}` instead of `\[   ...math   \]`   (or `\eqn{  ...inline-math...}` instead `\( ...inline-math...  \)` respectively).

**Comment by renkun-ken** [comment]
@ManuelHentschel Any thoughts on how we could make help pages render it correctly?

**Comment by ManuelHentschel** [comment]
That package seems to be using [mathjaxr](https://github.com/wviechtb/mathjaxr) to render equations, which does not work in the help viewer because the corresponding javascript is not loaded/run.
