### ISSUE TITLE
No more autocomplete for `data.frame`, `data.table` and `tibble` on Windows

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#1358]
R: 4.2.3
vscode-R: v2.8.0
OS: Windows 10

Auto-completion for variable names in all data frames is not working on my windows machine. 
This stays the same whether the new `Use Web Server` feature is enabled or disabled. 

It works fine on my Macbook.

**Comment by renkun-ken** [comment]
Thanks for reporting! The auto-completion works fine on all my testing environments (Windows 11, Windows 11 WSL2, macOS, and Ubuntu 20.04).

Does other functionalities work?

Would you like to take a look at the developer console and see if there is something wrong with the session watcher related operations?

**Comment by Fred-Wu** [comment]
I think I have found the issue, which is related to the option of `Object Length Limit`.  Somehow it was changed to 1. After I changed it to, say 90, then auto-completion for column names worked again. 

For some small testing data, 10 or 20 works fine, but for large data has to be near 100. 

Is this the expected behavior of that option?

**Comment by albertosantini** [comment]
It seems that line of code is not touched since 2 years and the default is 2000.

https://github.com/REditorSupport/vscode-R/blame/7dbd9338916d61e925cc4177321597a02aa59564/R/session/vsc.R#LL274C2-L274C68
