### ISSUE TITLE
How `Help Panel: Preview Local Packages` feature should be used?

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#1361]
The `Preview: xxx` seems only to appear after I select`R Package: Install`, which actually installs the package in the library. 

It does persist even after I remove the package from the library. 

What's the proper way to use this feature?

**Comment by ManuelHentschel** [comment]
When you have the root directory of a package (containing a DESCRIPTION file and man directory) open in vscode, the preview should appear automatically in the R sidebar. If you have a parent directory of the package open, you can configure the setting `"r.helpPanel.previewLocalPackages"` accordingly. If that does not work, please try to share a reproducible example and I can have a look.

**Comment by Fred-Wu** [comment]
Thanks.  The issue was I was specifying a full path to the package, not relative path if under a parent directory. 
So in a parent directory,  just specifying the package name in `r.helpPanel.previewLocalPackages`, not the path would work.
