### ISSUE TITLE
languageserver works in terminal but not editor/text area

### ISSUE THREAD

**Issue by alejandrohagan** [REditorSupport/vscode-R#1367]
R lan

**Describe the bug**
languageserver works just fine in the terminal but it will not work in the editor/script area

**To Reproduce**

1. Open vscode
2. Open new file, select language, click R
3. Start new R terminal
4. click on terminal and type a command from "dplyr::" auto-complete will work
5. click on editor/text area and replicate step, it will not work

**Can you fix this issue by yourself? (We appreciate the help)**

No

**(If yes,) can we assist you with anything?**

**(If applicable) Please attach `setting.json`**

**Expected behavior**
auto completion should work in the text/editor like it does the terminal area

**Environment (please complete the following information):**

my system stats:
Linux pop-os 6.2.6-76060206-generic #202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M x86_64 x86_64 x86_64 GNU/Linux

R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 22.04 LTS

VS code
April 2023 (version 1.78)

**Additional context**
I've used both languageserver and languagerversetup. Terminal worked after languageserver setup

**Comment by albertosantini** [comment]
Well, my experience is different, that's the autocomplete doesn't work neither in the terminal nor in the editor.
And it is expected, because `dplyr` is not loaded in the namespace. Maybe execute `sessionInfo()` for more info of your environment.

In your context, I suppose, the autocomplete in the terminal works because maybe you are loading `dplyr` package in `.Rprofile`.
In the editor, after loading the `dplyr` package - `library(dplyr)` - the autocomplete correctly works.

**Comment by alejandrohagan** [comment]
Hi,

I've taken a bunch of screen shots but basically shows a before (not loading any library) 

![Screenshot from 2023-05-25 17-52-39](https://github.com/REditorSupport/vscode-R/assets/87534364/b49e9c80-4477-4dd0-986d-a354284f9ba2)

and after (loading tidyverse) 
![Screenshot from 2023-05-25 17-51-43](https://github.com/REditorSupport/vscode-R/assets/87534364/161fe449-518d-4947-abff-1c95e3690f8f)


and in both cases in the terminal languageserver works just  fine but in the script it does not.

Also are pictures of my session info and my .Rprofile.

![Screenshot from 2023-05-25 17-52-04](https://github.com/REditorSupport/vscode-R/assets/87534364/e5f8a61f-9668-4dad-ab85-826f0fe59467)
t from 2023-05-25 17-50-11](https://github.com/REditorSupport/vscode-R/assets/87
![Screenshot from 2023-05-25 17-51-43](https://github.com/REditorSupport/vscode-R/assets/87534364/1f01f9d4-a86a-4511-9097-41333a72004e)
534364/c3ea34f5-7f08-48af-89cc-4fc6fde5f985)


appreciate any help at all

**Comment by renkun-ken** [comment]
The editor autocompletion is provided by langaugeserver, which has nothing to do with radian terminal autocompletion which relies on R's internal auto-completion facility.

It looks like the R language server process is not properly spawned. Would you enable `r.lsp.debug` in vscode settings and see if there is anything happening in "Output" pane -> "R Language Server "channel?

**Comment by alejandrohagan** [comment]
Team,

That is really helpful feedback that terminal autocomplete isn't sourced from languageserver and instead radian. 

the output I get in the output pane is "R Language Server (-1) started" which I assume to mean it failed to start?

If my understanding is correct, I can colose the comment and follow up with languageserver github
