### ISSUE TITLE
unexpected numeric constant in "00

### ISSUE THREAD

**Issue by DrLuong** [REditorSupport/vscode-R#1392]
Just updated vscode-R on my macbook (M1)

I not expert so I am interesting write code. 
<img width="1255" alt="Screenshot 2023-07-07 at 20 59 07" src="https://github.com/REditorSupport/vscode-R/assets/86107838/28b51065-c84c-4be3-96ac-f2c5e361e485">
When I sent the code to the terminal, this happened:

unexpected numeric constant in "00

Pls help me.

Thanl you so much

**Comment by CT-Li** [comment]
You can try to turn off "Bracketed Paste" in the R extension settings.
<img width="639" alt="Screenshot 2023-07-08 at 00 06 37" src="https://github.com/REditorSupport/vscode-R/assets/60499240/ea6a4932-c5a9-4a80-91f9-2caea437f449">

**Comment by DrLuong** [comment]
Thank you so much. I got it.
