### ISSUE TITLE
Progress tracking not working, it's always 0%.

### ISSUE THREAD

**Issue by HuangLab-CBI** [REditorSupport/vscode-R#1404]
**Describe the bug**
## Progress tracking not working, it's always 0%.
**To Reproduce**

**Can you fix this issue by yourself? (We appreciate the help)**

Yes / No

**(If yes,) can we assist you with anything?**

**(If applicable) Please attach `setting.json`**

```jsonc
// R.exe path for windows
"r.rterm.windows": "",

// R path for Mac OS X
"r.rterm.mac": "/usr/local/bin/R",

// R path for Linux
"r.rterm.linux": "/usr/bin/R",

// R command line options (i.e: --vanilla)
"r.rterm.option": [],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": false,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**

**Screenshots**
You can show the keyboard contents by pressing `F1` and `Developer: toggle screencast mode`
![image](https://github.com/REditorSupport/vscode-R/assets/119552232/ce1d5f71-f629-493c-8034-58257f889f84)

**Environment (please complete the following information):**

- OS: [e.g. Windows, macOS, Linux]
- VSCode Version: [e.g. 1.42.0]
- R Version: [e.g. 3.6.2]
- vscode-R version: [e.g. 1.2.2]

**Additional context**

**Comment by jmwingenroth** [comment]
This bug appeared for me when I updated R from 4.1.x to 4.3.1. I think it might be related to changes in the text that shows up under "Output" in VSCode when knitting an RMarkdown document. I don't have a screenshot of what it looked like before for comparison, but here's what it looks like now.

![image](https://github.com/REditorSupport/vscode-R/assets/25393472/76c725c0-d354-46a4-8be4-6fb0f3cb2cd0)
