### ISSUE TITLE
R tools not working, error when opening vscode

### ISSUE THREAD

**Issue by KatynaSada** [REditorSupport/vscode-R#1432]
[Error - 11:02:45] R Tools client: couldn't create connection to server.
Launching server using command dotnet failed. Error: spawn dotnet ENOENT

**Comment by albertosantini** [comment]
Maybe I am wrong, but are you sure this is the correct repo (extension) and not this one:
https://github.com/MikhailArkhipov/vscode-r/issues/51?

**Comment by ElianHugh** [comment]
Closing for now. Feel free to reopen if you feel this is an issue with the vscode-R extension
