### ISSUE TITLE
Limited number of characters in R terminal

### ISSUE THREAD

**Issue by IlmariTamminen** [REditorSupport/vscode-R#1438]
Type: <b>Bug</b>

Hi.

If I open R Interactive on Visual Studio Code on my Windows and input many characters in the terminal, the full width of the available terminal is not used. Instead, the terminal cuts the lines using $ signs. This is very tedious for documentation, because after experimenting I cannot simply copy paste even my relatively short lines of codes into notes. To reproduce, with the specs included in this bug report, if input enough let's say "s" characters, I see the following in the terminal:

> $ssssssssssssssssssssssssssssssssssssssssssssssssss

Please help, I wasn't able to find solution to this issue. 

The Visual Studio Code version and other info below:

Version: 1.83.0 (system setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

R Extension for Visual Studio Code v2.8.2
R version 4.2.1 (2022-06-23 ucrt)

Extension version: 2.8.2
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by MilesMcBain** [comment]
This is a known limitation of the R terminal on Windows.

**Comment by Fred-Wu** [comment]
> This is a known limitation of the R terminal on Windows.

But, isn't the native R terminal can show more characters if making it a large window, something like below?

![image](https://github.com/REditorSupport/vscode-R/assets/4111978/c509823d-dcd5-4d42-b030-c302c85cd914)

Also it can show longer error message than codes typed in each line in vscode-R. 

Is it possible to define the terminal window expanding size inside vscode?

**Comment by IlmariTamminen** [comment]
@gowerc Thanks for the tip. I added a screenshot from the problematic scenario, an R Interactive in the VSCode.

![image](https://github.com/REditorSupport/vscode-R/assets/69622962/85cd159f-ba7a-419a-92a2-0d212b72d5a7)

I tried the suggestions behind the link. In the `C:\Users\myuseraccount\AppData\Local\Programs\R\R-4.2.1\library\base\R\Rprofile` I added `options("width"=500)` in the end, but the issue persists. The Rprofile says it is run after every startup, why I restarted my VSCode and thus R session after the modifications. The new value becomes registered, because I can get:

```
> getOption("width")
[1] 500
```

Although I didn't fully understand the other suggestion behind the link, I also tried the following in the end of the Rprofile without luck:

```
options(width=Sys.getenv("COLUMNS"))
options(setWidthOnResize=TRUE)
```

**Comment by MilesMcBain** [comment]
Please. This is not a VSCode-R extension issue. Open R.exe or Rterm.exe and observe the same behaviour from those applications.

**Comment by IlmariTamminen** [comment]
@MilesMcBain Okay, sorry about the false alarm regarding this context. I closed the Issue.

**Comment by grantmcdermott** [comment]
Just got bit by this console width / wrapping issue. Setting dynamic width via 

```r
options(width=Sys.getenv("COLUMNS"))
options(setWidthOnResize=TRUE)
```

is a good should (and should also be mentioned in the wiki IMO, which I'll try to do later).

**Comment by grantmcdermott** [comment]
**Update:** Wiki entry here: https://github.com/REditorSupport/vscode-R/wiki/Interacting-with-R-terminals#control-console-print-width-and-text-wrapping

**Comment by Fred-Wu** [comment]
> Just got bit by this console width / wrapping issue. Setting dynamic width via
> 
> options(width=Sys.getenv("COLUMNS"))
> options(setWidthOnResize=TRUE)
> is a good shout and works well for me (and should also be mentioned in the wiki IMO, which I'll try to do later).

I think the original question was about the input of the codes in the R's native terminal on Windows, in stead of how output was displayed in the terminal. They are two different issues.
