### ISSUE TITLE
httpgd not respecting font in ggplot

### ISSUE THREAD

**Issue by fernandoroa** [REditorSupport/vscode-R#1439]
**Description**
While using
```
{
  "r.plot.useHttpgd": true,
}
```
in settings.json, instead of `false`, which doesn't show the problem, the font, or the spacings of it are not respected

**To Reproduce**
Make a ggplot and use `mono`

```
    theme(
      axis.text.y = element_text(family = "mono", size = rel(1))
    ) 
```

**Can you fix this issue by yourself? (We appreciate the help)**

No

**Expected behavior**
To see correctly the font and spacing as when using `false`

**Screenshots**
with: `false`
![Screenshot from 2023-10-17 14-31-52](https://github.com/REditorSupport/vscode-R/assets/98838147/acd8bcce-5600-47ff-8d02-5ee4909ad107)
with: `true`
![Screenshot from 2023-10-17 14-33-07](https://github.com/REditorSupport/vscode-R/assets/98838147/b58bf4df-752b-49ae-90e7-5e14c3ba3206)

**Environment (please complete the following information):**

- OS: Linux
- VSCode Version: 1.83.0
- R Version: 4.3.1
- R Extension for Visual Studio Code version: 2.8.2

**Comment by fernandoroa** [comment]
https://github.com/nx10/httpgd/issues/143

**Comment by benz0li** [comment]
See https://github.com/nx10/httpgd/issues/143#issuecomment-1898674407
