### ISSUE TITLE
This is not a bug, but help

### ISSUE THREAD

**Issue by lightningHoneypot** [REditorSupport/vscode-R#1449]
Greetings, I am so sorry if I posted this help post here.

I am using a data csv (there is a dta file too) that has 3,601,843 entries, 44 total columns.
when I tried to use these command:
```R
library(readr)
imp_hs10_1718 <- read_csv("C:/Users/[USER]/Downloads/imp_hs10_1718.csv")
View(imp_hs10_1718)
```
It just does not show up (the view table).

In the past, it shows this error: `Error: evaluation nested too deeply: infinite recursion / options(expressions=)?`.  But now I am just waiting.

Is there a way to have it quicker? When using Rstudio, it give it out in like a second

**Comment by lightningHoneypot** [comment]
Never mind, I think reinstalling python and also installing Microsoft C++ Build Tools helped.
Sorry for the post

**Comment by lightningHoneypot** [comment]
Edit: I think the reason why is because the data is just too large for vscode-R to handle?

**Comment by D3SL** [comment]
Short answer is no. Even Excel will only render just over 1 million rows. The only way you're going to "Show" 3.6 million rows of data is by having a database serve a frontend that loads and unloads rows as the user scrolls.

**Comment by lightningHoneypot** [comment]
> Short answer is no. Even Excel will only render just over 1 million rows. The only way you're going to "Show" 3.6 million rows of data is by having a database serve a frontend that loads and unloads rows as the user scrolls.

Thank you, I guess that's pretty much it.
