### ISSUE TITLE
unmanagably many blue lines

### ISSUE THREAD

**Issue by Milena-van-der-Molen** [REditorSupport/vscode-R#1468]
Type: <b>Bug</b>

in perfectly fine code
can only be removed one by one
stop involving me in your indentation war

Extension version: 2.8.2
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (8.88GB free)|
|Process Argv|--crash-reporter-id 2b63bca7-6940-4b1b-afe0-da3975b68edc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by mkoohafkan** [comment]
You can define your own linting rules by placing a file named `.lintr` in your Documents folder (or you can add a `lintr` file for each project). For example, mine looks like this:

```r
linters: linters_with_defaults(
  assignment_linter = NULL,
  line_length_linter(80),
  indentation_linter(2L, "never"),
  cyclocomp_linter = NULL,
  object_name_linter = NULL,
  object_usage_linter = NULL
)
```

Also see https://github.com/REditorSupport/vscode-R/issues/1400 and https://lintr.r-lib.org/articles/lintr.html#the--lintr-file

**Comment by andycraig** [comment]
Thanks @mkoohafkan!

Sounds like this is solved so I'll close it.

**Comment by mkoohafkan** [comment]
@andycraig I do think there is room for improvement to linting in vscode-r, e.g. https://github.com/REditorSupport/vscode-R/issues/1400#issuecomment-1867901192 for discussion.

**Comment by andycraig** [comment]
Thanks @mkoohafkan, reopening.

**Comment by mkoohafkan** [comment]
@andycraig I meant we continue the discussion in #1400 and close this since it's basically a duplicate 😅

**Comment by andycraig** [comment]
@mkoohafkan Whoops, I understand now! 😄 Let's do that.
