### ISSUE TITLE
Disable linting when previewing file differences in source control panel

### ISSUE THREAD

**Issue by psychelzh** [REditorSupport/vscode-R#1482]
Whenever previewing file differences in source control panel, the linting will complain with the following message:

```
Failed to run diagnostics: ! in callr subprocess.
Caused by error: 
! Linter 'object_length_linter' failed in : path[1]="": No such file or directory
```

It will be ideal to turn off the linting completely in such circumstances.

**Comment by renkun-ken** [comment]
Do you encounter this when you use GitLens git-diff preview editor like the following?

<img width="992" alt="image" src="https://github.com/REditorSupport/vscode-R/assets/4662568/0eba863e-4741-4c75-bdf5-a76612b606eb">

From the log, I observe that the preview editor has a Uri like

```
gitlens://7b22726566223a2235626130643735623437633436663733376635623737333631373038383061346261613763613034222c227265706f50617468223a222f55736572732f6b656e2f576f726b7370616365732f6769746875622f6c616e6775616765736572766572227d/Users/ken/Workspaces/github/languageserver/R/task.R?{%22ref%22:%225ba0d75%22}
```

which cannot be properly handled by the langauge server. Let me see how we could fix it.

**Comment by psychelzh** [comment]
Thanks. You are right! Seemingly an issue from GitLens?

**Comment by renkun-ken** [comment]
Should be fixed in languageserver. Please install latest development of languageserver via

```
remotes::install_github("REditorSupport/languageserver")
```
