### ISSUE TITLE
Rtmp files left in /tmp directory

### ISSUE THREAD

**Issue by tabulez** [REditorSupport/vscode-R#1486]
I'm having the same issue reported here: https://stackoverflow.com/questions/76425284/rtmp-files-remain-in-tmpdir-after-using-vscode-r-extension

Rtmp directories remain in /tmp unless I go in to manually delete them. With multiple users using vscode to SSH into a server to work interactively, Rtmp directories continue to compound. Is there a way to handle this without needing to go in and clear the Rtmp files manually?

Thanks!

**To Reproduce**
1. SSH into a remote server via putty and remove any existing Rtmp directories
2. With vscode, open test.R that has the line: print("hello world")
3. Close vscode after running the line. I noticed two new Rtmp directories in /tmp that remained.
4. In putty, run R, print("hello world") q(). No new Rtmp directories were added. Same happens if I use "Rscript test.R"
5. If I repeat step 2, I notice 2 new directories in /tmp are created that aren't removed after closing vscode.

**Environment**

- OS: Linux CentOS 7
- VSCode Version: 1.86
- R Version: 3.6.0
- vscode-R version:  2.8.2

**Comment by albertosantini** [comment]
Due to https://github.com/REditorSupport/languageserver/issues/515?

**Comment by tabulez** [comment]
I'm not sure. I don't see that I have Rscript* or calls to languageserver, but I have similar libloc and callr related files: 

language server version = 0.3.16
callr = 3.7.3

```
./RtmpkpecfE:
total 334K
callr-client--eff06ee.so
callr-env-4e74108faaf5
callr-fun-4e747d5c0b79
callr-res-4e7435f83e09
callr-scr-4e74584134a4
callr-sev-4e742c3c1549
callr-sev-4e744c22c3
callr-sev-4e744d2e7ca0
callr-sev-4e74531de39e
callr-sev-4e7463f7c62a
callr-spr-4e7418ba6840
callr-spr-4e741d41d3da
callr-spr-4e74606cd5c9
callr-spr-4e74748293fd
callr-spr-4e74c871bcd
callr-uev-4e74316db898
callr-uev-4e74480eebcf
callr-uev-4e74503ac808
callr-uev-4e74a9da0d6
callr-uev-4e74d3cfc3d
callr-upr-4e7418eb6e65
callr-upr-4e74433f3810
callr-upr-4e744509737a
callr-upr-4e74692e206a
callr-upr-4e74f103836

./RtmpwTGjlB:
total 83K
libloc_180_124706c06bfefeeb.rds
libloc_180_dbd70c741b94b12c.rds
libloc_215_684dcd0b7abed33c.rds
```

**Comment by tabulez** [comment]
Thanks! I opened a new issue here: https://github.com/r-lib/callr/issues/277
