### ISSUE TITLE
httpgd has been archived the 24/01/2024

### ISSUE THREAD

**Issue by ajreckof** [REditorSupport/vscode-R#1488]
**Describe the bug**
httpgd has been archived from CRAN and thus install.packages("httpgd") as instructed by vscode-r docs does not work anymore

**To Reproduce**
1. create a clean install of R 
2. try to install httpgd
3. see the error

**Can you fix this issue by yourself? (We appreciate the help)**

No

**Expected behavior**
Expect to be able to install the deendency by foloowing instruction

**Environment (please complete the following information):**

- OS: [e.g. Windows, macOS, Linux] : Macos
- VSCode Version: [e.g. 1.42.0] : 1.86.1
- R Version: [e.g. 3.6.2] : 4.3.2
- vscode-R version: [e.g. 1.2.2] : 2.8.2

**Comment by ajreckof** [comment]
It seems httpgd are trying to make it back online on CRAN (see https://github.com/nx10/httpgd/issues/145) but could be good still to add alternative version to install the package in case it happens again

**Comment by ElianHugh** [comment]
Might be worth pointing to the r-universe version in the interim

**Comment by nx10** [comment]
Its available again. Thanks for waiting.

**Comment by ElianHugh** [comment]
Glad to hear it @nx10, hopefully you get a well earned rest. Closing this for now if there's no objections
