### ISSUE TITLE
No response after clicking R: (not attached)

### ISSUE THREAD

**Issue by Aurorabili** [REditorSupport/vscode-R#1510]
**Describe the bug**
R session not attached after run command `R: create R terminal` or click `R: (not attached)`

This is similar to the problem in #393 but the solution doesn't apply.

**To Reproduce**

1. Use vscode to open a local folder
2. Install according to [wiki](https://github.com/REditorSupport/vscode-R/wiki/Installation:-Linux)
3. Click `R: (not attached)`
4. The R terminal is opened, prompting `.vsc.attach()`
5. The status bar is still `R: (not attached)`

**Can you fix this issue by yourself? (We appreciate the help)**

No

**(If yes,) can we assist you with anything?**

**(If applicable) Please attach `setting.json`**

```jsonc
"r.rterm.linux": "/home/4-BB/aurora/miniforge3/envs/dsenv/bin/R",
"r.rpath.linux": "/home/4-BB/aurora/miniforge3/envs/dsenv/bin/R",
"r.rterm.option": [
    "--no-save",
    "--no-restore",
],
"r.plot.useHttpgd": true,
"r.lsp.debug": true
```

I tried radian, but it also.

```jsonc
"r.rterm.linux": "/home/4-BB/aurora/miniforge3/envs/dsenv/bin/radian",
"r.rpath.linux": "/home/4-BB/aurora/miniforge3/envs/dsenv/bin/R",
"r.rterm.option": [
    "--no-save",
    "--no-restore",
    "--r-binary=/home/4-BB/aurora/miniforge3/envs/dsenv/bin/R"
],
"r.bracketedPaste": true,
"r.plot.useHttpgd": true,
"r.lsp.debug": true
```

**Expected behavior**
The status bar changes from `R: (not attached)` to the current R version number.

**Screenshots**
![image](https://github.com/REditorSupport/vscode-R/assets/30513775/6646e8a2-8b65-4538-b687-aada74dd24ea)

**Environment (please complete the following information):**

- OS: Linux CentOS7
- VSCode Version: 1.85.2
- R Version: 4.3.3
- vscode-R version: 2.8.2

**Additional context**

I saw that in other issues, when pressing `R: (not attached)`, the developer tools console will prompt `[updateRequest]` and other information, but in fact nothing happened here.

![image](https://github.com/REditorSupport/vscode-R/assets/30513775/65cad042-b85d-4e0c-abc1-803823af1b8d)

I also noticed there was an error, maybe this is related?

```
Activating extension 'REditorSupport.r' failed: EMFILE: too many open files, watch '/home/aurrora/.vscode-R/request.lock'.
$onExtensionActivationError @ mainThreadExtensionService.ts:113
```

**Comment by sjmgarnier** [comment]
I can confirm the problem on MacOS 14.4.1, VSCode 1.88.1.

**Comment by GB-IHE** [comment]
I also have this problem since the update 2024-05-07.

**Comment by albertosantini** [comment]
`EMFILE: too many open files` error is relevant and is not related with this extension.

A few suggestions:
- try to start vscode with only `vscode-R` extension: just to understand if it is a problem generated from another extension or it is a regression in vscode in your context.
- try to change the limit of your operating system with `ulimit` (check your man for the correct command): for instance, https://serverfault.com/questions/637212/increasing-ulimit-on-centos

Hope that helps.

**Comment by Aurorabili** [comment]
I think this may be an upstream issue, as a similar error is reported when I use `pylance`.

Unfortunately I don't have root access to change `ulimit` on this machine with the problem, and I can't reproduce the problem on a clean install of CentOS7.

**Comment by nolanjj** [comment]
me too!!! help~~~

**Comment by aaronschiff** [comment]
Not sure if this is relevant for others, but I had a similar issue with one of my workspaces but not others, where clicking `R: (not attached)` would not do anything. After some trial and error I realised it is because there was a special character (ō) in the name of the folder for the workspace. After removing this character from the directory name, attaching to R works fine.

**Comment by chkbm** [comment]
I'm having the same issue.
