### ISSUE TITLE
plot in External browser trigger error of “useMethod”

### ISSUE THREAD

**Issue by liuhuoz** [REditorSupport/vscode-R#1512]
**Describe the bug**
When open an external browser (in case, Google Chrome), and draw a ggplot2 plot, the plot would not draw or in a wired way that elements are disrupted. Further, the terminal show message like:
```
Error in UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"
Error in grid.Call.graphics(C_upviewport, as.integer(n)) : 
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)
```
However, after closing the browser, everything come back to normal.

Besides, directly using Radian without vscode and httpgd::hgd() function to open an external browser  would not response such error. 

**To Reproduce**
here is my test code
```
data <- data.frame(
  x=rnorm(10), 
  y=rnorm(10)
)
data
p <- 
data %>% 
  ggplot(aes(x=x,y=y))+
  geom_point(size=10)
p
```

1. draw a plot in vscode windows
2. Click on 'Open in External Browser' 
3. draw another plot

**Can you fix this issue by yourself? (We appreciate the help)**

 No

**(If applicable) Please attach `setting.json`**

```jsonc
{
    "r.rterm.option": [],
    "r.bracketedPaste": true,
    "files.associations": {
        "*.rmd": "markdown"
    },
    "r.rterm.windows": "D:\\miniconda3\\Scripts\\radian.exe",
    "r.rpath.windows": "D:\\R\\R-4.3.3\\bin\\R.exe",
    "r.plot.defaults.fullWindowMode": true,
    "r.workspaceViewer.showObjectSize": true,
    "r.lsp.use_stdio": true,
    "r.session.levelOfObjectDetail": "Detailed",
    "r.lsp.multiServer": false,
    "r.removeLeadingComments": true,
    "r.plot.useHttpgd": true,
    "r.session.useWebServer": true,
    "r.source.echo": true
}
```

**Expected behavior**
the plot should be draw both in vscode window and browser

**Screenshots**
You can show the keyboard contents by pressing `F1` and `Developer: toggle screencast mode`

**Environment (please complete the following information):**

- OS: Windows 11
- VSCode Version: 1.85.2
- VScode insider:1.89.0 (both stable and insider have this error)
- R Version: 4.3.3
- vscode-R version: 2.8.2

**Comment by liuhuoz** [comment]
The problem still exist after updating vscode-R to 2.8.5

**Comment by py9mrg** [comment]
I have the same problem. Seems to have started since httpgd was "revived" and the plotting split out into unigd.

**Comment by liuhuoz** [comment]
> I have the same problem. Seems to have started since httpgd was "revived" and the plotting split out into unigd.

Recently I draw the chord picture with the package "circlize" which is not a ggplot-based drawing system. When plotting in both vscode and bowser, it doesnt trigger any problem. However, when I draw other pic with ggplot2 in the same drawing dev, the error happened.
It seems like a quite complex problem, and may relate to many packages, vscode-R and vscode itself.

**Comment by liuhuoz** [comment]
#https://github.com/nx10/httpgd/issues/184

**Comment by liuhuoz** [comment]
#https://github.com/nx10/httpgd/issues/184
Same problem

**Comment by liuhuoz** [comment]
Since the bug is related to a  infrastructure problem about quartz graphics devices, but not a vscode-R or httpgd bug, I choose to close this issue.
It may be a very long wating to fix the bug, because of its complexity.
And for more info, please check those links. 
https://github.com/tidyverse/ggplot2/issues/3538
https://github.com/nx10/httpgd/issues/184
https://github.com/tidyverse/ggplot2/issues/5857
