### ISSUE TITLE
Can I view data through keyboard shortcuts？

### ISSUE THREAD

**Issue by nolanjj** [REditorSupport/vscode-R#1531]
For example, when I select a variable called data and press the keyboard shortcut, I can execute `view (data)` 

How to achieve

**Comment by andycraig** [comment]
Hi, you can do this by defining a keyboard shortcut with `runCommandWithSelectionOrWord`.

An example is here: https://github.com/REditorSupport/vscode-R/wiki/Keyboard-shortcuts#creating-keybindings-for-r-commands

I'll close this issue but let us know if you have any trouble.

**Comment by nolanjj** [comment]
> Hi, you can do this by defining a keyboard shortcut with `runCommandWithSelectionOrWord`.
> 
> An example is here: https://github.com/REditorSupport/vscode-R/wiki/Keyboard-shortcuts#creating-keybindings-for-r-commands
> 
> I'll close this issue but let us know if you have any trouble.

Great, thank you!!!
