### ISSUE TITLE
View() indicates an error

### ISSUE THREAD

**Issue by hyq9588** [REditorSupport/vscode-R#1543]
r$> View(exprSet)
Warning message:
In writeLines(json, path, useBytes = TRUE) :
  invalid char string in output conversion

**Comment by pMogramming7** [comment]
how did you solved this issue?

**Comment by EvanGit314159** [comment]
Has it been solved? 'Cause I have this, too.

**Comment by Lucyyang1991** [comment]
I have the same problem!

**Comment by tianranchunzhen** [comment]
I'm also having this problem, can you explain how you solved it?
