### ISSUE TITLE
SessionWatcher do not work.

### ISSUE THREAD

**Issue by iikkalord** [REditorSupport/vscode-R#1564]
**Describe the bug**
The sessionWatcher does not work anytime.

**To Reproduce**

1. Install vscode-R and R Debugger in vscode.
2. Install radian (with pip3 install radian).
3. Set up my setting.json.
4. Generate a data frame.
```
df1 <- data.frame(
    type = c("A", "B", "C"),
    value = c(5.6, 7.2, 3.1)
    )
```
5. Generate a plot using the data frame data.
```
width <- 6
height <- 3
windows(width = width, height = height)

barplot(df1$value,
    names.arg = df1$type,
    main = "chart",
    col = c("#EAC100", "#6FB7B7", "#C07AB8"),
    xlab = "Type",
    ylab = "Value"
)
```
6. A picture pops up, but not in vscode
7. Use the View function to view the data frame. The terminal accepted the command but the data frame did not appear in any form.
`View(df1)`

**How can I get my SessionWatcher to work properly?**
**It is my `setting.json`**

```
{
    "r.sessionWatcher": true,
    "r.bracketedPaste": true,
    "r.plot.useHttpgd": true,
    "r.rterm.windows": "c:\\Users\\username\\AppData\\Local\\Packages\\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\\localcache\\local-packages\\python312\\Scripts\\radian.exe",
    "r.rpath.windows": "C:\\Program Files\\R\\R-4.4.1\\bin\\x64\\R.exe",
    "r.rterm.option": [
        "--no-site-file"
    ]
}
```

**Expected behavior**
I hope I can view the parameters and data frames in my Global Environment normally.

**Screenshots**
![image](https://github.com/user-attachments/assets/336feea9-5c1d-453a-98a3-a6c1bfa4f408)

**Environment (please complete the following information):**

- OS: Windows11
- VSCode Version: 1.93.1
- R Version: 4.4.1
- vscode-R version: 2.8.4

**Comment by iikkalord** [comment]
> I am having the same issue, it started yesterday

I used it for the first time yesterday.

**Comment by tomasnobrega** [comment]
Hey,
Just to let you know I was able to figure out what was happening in my case. Yesterday I started running scripts on a folder with latin characters (é) and that was messing with the SessionWatcher. I
n your case, have you installed `languageserver` and `httpgd`? Check the installation instructions on the readme

**Comment by iikkalord** [comment]
> Hey, Just to let you know I was able to figure out what was happening in my case. Yesterday I started running scripts on a folder with latin characters (é) and that was messing with the SessionWatcher. I n your case, have you installed `languageserver` and `httpgd`? Check the installation instructions on the readme

Thanks for your help:
I have just solved my problem. The reason is that the file created by file.edit("~/.Rprofile") under Windows ends in txt, and it does not take effect. After I changed it to the correct suffix, everything It's normal.

**Comment by EvanGit314159** [comment]
Hi, I also have one issue, mine can display the picture, yet not for the View(), and this is my setting.json:
{
    "Codegeex.Privacy": true,
    "files.associations": {
        "*.rmd": "markdown"
    },
    "r.rterm.windows": "D:\\Python\\anaconda3\\Scripts\\radian.exe",
    "r.rpath.windows": "D:\\R\\R-4.3.3\\bin\\R.exe",
    "r.bracketedPaste": true,
    "r.rterm.option": [
        "--no-site-file"
    ],
    "r.plot.useHttpgd": true,
    "terminal.integrated.enableMultiLinePasteWarning": false
}

**Comment by iikkalord** [comment]
> Hi, I also have one issue, mine can display the picture, yet not for the View(), and this is my setting.json: { "Codegeex.Privacy": true, "files.associations": { "*.rmd": "markdown" }, "r.rterm.windows": "D:\Python\anaconda3\Scripts\radian.exe", "r.rpath.windows": "D:\R\R-4.3.3\bin\R.exe", "r.bracketedPaste": true, "r.rterm.option": [ "--no-site-file" ], "r.plot.useHttpgd": true, "terminal.integrated.enableMultiLinePasteWarning": false }

It is recommended to try to set up Rprofile by referring to the content of the following link:
https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions
