### ISSUE TITLE
Lines should not be more than 80 characters

### ISSUE THREAD

**Issue by Midreancgle** [REditorSupport/vscode-R#1582]
Hello: 
I've recently encountered a problem with the R extension in VScode that is causing me a lot of headaches!
<img width="1036" alt="截屏2024-12-24 15 59 37" src="https://github.com/user-attachments/assets/77fb3faf-70f4-4368-8de2-797d1a2275dd">

When a line of code exceeds 80 characters, a long wavy underline leaves indicating that I've exceeded 80 characters, which may override some other issues, so I've come to ask for help, is there any way to simply and brute force permanently ignore this alert?

I tried using a .lintr file and writing linters in it: with_defaults(line_length_linter=line_length_linter(100)), but another problem occurs with the prompt as shown here: 

`Failed to run diagnostics: ! in callr subprocess.
Caused by error in 'lintr::lint(path, cache = cache, text = content) ' :
! Malformed config file (.lintr):
Caused by error in 'load_config()':
! Error from config setting 'linters'.
Caused by error:
! Function with_defaults was deprecated in lintr version 3.0.0. Use linters_with_defaults or modify_defaults instead. lintr`

<img width="1040" alt="截屏2024-12-24 16 00 51" src="https://github.com/user-attachments/assets/c6509d23-0198-4c88-8825-4f49dd7df5a4">

Expect a reply soon and help me solve this problem!Thanks.

**Comment by albertosantini** [comment]
Hope this helps:

`.lintr`
```
linters: linters_with_defaults(
    line_length_linter(142)
  )
```

**Comment by Midreancgle** [comment]
Thanks for your prompt reply, my problem has been solved.

Thanks again!

**Comment by albertosantini** [comment]
You are welcome.
Please, close the issue. :)
