### ISSUE TITLE
Reduce overhead of session watcher task callback 

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#174]
Currently, we use `utils::capture.output(utils::str(obj, max.level = 0, give.attr = FALSE))` to get the string representation of each object in global environment. The overhead will become more significant as there are more symbols in it.

Suppose the global environment contains as many symbols as base environment (more than 1200 visible symbols), the overhead of getting object metadata will be more than 300ms, i.e., on each user input, there will be an extra 300ms to wait for the metadata of objects to be gathered.

To reduce the overhead, we could avoid using `capture.output` and `str` and instead create a simple string that contains simple information such as class, type, length, dim to represent the object.

```r
system.time(objs <- eapply(baseenv(), function(obj) {
  utils::capture.output(utils::str(obj, max.level = 0, give.attr = FALSE))
}))
#>    user  system elapsed 
#>   0.335   0.004   0.339
system.time(objs <- eapply(baseenv(), function(obj) {
  list(
    type = typeof(obj),
    length = length(obj),
    class = class(obj)
  )
}))
#>    user  system elapsed 
#>   0.013   0.001   0.013
```

If the time of writing files are included,

```r
system.time({
  objs <- eapply(baseenv(), function(obj) {
    list(
      type = typeof(obj),
      length = length(obj),
      class = class(obj),
      str = trimws(utils::capture.output(utils::str(obj, max.level = 0, give.attr = FALSE))),
      names = names(obj)
    )
  })
  jsonlite::write_json(objs, "test.json", auto_unbox = TRUE, pretty = FALSE)
})
#>    user  system elapsed 
#>   0.557   0.011   0.570
system.time({
  objs <- eapply(baseenv(), function(obj) {
    list(
      type = typeof(obj),
      length = length(obj),
      class = class(obj),
      names = names(obj)
    )
  })
  jsonlite::write_json(objs, "test.json", auto_unbox = TRUE, pretty = FALSE)
})
#>    user  system elapsed 
#>   0.113   0.000   0.113
```

**Comment by mkb007** [comment]
First, thanks for making this extension available.  It is, in general, far more robust than RStudio when working on large datasets.

There is a sizeable delay after the R terminal evaluates an expression and shows its output before the terminal prompt appears.  

The symptom, with a somewhat tolerable short delay, can be reproduced as follows.  The vscode-R and the R Debugger for VS code are the only extensions.  The R terminal is RTerm.exe - not radian.  With session watcher on and Watch Global Environment on, and Show Object Size is FALSE, run the following and witness the delay with the terminal prompt.

    db = new.env(hash = TRUE, parent = emptyenv())
    for (i in seq_len(10^6 * 2)) db[[as.character(i)]] = i
    # the following evaluates quickly, but there's a delay after the output is shown in the terminal
    exists("db")

The current work-around is disabling Watch Global environment.  Please don't hesitate to request additional information.

**Comment by renkun-ken** [comment]
@mkb007 Thanks for providing that example. The delay is mostly caused by the object `db` in the global environment having millions of elements and each time `names(db)` is written to `globalenv.json`.

**Comment by mkb007** [comment]
@renkun-ken Thanks for the quick reply.  Pardon my newbie-ness, but it's not clear why names(db) is a necessary evaluation when Show Object Size is FALSE and Level Of Object Detail (aka vsc.str.max.level) is set to "Minimal."  Simply seeing db in the workspace view as an environment type would be sufficient.

The problem with the work around, i.e. disabling Watch Global environment, is that all the buttons on the Workspace view are disabled.  There's no way to use "Load", "Save", or "Manual Refresh".  Manual Refresh, in particular, might be useful with a workspace containing millions of objects.

What do you suggest?

**Comment by ElianHugh** [comment]
As a side note, manual refresh at present only refreshes the tree view and *not* the data. Realistically, the command does very little at the moment. This is probably something we should change at some point.

**Comment by ElianHugh** [comment]
> @renkun-ken Thanks for the quick reply. Pardon my newbie-ness, but it's not clear why names(db) is a necessary evaluation when Show Object Size is FALSE and Level Of Object Detail (aka vsc.str.max.level) is set to "Minimal." Simply seeing db in the workspace view as an environment type would be sufficient.
> 
> The problem with the work around, i.e. disabling Watch Global environment, is that all the buttons on the Workspace view are disabled. There's no way to use "Load", "Save", or "Manual Refresh". Manual Refresh, in particular, might be useful with a workspace containing millions of objects.
> 
> What do you suggest?

@mkb007 The names() call (I believe, correct me if I'm wrong @renkun-ken) is used to supply auto-completions in the editor. E.g., `mtcars$` uses `names()` to suggest `cyl`, `mpg`, etc. as auto-completions.

@renkun-ken would it make sense to set an upper-limit on object length, so that names isn't called on super big objects? I don't think many people would be expecting auto-completions for 1k+ length objects

**Comment by renkun-ken** [comment]
Looks like for large objects with millions of elements, calling `names()` will have a significant overhead already.

Then I agree with @ElianHugh that we should set an upper limit on object length so that `names()` is not even called on these objects.

**Comment by renkun-ken** [comment]
With some experiments, it looks like we could set a default limit of 2000 as the upper limit to call and write names. The delay is hardly noticeable.

**Comment by renkun-ken** [comment]
Also, if the length of an object exceeds the limit, then its `str` should be called with `max.level = 0` regardless of `vsc.str.max.level`.

**Comment by mkb007** [comment]
Thanks for the insight re: auto-completion and names().  The limit will 
be welcome enhancement.

------ Original Message ------
From: "Kun Ren" ***@***.***>
To: "REditorSupport/vscode-R" ***@***.***>
Cc: "mkb007" ***@***.***>; "Mention" 
***@***.***>
Sent: 9/7/2021 11:13:12 PM
Subject: Re: [REditorSupport/vscode-R] Reduce overhead of session 
watcher task callback (#174)

**Comment by Fred-Wu** [comment]
Thanks for directing me here regarding the issue I raised under `radian`. 
I have tried the development build, and the lag issue related to large `list` seems no more. 

However, the issue still remains after I loaded 9 years of `data.table`, and each of them has less than 100,000 records.

Once I combined all the data into one and deleted individual year records, the issue seemed to have stopped.

**Comment by Fred-Wu** [comment]
I think the issue related to `data.table` is still quite significant. If I leave data uncombined, and run other codes, it takes about 8 seconds to make the next input ready,  just for running 3 lines of simple codes. I think the lag time is increasing with the lines of codes sent to the terminal.

**Comment by renkun-ken** [comment]
The number of rows should not affect the performance. The delay will be significant if there are many named objects in the global environment.

Would you like to paste the `ls.str()` when you have significant delay?

Does it help to set `"r.session.levelOfObjectDetail": "Minimal"` in your settings?

**Comment by Fred-Wu** [comment]
> 
> 
> The number of rows should not affect the performance. The delay will be significant if there are many named objects in the global environment.
> 
> Would you like to paste the `ls.str()` when you have significant delay?
> 
> Does it help to set `"r.session.levelOfObjectDetail": "Minimal"` in your settings?

I tried to setup `"r.session.levelOfObjectDetail"` to Minimal in the settings, but it seemed no effect. 
For 9 years of data, each contains 69 variables.  So there are about 630 lines of output plus a few folder paths from `ls.str()`

**Comment by Fred-Wu** [comment]
I also tried to write all the data into a new environment, and `get` them into a list first. However, there still experienced a small lag which was similar to the one I reported earlier.  I thought the lag associated with the list has been fixed.  Here is the `ls.str()` output with this approach. 

```
r$> ls.str()
create_proj_folders : function ()  
ED : List of 9
 $ :Classes 'data.table' and 'data.frame':      31020 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      36248 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      38881 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      40631 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      45621 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      48992 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      52266 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      55837 obs. of  69 variables:
 $ :Classes 'data.table' and 'data.frame':      95900 obs. of  69 variables:
overlay : function (lng, lat, data, basemap)
sqlFetchData : function (connection, database, schema, table, nobs = "All")
```

**Comment by mkb007** [comment]
Nice work on v2.3.0 based on a quick test.  Thanks.

------ Original Message ------
From: "Fred-Wu" ***@***.***>
To: "REditorSupport/vscode-R" ***@***.***>
Cc: "mkb007" ***@***.***>; "Mention" 
***@***.***>
Sent: 9/15/2021 9:53:20 PM
Subject: Re: [REditorSupport/vscode-R] Reduce overhead of session 
watcher task callback (#174)
