### ISSUE TITLE
Markdown formatting support

### ISSUE THREAD

**Issue by atanasj** [REditorSupport/vscode-R#238]
I think it would be great to have `Markdown` formatting support in `R markdown` document (see [this issue](https://github.com/yzhang-gh/vscode-markdown/issues/618)). 

The maintainer of the relevant extension said they would add support of there was enough interest. 

Is this something the `VSCode` `R` community would be interested in? I know I would... This would really bring the features of`polymode` from `Emacs` to this extension.

**Comment by andycraig** [comment]
Hi @atanasj, it’s possible that this functionality will be added by PR #228, which will make R Markdown documents function more like Markdown documents.

**Comment by atanasj** [comment]
Thanks @andycraig. I was wondering about that PR... Hopefully, the screenshots look good. When will it be available?

**Comment by andycraig** [comment]
Not sure when it will be merged. You can try it out now if you want by following the instructions on CONTRIBUTING.md up to and including the ‘Test’ section.

**Comment by atanasj** [comment]
@andycraig... that doesn't seem to have done what I was looking for. But I may have done something wrong, because as you can see the `yaml` syntax is not highlighted: 

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/27214625/75110506-2209e600-5683-11ea-9359-f4d9f6217499.png">

For comparison, see below when language of the same files is set to `Markdown`. 

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/27214625/75110530-5d0c1980-5683-11ea-9e02-9e86c3f1dd06.png">

Have I don't something wrong?

**Comment by andycraig** [comment]
Hi @atanasj, it looks like you are on `master` branch. You will need to pull the branch `andycraig:issue-220-rmd-grammar` from my fork of vscode-R: https://github.com/andycraig/vscode-R

**Comment by atanasj** [comment]
I'm pretty sure it is the branch you recommended: 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/75123417-55885700-56fb-11ea-87f2-3f1904f5f575.png">

**Comment by andycraig** [comment]
I’ve just merged PR #228 into this repo’s `master` branch, so try doing a git pull from that and see if it works.

**Comment by atanasj** [comment]
Okay, so that works as it is supposed to:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/75149507-45ea2c00-5756-11ea-976f-c4bd5b67f582.png">

However, the `Markdown` shortcuts etc. don't work. I can et bold, etc. via the command palette but not the keybindings, as per the the feature request at [vscode-markdown](https://github.com/yzhang-gh/vscode-markdown/issues/618). I have the `file.associations` set as recommend, but still no joy.

Not sure if others would like this functionality, but I think this would really make it `R` in `vscode` just that little bit more awesome.

**Comment by andycraig** [comment]
@atanasj Thank you for checking and reporting back. It’s a pity that this doesn’t work.

It could be that VSCode ignores embedded languages when checking `editorLangId` in keybindings. If so that might be a feature that the VSCode developers would be willing to add. I will look into that.

**Comment by atanasj** [comment]
Great, thanks @andycraig.

**Comment by atanasj** [comment]
@andycraig, I think I found an issue with the latest commit related to comments. It provides `R` `#` comments in r-chunks, and `html` comments in `markdown`, however in the `yaml` header, it also some `html` comments, instead of the `#` type ones. Is this behaviour expected?

<img width="573" alt="image" src="https://user-images.githubusercontent.com/27214625/75290618-cf901b80-5874-11ea-83f1-ca77889c09a6.png">

**Comment by andycraig** [comment]
> It could be that VSCode ignores embedded languages when checking editorLangId in keybindings. If so that might be a feature that the VSCode developers would be willing to add. I will look into that.

I created a VSCode issue for this: https://github.com/microsoft/vscode/issues/95442 Please upvote it if you'd like this feature.

**Comment by atanasj** [comment]
Done! Thanks for following this up.
