### ISSUE TITLE
Modify function browser / argument url (options) to allow proxied requests

### ISSUE THREAD

**Issue by benz0li** [REditorSupport/vscode-R#275]
**Is your feature request related to a problem? Please describe.**

On [code-server](https://github.com/cdr/code-server) it is currently impossible to access HTML help or view Shiny Apps.

This is because the `url` points to `127.0.0.1` (`localhost`) instead of the URL at which code-server ist running. Related to Issue #192.

**Describe the solution you'd like**

At Coder they are working on a [HTTP proxy](https://github.com/cdr/code-server/pull/1453), which will enable port forwarding using path `/proxy/<number>`.

Is there a way to modify function `browser` / argument `url` (options) to use the proxied address instead of `127.0.0.1`?

It needs to be clarified how a local (VS Code) installation can be differentiated from a server (code-server) installation.

**Describe alternatives you've considered**

One could check the port used by the httpd help server or Shiny app, open a new browser window and fill in the URL to be proxied.

**Additional context**

Maybe it is worth looking on how RStudio handles `url` differently for Shiny Apps on the Desktop and Server version.

**Comment by kevinykuo** [comment]
Seems like they’ve got the `/proxy/<number>` scheme working on the code-server side. Where in the codebase should we need to make the proposed change? This is blocking both help docs and Shiny apps for code-server deployments (in that users would have to manually replace `127.0.0.1` with the URL of the code-server instance).

**Comment by benz0li** [comment]
@renkun-ken I'm going to ask the Coder guys about the environment variable `VSCODE_HTTP_REFERER` (or [`CODE_SERVER_HTTP_REFERER`](https://github.com/cdr/code-server/issues/1939#issuecomment-668158611)?) again.

**Comment by benz0li** [comment]
> @renkun-ken I'm going to ask the Coder guys about the environment variable `VSCODE_HTTP_REFERER` (or [`CODE_SERVER_HTTP_REFERER`](https://github.com/cdr/code-server/issues/1939#issuecomment-668158611)?) again.

I'm trying to get `VSCODE_HTTP_REFERER` accepted as environment variable.  
👉 The name of their ancestor; a common name to implement the functionality for [Ikuyadeu/vscode-R](https://github.com/Ikuyadeu/vscode-R) in all of VS Code derivatives - if their collaborators decide to do so.

**Comment by benz0li** [comment]
PR https://github.com/cdr/code-server/pull/3621 should be part of the next code-server release.

The environment variable will be named `VSCODE_PROXY_URI`.

**Comment by benz0li** [comment]
@renkun-ken Applying patch

```diff
diff --git a/R/session/vsc.R b/R/session/vsc.R
index cc17286..90a8bf7 100644
--- a/R/session/vsc.R
+++ b/R/session/vsc.R
@@ -494,11 +494,23 @@ request_browser <- function(url, title, ..., viewer) {
 
 show_browser <- function(url, title = url, ...,
                          viewer = getOption("vsc.browser", "Active")) {
+  if (nzchar(Sys.getenv("VSCODE_PROXY_URI"))) {
+    is.base_path <- grepl("\\:\\d+$", url)
+    url <- sub("^https?\\://(127\\.0\\.0\\.1|localhost)(\\:)?",
+      sub("\\{port\\}", "", Sys.getenv("VSCODE_PROXY_URI")), url)
+    if (is.base_path) {
+      url <- paste0(url, "/")
+    }
+  }
   if (grepl("^https?\\://(127\\.0\\.0\\.1|localhost)(\\:\\d+)?", url)) {
     request_browser(url = url, title = title, ..., viewer = viewer)
   } else if (grepl("^https?\\://", url)) {
     message(
-      "VSCode WebView only supports showing local http content.\n",
+      if (nzchar(Sys.getenv("VSCODE_PROXY_URI"))) {
+        "VSCode is not running on localhost but on a remote server.\n"
+      } else {
+        "VSCode WebView only supports showing local http content.\n"
+      },
       "Opening in external browser..."
     )
     request_browser(url = url, title = title, ..., viewer = FALSE)
@@ -535,11 +547,23 @@ show_webview <- function(url, title, ..., viewer) {
       stop("Invalid object")
     }
   }
+  if (nzchar(Sys.getenv("VSCODE_PROXY_URI"))) {
+    is.base_path <- grepl("\\:\\d+$", url)
+    url <- sub("^https?\\://(127\\.0\\.0\\.1|localhost)(\\:)?",
+      sub("\\{port\\}", "", Sys.getenv("VSCODE_PROXY_URI")), url)
+    if (is.base_path) {
+      url <- paste0(url, "/")
+    }
+  }
   if (grepl("^https?\\://(127\\.0\\.0\\.1|localhost)(\\:\\d+)?", url)) {
     request_browser(url = url, title = title, ..., viewer = viewer)
   } else if (grepl("^https?\\://", url)) {
     message(
-      "VSCode WebView only supports showing local http content.\n",
+      if (nzchar(Sys.getenv("VSCODE_PROXY_URI"))) {
+        "VSCode is not running on localhost but on a remote server.\n"
+      } else {
+        "VSCode WebView only supports showing local http content.\n"
+      },
       "Opening in external browser..."
     )
     request_browser(url = url, title = title, ..., viewer = FALSE)
```

will open shiny apps, htmlwidgets, etc. in separate browser windows on code-server if environment variable `VSCODE_PROXY_URI` is set. Should `options(vsc.helpPanel = FALSE)`, this is also true for the help panel when called from R terminal.

This does not affect the behaviour of the 'Help viewer' from the R extension itself, though. And 'R Help Panel: Open in external browser' will still use `http://localhost:${this.port}/${requestPath}`.  
👉 Unfortunately, I can't tell you which modifications have to be applied to the [helpViewer scripts](https://github.com/REditorSupport/vscode-R/tree/master/src/helpViewer).

**Comment by benz0li** [comment]
`options(vsc.use_httpgd = TRUE)` (the SVG plot viewer based on httpgd) works well on code-server.

'Open in external Browser' currently fails because [httpgd.ts](https://github.com/REditorSupport/vscode-R/blob/master/src/plotViewer/httpgd.ts) does not consider `VSCODE_PROXY_URI`.  
ℹ️ Even if `VSCODE_PROXY_URI` could be considered, the request would fail throwing error `Uncaught DOMException: The operation is insecure.` with my setup, as code-server is served via JupyterHub and neither `VSCODE_PROXY_URI` nor `JUPYTERHUB_API_TOKEN` currently being considered when requesting the httpgd API endpoints.

**Comment by benz0li** [comment]
Thanks for the prompt feedback.

I've just recently updated the R extension from v1.6.8 to v2.3.0. Might be related to https://github.com/REditorSupport/vscode-R/pull/708 as the data viewer worked with v1.6.8.

**Comment by benz0li** [comment]
Most probably related to https://github.com/cdr/code-server/discussions/4075#discussioncomment-1364100.

**Comment by benz0li** [comment]
@renkun-ken Should I prepare a pull request for the changes in `vsc.R`?

**Comment by renkun-ken** [comment]
@benz0li Sure, please.

**Comment by benz0li** [comment]
@renkun-ken This issue may be closed, as I do not consider possible modifications to the [helpViewer scripts](https://github.com/REditorSupport/vscode-R/tree/master/src/helpViewer) and [plotViewer scripts](https://github.com/REditorSupport/vscode-R/tree/master/src/plotViewer) to be relevant to this issue.

**Comment by benz0li** [comment]
@renkun-ken `View(mtcars)` works now. Not sure why, though.

Updated this extension from v2.3.0 to v2.3.3. code-server hasn't been updated in the meantime.
