### ISSUE TITLE
There are no open terminals

### ISSUE THREAD

**Issue by ZHULOO** [REditorSupport/vscode-R#291]
- VSCode Version: 1.44.2
- VSCode-R Version: 1.2.8
- OS Version: windows 10
All settings were done, but when I type the `ctrl+enter`, there will be a massage "There are no open terminals.", so I have to run `R : Create  R terminal` and then type `ctrl +enter` to run the selected line in the created radian terminal.
How can I run the selected line in the radian terminal directly when I type the `ctrl+enter`, without having to run `R : Create  R terminal`  first ?

(If related)setting.json

```json
// R.exe path for windows
"r.rterm.windows": "D:\\Anaconda\\Scripts\\radian.exe",


// R command line options (i.e: --vanilla)
"r.rterm.option": [],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": true,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher (experimental)
"r.sessionWatcher": true,
```

**Comment by andycraig** [comment]
Hi @ZHULOO, thank you for posting this issue. That’s the error message when `"r.alwaysUseActiveTerminal": true` and there are no open terminals. But you’re right, it would probably be better to just create a new terminal in that case.

**Comment by ZHULOO** [comment]
I still have another problem, at first, I thought it was [the `radian` 's problem](https://github.com/randy3k/radian/issues/176), Now it has been proved it maybe the `vscode-R` 's encoding problem. would you please help me to resolve it?

**Comment by renkun-ken** [comment]
@ZHULOO Please file a new issue for your plot encoding problem. Thanks!

**Comment by gowerc** [comment]
@renkun-ken I think this can be closed now ?
