### ISSUE TITLE
.rmd becomes .md 

### ISSUE THREAD

**Issue by fdq09eca** [REditorSupport/vscode-R#295]
I am very new to r and i would like to use it in vscode. I wanted to test the `.rmd` possibility, but the `rmd` is considered as `md` by vscode. the keybinding `cmd+shift+s` triggers **_save as_**  but not **_executes_** `.rmd` as expected; having said that, `.r` works fine with the keybinding. Any idea?

![image](https://user-images.githubusercontent.com/51902242/80712824-1aecd180-8b25-11ea-887c-4199321372c2.png)

Thank you

**Comment by renkun-ken** [comment]
You may need to add the following to `settings.json`:

```json
"files.associations": {
        "*.rmd": "rmd"
}
```

**Comment by fdq09eca** [comment]
> You may need to add the following to `settings.json`:
> 
> ```json
> "files.associations": {
>         "*.rmd": "rmd"
> }
> ```

thanks, it works it is interpreted as it should be now, but I have this instead when I hit`Knit  Rmd`
```terminal
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
```
![image](https://user-images.githubusercontent.com/51902242/80764146-a50f5700-8b72-11ea-8d2a-262e2232a7d5.png)

**Comment by fdq09eca** [comment]
> > You may need to add the following to `settings.json`:
> > ```json
> > "files.associations": {
> >         "*.rmd": "rmd"
> > }
> > ```
> 
> thanks, it works it is interpreted as it should be now, but I have this instead when I hit`Knit Rmd`
> 
> ```
> Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
> ```
> 
> ![image](https://user-images.githubusercontent.com/51902242/80764146-a50f5700-8b72-11ea-8d2a-262e2232a7d5.png)

I got it through by
```
brew install pandoc
```
now it renders to `.html` nicely.
but any chance that i can get it in `.pdf`?
last question how do i have the icon of `.rmd` in vscode? now it appears as unknown file type

**Comment by renkun-ken** [comment]
Good to know that you figure it out. We need to put this into wiki.

As for the icon, @andycraig Any idea?

**Comment by andycraig** [comment]
@fdq09eca @renkun-ken I'd never noticed that .Rmd files don't have an icon! I'll make a new issue for it.

**Comment by assignUser** [comment]
With #298 being closed this issue can probably also be closed?
