### ISSUE TITLE
Magrittr pipes trigger indent on newline

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#321]
Not sure if this is the right place for this request, please delete if not !

Would it be possible to get magrittr's pipes `%>%` to be treated akin to brackets where an automatic indent happens if you press enter on a line whose last symbol is the pipes? 

i.e.
 having

```
iris %>% mutate(...)
```

and pressing `enter`  after the `%>%` but before the `mutate(...)`  would result in 

```
iris %>%
    mutate(...)
```

At the moment when I do this it just comes out as:

```
iris %>%
mutate(...)
```

**Comment by andycraig** [comment]
@gowerc Thank you for the suggestion! This would be a good feature.

The slightly tricky thing here is that the indentation should not increase with subsequent pipes:

```
# BAD
iris %>%
    mutate(...) %>%
        select(...)

# GOOD
iris %>%
    mutate(...) %>%
    select(...)
```

Hopefully we can do it using `onEnterRules` here: https://github.com/Ikuyadeu/vscode-R/blob/725c1a873440d004ec47af847912665a82aa8ad5/src/extension.ts#L165

**Comment by andycraig** [comment]
Actually looks like `indentNextLinePattern` might be the key here, as it applies to the next line only: https://code.visualstudio.com/api/references/vscode-api#IndentationRule

**Comment by renkun-ken** [comment]
@gowerc https://github.com/REditorSupport/languageserver/pull/209 implements on-type-formatting on user input at expression-level based on a backward parsing strategy. With `editor.formatOnType = true` and vscode-r-lsp and languageserver installed, the formatting is exactly what you want.

**Comment by gowerc** [comment]
Thanks @renkun-ken ,   

This indeed does work.  Only caveat would be that it also comes with the automatic formatting as well (i.e.  converting `1+1` to `1 + 1`) which I'm not sure if I want or not yet. There is also a noticeable twitch/jump from pressing enter to the code being re-formatted into position. 

This this does what I need so thank you very much :) 

@andycraig ,  I still think it would be nice to have an editor specific solution to this (if you have the desire to implement it) but I do have a workaround now so feel free to close the ticket if you are not interested :)

**Comment by andycraig** [comment]
@renkun-ken I’d quite like this feature too so that it’s there even when `editor.formatOnType` is `false`. I would guess any performance hit from formatting coming from both VS Code and the language server should be negligible when `editor.formatOnType` is `true` but what do you think?

**Comment by andycraig** [comment]
I thought this would be a matter of adding this to `r-configuration.json`:

```
"indentationRules": {
    "indentNextLinePattern": "%>%"
}
```

But when I do that and type

```
iris %>%
```

and hit enter, this is the result:

```
iris %>%
#' 
```

So it seems that the indentation rule is erroneously triggering the `onEnterRules` rule from `extension.ts`. Not sure if that's me misusing one of them, or from a VS Code bug.

**Comment by gowerc** [comment]
I tried the following in `r-configuration.json` which nearly works but not quite :(

```
"indentationRules": {
		"increaseIndentPattern": "^.*\\{[^}\"']*$|^.*\\([^\\)\"']*$",
		"decreaseIndentPattern": "^\\s*(\\s*\\/[*].*[*]\\/\\s*)*[})]",
		"indentNextLinePattern" : "%>%\\s*$",
		"unIndentedLinePattern" : "^\\s+.*%>%\\s*$"
	},
```

The results were: 

![2020-05-14 13 53 14](https://user-images.githubusercontent.com/8447209/82206603-6dd5cf80-9900-11ea-8429-27b834ab9549.gif)

I'm struggling to think of a pattern that would work in both cases.  I tried only using the `indentNextLinePattern` but as you feared it just continuously indented...

**Comment by gowerc** [comment]
Perhaps as a half way house solution we could try this ? 

A new enter rule which indents on lines that contain `<-` but ends in `%>%`

```
            {
               action: { indentAction: IndentAction.Indent},
               beforeText: /<-.*%>%\s*$/,
            }
```

![2020-05-18 14 03 01](https://user-images.githubusercontent.com/8447209/82216184-7c2be780-9910-11ea-909c-55821b9787eb.gif)

Its not perfect but should cover the main usecases ?

**Comment by andycraig** [comment]
@gowerc Thank you for working on this! I'll have a proper look this weekend.

**Comment by andycraig** [comment]
> A new enter rule which indents on lines that contain <- but ends in %>%

I think this is probably the best option for now but I want to have a little bit more of a think/experiment before we incorporate it.

**Comment by renkun-ken** [comment]
I'm curious about how the text edits are handled if `editor.formatOnType` is enabled and languageserver also performs on-type-formatting and indention, and vscode-R also makes some indention?

**Comment by andycraig** [comment]
I've had a bit more of a think and haven't come up with anything else. I think it would be okay to incorporate this provided there's no conflict between vscode-R formatting and languageserver formatting when `editor.formatOnType` is enabled. I haven't checked whether that's the case.

**Comment by andycraig** [comment]
It would be good to have indentation for parenthesis, brackets and braces specified in `r-configuration.json` to address #435 

The open question is whether it will work properly together with format on type: https://github.com/Ikuyadeu/vscode-R/issues/321#issuecomment-633177496

@gowerc Are you interested in doing some testing of how automatic indentation works together with format on type? If not I can work on this.

**Comment by gowerc** [comment]
Apologies but I just don't have time at the moment to assist :(

**Comment by andycraig** [comment]
@gowerc No problem, thank you for all your research! I will do some testing and see if I can get Reindent Lines working.

**Comment by storopoli** [comment]
Guys I am having something strange.

My vscode-R with R LSP Client and languageserver installed in a Intel Mac and a M1 Mac. All configurations the same. I cannot get the:

```json
"editor.formatOnType": true,
"editor.formatOnSave": true,
"editor.formatOnPaste": true
```

to work in the M1 and it is flawless in the Intel. Same VS Code versions and extensions installed in both systems.

**Comment by reliscu** [comment]
Any plans to implement this capability?
