### ISSUE TITLE
Rmd Color coding doesn't work if there is a space after the backticks and the bracket

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#326]
Rmd Color coding doesn't work if there is a space after the backticks and the bracket.

Image for clarity:

![image](https://user-images.githubusercontent.com/8447209/82070984-5ebb0b80-96cd-11ea-8a34-4a5e09798e00.png)

Apparently this is still valid for Rmd and will still render without issue -.-

**Comment by gowerc** [comment]
Posted in wrong place please ignore - Sorry

**Comment by renkun-ken** [comment]
Syntax highlighting is handled in vscode-R.

Looks like Rmd chunk could start with "`{3,}\s*\{", all marked as code chunk in RStudio and valid for knitr to render.

@andycraig Should we adjust the syntax highlighting to be consistent with RStudio and knitr?

**Comment by andycraig** [comment]
Interesting, I never knew spaces were allowed there! Yes, let’s adjust the syntax highlighting.

**Comment by andycraig** [comment]
@gowerc This should be a fairly straightforward fix. Are you interested in putting together a PR for it? :)

**Comment by gowerc** [comment]
Happy to try though I caveat I don't know JS or node at all (but could be a good learning experience :) )

**Comment by andycraig** [comment]
@gowerc Great! The R Markdown highlighting is defined in this file: https://github.com/Ikuyadeu/vscode-R/blob/master/syntax/Markdown%20Redcarpet.tmLanguage It's the only file that should need editing. The lines that needed editing are like this: https://github.com/Ikuyadeu/vscode-R/blob/b27399c9bbd2711454367fe0ce73bd77b7b239e6/syntax/Markdown%20Redcarpet.tmLanguage#L97 That one's for R chunks, and there are some for other languages as well.

Instructions for how to get set up for contributing are here: https://github.com/Ikuyadeu/vscode-R/wiki/Contributing

Let us know if you have any difficulties!

**Comment by gowerc** [comment]
@andycraig  - Can I just double check my understanding of how this works:

package.json - specifies the new grammers introduced by the package (amongst lots of other stuff)

This then adds the scope `text.html.rmarkdown` to files that meet the requirements set out by  `./syntax/RMarkdown.json` which within that file is defined for `Rmd` and `rmd` however the actual langauge grammar for `text.html.rmarkdown` is defined within `Markdown Redcarpet.tmLanguage` ?

How come Rmd is using the xml format and split across 2 files opposed to the R format which is just 1 single Json file ? Am I missing something ?

**Comment by gowerc** [comment]
On a separate note,  the current regex pattern matches on any number of leading/trailing `{`  is this expected ? 

I don't think knitr will render R code unless it is exactly 1 `{`  so should we adapt the regex to only match on exactly `{r}` ?

**Comment by andycraig** [comment]
> I don't think knitr will render R code unless it is exactly { r <options>} so should we adapt the regex to only match this setup ?

Matching what knitr will render sounds like a good approach to me. Thank you!

> How come Rmd grammar is using the xml format and split across 2 files opposed to the R grammar which is just 1 single json file ? Am I missing something ?

Good questions.

**XML/JSON**
VS Code supports both. `Markdown Redcarpet.tmLanguage` existed first, and when I added `RMarkdown.json` I used a JSON file because I find them easier to work with.

**Split across 2 files**
The R Markdown definition is complicated because it combines features of multiple languages.

- `Markdown Redcarpet.tmLanguage`: Defines highlighting for R Markdown-specific structures
- `RMarkdown.json`: Causes Rmd files to also use VS Code's built-in Markdown highlighting

`r.json` is the equivalent of `Markdown Redcarpet.tmLanguage`. For R, there's no equivalent of `RMarkdown.json` because it doesn't use highlighting defined elsewhere.

The current set up for R Markdown still has some limitations and may not be optimal (#289).

Hopefully that makes things a bit clearer but let me know if you'd like anything else clarified.

**Comment by gowerc** [comment]
Any objections to me converting the .tmLanguage file into Json,  my opinion is that it will make it much easier to read and edit in the future and the conversion doesn't look too painful to do

**Comment by andycraig** [comment]
> Any objections to me converting the .tmLanguage file into Json, my opinion is that it will make it much easier to read and edit in the future and the conversion doesn't look too painful to do

I agree that it would be easier to read and edit, so it’s okay by me! My only request is that there’s a commit that contains ONLY that change.

@Ikuyadeu Is this okay with you?

**Comment by Ikuyadeu** [comment]
@andycraig @gowerc Great discussion!
Making syntax files to JSON is good.

**Comment by gowerc** [comment]
Looks like this got fixed in a prior commit (no idea which) closing
