### ISSUE TITLE
Understanding how the Rmd regex should work

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#341]
Hi @andycraig & @renkun-ken ,

I was hoping to query the logic behind the regex in the Rmd language file as well as question how we want these files to work.  For reference here is the current R pattern:

```
(^|\G)([`]{3})\{*[ ]*(?:r|R)([ ,\}].*\}*|\})$
```

1) Patterns

Currently the regex starts with `\G` which means it can match to the last previous pattern. Should it not be hard fixed to start on a new line ? 

Likewise the pattern uses a non capturing group to see what language is being used. Whilst not incorrect, I feel the regex would read nicer if it was just a standard pattern, is there a reason for using the groups and non capturing groups here?

For example would the following not be valid ? 

```
^`{3} *\{(R|r)(\}|[ ,].*\}) *$
```

2) Syntax highlighting vs validity

There are several cases where the pattern will match and syntax highlighting will be added even though the block isn't valid for knitr. I think in these cases though the match is still valid for standard markdown and it might be that the user just wants to add example code to the document (equivalent to using `eval=False`)

For example  ` ```{C}`  is invalid and wouldn't be evaluated by knitr but ` ```{c}` is valid however both are given syntax highlighting under our current pattern rules.  

Another invalid example that we add highlighting to is where there is a space between the `{` and the  language name e.g.

 
![image](https://user-images.githubusercontent.com/8447209/82749803-95ff7b80-9da3-11ea-82b3-f8b1fa937aec.png)

vs Rstudio

![image](https://user-images.githubusercontent.com/8447209/82749773-6d778180-9da3-11ea-9035-7923f0cc5836.png)

---

For (1) I guess I don't understand enough of how these regex's are used by vscode but personally I would like to simplify them if it doesn't impact anything

For (2),  my personal opinion is that in Rmd files we should focus on highlighting only valid knitr blocks (even if it is valid markdown) for example `rcpp` isn't a supported but `Rcpp` is therefore I think we should only highlight the code if `Rcpp` is being used to give a visual cue to the user wether their block is correct or not.

(Apologies for the long post but I just wanted to better understand what is going on as it is related to #326  & #334 )

**Comment by andycraig** [comment]
Hi @gowerc, thank you for writing this.

(1) I think it's fine to do the simplifications you suggest.

> Currently the regex starts with \G which means it can match to the last previous pattern. Should it not be hard fixed to start on a new line ?

Agree, I think new line makes more sense.

> Likewise the pattern uses a non capturing group to see what language is being used. Whilst not incorrect, I feel the regex would read nicer if it was just a standard pattern, is there a reason for using the groups and non capturing groups here?

I THINK the groups are there because the individual elements were given different identifiers at some point. This would have allowed for the backticks to be given different highlighting from the language name. I think these groups can be removed.

(2) I agree with the approach for highlighting being consistent with what knitr can process.
