### ISSUE TITLE
Syntax highlighting incorrectly applied to characters wrapped in backticks

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#346]
Incorrect syntax highlighting is being added to variable names that are enclosed in backticks (see screenshot below)

![image](https://user-images.githubusercontent.com/8447209/83008395-fd6c3400-a00c-11ea-8d36-d09dbba33416.png)

(wasn't sure where to post this so please let me know if it needs to go to the language server extension repo instead)

**Comment by renkun-ken** [comment]
Yes, you are right. All syntax highlighting is provided by vscode-R.

**Comment by renkun-ken** [comment]
Already fixed via #859.
