### ISSUE TITLE
Options to customize session watcher behavior

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#358]
There are plenty of issues requesting options to customize session watcher behavior. This issue is a collection of all existing issues regarding session watcher options.

* Plot created by plot functions:
  * [x] Device: #277
  * [x] Viewer: #331
* WebView in general:
  * [ ] Theming: #178, #172
* `browser` webview created by shiny, R help, httpgd, etc.
  * [x] Viewer: https://github.com/Ikuyadeu/vscode-R/issues/329#issuecomment-641004693, #243, #166
  * [x] Proxy: #275
  * [x] Search: #204
  * [ ] Customizable port mapping: #192
* `viewer` and `page_viewer` webview created by htmlwidgets, profvis, etc.
  * [x] Viewer: #243
* Data webview created by `View()`
  * [x] Viewer: #243
  * [ ] Replace existing: #214

I'm thinking of defining more options to allow users to customize the behavior of session watcher so that different features (e.g. plot) could be disabled, and the viewer of `browser`, `viewer`, `page_viewer`, and `View()` could be a VSCode ViewColumn (Active, Beside, etc.) or external (open a web browser on client side like R's native behavior).

**Comment by benz0li** [comment]
@renkun-ken May you/we have another go at issue #275?

The [integration of httpgd](https://github.com/Ikuyadeu/vscode-R/pull/620) works fine with VS Code but not with code-server. This is because the `url` points to `127.0.0.1` (`localhost`) instead of the URL at which code-server ist running.

I'm happy to provide you with a dev environment. You will receive an email with more details asap.

**Comment by renkun-ken** [comment]
@benz0li Thanks for providing a dev environment.

**Comment by benz0li** [comment]
@renkun-ken Just tell me, if you need additional Linux packages for development.

**Comment by benz0li** [comment]
I have set up a dev environment at https://vscode-r.jupyter.b-data.ch. Sign in is done with your GitHub account.
ℹ️ Whitelisted users: @renkun-ken @Ikuyadeu 

The setup is based on https://gitlab.b-data.ch/docker/deployments/jupyter and currently running
*  JupyterHub v1.4.1
*  JupyterLab v3.0.16 including
    *  code-server v3.10.2 (aka VS Code v1.56.1)
    *  Extensions: R v1.6.8 and R LSP Client v0.1.14
    * ...

👉 Full specification of the JupyterLab image at https://gitlab.b-data.ch/jupyterlab/r/r-ver/-/blob/master/r-ver/latest.Dockerfile; plus `libxt-dev` installed in addition.

I’m happy to further customize the Docker image, i.e. adding any Linux package you need to get your work done.

**Comment by benz0li** [comment]
FYI https://vscode-r.jupyter.b-data.ch has been updated:

*  JupyterHub v1.4.2
*  JupyterLab v3.1.12 including
    *  code-server v3.12.0 (aka VS Code v1.60.0)
    *  Extensions: R v2.2.0
    * ...

https://github.com/cdr/code-server/blob/main/docs/CONTRIBUTING.md#requirements are installed, too.  
ℹ️ https://github.com/cdr/code-server/issues/3661 is still an open issue, though.
