### ISSUE TITLE
Notebook format

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#395]
As I'm trying to implement the R Notebook using the [Notebook API](https://code.visualstudio.com/api/extension-guides/notebook) at #394 initiated by #378, the first question is 

*What is the format of R Notebook in VSCode*?

From the perspective of API, we could read any file into a collection of markdown cells and R code cells. Currently, https://github.com/Ikuyadeu/vscode-R/pull/394/files#diff-896fa9128d2e83307ffcf26741d257d2R142-R212 implements a simple line-by-line reader from Rmd file. All R code chunks are treated as R code cells, and others are treated as markdown cells.

The Rmd format is easy to read and write but it does not store output inside the file. I've tried R Notebook in RStudio and I don't have time to investigate how it could recover the output when I open an R Notebook from a Rmd file.

As most VSCode Notebook examples implement, the notebook is a JSON file of all cells and metadata, which could preserve all information in a notebook including cells and outputs.

I'm wondering if we should also implement R Notebook as a JSON file to achieve this, and preserve the capability of reading/writing Rmd as a Notebook but does not preserve outputs?

**Comment by andycraig** [comment]
I had a quick look at the way RStudio R Notebooks save the output. Here are the relevant files from the `.Rproj.user` directory in a project that contains an R Notebooks `test.Rmd`, which has two R chunks:

```
└───shared
    └───notebooks
        │   patch-chunk-names
        │   paths
        │
        └───B5CE159A-test
            └───1
                └───s
                    │   chunks.json
                    │
                    ├───c68yx1b0064yu
                    │       000002.csv
                    │       000003.png
                    │
                    └───ccw2gfveoholl
                            000002.csv
```

The content of `chunks.json` is:

```json
{"chunk_definitions":[{"chunk_id":"c68yx1b0064yu","expansion_state":0,"options":[],"row":11,"row_count":1,"visible":true},{"chunk_id":"ccw2gfveoholl","expansion_state":0,"options":[],"row":17,"row_count":1,"visible":true}],"doc_write_time":1597363618.19062}
```

It seems logical but figuring out the details could take a while, as you say.

I think the user should only need to know about the Rmd file. Having the 'actual' notebook be a JSON file sounds fine to me. I think it should be hidden from the user (e.g., saved in `.Rproj.user`). Then we could replace it later with an RStudio-compatible version if we wanted to.

From https://bookdown.org/yihui/rmarkdown/notebook.html#saving-and-sharing 'The document’s chunk outputs are also stored in an internal RStudio folder beneath the project’s `.Rproj.user` folder. If you work with a notebook but do not have a project open, the outputs are stored in the RStudio state folder in your home directory (the location of this folder varies between the desktop and the server)'.
