### ISSUE TITLE
In VSCode only, re-knitting [Rmd -> XeLaTeX -> PDF] fails after first knit, until R session terminated.

### ISSUE THREAD

**Issue by epgui** [REditorSupport/vscode-R#414]
With a fresh session, I can hit `⌘⇧K` and get my Rmd knit into a nice PDF using XeLaTeX without problem. However, once this job is finished, the R session remains open in the terminal.

<img width="1680" alt="Screen Shot 2020-09-27 at 10 23 08 PM" src="https://user-images.githubusercontent.com/1992822/94394241-b359a300-0111-11eb-98c8-5dfd78503295.png">

If I `quit()` the  R session, I can knit my document again, no problem.

<img width="1680" alt="Screen Shot 2020-09-27 at 10 23 08 PM" src="https://user-images.githubusercontent.com/1992822/94394241-b359a300-0111-11eb-98c8-5dfd78503295.png">

If I don't `quit()` the R session from the terminal and attempt to re-knit the same document, things blow up like the Hindenburg:

<img width="1680" alt="Screen Shot 2020-09-27 at 10 23 33 PM" src="https://user-images.githubusercontent.com/1992822/94394101-5958dd80-0111-11eb-9d37-350d45c6aab0.png">

Package `kableExtra` injects dependencies in LaTeX document ([see page 4](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf)):

```
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
```

If I add these to my YAML, then I can re-knit multiple times without terminating my R session. If I run my thing from RStudio, I don't have this issue. I only have this issue when I run it in VSCode.

Apart from using XeLaTeX and kableExtra, I am not doing any other funny business. Attached is the successfully rendered document as evidence:

[Analysis.pdf](https://github.com/Ikuyadeu/vscode-R/files/5290124/Analysis.pdf)

sessionInfo()
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
locale: en_US.UTF-8||en_US.UTF-8||en_US.UTF-8||C||en_US.UTF-8||en_US.UTF-8
attached base packages: stats, graphics, grDevices, utils, datasets, methods and base
other attached packages: kableExtra(v.1.2.1), stringr(v.1.4.0), reshape2(v.1.4.4), dplyr(v.1.0.2) and ggplot2(v.3.3.2)
loaded via a namespace (and not attached): Rcpp(v.1.0.5), pillar(v.1.4.6), compiler(v.4.0.2), plyr(v.1.8.6), tools(v.4.0.2), digest(v.0.6.25), viridisLite(v.0.3.0), evaluate(v.0.14), lifecycle(v.0.2.0), tibble(v.3.0.3), gtable(v.0.3.0), pkgconfig(v.2.0.3), rlang(v.0.4.7), rstudioapi(v.0.11), yaml(v.2.2.1), xfun(v.0.17), withr(v.2.2.0), httr(v.1.4.2), knitr(v.1.29), xml2(v.1.3.2), generics(v.0.0.2), vctrs(v.0.3.4), webshot(v.0.5.2), grid(v.4.0.2), tidyselect(v.1.1.0), glue(v.1.4.2), R6(v.2.4.1), rmark- down(v.2.3), pander(v.0.6.3), purrr(v.0.3.4), magrittr(v.1.5), scales(v.1.1.1), ellipsis(v.0.3.1), htmltools(v.0.5.0), rvest(v.0.3.6), colorspace(v.1.4-1), stringi(v.1.5.3), munsell(v.0.5.0) and crayon(v.1.3.4)
```

OS:
```
Mac OS version 10.15.3
```

VSCode:
```
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.3.0
```

**Comment by MilesMcBain** [comment]
Just a guess here but I think this may be related to this:

https://github.com/rstudio/rmarkdown/issues/1673

The issue being global environment contamination coming from the rendering.

You could test this by attempting to render from R terminal, e.g. with `rmarkdown::render()`:

* if you can render from the R terminal twice in a row, this is not the issue.
* If you cannot do above, but you can do  `callr::r(func = function() rmarkdown::render())`, without issues, then session contamination is the issue.

**Comment by MilesMcBain** [comment]
One other theory would be render #2 is failing because an application that is showing the output of render #1 has acquired a write lock on the file (Acrobat is notorious for this). So you could make sure the output is not open anywhere before trying to render again.

**Comment by MilesMcBain** [comment]
I'm now 99% sure this is a contamination issue. `{kableextra}` injects those dependencies via it's [`onLoad` hook](https://github.com/haozhu233/kableExtra/blob/master/R/zzz.R), which will only be called the first time the document is rendered, because that load happens in the same session as the one in the R terminal.

**Comment by ElianHugh** [comment]
The new knit button uses a background process for knitting, so the contamination issue should be fixed! Feel free to re-open if you still run into this issue :)
