### ISSUE TITLE
R session watcher -  autocomplete function names loaded in the session

### ISSUE THREAD

**Issue by adicara** [REditorSupport/vscode-R#418]
- VSCode Version:  1.49.2
- VSCode-R Version: 1.4.6
- OS Version: Ubuntu 16.04

Very nice work on this extension. Thanks !
I was wondering if the R session watcher can provide some code completion help, based on the functions loaded in the session. For example after executing `library(ggplot2)` I would like the code completion to propose all the geom_* functions. This currently works in the terminal but not in the editor.

**Comment by renkun-ken** [comment]
Providing completions based on loaded functions in session will require near-live communication between vscode-R and the session via R's built-in completions which further requires constantly asking the session to evaluate expressions to get completions on the current token.

Currently, we impose minimal control on the evaluation of the user R session so it is not likely to be supported unless we decide to move to the approach to fully manage the session, just like how [VSCode R Debugger](https://github.com/ManuelHentschel/VSCode-R-Debugger) supports session completion with its [vscDebugger](https://github.com/ManuelHentschel/vscDebugger/blob/master/R/completion.R#L41).
