### ISSUE TITLE
Issues with rstudioapi emulation

### ISSUE THREAD

**Issue by MilesMcBain** [REditorSupport/vscode-R#421]
A couple of things I noticed when the update landed on my work PC:

* `tidyverse` calls the rstudioapi to check the version which errors, stopping it from being attached.
* For some reason the R building of the addin list fails which interferes with `.vsc.attach`.

@Ikuyadeu @renkun-ken `tidyverse` is a bit of a showstopper. The second issue might be to do with my work PC library setup which is a bit unusual. I'll so some debugging on it now.

Is it possible to roll back to previous release?

**Comment by dcangst** [comment]
I have the same issue. Any pointers on how to fix/downgrade?

(love the new features though! Thanks!)

**Comment by MilesMcBain** [comment]
Yes sorry @dcangst, you can install a vsix file from a recently tagged release. Or if you want a very recent build you might try the one here:

https://github.com/Ikuyadeu/vscode-R/actions/runs/300521275

Instructions on manual vsix install:
https://code.visualstudio.com/docs/editor/extension-gallery#:~:text=Install%20from%20a%20VSIX%23,vsix%20file.

**Comment by dcangst** [comment]
no worries! thanks for the quick reply!!

**Comment by MilesMcBain** [comment]
I've figured out the second issue. This is to do with malformed addins.dcf files. In this case from `shrtcts` on my work machine. I can do some filtering to protect against it and perhaps put the whole parsing thing in a try-catch so that it doesn't stop the session being attached properly.

**Comment by renkun-ken** [comment]
I guess we need to do a quick fix to opt-in this feature using `options(vsc.rstudioapi = TRUE)`.

By default, it is not enabled and rstudioapi-related code will not be sourced?

@MilesMcBain @Ikuyadeu What do you think?

**Comment by MilesMcBain** [comment]
I think it's a good idea. :+1:

**Comment by renkun-ken** [comment]
@MilesMcBain I don't quite get what's not working.

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/4662568/96118469-1fb01100-0f1e-11eb-9822-661455c5db7d.png">

`library(tidyverse)` seems to work normally?

**Comment by dcangst** [comment]
this is what I get when running the master branch using 'f5':
<img width="1311" alt="Screenshot 2020-10-15 at 13 43 51" src="https://user-images.githubusercontent.com/7902555/96118965-90d6d080-0eec-11eb-9d48-24e20a273191.png">

**Comment by MilesMcBain** [comment]
Yeah that's what I saw too.

**Comment by MilesMcBain** [comment]
Oh classic I see in only on my Windows work machine. Not on my personal Linux machine.

It'll be something to do with checking the terminal type for the fancy tidyverse colours I bet.

**Comment by dcangst** [comment]
I don't think this is a solution, but defining these two rstudioapi functions 'fixes' the issue

```
getVersion <- function() {
    numeric_version(0)
}

versionInfo <- function() {
    numeric_version(0)
}
```

random version numbers work. versionInfo is supposed to return a list, still works.

**Comment by MilesMcBain** [comment]
I think I was on the right track: 

The call which fails is in cli https://github.com/r-lib/cli/blob/cd4374c736e0c65f54ec56e40d6ba432b6c74b7b/R/rstudio-detect.R#L24

And there's a bunch of stuff in there which looks platform dependent.

**Comment by MilesMcBain** [comment]
I think for now the only thing that is going to work for Windows users is the fix suggested by @dcangst.

RStudio did offer to discuss any issues we had, so I might contact them and see if there's a better way to do things. Maybe we can set an env var or option that tells these tools the terminal is VSCode.

**Comment by MilesMcBain** [comment]
Okay PR in a few mins with fixes and option to enable the emulation.

**Comment by renkun-ken** [comment]
Maybe off the topic but I notice in the [wiki page](https://github.com/Ikuyadeu/vscode-R/wiki/RStudio-addin-support#installing-addins) that

>Unlike RStudio the VSCode addin registry is regenrated every time a new R session is attached, not when a new package is installed. You can use rstudioapi::restartSession() to reattach the R session and repopulate installed addins.

It looks like user only needs to click the `R: (pid)` status bar item to re-attach the session to update the addin registry, no need to restart session?

**Comment by MilesMcBain** [comment]
Yeah sorry I think at one point I thought attach restarted R. I will fix.

**Comment by renkun-ken** [comment]
@Ikuyadeu We might need a release once this PR is merged and notice users that `options(vsc.rstudioapi = TRUE)` should be used to enable rstudioapi emulation in the changelog.

When the feature become more stable, then we could make it `TRUE` by default.

**Comment by Ikuyadeu** [comment]
@MilesMcBain @renkun-ken  Thank you for your early works. I'll put that notification on the CHANGELOG.
After Rstudio issue reports are stopped for more than 2 weeks, let's change it to be `TRUE`.

**Comment by ElianHugh** [comment]
Sorry to bump :smile:  

Given it has been a little while, would it make sense to set `r.session.emulateRStudioAPI` to true by default?

**Comment by MilesMcBain** [comment]
I'm in favour!
