### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#423]
For the following code:

```r
test[, (var1 * s)]
test[, test(var1)]
test[, test(var1 * var2)]
test[, test(x = var1 * var2)]
test[, test(x + var1 * var2)]
test[, .(
  p1 = test(var1 / var2),
  p2 = test((var1 + var2) / var1),
  p2 = test((var1 + var2) / var1 - var2)
)]

```

![image](https://user-images.githubusercontent.com/4662568/96219941-6e12ed80-0fba-11eb-94ea-0299c737cc49.png)

I'm curious why some `var1` got different coloring from `var2`?

**Comment by andycraig** [comment]
The highlighting being affected by what follows makes me wonder if this has the same cause as #120.

**Comment by andycraig** [comment]
I used the `Developer: Inspect Editor Tokens and Scopes` command and checked the textmate scopes. The orange ones have these scopes:

```
variable.parameter.r
meta.function-call.arguments.r
meta.function-call.r
source.r
```

The white ones are:

```
variable.other.r
meta.function-call.arguments.r
meta.function-call.r
source.r
```
