### ISSUE TITLE
Improve display of help pages

### ISSUE THREAD

**Issue by ManuelHentschel** [REditorSupport/vscode-R#432]
The integrated [viewer](https://github.com/Ikuyadeu/vscode-R/blob/63edf49d33cd2eb4f7a04f8b0c452a9e1c6ed463/src/session.ts#L207:L228) for e.g. help pages is already a great improvement over external browsers or simple text.

In [vscode-R-help](https://github.com/ManuelHentschel/vscode-R-help) I've tried to improve the help pages a bit further by reading the content of the html help files (found in the installation directory of packages), and directly rendering the html in a vscode.Webview. This makes it possible to modify the html to e.g.:
* apply custom css (match the color theme of the editor)
* apply syntax highlighting
* enable further customization (foldable sections, "click-to-run" examples, ...)

Instead of reading the html files directly, it would also be possible to start a normal http help server in R and forward all queries there to get the html (instead of doing so "indirectly" in an iframe).

Is this something you would consider implementing here?

I'd be happy to keep working on this, but could probably use some help, since I'm not very familiar with the codebase of this extension and don't have much experience with html/css either... :)

**Comment by Ikuyadeu** [comment]
@ManuelHentschel Thank you for your great implementation idea!
It looks helpful to not only display, but it also makes it easy to maintain the viewer source code.
If you submit a pull request here, we will review and merge that.

**Comment by ManuelHentschel** [comment]
The following improvement ideas came up while working on the help panel, but are not implemented yet:
- [ ] Include images etc. (e.g. the R logo on the main doc page)
- [ ] Handle links to PDF files (and other file types?)
- [ ] Improve the usability of `r.showHelp`: implement fuzzy matching, autocomplete, simulation of `?` in the command palette
- [ ] Implement `??`
- [ ] Adapt the style file to different themes, maybe let the user choose a style file

Anyone interested in working on this or further ideas are of course highly welcome! :)
