### ISSUE TITLE
data manipulation in vscode-r

### ISSUE THREAD

**Issue by LeoUtas** [REditorSupport/vscode-R#445]
**Is your feature request related to a problem? Please describe.**
I handle data a lot with R. In R studio, it's easy to use $ to access some layers of a data frame but it doesn't work yet in vscode.
Thanks for your great work
Hoang

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by renkun-ken** [comment]
If you enabled [R session watcher](https://github.com/Ikuyadeu/vscode-R/wiki/R-Session-watcher), then you should be able to complete the first level of names of any object.

**Comment by LeoUtas** [comment]
G' day there

Perhaps, I didn't express it clearly. I wanted to mention the suggestion or autocompletion when working with data. E.g. a data frame usually contains a bunch of columns, it'd be great to have the suggestions/autocompletion of a column to use with just a simple $ sign or something. 
Another thing is I can't handle python anymore. I tried to open a python file and execute it but the terminal is set to R automatically then it doesn't realize the python code. Did I miss something

Thanks a bunch for your beautiful work
H

**Comment by renkun-ken** [comment]
>I wanted to mention the suggestion or autocompletion when working with data. E.g. a data frame usually contains a bunch of columns, it'd be great to have the suggestions/autocompletion of a column to use with just a simple $ sign or something.

The session watcher supports session symbol completion (#165), i.e. `$`, `@` and `[` to trigger auto-completion of session symbols of list, data.frame and S4 objects. If you properly enabled this feature, it should work out of the box.

> Another important thing with data handling is to view list. If a dataset is in a format of a nested list. It'd great to have a way to view the list to see its structure (such as view() in R studio). It's necessary to view when it comes to set some loops for the nested list of data.

We don't have the RStudio-like viewer of nested list at the moment. The session watcher currently only supports a naive list viewer implemented in #150.

> Another thing is I can't handle python anymore. I tried to open a python file and execute it but the terminal is set to R automatically then it doesn't realize the python code. Did I miss something

You need to install [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension to work with python scripts and optionally [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) and a better language server for Python. Please visit https://code.visualstudio.com/docs/python/python-tutorial for more details.

**Comment by jooyoungseo** [comment]
In my case, auto-completion does not work for data.frame even though "r.sessionWatcher" is enabled. For example, I typed `airquality$` in VSCode editor, but it does not suggest any related columns, such as Ozone, Month, etc.

**Comment by renkun-ken** [comment]
Currently, the completion provided by session watcher is only capable of providing completions from global environment, i.e. variables created by user in `globalenv`, rather than symbols defined in packages (in this case, `airquality` comes from `{datasets}`).

If we implement #440 and use R's built-in completion in editor, we could provide completions like in RStudio but it will suffer from the same problem using such completion too.

**Comment by LeoUtas** [comment]
@renkun-ken You know what you guys are doing great I love your work. It greatly helps me to make my code tidy and neat using format document in vscode. Perhaps, we are just too familiar with Rstudio for such a long time then we find the auto completion in data handling and some other features e.g. we can run all the codes inside {} with just ctrl + Enter. 
I sometimes need to use Rstudio for quickly testing some chunks of codes and parallelly open my work in vs code
