### ISSUE TITLE
Help view: send code to console?

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/vscode-R#459]
Since the new help view (v1.6.0) (which is great @ManuelHentschel) includes hyperlinks and highlighting, I was wondering if it would be technically possible to send code from the examples to the active R session?

**Comment by ManuelHentschel** [comment]
This is definitely technically possible but might be quite difficult to implement.

The help view is implemented as [Webview](https://github.com/microsoft/vscode/blob/1436b523d4aaa773ab246daa68daaa70cef48b1d/src/vs/vscode.d.ts#L6943:L7021), which can only communicate with the rest of the editor through the command `postMessage`. Hence, keybindings like `Ctrl+Enter` from the normal editor would need to be implemented separately for the webview, entailing a lot of compatibility issues, overlapping configurations etc.

A cleaner and simpler approach might be to add a command that extracts the entire example code from the help page and copies it to a new editor, giving the user the possibility to execute the code from there or save the editor and expand on the examples.

Would that second approach work for you?

**Comment by pat-s** [comment]
> A cleaner and simpler approach might be to add a command that extracts the entire example code from the help page and copies it to a new editor, giving the user the possibility to execute the code from there or save the editor and expand on the examples.

You mean as a shortcut? Not sure if this would be worth the time since c/p + opening a new file might take the same time.
The main issue I see is that you usually would need a scratch file and then save this first to run the code.

Whereas if the code would directly go into the R console (preferrably line by line) this would be more convenient.

The issue is really minor and just an idea - there are others that are way more important with lower complexity I guess :)

**Comment by nathaneastwood** [comment]
I think this might be similar to https://github.com/Ikuyadeu/vscode-R/issues/147 which alas, I have not had time to work on as of yet (requires knowledge of TypeScript).

**Comment by eitsupi** [comment]
Note that, the help page of R 4.2.0 can display the executed examples, so it is easier to check the results of running the examples, not only with this extension.

**Comment by pat-s** [comment]
Great @ManuelHentschel, thanks for implementing!
