### ISSUE TITLE
Review usage of workspaceContains activationEvent

### ISSUE THREAD

**Issue by roblourens** [REditorSupport/vscode-R#498]
Hi, I'm reaching out to let you know that we are fixing a bug with the `workspaceContains` VS Code extension activationEvent that could change the activation behavior for your extension.

Here's the issue: This event is supposed to start a search in the user's workspace with the given glob pattern. A pattern like `*.txt` should activate the extension whenever the __root__ of the workspace has a file matching `*.txt`, but it should not search the entire workspace. A pattern like `**/*.txt` should recursively search the entire workspace. We discovered that VS Code is incorrectly applying the `**` pattern to every workspaceContains pattern that includes a `*`. 

Since this may impact the startup performance of VS Code, we need to scope these searches correctly. Once we fix this, a pattern like `*.txt` will only match a .txt file in the root of the workspace.

The change will be in VS Code Insiders in early January. It will be released with 1.53 in early February. Please see https://github.com/microsoft/vscode/issues/110510 for more details and let me know if you have any questions.

**Comment by Ikuyadeu** [comment]
@roblourens Thank you for your kind notifications
I will check the behavior after 1.53 is released.
https://github.com/Ikuyadeu/vscode-R/blob/b5be1c3d5235ef44bec85ce554aa189984c43b46/package.json#L36

**Comment by ElianHugh** [comment]
I don't believe we ran into an issue with workspaceContains. Closing for now!
