### ISSUE TITLE
Multi-root support

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/vscode-R#499]
Disclaimer: I used to work on single projects so far and haven't checked on multi-root support lately.

I have two git repos in subdirectories.

IIRC, when opening an R file and hitting the `r.loadall` shortcut, usually the R session was attached with whe root of PROJECT1 as the working directory instead of the workspace root.

Right now the session is always started in the workspace root and subsequently `r.loadall` fail because no DESCRIPTIOIN file is found.

Did something change lately or was my memory wrong in this case?

**Comment by renkun-ken** [comment]
Basically, you are suggesting that the "R: Create R terminal" command should use the workspace folder of the active document as the working directory to start an R session if there's no active session. Does this make sense to you?

**Comment by renkun-ken** [comment]
If we plan to provide better support for multi-root workspace, it seems that we could associate each R session created by "R: Create R terminal" with a workspace folder? When the user runs any command that needs to send text to the terminal, it should send to the terminal associated with the workspace folder where the current active document is contained.

This requires that we keep track of multiple terminals.

**Comment by pat-s** [comment]
> Basically, you are suggesting that the "R: Create R terminal" command should use the workspace folder of the active document as the working directory to start an R session if there's no active session. Does this make sense to you?

Yeah - if the workspace folder is the package root in this case. 
This could be found out by searching for a description file upwards.

- If none is found, the uppermost workspace root is used.
- If one is found, this directory is used.

For example when I open `WORKSPACE_ROOT/project1/R/file.R`, the working directory in R should become `WORKSPACE_ROOT/project1`. 
It then would be awesome if all R calls made in one of these R functions would be send to the active R session of this project (which is usually a package).

If I then open another file in `WORKSPACE_ROOT/project2/R/file.R` and hit `r.loadall`, it should start a new R session (if none exists yet for this project) and follow the same logic as described for project1.

All of this is an R package centric workflow. Users working on non-R packages may want to use one R session with scripts from different projects and use only one R session with all R commands be sent to this one.

Hence an option for this behavior might probably be needed.

> This requires that we keep track of multiple terminals.

Yeah - probably a complex one. Not sure if any editor is currently capable of this.
Having this would be a blast 🚀

**Comment by ManuelHentschel** [comment]
To be clear, are you using a [mutli-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) or just a single-root workspace that contains two R packages?

**Comment by pat-s** [comment]
In my example its a single-root workspace with two R packages - so the title might actually be wrong? Feel free to update and clarify if so  👍
