### ISSUE TITLE
Create terminal link provider for {testthat} errors / warnings

### ISSUE THREAD

**Issue by MilesMcBain** [REditorSupport/vscode-R#512]
**Is your feature request related to a problem? Please describe.**
When showing test reports like:

```
✔ |   7       | test data.table paste [0.3 s]
✖ |   0 1     | test RStudio preference API calls
─────────────────────────────────────────────────────────
test_rstudio.R:10: failure: readPreference() returns an integer
rstudioapi::readPreference("num_spaces_for_tab", 4) has type `double`, not `integer`.
─────────────────────────────────────────────────────────
✔ |  28       | test tribble paste [0.6 s]
✔ |  16       | test vector paste [0.3 s]

```

It would be convenient if the `test_rstudio.R:10` text was a clickable link to that file and line number. I am not sure if RStudio has this feature, but it is implemented in Emacs/ESS.

I have not researched it thoroughly yet, but it seems like the VSCode [TerminalLinkProvider API](https://code.visualstudio.com/api/references/vscode-api#TerminalLinkProvider) is designed for this purpose. I found some example code [here](https://code.visualstudio.com/updates/v1_49).

**Comment by ElianHugh** [comment]
I fiddled with this a bit and it seems to be working (my regex skills are pretty awful): 
![mF26j1N983](https://user-images.githubusercontent.com/60372411/122151104-79226400-ce4e-11eb-9bf8-84af3906f3df.gif)

**Comment by ManuelHentschel** [comment]
When I launch vscode with all extensions disabled and hold `ctrl` (windows 10) while clicking a filename, I can directly open the file, as well. Is this the behaviour you're looking for or do you have something else in mind?
