### ISSUE TITLE
Display rowname of dataframe when using r.preview.dataframe

### ISSUE THREAD

**Issue by wdiao-zju** [REditorSupport/vscode-R#514]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that rowname of dataframe is missing when using r.preview.dataframe

**Describe the solution you'd like**
I hope to display rowname of dataframe when using r.preview.dataframe. I think it is very useful function in many cases especially exploring dataset.

**Comment by renkun-ken** [comment]
Row names are displayed in the data viewer when session watcher is enabled.
