### ISSUE TITLE
Verify extension in the Open VSX Registry

### ISSUE THREAD

**Issue by gvelasq** [REditorSupport/vscode-R#524]
**Is your feature request related to a problem? Please describe.**
This extension is unclaimed/unverified on open-vsx.org. Link [here](https://open-vsx.org/extension/Ikuyadeu/r).

**Describe the solution you'd like**
Verification on open-vsx.org would reassure users of the Open VSX Registry (e.g. VSCodium) of the authenticity of the extension. Would the maintainers consider claiming the extension and verifying it?

**Comment by renkun-ken** [comment]
Maybe related: https://github.com/REditorSupport/vscode-r-lsp/issues/55

**Comment by gvelasq** [comment]
@renkun-ken and @phillc73, now that vscode-R has been moved to REditorSupport, perhaps the extension can be verified on open-vsx.org? It does not look like open-vsx.org has yet been updated to reflect the change per the link in the original post.

**Comment by benz0li** [comment]
Cross reference: https://github.com/REditorSupport/vscode-R/issues/690

**Comment by renkun-ken** [comment]
@gvelasq Thanks for the reminder! I wonder what should be done to do so?

**Comment by gvelasq** [comment]
Thanks very much for seeing this through, @renkun-ken. I wonder if it takes a while to update, but as of now I don't see https://open-vsx.org/extension/reditorsupport/r is available, only the old extension https://open-vsx.org/extension/ikuyadeu/r. Is this related to the error you're seeing in https://github.com/open-vsx/publish-extensions/issues/591#issuecomment-1129522431?
