### ISSUE TITLE
The text in a plot cannot be rendered in the preview window

### ISSUE THREAD

**Issue by Dawntown** [REditorSupport/vscode-R#539]
**Describe the bug**
Any texts in a plot cannot be rendered in the preview window, but work well in the `pdf()` device. The following is a simple instance for reproducing this bug.

**To Reproduce**
```R
# render a plot in the pdf device
pdf("temp.pdf",width=4,height=4)
plot(x=1:10, y=1:10, xlab='X', ylab='Y')
text(x=c(3,6), y=c(6,3), labels=c('A', 'B'))
dev.off()

# render the plot in the preview window
plot(x=1:10, y=1:10, xlab='X', ylab='Y')
text(x=c(3,6), y=c(6,3), labels=c('A', 'B'))
```

setting.json
> Only the modified terms were listed.
```json
    "r.rpath.linux": "/home/dawntown/miniconda3/envs/zxcpy/bin/R",
    "r.rterm.linux": "/home/dawntown/miniconda3/envs/zxcpy/bin/R",
    "r.sessionWatcher": true,
    "r.rterm.option": ["--r-binary=/home/dawntown/miniconda3/envs/zxcpy/bin/R"]
```
**Expected behavior**
The previewed plot should have had the same appearance as the one in the pdf.

**Screenshots**
![image](https://user-images.githubusercontent.com/28901564/105963184-a5b22b00-60bb-11eb-9725-ebfb37df5783.png)

**Environment**
 - OS: WSL 2, Ubuntu 18.04
 - VSCode Version: 1.52.1
 - R Version: 3.6.1
 - vscode-R version: 1.6.3

**Additional context**
It is definitely an excellent plugin for R. Thanks for your contribution and maintenance!

**Comment by renkun-ken** [comment]
Looks like your R session cannot find the proper font lib?

Does it occur if you start a terminal outside vscode?

**Comment by Dawntown** [comment]
Yes, the problem exists in the terminal outside vscode as well. So, is it a problem with the setting of my R?

**Comment by nxli** [comment]
Reproducible using vscode and generating plot within vscode.

**Comment by renkun-ken** [comment]
It is more likely caused by radian. Does this happen in official R terminal?
