### ISSUE TITLE
Bracket colour matching appears to be broken

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#546]
**Describe the bug**
Bracket colour matching appears to be broken.

![image](https://user-images.githubusercontent.com/8447209/106597052-c233e480-654d-11eb-9785-939e27efbb7c.png)

I don't get this issue in any other languages other than R which leads me to believe its an R specific issue.

**To Reproduce**
1. Open an R program
2. Type the text shown in the image

**Do you want to fix by self? (I hope your help!)**

Maybe. Happy to try and look into it but not sure when I will have time so am happy for someone else to jump in if they can do it sooner. 

Main thing is if someone else can confirm it is a bug and not just a settings problem on my local machine

![image](https://user-images.githubusercontent.com/8447209/106597275-1b037d00-654e-11eb-9926-50806706c468.png)
everything else is defaults

**Expected behavior**
Brackets should match colour properly 

**Environment (please complete the following information):**
 - OS: macOS
 - VSCode Version: 1.52.1
 - R Version: 4.0.3
 - vscode-R version: v1.6.4

**Comment by renkun-ken** [comment]
I cannot reproduce it yet.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/4662568/106599431-021dba80-6594-11eb-8d65-745e5aa8ad7d.png">

Does it occur if you change your theme?

**Comment by gowerc** [comment]
Not really sure whats going on....

![image](https://user-images.githubusercontent.com/8447209/107152238-ac179100-695e-11eb-89f8-e618279244e9.png)


I also tried other themes with bracket color matching and got the same result:
![image](https://user-images.githubusercontent.com/8447209/107152346-542d5a00-695f-11eb-805f-39117e90d1e0.png)

Though I note that theres also 1 miss match with the python brackets as well so am lost as to where the issue could be coming from :(

**Comment by ElianHugh** [comment]
I've had this issue sporadically as well. From memory, the times its occured I've also had a callr error on the first line of the document. Unfortunately don't have a screenshot handy!

**Comment by renkun-ken** [comment]
Feel free to reopen if this still persists.
