### ISSUE TITLE
Can rstudioapi::getThemeInfo() be supported?

### ISSUE THREAD

**Issue by MilesMcBain** [REditorSupport/vscode-R#547]
getThemeInfo() not currently supported. It is used by {thematic} to do automatic theming of ggplots: 
https://twitter.com/grrrck/status/1357709982351974400?s=20

**Describe the solution you'd like**
An implementation that works with {thematic}.

**Describe alternatives you've considered**
It might be possible to shim thematic itself if the theme info is too RStudio dependent.

**Comment by ElianHugh** [comment]
Hi @MilesMcBain , did you end up looking at this? I'd be happy to give this a look :)
