### ISSUE TITLE
ggplot window doesn't refresh

### ISSUE THREAD

**Issue by MrJGao** [REditorSupport/vscode-R#554]
Hi, I'm wondering if anyone is experiencing the same ggplot issue I have. So, when I plot graphs using ggplot and move the plot window to other places (or just change the ratio of the plot window), the plot window won't refresh after the moving or adjusting. I'm not using session watcher and I'm on Mac OS, so the plot is shown in the Quartz window.

**To Reproduce**
1. Just do `dat <- data.frame(x = 1:10, y = 1:10); ggplot(dat, aes(x = x, y = y)) + geom_point()`
2. A window would show up with a scatter plot.
3. Move the plot window to other places or change the ratio of the window.
4. Now, change the scatter plot to line plot: `ggplot(dat, aes(x = x, y = y)) + geom_line()`
5. See if the window refreshes. Mine didn't refresh and still showed the scatter plot.

Thanks.

**Comment by gowerc** [comment]
@MrJGao , Does this issue happen if you use the regular terminal outside of vscode ?

**Comment by MrJGao** [comment]
> 

Thanks. Yes, I just tried, it's the same issue, no refreshing. So, the issue is from XQuartz? Do you have the same problem?

**Comment by gowerc** [comment]
I don't have this issue sorry :( 

What version of XQuartz are you running, according to [here](https://discussions.apple.com/thread/250731310) there is an issue with 32bit versions of it on Catalina. Quite a few articles I'm finding just recommend re-installing to see if that fixes the problem.

```
brew cask reinstall xquartz --force
```

Sorry I'm not really sure what else to suggest, you may get better help by re-posting on stackoverflow

**Comment by MrJGao** [comment]
ok, thank you, I reinstalled it, but the issue still exists. Not sure where is wrong, but since it's an issue with my machine only, I'll close this.

**Comment by MrJGao** [comment]
Also, see [this](https://github.com/XQuartz/XQuartz/issues/168) and [this](https://github.com/tidyverse/ggplot2/issues/4288) for the same issue.
