### ISSUE TITLE
autocomplete file path

### ISSUE THREAD

**Issue by shangguandong1996** [REditorSupport/vscode-R#576]
Dear developer, I am not sure it is a suitable feature request. But I am wondering whether vscode-R can support file path autocomplete just like R stuido
![图片](https://user-images.githubusercontent.com/22555126/110325659-91663400-8052-11eb-843d-dbc5c09195bb.png)

**Is your feature request related to a problem? Please describe.**
no

**Describe alternatives you've considered**
or maybe I can install other plugin like `Path Intellisense`?

Please forgive me if it is a bad feature request :)

Best wishes
Guandong Shang

**Comment by eitsupi** [comment]
@shangguandong1996 There are some extensions which provide path completion.
How about use these extensions?

- [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)
- [Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete)

![image](https://user-images.githubusercontent.com/50911393/110328830-2c650b00-805f-11eb-990b-6f7f4abb0170.png)
(with Path Autocomplete)

**Comment by shangguandong1996** [comment]
> 
> 
> @shangguandong1996 There are some extensions which provide path completion.
> How about use these extensions?
> 
>     * [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)
> 
>     * [Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete)
> 
> 
> ![image](https://user-images.githubusercontent.com/50911393/110328830-2c650b00-805f-11eb-990b-6f7f4abb0170.png)
> (with Path Autocomplete)
> ![image](https://user-images.githubusercontent.com/50911393/110329514-0be98080-8060-11eb-89e2-3c447f70f2cc.png)


Thanks for your reply :)
But I find some trouble when using `Path Autocomplete` . Just for example
```


# my R work dir 
r$> getwd()                                                                                                                                                   
[1] "/home/sgd/test/test"

# my workspace structure tree
sgd@localhost ~/test/test
$ tree
.
├── script
│   └── test.R
└── file

2 directories, 1 file


```
The Path Autocomplete support triggle autocomple when
- it supports relative paths (starting with ./)
- it supports absolute path to the workspace (starting with /)

when I open the test.R file, I want to using `write.csv` to write object to `file` dir, I have two choice to triggle autocomplete
```
write.csv("../file/")

# or 

write.csv("/file/")
```

But the latter is not certified by `R`. Actually, what I expect is like `R stuido` autocomplete, which can identify whole `project` path, (I think it have some similar with `vscode workspace`), then I just need `write.csv("file/")`.

**Comment by eitsupi** [comment]
@shangguandong1996 [Path Intellisense](https://github.com/ChristianKohler/PathIntellisense#mappings) and [Path Autocomplete](https://github.com/ionutvmi/path-autocomplete#options) have custom mapping settings.
Mapping `.` to the project root directory seems work well.
<img width="398" alt="スクリーンショット 2021-03-09 230736" src="https://user-images.githubusercontent.com/50911393/110484145-bda2b300-812d-11eb-9192-ea3edf09acc3.png">

In `.vscode/settings.json`
```
{
    "path-intellisense.mappings": {
        ".": "${workspaceFolder}"
    },
    "path-autocomplete.pathMappings": {
        ".": ["${folder}"]
    }
}
```

**Comment by shangguandong1996** [comment]
> 
> 
> @shangguandong1996 [Path Intellisense](https://github.com/ChristianKohler/PathIntellisense#mappings) and [Path Autocomplete](https://github.com/ionutvmi/path-autocomplete#options) have custom mapping settings.
> Mapping `.` to the project root directory seems work well.
> <img alt="スクリーンショット 2021-03-09 230736" width="398" src="https://user-images.githubusercontent.com/50911393/110484145-bda2b300-812d-11eb-9192-ea3edf09acc3.png">
> 
> In `.vscode/settings.json`
> 
> ```
> {
>     "path-intellisense.mappings": {
>         ".": "${workspaceFolder}"
>     },
>     "path-autocomplete.pathMappings": {
>         ".": ["${folder}"]
>     }
> }
> ```


That's awesome ! It did work well and is enough for me, thanks for your suggestion :)

> PS: I still expect this type autocomplete, which can atuocomplete all the files under the workspace(project) 
![图片](https://user-images.githubusercontent.com/22555126/110564497-e2c40f80-8187-11eb-9854-3f61270e7473.png)


Best wishes
Guandong Shang

**Comment by renkun-ken** [comment]
I think we should write more to the wiki at <https://github.com/Ikuyadeu/vscode-R/wiki/Recommended-extensions-and-configuration>.

**Comment by renkun-ken** [comment]
Closing as done by other extensions.
