### ISSUE TITLE
Use an external browser for vsc.view

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#589]
I would like to use an external web browser while keeping the default behavior of `View()` function provided by this extension. However, the following option just falls back to the `utils::View()`:

``` r
options(vsc.view = FALSE)
```

Could you please add an option argument to address this need?

**Comment by renkun-ken** [comment]
What are you trying to view? A html file, a url, an htmlwidget, a shiny app, etc.?

**Comment by jooyoungseo** [comment]
Data.frame object using `View()` function like below:

``` r
View(airquality)
```

**Comment by renkun-ken** [comment]
In your case, you need to make the data frame an htmlwidget to view it in a web browser.

You may try the following:

```r
options(vsc.viewer = FALSE)
DT::datatable(airquality)
```

**Comment by jooyoungseo** [comment]
Thank you very much for your kind response, @renkun-ken. I was wondering if there would be any way to get `View(...)` to open in an external browser while keeping the default behavior of `show_dataview(...)` function defined within `~/.vscode-R/init.R`.

I know, I could use `DT::datatable(airquality)` or `gt::gt(airquality)`; however, I am looking for a way to open a data in an external browser via `View(airquality)`.
