### ISSUE TITLE
automatically resize plots according to fig.width and fig.height in Rmarkdown code chunk

### ISSUE THREAD

**Issue by JakeJing** [REditorSupport/vscode-R#611]
I am looking for the way of adjusting the size of plots in vscode-R, and I am wondering whether it is possible to automatically detect the args (fig.width and fig.height) in Rmd chunk. 

I found a solution by manually specifying the size of the plot via `options()`, as documented in the vscode-R description. I simply put this following code inside my **.Rprofile** or my **Rmd** file. 

```{r}
options(vsc.dev.args = list(width = 800, height = 800))
```

But this global setting is not very flexible. I think it would be better to let vscode-R automatically detect the configuration of dev.args (fig.width and fig.height) in each chunk, so that people can directly adjust the sizes of their plots locally, as what has been implemented in Rstudio. 

Ideally, whenever we run a single line or the whole chunk, vscode-R will first check whether there is any setting (fig.width and fig.height) inside the chunk. After extracting the necessary args, vscode-R can resize the plot accordingly.

**Comment by renkun-ken** [comment]
Please try the plot viewer introduced at <https://github.com/Ikuyadeu/vscode-R/wiki/Plot-viewer#svg-in-plot-viewer>.

**Comment by JakeJing** [comment]
@renkun-ken I tried the `httpgd` package and enabled the `vsc.use_httpgd` option in my .rprofile. But it seems that it cannot automatically detect the figure sizes in the Rmd code chunk. Also, is it possible to show the plot panel inside the current editor instead of opening another panel?

It works well by using the following setting so that the new plot is show at the right side of the current scripts (easy to navigate). I am wondering whether it is doable in `httpgd`. Thanks a lot!

```
options(vsc.plot = "Active")
```

**Comment by renkun-ken** [comment]
> But it seems that it cannot automatically detect the figure sizes in the Rmd code chunk.

Run chunk only sends code to terminal. It does not tell httpgd anything about the code chunk options. Only when you render the Rmd will it respect the chunk options.

>  is it possible to show the plot panel inside the current editor instead of opening another panel?
It seems that the httpgd viewer does not respect the `vsc.plot` option as the `viewColumn` to show the WebView. @ManuelHentschel Is it handy to make httpgd plot viewer respect this option?
