### ISSUE TITLE
Use r.rpath.xxx and R for tasks

### ISSUE THREAD

**Issue by andycraig** [REditorSupport/vscode-R#612]
Would there be problems with using `r.rpath.xxx` for these tasks? From my experience, the normal `R -e ...` (rather than `Rscript`) works as well and the user would be able to configure the R path used to run the task.

_Originally posted by @ManuelHentschel in https://github.com/Ikuyadeu/vscode-R/issues/603#issuecomment-813889883_

**Comment by andycraig** [comment]
@ManuelHentschel I've created a new issue for this. These both sound like good ideas to me. I can do a PR for this in the next couple of weeks, or feel free to do one in the meantime.

**Comment by ElianHugh** [comment]
I believe that tasks now use r.rpath, so I think this is resolved! Please feel free to reopen if I am mistaken :)
