### ISSUE TITLE
Ask to save workspace image when closing

### ISSUE THREAD

**Issue by MatrixRanger98** [REditorSupport/vscode-R#622]
Sometimes my R code takes a long time to run so I need to save a workspace image with `save.image()`. But it is easily forgotten and next time I have to run from the beginning again. I believe it would be great to pop up a warning every time you close an R project. Note that this is a feature in RStudio. Moreover, it would be even better if there is a setting to control whether to show the warning in case one may not want the feature and also a setting to control whether to save an image automatically.

**Comment by albertosantini** [comment]
Default settings are 

```
    "r.rterm.option": [
        "--no-save",
        "--no-restore"
    ],
```

If you want to load the image at the startup of the terminal you may remove `--no-restore`; and if you remove `--no-save`, when you try to exit from the terminal, the usual question arises `Save workspace image? [y/n/c]:`.
