### ISSUE TITLE
OS process not terminated when the `rterm` is closed

### ISSUE THREAD

**Issue by mihaiconstantin** [REditorSupport/vscode-R#630]
**Describe the bug**
When closing an `R` terminal, the associated process is not terminated.

**To Reproduce**
Open an `R` terminal in VS Code, evaluate something then close it. Repeat this, then check the process monitor.

**`setting.json` config** 
```json
{
    "r.bracketedPaste": true,
    "r.rterm.windows": "C:\\Users\\const\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\radian.exe",
    "r.rpath.windows": "C:\\Program Files\\R\\R-4.0.4\\bin\\R.exe",
    "r.lsp.debug": false,
    "r.lsp.diagnostics": false,
    "r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--r-binary=C:\\Program Files\\R\\R-4.0.4\\bin\\R.exe"
    ],
    "r.sessionWatcher": true,
}
```

**Expected behavior**
When I close a terminal in VS Code the associated process to be terminated.

**Screenshots**

![processes](https://user-images.githubusercontent.com/20051042/116515316-6a96e200-a8cc-11eb-92bd-a4abfb4f4200.png)

**Environment:**

I am running the following VS Code version:

```
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

And the following `R` version:

```
platform       x86_64-w64-mingw32
arch           x86_64
os             mingw32
system         x86_64, mingw32
status
major          4
minor          0.4
year           2021
month          02
day            15
svn rev        80002
language       R
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book
```

**Comment by albertosantini** [comment]
Resolved with https://github.com/REditorSupport/vscode-R/pull/941

**Comment by renkun-ken** [comment]
Reopen if the problem still persists.
