### ISSUE TITLE
Fenced code chunk is ignored in Go to Next/Previous Chunk

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#634]
1. Put your cursor in `Para 1.`
2. Execute `R: Go to Next Chunk`.

It skips r chunk. I know it is treated as a just fenced block, but it would be better to be included in the go to next/previous chunk chain.

## `test.Rmd`

````
Para 1.

``` r
print("foo")
```

Para 2.

```{python}
print("bar")
```
````

**Comment by ElianHugh** [comment]
RStudio appears to treat fenced blocks as purely foldable regions: 

![image](https://user-images.githubusercontent.com/60372411/122659545-c95c3780-d168-11eb-9929-8b70f304461c.png)

We don't have to emulate RStudio necessarily here, but its definitely different behaviour to 'standard' practice. Having said that, this should be pretty simple to patch if necessary
