### ISSUE TITLE
Add "Go to Next/Previous Non-Chunk Paragraph" in Rmd

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#638]
Currently, there is not a efficient way to jump between non-code-chunk paragraphs in Rmd files.

When code chunk gets longer, users have to either manually scroll down or use search function to go to next/previous text paragraphs.

If this feature is added, it would benefit heavy Rmd writers in many ways.

**Comment by renkun-ken** [comment]
Thanks for the feature request. There are some extensions dedicated to code navigation suggested in https://github.com/Microsoft/vscode/issues/10093:

* https://marketplace.visualstudio.com/items?itemName=jmfirth.vsc-space-block-jumper
* https://marketplace.visualstudio.com/items?itemName=sashaweiss.block-travel

Looks like they are not specifically designed for jumping between non-chunk paragraphs but text blocks, yet you might find them useful enough.

**Comment by jooyoungseo** [comment]
Thanks for your response. Yes, I have been using the "Space Block Jumper" extension, but it lacks non-code chunk skip feature. In the long run, it would be so nice if that missing feature could be implemented in "vscode-R" extension for Rmd files!
