### ISSUE TITLE
Support packages in sub-directories for package-related tasks

### ISSUE THREAD

**Issue by jolars** [REditorSupport/vscode-R#645]
**Is your feature request related to a problem? Please describe.**
I sometimes keep a R package in a subdirectory of a project folder, for instance when organizing projects that distribute a package as part of that project. The package-related tasks in the extension, however, only works in the case when the working directory is the package directory. Instead, I currently use vscode build tasks where I hard-code the package name, which isn't a great way to go.

**Describe the solution you'd like**
I would like the extension to have a setting called something like `r.packageDirectory` that has the default value `"."` and can be set on a workspace basis and is honored by the package-related tasks in the extension. Say, for instance, that I have set `"r.packageDirectory": "PackageName"`. Then when I run `R: Install Package`, what I want to get is `devtools::install("PackageName")`.

**Comment by psobolewskiPhD** [comment]
Is this a vs-code issue or a more general one?
Perhaps you can use the {here} package to organize your relative paths:
https://here.r-lib.org
and then use {install_local} for your local package:
https://devtools.r-lib.org/reference/install_local.html

**Comment by jolars** [comment]
Thanks, but this is a vs-code-related issue and I don't see how the here package would help here. I know that I can get what I want by typing `devtools::install("PackageName")` and `devtools::document("PackageName")` etc, but what I'm looking for is a more efficient solution with less typing (i.e. by using the package-related tasks that the vs code R extension enables).

**Comment by aaronwolen** [comment]
Came here to make the same request. Another use case for this feature would be multi-language repos (e.g., [arrow](https://github.com/apache/arrow) and [duckdb](https://github.com/duckdb/duckdb)), in which the R package is located in a subdirectory.
