### ISSUE TITLE
Leaflet tiles not showing in web viewer

### ISSUE THREAD

**Issue by jolars** [REditorSupport/vscode-R#665]
**Describe the bug**

Leaflet tiles are not showing in the web viewer.

**To Reproduce**

1. Install and load **leaflet**
2. Run `leaflet %>% addTiles()`
3. The plot opens up in the web viewer, there are zoom controls, but no map. It is all grey.

## Do you want to fix by self? (We hope your help!)

Yes

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

I'd love to help, but I don't know where to get started.

(If related)setting.json

```json
// R path for Linux
"r.rterm.linux": "/home/<user>/.local/bin/radian",

// R command line options (i.e: --vanilla)
"r.rterm.option": [],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher (experimental)
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**

**Screenshots**

Here is what is looks like in VS Code:

![image](https://user-images.githubusercontent.com/13087841/121586189-a5e01100-ca33-11eb-904c-eb1423eee641.png)

Here is what is looks like in RStudio:

![image](https://user-images.githubusercontent.com/13087841/121586420-efc8f700-ca33-11eb-9289-49294685c5b3.png)

**Environment (please complete the following information):**

- OS: Linux (Fedora 34)
- VSCode Version: 1.56.2
- R Version: 4.0.5
- vscode-R version: 1.6.8

**Additional context**

When running a shiny application, the map renders just fine.

**Comment by renkun-ken** [comment]
I can reproduce this. I guess it is caused by WebView limitations. Let me take a closer look.

**Comment by ElianHugh** [comment]
It seems to me that the webview is incorrectly converting urls with the structure `//domain.com` to `vscode-webview://domain.com` (which doesn't resolve). Explicitly setting the urls to `http://` appears to show the tiles.

**Comment by renkun-ken** [comment]
@ElianHugh Looks like we should use a more robust regex to replace the urls that only refer to local resources.

**Comment by ElianHugh** [comment]
I think there's an issue with additional resource requests, which aren't present in the html body, but are loaded on-demand. Perhaps a listener that modifies requests would help for that?

**Comment by renkun-ken** [comment]
@ElianHugh Modifying requests sounds better. Are you interested in having a try?

**Comment by ElianHugh** [comment]
So, I've managed to get this working by modifying the args in the inline-htmlwidgets script:
`.replace('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png')` (which would be changed to a regex).

![image](https://user-images.githubusercontent.com/60372411/126938177-7fa7005e-54d5-43b6-bc1d-05190becd3c4.png)

Unfortunately this would likely only work in the case of webviews that use html widgets. I've been fiddling around with modifying requests, but it's proven a little difficult in the scope of a webview

**Comment by ElianHugh** [comment]
I have the following in order to safely replace strings that could be parsed as URLs:

```ts
.replace(/(?<='|")\/\/[A-Za-z0-9./{}]*(?='|")/g, function(match): string {
                const matchNoTemplates = match
                    .replace(/{[A-Za-z0-9]}/g, 'a')
                    .replace(/(\/\/)/, 'https://');
                let isUrl: boolean;

                try {
                    isUrl = !!(new URL(matchNoTemplates));
                } catch (_) {
                    isUrl = false;
                }

                if (isUrl) {
                    return (match.replace(/\/\//, 'https://'));
                } else {
                    return (match);
                }
            })
```

This does the following:

1. Match a string encapsulated by quotes, that starts with `//`
2. Create a dummy string with templates removed and the beginning `//` replaced with `https://`
2. Check if the dummy string can be used to create a new URL
3. If it can be, replace the match's `//` with `https://`, else return match

I have had this successfully work with loading `leaflet() |> addTiles()`.

There is the route of going purely regex, but I was thinking that this route is safer for modifying the html body

**Comment by renkun-ken** [comment]
@ElianHugh Thanks for digging into this. Feel free to file an PR :+1:

**Comment by ElianHugh** [comment]
Thanks! I should have a PR up tomorrow, which handles on-demand  loading as well
