### ISSUE TITLE
Sending code to terminal may hang for tens of seconds

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#673]
I'm not sure how I could reliably reproduce this problem, but sometimes sending code to the terminal might hang for tens of seconds, especially after the terminal is resized, or the window is zoomed.

It could be ensured that it is awaiting in the extension because hanging over a symbol in the editor will trigger a tooltip "Loading..." rather than the help documentation received from the R language client via vscode-r-lsp, i.e. sending lsp request is not working as vscode-R is awaiting.

I wonder if there is a way to walk around this by e.g. using a timeout or something so that the worst case is better than hanging for tens of seconds.

**Comment by renkun-ken** [comment]
It is quite likely that the hanging occurs in `chooseTerminal()`.

**Comment by ElianHugh** [comment]
Do you think this is a vscode-R problem, or more broadly an issue with vscode? I can't say I've come across this problem before, but that might be down to my habit of manically switching projects often
