### ISSUE TITLE
`.vsc.attach()` not found for self-managed R sessions in tmux

### ISSUE THREAD

**Issue by dwhdai** [REditorSupport/vscode-R#688]
**Describe the bug**
When working in a Remote SSH environment, `.vsc` commands are not found for R sessions created manually within tmux, even after following the instructions found [here](https://github.com/Ikuyadeu/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions). They work fine when creating an R terminal using the control palette command.

Details that may be relevant:

- renv version 0.13.2 (.Rprofile has been modified as per [these instructions](https://github.com/Ikuyadeu/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions) at `~/.Rprofile` as well as within the renv project)
- using radian R console

**To Reproduce**

1. From VS code, connect to SSH host using Remote SSH extension
2. Create a new terminal
3. Start tmux
4. Within tmux, start a radian console
5. Within radian, try running `.vsc` commands or `View()`, `plot()`, etc.

## Do you want to fix by self? (We hope your help!)

Yes

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

(If related)setting.json

```json

// R path for Linux
"r.rterm.linux": "r4", // alias for 'radian --r-binary=/opt/R/4.0.2/bin/R'

// R command line options (i.e: --vanilla)
"r.rterm.option": ["--r-binary=/opt/R/4.0.2/bin/R"],

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": true,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**
- when running `.vsc.attach()`, the R console should be attached to the session watcher
- when running `View()` and `plot()` commands, the associated viewer/plot object should be displayed in a panel

**Screenshots**
You can show the keybord contents by pressing `F1` and `Developer: toggle screencast mode`

**Environment (please complete the following information):**

- OS: Ubuntu 18.04 (via SSH)
- VSCode Version: 1.57.1
- R Version: 4.0.2
- vscode-R version: 2.0.0

**Additional context**

**Comment by renkun-ken** [comment]
Did you set envvar `TERM_PROGRAM=vscode` inside tmux? For example, <https://github.com/renkun-ken/dotfiles/blob/master/.Rprofile#L29>?

**Comment by dwhdai** [comment]
> Did you set envvar `TERM_PROGRAM=vscode` inside tmux? For example, https://github.com/renkun-ken/dotfiles/blob/master/.Rprofile#L29?

yep! I added `Sys.getenv("TERM_PROGRAM="vscode")` to my `.Rprofile`, before sourcing the init script

**Comment by eitsupi** [comment]
@dwhdai Hi, Has the environment variable `R_PROFILE_USER` been set?
If `R_PROFILE_USER` does not exist, `~/.Rprofile` may not be loaded.
Wouldn't putting the `.Rprofile` in the root directory of the project solve the problem?

For more information, run `?Startup` on R and read the help.

**Comment by dwhdai** [comment]
> @dwhdai Hi, Has the environment variable `R_PROFILE_USER` been set?
> If `R_PROFILE_USER` does not exist, `~/.Rprofile` may not be loaded.
> Wouldn't putting the `.Rprofile` in the root directory of the project solve the problem?
> 
> For more information, run `?Startup` on R and read the help.

@eitsupi the `R_PROFILE_USER` is not set (verified via `Sys.getenv("R_PROFILE_USER")` returning empty string), and my `.Rprofile` is located in the root directory of the project. I'm using the `.Rprofile` section here: https://github.com/renkun-ken/dotfiles/blob/3ff7def0e27203131fd4b4955e803671531e91a5/.Rprofile#L28. Also tried manually sourcing it after R has started up, and still getting errors like `.vsc.attach()` not found

**Comment by eitsupi** [comment]
@dwhdai `~/.Rprofile` is used if you set your home directory to the environment variable `R_PROFILE_USER` ?
Or, how about edit `R_HOME/etc/Rprofile.site`?

**Comment by dwhdai** [comment]
> @dwhdai `~/.Rprofile` is used if you set your home directory to the environment variable `R_PROFILE_USER` ?
> Or, how about edit `R_HOME/etc/Rprofile.site`?

I did not set the `R_PROFILE_USER` environment variable, and I've also confirmed that the `.Rprofile` within the project directory is the one being sourced (I use `renv` which enforces this)

**Comment by eitsupi** [comment]
@dwhdai If you write other functions to the .Rprofile in you project, will it be executed?

**Comment by eitsupi** [comment]
@dwhdai For more information about Rprofile, please see this page.
https://cran.r-project.org/web/packages/startup/vignettes/startup-intro.html

Do you find the Rprofile that contains the `repos` setting used when you install R packages?

**Comment by dwhdai** [comment]
Thanks for that tip @eitsupi! I verified that the code chunk INSIDE the `if` conditional (`if (interactive() && Sys.getenv("RSTUDIO") == "")`) was not running when starting radian from tmux, but it was running when using VS Code's `> Create R Terminal` command. After removing the condition, the extension works and I'm able to use `.vsc` commands, render plots, View 
dataframes, etc. from tmux

Do you know why this conditional does not pass for tmux R sessions? To start R sessions in tmux, I do:

1. start tmux
2. start radian console via `radian --r-binary=/opt/R/4.0.2/bin/R`

**Comment by eitsupi** [comment]
@dwhdai I'm sorry, I don't know.
I just replied because I noticed that `~/.Rprofile` may not run without `R_PROFILE_USER`.

If you run `interactive()` on radian in your tmux, will the result be `FALSE`?
The script currently written in the wiki does not have that conditional expression.
https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions
![image](https://user-images.githubusercontent.com/50911393/127001274-e624fcf8-c314-47d6-9164-ac11357c8a98.png)

**Comment by eitsupi** [comment]
Perhaps that's not the factor, perhaps it may be because you reloaded the VSCode window?

**Comment by eitsupi** [comment]
It seems that the `init.R` contains the expression now, so we don't need to set that in our Rprofiles.
https://github.com/REditorSupport/vscode-R/blob/8ec924b2a1b18ea722172995fa702c938604ecaf/R/init.R#L9-L17

**Comment by dwhdai** [comment]
It appears that the `.Rprofile` must contain a trailing new line (see [here](https://yihui.org/en/2018/04/rprofile-trailing-newline/)), which may have been removed by VS code linters. After adding a new line, everything works as intended.
