### ISSUE TITLE
Change the publishId in VS Code marketplace

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#690]
Since the project has been transferred to REditorSupport as suggested in #98, we may better have a discussion on the issue of changing publishId in the VS Code marketplace here.

When the repo is transferred, the following are examples for both sides: changing or keeping the publishId.

Changed: 
Unchanged: [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint), [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

Some related issues:

* https://github.com/microsoft/vscode/issues/3670
* https://github.com/prettier/prettier/issues/781

**Comment by Ikuyadeu** [comment]
When I discussed with them, I got the opinion to keep the current id for users' experience.
But I'll ask again about differences with your examples.

**Comment by eitsupi** [comment]
Thank you all for your continued work.

Looking at the Prettier extension, it seems that the ID of the extension remains the same even if the publisher is changed. If it is changed, will it affect the user?
![image](https://user-images.githubusercontent.com/50911393/124112686-832aa080-daa5-11eb-954c-09f576c66557.png)

**Comment by renkun-ken** [comment]
@eitsupi Thanks for pointing out. Looks like the case of changed publishId is quite few?

**Comment by Ikuyadeu** [comment]
`publishid` and author are different.
Changing `author`, does not have any impact on the user.
I think, `Yuki Ueda` to be `REditor` is enough.

```diff
-  "author": "Yuki Ueda",
+  "author": "REditor",
   "license": "SEE LICENSE IN LICENSE",
   "publisher": "Ikuyadeu",
```

**Comment by renkun-ken** [comment]
To be consistent with the organization name and vscode-r-lsp, the author should be "REditorSupport".

**Comment by eitsupi** [comment]
The Prettier extension seems to have changed publishers in March of this year when it was no longer in beta?
https://github.com/prettier/prettier-vscode/commit/78ae1a54c95bb4fa11620799121ac951d92213e7

**Comment by eitsupi** [comment]
It seems that the Prettier extension has changed its publisher several times between `esbenp` and `prettier` in order to publish the development version as a separate ID, and the stable version has not changed from `esbenp`.
https://marketplace.visualstudio.com/items?itemName=prettier.prettier-vscode
https://marketplace.visualstudio.com/items?itemName=prettier.prettier-vscode-beta

**Comment by renkun-ken** [comment]
From the existing cases, it looks like we might have to stick to the current publishId and only update the author.

**Comment by randy3k** [comment]
Thanks for initiating the discussion. Looks like we could stick with the current publisher for now. 

We could consider it again in the future if there is a necessity (e.g. cannot publish releases). An alternative but less ideal solution is to publish a new extension under REditorSupport and deprecate this extension.

**Comment by randy3k** [comment]
It seems changing the author of a package is not enough to change the display name on the extension page. 

For the case of https://marketplace.visualstudio.com/publishers/esbenp. The publisher id is `esbenp` and the display name is "Prettier".
It is possible for @Ikuyadeu to change his display name to "REditorSupport" but I wonder if he wants to do it for all his extensions.

@Ikuyadeu, do you mind transferring the extension to the publisher [REditorSupport](https://marketplace.visualstudio.com/publishers/REditorSupport) which you are already one of the owners alongside @renkun-ken and me.

**Comment by isidorn** [comment]
Hi VS Code PM here 👋 

I apologise that the Marketplace team did not respond to your request.
Can the current extension author please email vsmakretplace@microsoft.com and make sure to include me inikolic@microsoft.com in the email.

We can easily move your extension to your publisher, however please note that if there are current extension packs or extension dependencies on your extension they will have to get updated.
Extension recommendations also need to be updated, but I can easily do that on the VS Code side to take into account the new publisher id.

**Comment by renkun-ken** [comment]
Just notice that the publisher id of the extension has been updated:

https://marketplace.visualstudio.com/items?itemName=REditorSupport.r

I wonder if there's anything broken on user side?

**Comment by eitsupi** [comment]
I was wondering why the R extension was not automatically installed when I rebuilt Dev Container last night.
Definitely an effect of the ID change.

https://github.com/microsoft/vscode-dev-containers/blob/7a8fa56b33f0477c3f9aed3afdc4e22ace1d606c/containers/r/.devcontainer/devcontainer.json#L29

**Comment by eitsupi** [comment]
Perhaps it would be a good idea to announce in the README or elsewhere that the ID has been changed.

**Comment by renkun-ken** [comment]
> Perhaps it would be a good idea to announce in the README or elsewhere that the ID has been changed.

Yes. I'll include it in the NEWS in the next release.

**Comment by isidorn** [comment]
@eitsupi thanks for letting us know. I will update the `devcontainer.json` today.

**Comment by eitsupi** [comment]
FYI, after rewriting the ID in `devcontainer.json`, it is now installed automatically again.

**Comment by isidorn** [comment]
@Ikuyadeu you should also update the publisher in the `package.json` of your extension to be the new one.

**Comment by xgdgsc** [comment]
When I click `Install in SSH:...` in vscode which has a reditorsupport.r installed locally when using remote ssh, it installs `ikuyadeu.r`.

**Comment by renkun-ken** [comment]
> When I click `Install in SSH:...` in vscode which has a reditorsupport.r installed locally when using remote ssh, it installs `ikuyadeu.r`.

It should work if you uninstall the extension on both local and remote machine, reload vscode, and install again.

**Comment by xgdgsc** [comment]
No. It doesn' t work for me. I also tried removing `.vscode-server/extensions/ikuyadeu.r-2.4.0/` and `.vscode-server/`. It still would install `reditorsupport.r` locally and `ikuyadeu.r` remotely.

**Comment by isidorn** [comment]
The reason for this is that the latest published extension version still has the `publisher: ikuyadeu` in the `package.json`.
@renkun-ken To fix this the extension simply needs to publish a new version (since the publisher is already fixed on the main branch).

**Comment by renkun-ken** [comment]
A new version is released. @isidorn You could take a look if this still happens.

**Comment by isidorn** [comment]
@renkun-ken thanks! @xgdgsc can try it out and let us know.
