### ISSUE TITLE
Integrate vscode-r-lsp into vscode-R

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#691]
Since the project has been transferred to REditorSupport as suggested in #98, it is straightforward to integrate vscode-r-lsp into vscode-R, just like I did in https://github.com/REditorSupport/vscode-R/issues/98#issuecomment-638852903.

The vscode-r-lsp has some major changes since then, therefore I need to re-work on it if we still think it is a good idea.

Also, we need to discuss what should be done after the integration on our side and user side, e.g. announcement, deprecation, etc.

**Comment by renkun-ken** [comment]
Is there a good way to ensure that vscode-r-lsp is disabled before the vscode-R lsp starts running?

**Comment by ManuelHentschel** [comment]
> 
> 
> Is there a good way to ensure that vscode-r-lsp is disabled before the vscode-R lsp starts running?

``` ts
    const lsp = vscode.extensions.getExtension('REditorSupport.r-lsp');
    const lspDisabled = !lsp;
```
More precisely, this yields `false` iff vscode-r-lsp is installed and enabled (for the workspace). There's also `lsp.isActive`, though this will depend on the activation events/order of ativation of the two extensions.

**Comment by renkun-ken** [comment]
Note that vscode-R may be activated before vscode-r-lsp does. In this case, vscode-R starts a language server and then vscode-r-lsp starts another language server when it is activated.

It seems vscode-r-lsp has to be updated too in order to avoid duplication.

**Comment by ManuelHentschel** [comment]
> 
> 
> Note that vscode-R may be activated before vscode-r-lsp does. In this case, vscode-R starts a language server and then vscode-r-lsp starts another language server when it is activated.


The code I posted above would still catch the case where vscode-r-lsp is installed but not activated yet. So you could still abort the vscode-R integrated languageserver if vscode-r-lsp is installed (and hence expected to activate when necessary)

**Comment by renkun-ken** [comment]
We could detect if `REditorSupport.r-lsp` is enabled using the method suggested by @ManuelHentschel and show a message that recommends disabling or uninstalling it and show the extension in the side bar.

I take a look at the commands and can only find `workbench.extensions.action.showEnabledExtensions` useful but I don't find a way to filter the extensions. The [source code](https://github.com/microsoft/vscode/blob/9f7309348f4139404cc1e339216a017bc49884f2/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L986) of the command makes the filter hard coded.

**Comment by renkun-ken** [comment]
Now "show the extension in the side bar" has been done. I guess we could merge the PR and I'll phase out `REditorSupport.r-lsp` in a way.
