### ISSUE TITLE
Create or provide choice for multiple R versions and x64 or i386 architectures for R terminal

### ISSUE THREAD

**Issue by gwd666** [REditorSupport/vscode-R#696]
**Is your feature request related to a problem? Please describe.**
No problem only a feature request ... 
When hitting CTRL+P the `R: Create R terminal` command opens up the VSC Terminal and starts a R session based on the Rpath (in my case WINdows) setting, but only allows for one distinct R architecture (either x64 or i386) and R version 

Because of (mainly database client) driver architecture issues on Windows (ODBC etc) this means a lot of manual hassle with extension `Settings` in case one would like/need to switch to R i386 architecture (in my case b/c x64 is usually my default) or vice versa. 

**Describe the solution you'd like**
Choice between 
`R: Create R-x64 terminal ` 
`R: Create R-i386 terminal ` 

Maybe even side by side? 

**Describe alternatives you've considered**
None so far - I am open for workarounds (eg keyboard shortcuts or similar). 

**Additional context**
NA

PS: this extension of yours ROCKS!

**Comment by renkun-ken** [comment]
Have you tried typing in the terminal to start R-x64 and R-i386 terminal and do both work?

**Comment by gwd666** [comment]
Hi 
Sorry I do not fully understand your proposal or hint. 
If I execute a fully qualified path to R_HOME\bin\i386\R.exe or ...x64\R.exe versions in the Terminal the respective R version will start up, yes. 
I was just hoping for a small enhancement to VSC R to be available when hitting the CTRL+P keyboard shortcut. 
![image](https://user-images.githubusercontent.com/57595487/124469974-4c9da000-dd9b-11eb-8b1d-b2142ef8edf4.png)

**Comment by gwd666** [comment]
OTHERWISE ... I forgot to mention that for R DEV work I can or usually always do "tweak" the  Workspace R extension Setting accordingly! It is mainly when I use VSC interactively ie when I use that package (with its 32 bit driver dependency) that I tend to forget or need to switch the R-ARCH in the "User" Settings.

**Comment by ManuelHentschel** [comment]
I can 100% understand where you're coming from, but I'm not quite sure what the best approach would be here. E.g. when a new R version is released which I want to try, but not switch to permanently (yet), I'm in a similar situation as you, but not between architectures but R versions.

Also, e.g. in https://github.com/REditorSupport/vscode-R/issues/597 we're looking to simplify the path settings, to make using the extension easier for new users, and adding support for different architectures/versions is somewhat contradictory to this.

The alternative that currently works best for me is to not use `r.path.xxx` and `r.term.xxx` at all, and simply have the version I'm currently using on the PATH. Or if the R path is project specific, using the `settings.json`, but you already mentioned that that wouldn't help with your current issue.

A solution that might work for you without making the configuration more complicated for new users might be the following:
* Have an extra (hidden?) setting, where you can specify additional R paths.
* The first time, an R path is required by vscode-R, the user is asked, which R path to use (similar to what the python extension does)

This would be opt-in without cluttering the regular path settings for most users and flexible enough to be used for different architectures/versions etc.. And un-setting this setting in a given workspace would avoid asking for the R path all the time.

**Comment by renkun-ken** [comment]
What if we accept multiple paths in `r.term.xxx`? User could specify a single path (currently supported) or multiple paths separated by `;`. If multiple paths are specified, then "R: Create R terminal" will show a picker for you to decide which one to use?

@ManuelHentschel @gwd666  Does it sound okay?

**Comment by ManuelHentschel** [comment]
Sounds good!

Note that on windows `;` can be part of a path, but e.g. requiring such paths to be quoted should work fine.

I'd also suggest implementing the same mechanism for `r.path.xxx`.

**Comment by gwd666** [comment]
> I can 100% understand where you're coming from, but I'm not quite sure what the best approach would be here. E.g. when a new R version is released which I want to try, but not switch to permanently (yet), I'm in a similar situation as you, but not between architectures but R versions.

This is definitely also a very valid and common scenario. 
@renkun-ken @ManuelHentschel - I do like the multiple paths approach, especially since this would as a result fix one of the major inconveniences you usually have in RStudio for VSC 
Looking forward to your ideas and if this feature will make it into one of the future releases. 
Thanks ...

**Comment by renkun-ken** [comment]
>I'd also suggest implementing the same mechanism for r.path.xxx.

If multiple paths are specified in `r.path.xxx`, then starting background processes (e.g. R help, language server) will prompt?

**Comment by ManuelHentschel** [comment]
> If multiple paths are specified in `r.path.xxx`, then starting background processes (e.g. R help, language server) should prompt?

Yes, once per session. Normally, people will have only one path here, but if someone decides to put multiple paths in `r.path.xxx`, this is the behaviour I'd expect.

**Comment by ElianHugh** [comment]
If its of any use, the python extension does a neat thing where you can set the interpreter 

https://code.visualstudio.com/docs/languages/python

![Screenshot_20210706-200518_Firefox.jpg](https://user-images.githubusercontent.com/60372411/124582649-8d79df80-de95-11eb-8607-3188ac4e5cc8.jpg)

**Comment by renkun-ken** [comment]
I was thinking about exactly the same thing as @ElianHugh suggests.

**Comment by gwd666** [comment]
@renkun-ken and @ElianHugh - I also like the idea of not reinventing the wheel and presenting people with something "familiar" partly also b/c the intersection of Py and R users (bilingual ones using both extensions) is probably quite significant and that binbg similar would end up being a nice muscle memory feature then

**Comment by gwd999** [comment]
> One could probably also assume that the respective architectures will be available from R_HOME\bin\ in the i386 and ...x64 subfolders. Not so sure about how that would look like / work with `radian` (since I do not use that). But for defining `Rterm` path in the R extension `Settings` you would also have to decide the `ARCH` - a lot like in RStudio, where you always have to restart after changing the ARCH, but I thought maybe these Setting changes could be avoided for the `R: Create R terminal` command, if this was available via CTRL+P?

you can also define the desired architecture as an argument when calling R_HOME/bin/R 
Taken from R Install Admin manual: 
Sub-architectures are also used on Windows, but by selecting executables within the appropriate bin directory, R_HOME/bin/i386 or R_HOME/bin/x64. 
**For backwards compatibility there are executables R_HOME/bin/R.exe** and R_HOME/bin/Rscript.exe: these will run an executable from one of the subdirectories, which one being taken first from the R_ARCH environment variable, then from the --arch command-line option = possible value: ‘i386’, ‘x64’, ‘32’ and ‘64’ so eg.: `R_HOME\bin\R --arch i386`

**Comment by hermidalc** [comment]
In https://github.com/REditorSupport/vscode-R/issues/1130 I'm pretty much asking for the same thing and what isn't mentioned here is many R users will not have a single R install and will use something like mamba/conda where, per project/github repo, one will have a conda environment with it's own R, radian, and libraries each with their own versions/builds required by that particular project.

The feature request for me would be to make `vscode-R` work *exactly* the same as `vscode-python`. I should be able to hit `Ctrl + Shift + P` -> `R: Select Interpreter` and an auto-populated drop-down list of all the R binaries avail on my computer will be shown and I should be able to select this binary (and by extension the conda env) per project folder (or workspace level).

Then in the lower right-hand status bar should show in place of the `Python (Extension)` status info it should have the `R (Extension)` status info with e.g. `4.1.3 ('myenv': conda)`

**Comment by ElianHugh** [comment]
I've done a bit of work on this recently. I've succy retrieved a list of paths, versions, and architectures on Linux so hopefully implementation isn't too far off. Just looking at retrieval from renv (i.e. using r version specified in the lock file) and conda now

**Comment by hermidalc** [comment]
Thank you @ElianHugh 

Hopefully it will work like I’ve described above like python extension does, then this would make a lot of sense to new users. This would be a very useful feature to the R extension

**Comment by gwd999** [comment]
Though 32-bit R is soon being deprecated choosing different versions is still a cool feature. Just curious if there is going to be a way for `radian` integration for that? Currently I am using `—r-binary= …` when having a radian path defined for R. Maybe some environment variable could derived from that „new“ R version path could stand in there? 
Really looking fwd to that feature.

**Comment by ElianHugh** [comment]
Thanks. Regarding radian, I've played around with setting the R_BINARY environment value, which appears to work + is relatively unobtrusive. This would be accessed via the provided R terminal profile.

**Comment by hermidalc** [comment]
I also cannot seem to even get `vscode-R` linting to work. Coming from Atom where things just worked thhisIn python everything works beautifully. For R I've installed everything in a single conda environment and then I launch `code` from the terminal with that environment activated. I also specified the full path to that conda environment R binary in the `r.term` settings. This should be equivalent to someone installing everything in their system path. But nothing works for me I open an R code file and it doesn't lint, it says `Loading...` on hover over, attaching doesn't work, basically nothing useful works. Kind of frustrating for a new user and trust me I know my way around I've been using Atom for like 5 years.

**Comment by ElianHugh** [comment]
I can sympathise with the frustration. The issue by-in-large is likely with regard to the use of conda environments, which have historically had issues with this extension. Hopefully this will be resolved when this feature gets PR worthy

**Comment by hermidalc** [comment]
The thing is though I'm not getting that explanation, why does the `vscode-R` extension not look at what binaries are available in the users `$PATH`? If I've launched `code` from a terminal with the conda environment that has the all the binaries needed activated? This is how Atom would work. In Linux that's completely equivalent installed the binaries system-wide via apt/dnf packages, which if I'm understanding correctly you are saying it would work if I did it this way. Sorry just my new user frustration.

Hopefully like you said your PR will work exactly like `vscode-python` is designed, which is really great and much better than Atom. You don't need to install anything system-wide or launch `code` from a terminal, it can simply be launched from your GNOME desktop and just works.

**Comment by ElianHugh** [comment]
Still WIP but getting there: 

![select](https://user-images.githubusercontent.com/60372411/175861961-a0d1cad8-9bd8-404c-bd14-ade96c0f4e35.gif)

**Comment by hermidalc** [comment]
@ElianHugh and that executable setting sticks for each project folder in a workspace? And how does it work the `R: (not attached)`? I could also not get that to work, it would just `.vsc.attach()` do nothing in the terminal.

**Comment by ElianHugh** [comment]
Yep, the R version is set on a workspace basis, so each time you open it up it will use the version that you set. If there isn't one set it'll default to the rpath in settings, otherwise will prompt user to choose. 

I'm still thinking about what to do re: the terminal.  The whole not-attached thing probably also needs some special treatment for conda environments (e.g. need to auto-activate for users). Also, it'll now follow the R version specified but it looks a little redundant having two R buttons there.  Any thoughts on the issue @renkun-ken ?

**Comment by hermidalc** [comment]
Hey @ElianHugh it should be on a project folder basis not workspace basis. Just like `vscode-python`. It makes dev sense to because each project folder is a github repo, which will usually have it's own dependency environment.

**Comment by ElianHugh** [comment]
When you say project folder basis, what kind of setup do you mean?
Something like:

- workspace
	- ProjectA
	- ProjectB
	- ProjectC

**Comment by hermidalc** [comment]
Yes that's a project folder in a workspace and each one is it's one github repo usually. It's just like `vscode-python` designed it I can set my conda environment and executable at the `ProjectA` `ProjectB` and `ProjectC` folders separately. It's exactly the way you want it as a developer.

The workspace is just a collection of related github repos (projects). A dev could have things the same between projects and just set it at workspace level, but that's not often the case.

**Comment by ElianHugh** [comment]
Alright, I getcha. I'll have to look at how python handles the languageserver sessions

**Comment by hermidalc** [comment]
Here's my current VSCode screen. My workspace right now is my collection of sklearn/sksurv based framework and extension projects (each its own github repo). For example, `sklearn-bio-workflows` has a different conda environment and deps than `sksurv-bio-workflows`. In this case same python but it could be that different project folders have different python.

When I have my cursor active in a code window from `sklearn-bio-worflows` you see in the bottom right-hand corner is automatically switches to its conda environment:

![Screenshot from 2022-06-27 01-13-49](https://user-images.githubusercontent.com/461066/175865066-da31629f-9010-461f-ab06-dd7b4971768a.png)

When I have my cursor active in a code window from `sksurv-bio-workflows` you see it automatically switches to its conda environment:

![Screenshot from 2022-06-27 01-14-17](https://user-images.githubusercontent.com/461066/175865162-730af9b2-64b7-4837-9ac3-208c6659f4bc.png)
nt:

**Comment by hermidalc** [comment]
And sorry forgot to mention a super important other reason. Since the projects have different environments and dependencies, the auto switching of environments between code windows from separate projects enables the syntax checking, autocomplete, and signature help of deps to work seamlessly.

For one project I might have `lifelines` as a dep in the environment and the syntax checking of a code file using `lifelines` checking will know and do the right things. `vscode-python` does all this.

**Comment by ElianHugh** [comment]
Hi @renkun-ken , this implementation would likely require the modification of the language service. Specifically, modifying the root folder away from workspace folder to some sort of project folder, so that we can distinguish between projects + have multiple servers running per project. This would also mean that we'd need a way of distinguishing projects (e.g., rproj file, description file, etc). Curious to hear your thoughts!

**Comment by hermidalc** [comment]
And to highlight more, this is what I mean by project folder (Github repo) level. When you open the VSCode Settings, you will see at the top User > Workspace > Folder. When dealing with vscode-python and Python extension settings, you see when selecting a project folder the extension settings are still there and things can be set at this level. But you see the vscode-R extension settings disappear at the folder level:

![Screenshot from 2022-06-29 10-04-40](https://user-images.githubusercontent.com/461066/176457039-ede37ce4-c111-4a5e-ac54-4341864622c8.png)

You can only see or change ***some*** of vscode-R settings at the workspace level. And the R interpreter path can only be done at the User level, which isn't usable for many of us I need a different R for each Github repo:

![Screenshot from 2022-06-29 10-09-22](https://user-images.githubusercontent.com/461066/176457773-c587f6a4-2201-4973-862a-2d3e31a82d9b.png)

Some projects I have only can use R 3.6 because of various dependency needs, while others use R 4.1. Some project can use the same R version, but have different dependency version needs.

**Comment by hermidalc** [comment]
Sorry to add something, VSCode already has full support of conda for Python, and at the project folder level, all the infrastructure is there for R to do the same thing. Why spend effort to support another dependency manager that is limited to only R when conda has full R dependency management plus for other languages.

**Comment by hermidalc** [comment]
> > Why spend effort to support another dependency manager that is limited to only R when conda has full R dependency management plus for other languages.
> 
> I believe many R users do not use conda to install R. In that case they cannot use conda or mamba, right? While there are certainly many R packages in conda-forge, it does not cover all packages in CRAN nor does it necessarily install the latest R versions.

You don't have to in VSCode... As with `vscode-python` it searches and finds all interpreter/environment paths, including your system ones or other ones outside of conda. See my screenshot below after clicking `Python: Select Interpreter`. It shows all my python paths including my system ones and other ones outside of my conda envs.

This is exactly how `vscode-R` should work, so it continues providing the same support it already did for ppl who don't use conda and then also for people who do and who do it at the Github repo/project folder level.

![Screenshot from 2022-06-29 11-39-57](https://user-images.githubusercontent.com/461066/176478701-4ce5647d-7577-4faf-9c05-26022df78f49.png)

**Comment by gwd666** [comment]
I am definitely sold on that feature extension. And props to the (two) main developers/maintainers here! 
That extension of yours is definitely a great addition the the R ecosystem imho not replacing RStudio but extending it to more types of use-cases. 
And tbh if it takes more than a couple of steps or iterations to get there -> also fine by me ... to me it looks like it will be worth the "wait"

**Comment by hermidalc** [comment]
Me too, will make VSCode really usable for me. And I will beta test whatever you need

**Comment by ElianHugh** [comment]
Thank you all for the feedback. We are a tiny repo in comparison to the python extension + don't have the resources of a full-time dev, so any and all help (be it feedback, testing, or dev work) is greatly appreciated.

**Comment by ElianHugh** [comment]
Hi @ManuelHentschel,

At the moment the help server is spun up globally with a static path. If I was looking to have a separate help server per workspace folder (i.e. for multiroot), would it be viable to have a map of help servers rather than one global server?

**Comment by ManuelHentschel** [comment]
> Hi @ManuelHentschel,
> 
> At the moment the help server is spun up globally with a static path. If I was looking to have a separate help server per workspace folder (i.e. for multiroot), would it be viable to have a map of help servers rather than one global server?

Yes that shouldn't be a problem. We could just have multiple instances of the classes in helpProvider.ts, and the methods `RHelp.getHelpFileForPath` etc. would need to be rewritten to use the correct providers (or e.g. try them all in order). If you like, I can implement this, just let me know your specific requirements.

**Comment by ElianHugh** [comment]
Absolutely, that would be fantastic! I'll try to setup a WIP PR for reference either tonight or tomorrow, just need to tidy up a bit first :)
