### ISSUE TITLE
Live preview of pkgdown, blogdown and bookdown pages?

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/vscode-R#698]
VSCode [v1.58](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) shipped with a new [live-preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) for html outputs.

I was wondering if the R extension could make use of it in a smart way for local embedded previews of blogdown, bookdown, xaringan or pkgdown?

I.e. I would be very happy if `xaringan::inf_mr()` or `bookdown::serve_book()` (and others) could make use of this extension by default somehow.

It is not bundled by default and currently one always needs to have the html output open to initiate the preview which is a bit cumbersome in the long run.

**Comment by renkun-ken** [comment]
I think these packages already provide http server backend to serve the website.

**Comment by pat-s** [comment]
My comment was probably unclear, sorry.

I am aware of the internal preview servers of such.

I was referring to opening the live preview within vscode. I never found the correct setting to do so and still opening the preview in an external browser. 

Also reading past issues related to the internal browser I thought it might not be so easy to do this within vscode. And then I saw this new feature now and thought this might change things.

Am I just missing a setting maybe?

**Comment by renkun-ken** [comment]
If you enable `r.sessionWatcher` (now it is the default), then in an attached R session running `blogdown::serve_site()` will open a WebView to show the website.

**Comment by pat-s** [comment]
Indeed that works just OOB 🤔 Was there a time when this did not work maybe? I think I've tried that many times in the past 😅 That's why I was so excited now about the new feature

`pkgdown::preview_site()` still opens externally for me but it uses `utils::browseURL()` under the hood and does not come with a server capability anyhow.

Thanks for your help!
