### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by itsmesunnyanand** [REditorSupport/vscode-R#702]
I am getting this error everytime I open VS Code.

Unable to start Microsoft.R.Host process. Exception: R host process did not start on the machine. Exception: Unknown error (0xc0000005) at Microsoft.R.Host.Client.BrokerServices.WebService.EnsureSuccessStatusCode(HttpResponseMessage response) at Microsoft.R.Host.Client.BrokerServices.WebService.GetHttpPutResponseAsync(Uri uri, String requestBody, CancellationToken cancellationToken) at Microsoft.R.Host.Client.BrokerServices.WebService.RepeatUntilAuthenticatedAsync[T](Func`2 action, CancellationToken cancellationToken) at Microsoft.R.Host.Client.BrokerServices.WebService.HttpPutAsync[TRequest,TResponse](Uri uri, TRequest request, CancellationToken cancellationToken) at Microsoft.R.Host.Client.Host.BrokerClient.CreateBrokerSessionAsync(String name, Boolean useRCommandLineArguments, Boolean isInteractive, CancellationToken cancellationToken)

Extension version: 2.0.0
VS Code version: Code - Insiders 1.59.0-insider (87d692b7bf1eb5a663b3e62620a6e7e436e1838c, 2021-07-09T05:13:26.890Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (2 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.59GB (2.06GB free)|
|Process Argv|--crash-reporter-id 61c7c90e-9d22-44ae-aedb-d9aa6d9d997c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
bridge0708:30335490

```

</details>

d data into your clipboard because it was too large to send. Please paste.

**Comment by renkun-ken** [comment]
Looks like you are using [R Tools](https://marketplace.visualstudio.com/items?itemName=Mikhail-Arkhipov.r). [vscode-R](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r) is the extension we build here.

**Comment by itsmesunnyanand** [comment]
Yes I am, should I uninstall it?

**Comment by renkun-ken** [comment]
Yes, there's some conflict between R Tools and vscode-R.

**Comment by itsmesunnyanand** [comment]
Thanks, let me check.

Sent from Yahoo Mail on Android 
 
  On Mon, 12 Jul 2021 at 17:45, Kun ***@***.***> wrote:   


Yes, there's some conflict between R Tools and vscode-R.

**Comment by gowerc** [comment]
@renkun-ken , I think this can be closed
