### ISSUE TITLE
Let httpgd resize plots automatically to editor size

### ISSUE THREAD

**Issue by BerriJ** [REditorSupport/vscode-R#705]
**Is your feature request related to a problem? Please describe.**
I'm using this new "Terminals in the editor area" feature of VS-Code a lot. However, resizing the grid layout horizontally does not lead to a horizontal resize of the plot. This already works for adjusting the width, but not for the height. I created a gif for the demonstration.

![Peek 2021-07-14 16-49](https://user-images.githubusercontent.com/37799358/125643986-139e6e88-5e5c-4104-9967-f98dd4113a71.gif)

I'm aware that this means removing the plot selection. However, those backward/forward buttons are fully sufficient for me to access my plot history.

I would like to disable this "Empty space + Plot Selection" area under the plot and just let httpgd use the full window. This way one could resize using the editor drag and drop.

**Comment by renkun-ken** [comment]
I agree that the resizing of the plot viewer should be somehow improved. Sometimes dragging the horizontal line keeps scrolling to a huge image of infinite height.

You may try the [original httpgd viewer](https://github.com/REditorSupport/vscode-R/wiki/Plot-viewer#svg-in-httpgd-webpage) for the moment as a walk around.

**Comment by ManuelHentschel** [comment]
You can hide the plot preview by calling `r.plot.togglePreviewPlots` 1-2 times (it toggles through 3 different modes).

Implementing a "full window" mode sounds like a good idea and shouldn't be that hard, I'll take a look in the coming days.

**Comment by psobolewskiPhD** [comment]
Thank you for articulating this more clearly.
I've gone back to a previous version of vscode-r for this reason, after trying somethings previously:
https://github.com/REditorSupport/vscode-R/pull/678#issuecomment-864605405
I found myself frequently making ginormous plots in the y direction when trying to resize to fill my available screen space (13" MBP so utilizing screen space well is crucial).
It's a tricky issue given how the panes/panels/segments are interconnected (code/terminal/plot), but finding a way to maximize plot area (at the expense of other elements) to me would be a huge boon.
