### ISSUE TITLE
Add "Create .lintr" command

### ISSUE THREAD

**Issue by eitsupi** [REditorSupport/vscode-R#712]
How about adding a command to add a `.lintr` file to the workspace, similar to the command that already exists to add `.gitignore`?
(Perhaps a function in the {lintr} or {languageserver} package would be more appropriate ?)

When I used vscode-R and R LSP for the first time, I struggled a lot because I did not know how to write a `.lintr` file.

**Comment by renkun-ken** [comment]
Thanks for raising this. It is indeed important to make things easier for new users.

Similar:

* Edit user `~/.Rprofile`
* Edit project `.Rprofile`
* Edit user `~/.lintr`
* Edit project `.lintr`

**Comment by renkun-ken** [comment]
It would be nice if we have something to make it easier for users to edit these config files.

**Comment by eitsupi** [comment]
Related to https://github.com/r-lib/lintr/issues/886

**Comment by eitsupi** [comment]
There are functions called `usethis::edit_r_environ()` and `usethis::edit_r_profile()`.

However, if we want to edit files in a project, not the user, a directory without a `.Rproj` file is not considered a project by the usethis package and cannot be used.

**Comment by AshesITR** [comment]
We now have `lintr::use_lintr()` to help create a dummy file.
