### ISSUE TITLE
Syntax highlighting fails when there's a vector argument

### ISSUE THREAD

**Issue by Alanocallaghan** [REditorSupport/vscode-R#713]
I came here by following the link in `[...]/code/resources/app/extensions/r/syntaxes/r.tmLanguage.json` so I hope I'm in the right place.

**Describe the bug**

The following code breaks the syntax highlighting; everything after the last quote is considered part of an (unfinished) string

```r
fun <- function(a, c = c("a", "()"), d) {
    function body, not a quoted string
}
```

![syntax](https://user-images.githubusercontent.com/10779688/126529731-a72b9056-97b6-4d7b-bd41-45cb2d4fca07.png)

It seems to view the close bracket within the quoted string as the end of the function args.

**To Reproduce**

1. Open an R file
2. Copy or type that code
3. Observe the results

## Do you want to fix by self? (We hope your help!)

I have tried to, but I'm not familiar with textmate grammars... so... maybe? I gather I've got to mess with function-parameters so that it no longer views the close bracket as the end of the function args, probably by allowing arguments to have default values that are the evaluation of function calls

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

**Expected behavior**
Pretty clear I think

**Screenshots**
Above

**Environment (please complete the following information):**

- OS: Linux
- VSCode Version: [e.g. 1.58.2]
- not important
- also unimportant, but I'm testing with the current language definition in this repo

**Comment by renkun-ken** [comment]
I could reproduce this. In this case, the language service does not work either when editing code below this function.

**Comment by eitsupi** [comment]
Out of curiosity, is this a problem with this extension?
The syntax highlighting seems to go wrong even in environments without vscode-R.

**Comment by renkun-ken** [comment]
It is likely that the built-in syntax does not correctly handle such case.

**Comment by eitsupi** [comment]
I looked it up and it looks like the syntax for this extension is built into vscode?
https://github.com/microsoft/vscode/blob/4f5f5de28ffbe4d9321148479d9e050cdb1551ed/extensions/r/syntaxes/r.tmLanguage.json#L3

**Comment by renkun-ken** [comment]
Thanks for the finding. Then it is up to us to fix the syntax.

**Comment by Alanocallaghan** [comment]
> I looked it up and it looks like the syntax for this extension is built into vscode?

Yeah that's what I meant by
> I came here by following the link in [...]/code/resources/app/extensions/r/syntaxes/r.tmLanguage.json so I hope I'm in the right place.

Sorry if that wasn't clear!

**Comment by eitsupi** [comment]
There is a link to R-Box in the comment after opening the link from vscode above, but R-Box is already archived and updates are already made directly to this repository, so it would be better to modify the comment.
https://github.com/REditorSupport/vscode-R/blob/8ec924b2a1b18ea722172995fa702c938604ecaf/syntax/r.json#L2-L6

**Comment by ElianHugh** [comment]
(to state the obvious) it looks like brackets are still being parsed as punctuation when quoted and in the presence of `function`. this leads me to think it's an issue with the `function-declarations` definition

![image](https://user-images.githubusercontent.com/60372411/126751598-4c5beed7-510e-4dcf-87de-b7ca2afd07b4.png)
![image](https://user-images.githubusercontent.com/60372411/126751717-e8782cc5-61be-437e-9a52-02318b25a597.png)
![image](https://user-images.githubusercontent.com/60372411/126751745-c95d6689-fd17-4991-9413-258774d5eb8f.png)

**Comment by eitsupi** [comment]
FYI,  [the syntax highlighting on GitHub](https://github.com/github/linguist/blob/ca8b0027028d6d2f42ebe7d347b55f7c30572393/vendor/README.md) seems to be normal, and the source code seems to be from this repository.
https://github.com/textmate/r.tmbundle

**Comment by ElianHugh** [comment]
> FYI,  [the syntax highlighting on GitHub](https://github.com/github/linguist/blob/ca8b0027028d6d2f42ebe7d347b55f7c30572393/vendor/README.md) seems to be normal, and the source code seems to be from this repository.
> https://github.com/textmate/r.tmbundle

Thanks for the link @eitsupi! I tested the grammar in vscode, and like you said, didn't into any problems.

 I don't know a whole lot about textmate grammar, but I wonder if there would be any issues with adopting the linked one?

**Comment by ElianHugh** [comment]
The issue is definitely with the function declarations section, replacing the `function-declarations` match pattern with the textmate repo's pattern fixes the issue.
