### ISSUE TITLE
Install languageserver automatically

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#718]
When extension is activated, if languageserver is not installed, we could install it automatically. This looks easy to implement:

We could run a script instead of the expression `languageserver::run(...)`. In the script, we check if languageserver is installed. If not, run `install.packages("langaugeserver")` before running the language server.

We could either use command args to pass the values of `debug` and `port`, or use environment variables instead.

**Comment by renkun-ken** [comment]
Still relevant, unstale.

**Comment by benz0li** [comment]
Without the required packages installed, one gets

```
VSCode R Session Watcher requires jsonlite, rlang. Please install manually in order to use VSCode-R.
```

in the Terminal if _R session watcher_ is enabled (default) AND

<img width="450" alt="languageserver" src="https://user-images.githubusercontent.com/20233085/180947508-acc65a86-8096-4551-ad45-add2cee8f5d7.png">

in the GUI about package `languageserver` for _R Language Server_.

---

IMHO this is sufficient.

**Comment by renkun-ken** [comment]
Agree. Closing.
