### ISSUE TITLE
Old rlsp processes not being removed

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#722]
I'll start by saying this could likely be a user error (in which case would appreciate any advice).  So through the course of development I will often close my R session and launch a new R process several times (in order to ensure a clean environment). Whilst doing this it appears that a new rlsp process is launched and the old one is not removed / cleaned up. Each process holds onto quite a large amount of memory which is slowly leading to memory exhaustion on my machine.  

![image](https://user-images.githubusercontent.com/8447209/117573940-a141d900-b0d2-11eb-9aa8-470c3694b05a.png)

I am running vscode on Ubuntu Focal from windows wsl. 

(unless I am misreading this and there is supposed to be that many rlsp processes?)

**Comment by renkun-ken** [comment]
Resolved with #941
