### ISSUE TITLE
[Feature request] Show linting messages from files opening only

### ISSUE THREAD

**Issue by psychelzh** [REditorSupport/vscode-R#724]
Currently "lintr" messages is very annoying even when files are closed. What's more, it is absolutely strange that linting messages of files deleted remain there.

**Comment by psychelzh** [comment]
Is there any updating?

**Comment by eitsupi** [comment]
Is this a issue of this extension?
I think I have the same problem with other types of files (i.e. is it a vscode issue?).

**Comment by psychelzh** [comment]
In light of https://github.com/microsoft/vscode/issues/30038, it is not the issue of current extension. Thanks!
