### ISSUE TITLE
execute multiples lines not working

### ISSUE THREAD

**Issue by verajosemanuel** [REditorSupport/vscode-R#731]
**Describe the bug**
unable to send multiple lines to execute whithin pipes or functions.

**To Reproduce**
Code some procedure involving multiple lines , pipes or function declaration

Sample code (requires to press Ctrl + Enter Three times)

```
iris %>% 
dplyr::group_by(Species) %>% 
tally()
```

**Expected behavior**
execute multiline statements in one stroke.

**Environment (please complete the following information):**

- OS: [Windows10]
- VSCode Version: [1.58.2]
- R Version: [4.0.5]
- vscode-R version: [2.1.0]

[](url)

**Comment by renkun-ken** [comment]
Cannot reproduce it in Ubuntu and macOS. Are you sure you are using "R: Run Selection/Line" by pressing "Ctrl + Enter"?

**Comment by verajosemanuel** [comment]
Running via Ctrl + Enter does not work, but running via palette command worked. Maybe is not properly assigned to keybinding?

**Comment by verajosemanuel** [comment]
Seems the issue was related to other installed R-addin: Mikhail Arkhipov Rtools
Disabling it set everything back to normal.

**Comment by renkun-ken** [comment]
We encountered multiple issues when [Mikhail Arkhipov R Tools](https://marketplace.visualstudio.com/items?itemName=Mikhail-Arkhipov.r) is installed. Need to uninstall it.

**Comment by renkun-ken** [comment]
Maybe we need to check if this extension is installed and give a warning of conflict like checking vscode-r-lsp which is obsolete.
