### ISSUE TITLE
R: (Not attached) + unknown file attribute: C

### ISSUE THREAD

**Issue by 1DmntdMnky** [REditorSupport/vscode-R#732]
**R : (Not attached) + unknown file attribute C** 

Did not happen yesterday, suddenly opened VSCodium and saw this error. Tried the same installation on a Windows but it's working as it should, has the same error on my friends MBP. I opened the R application and it showed this [error](https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c). Solved it using the same link. The same code works on the terminal, but returns ```zsh: unknown file attribute: C``` in vscodium integrated terminal.

Clicking on R: (Not attached) puts this in the terminal and nothing happens next ```.vsc.attach() function>```

**Screenshots**
![image](https://user-images.githubusercontent.com/68737810/126780162-e7072193-f772-47f9-8e69-98ab3bbeb986.png)

**Environment:**

- OS: macOS 11..4
- VSCodium Version: Version: 1.58.2
- R Version: 4.1.0
- vscode-R version: 2.1.0

**Comment by renkun-ken** [comment]
From the screenshot, looks like your terminal contains some control characters?

**Comment by 1DmntdMnky** [comment]
> From the screenshot, looks like your terminal contains some control characters?

Might be? I'm running oh-my-zsh with it's plugins, and powerline10k theme. What should I look for exactly?

**Comment by 1DmntdMnky** [comment]
> From the screenshot, looks like your terminal contains some control characters?

Okay so my friend has the same issue? He also has a vanilla zsh terminal (Apple changed from bash to zsh in bigsur).
I tried disabling the theme, but it returned the same error. When we click run as source it returns the ```zsh: unknown file attribute: C``` error, if we type radian first and then do run as source, then it works. Run as code works normally. Also, when we do run as source in radian, the plots and charts don't open in a vscode pane, but it opens in macos window.

Screenshot:
![deezerror](https://user-images.githubusercontent.com/68737810/127634750-a5f4cbcd-aa0c-4065-9ed7-9c53f3e60a1b.png)
