### ISSUE TITLE
Not able to run Rcpp due to space in R root directory: 'C:/Program' not found

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#737]
- OS: Windows
- VSCode Version: 1.58.2
- R Version: 4.1.0
- vscode-R version: 2.1.0

Don't know whether it is a `vscode-R` issue or `vscode` issue. 

```
r$> library(Rcpp)

r$> evalCpp("2*2")
Error in system(cmd, intern = !showOutput) : 'C:/Program' not found
Error in system(cmd, ignore.stderr = TRUE, intern = TRUE) : 
  'C:/Program' not found
```

Is there anyway to fix this without re-installing in a non-space directory?

**Comment by renkun-ken** [comment]
Does it occur with 

* Offical R terminal instead of radian in vscode
* radian outside vscode

**Comment by Fred-Wu** [comment]
> 
> 
> Does it occur with
> 
>     * Offical R terminal instead of radian in vscode
> 
>     * radian outside vscode

It occured with radian in vscode. 

![image](https://user-images.githubusercontent.com/4111978/127595648-dc36463b-fc84-4f0b-870a-3716cc77acc7.png)

![image](https://user-images.githubusercontent.com/4111978/127595676-7523bd82-ad91-4146-b5a9-800710a6867c.png)

**Comment by Fred-Wu** [comment]
> 
> 
> Does it occur with
> 
>     * Offical R terminal instead of radian in vscode
> 
>     * radian outside vscode

Just tried to disable the radian, and used the official R terminal. 

It works on it.

**Comment by renkun-ken** [comment]
Then it should be radian's issue.

**Comment by Fred-Wu** [comment]
> 
> 
> Then it should be radian's issue.

Thanks, I will raise the issue over there then.

**Comment by Fred-Wu** [comment]
Found a way to fix this by defining R path in `settings.json`

```
"r.rterm.option": ["--r-binary=C:\\Program Files\\R\\R-4.1.0\\bin\\R.exe"]
```
