### ISSUE TITLE
Is there anyway to disable diagnostic for stylistic error?

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#740]
Is there anyway to disable diagnostic for stylistic error only?

**Comment by ElianHugh** [comment]
You can create a .lintr file in your workspace root. See "project configuration": https://github.com/jimhester/lintr

**Comment by Fred-Wu** [comment]
> 
> 
> You can create a .lintr file in your workspace root. See "project configuration": https://github.com/jimhester/lintr
> 
> Edit: also, a neat extension for this is ['Error Lens'](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens). you can fine-tune the display of diagnostics through the extension's settings

Thanks for the suggestion. Able to implement it through `.lintr`.

**Comment by ElianHugh** [comment]
Great! Closing this for now. Feel free to re-open if you have any issues with getting this to work
