### ISSUE TITLE
Default to utils::view() when no asJSON S3 method exists

### ISSUE THREAD

**Issue by mkoohafkan** [REditorSupport/vscode-R#742]
R `tibble()` objects can contain objects that do not have asJSON methods (e.g., `difftime` objects, `units` objects, etc.) . In these cases R will return an error when calling the `View()` function provided by VSCode-R:

> Error: No method asJSON S3 class: units

However, the default `utils::View()` function can still display these datatypes. It would be great if either:

1) VSCode-R `View()` function could automatically default to using `utils::View()` if an `asJSON` error is encountered, or
2) The error message returned by VSCode-R `View()` function could direct users to try using `utils::View()` to display the dataset.

**Comment by renkun-ken** [comment]
Thanks for reporting! I could reproduce this with the following code:

```r

df <- data.frame(
  diff = difftime(Sys.time() + 1:2, Sys.time(), units = "s")
)
View(df)
```

```
Error: No method asJSON S3 class: difftime
Backtrace:
1: base::stop(..., call. = FALSE)
2: stop("No method asJSON S3 class: ", class(x))
3: .local(x, ...)
4: FUN(X[[i]], ...)
5: FUN(X[[i]], ...)
6: vapply(x, asJSON, character(nrow(x)), collapse = FALSE, complex = complex, 
7: .local(x, ...)
8: FUN(X[[i]], ...)
9: FUN(X[[i]], ...)
10: vapply(x, asJSON, character(1), na = na, auto_unbox = auto_unbox, 
11: .local(x, ...)
12: asJSON(x, dataframe = dataframe, Date = Date, POSIXt = POSIXt, 
13: asJSON(x, dataframe = dataframe, Date = Date, POSIXt = POSIXt, 
14: jsonlite::toJSON(x, ...)
15: jsonlite::write_json(data, file, auto_unbox = TRUE)
16: View(df)
```

Does it work for you if we do either of the following

1. Use `jsonlite::toJSON(..., force = TRUE)` to force converting to JSON so that difftime will become numerics but without " secs" in the formatted string representation.
2. Format the columns that do not implement `asJSON` method into their string representation.

**Comment by mkoohafkan** [comment]
Yeah, that should work great! The string representation can be unhelpful for certain objects, they become very long strings that can be irritating to navigate in a table---but I think  that's what `utils::View()` does too, so it certainly would not be a step backwards. I also think a placholder `[OBJECT]` string would be fine for objects that can't be converted to JSON, users can't expect every R object to be perfectly displayed!

**Comment by mkoohafkan** [comment]
Any updates on this? After a recent update, it seems like you can no longer call `utils::View()` to get a window outside of vscode.

**Comment by renkun-ken** [comment]
> Any updates on this? After a recent update, it seems like you can no longer call `utils::View()` to get a window outside of vscode.

We don't use `force=TRUE` yet.

#818 replaces `utils::View()` so that `tibble::view()` could work properly. To get a window outside of vscode, you need to specify the following settings in vscode to disable the vscode data viewer:

```json
"r.session.viewers.viewColumn": {
  "view": "Disable"
}
```

**Comment by mkoohafkan** [comment]
Still no solution for viewing tibbles that include a difftime column.

```
d = tibble(a = difftime(Sys.time(), Sys.time() - 853563))
View(d)
## Error: No method asJSON S3 class: difftime
```

**Comment by renkun-ken** [comment]
I guess the only thing we could do is use `force=TRUE` then.
