### ISSUE TITLE
workspace variable view not work

### ISSUE THREAD

**Issue by kongdd** [REditorSupport/vscode-R#744]
Help! workspace variable view not work. Should I modify some setting?

![image](https://user-images.githubusercontent.com/9815742/128594663-952416ad-0990-4383-a12a-efaead2ca7ed.png)

**Comment by renkun-ken** [comment]
Could you confirm that the session is attached? Look at the status bar and see if there is a valid pid in "R: (pid)" status bar item.

**Comment by kongdd** [comment]
Indeed, "R: (not attached)" in the status bar.
I am using radian in win10. Any solution?

**Comment by renkun-ken** [comment]
You could click "R: (not attached)" and it will send `.vsc.attach()` to the terminal and then the session will be attached.

**Comment by renkun-ken** [comment]
Are you starting your own `radian` rather than using "R: Create R terminal"? If it is the case, then you might need to configure your `~/.Rprofile` according to https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions.

**Comment by kongdd** [comment]
Thank u. But the variable information looks like a string. Is this normal?
![image](https://user-images.githubusercontent.com/9815742/128600428-8aa83925-9ee2-42b2-9712-4fb5533cee9b.png)

**Comment by renkun-ken** [comment]
If you are looking for output their element names, you might want to set the following option in your `~/.Rprofile`:

```r
options(vsc.str.max.level = 2 )
```

**Comment by kongdd** [comment]
Thank you very much!
