### ISSUE TITLE
Awalys has a "`)`" when submit a function to terminal for the first time. 

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#748]
When I submit a user-defined function to terminal for the first time, it always ends up with a `)` in the terminal. 
Re-submit won't see `)`. 

Something like this. 
```
toy_fun <- function() {

}
)
```
Not sure it is the issue with Radian or R editor here.

**Comment by renkun-ken** [comment]
Cannot reproduce it. Should be a radian issue.

**Comment by EvoLandEco** [comment]
I often had the same issue while using radian

**Comment by hongooi73** [comment]
Radian has this long-standing glitch of copying extraneous chars to the terminal. I've never been able to make it work 100% correctly.

**Comment by gowerc** [comment]
@renkun-ken , Can this be closed as its not a vscode-R issue ?

**Comment by shrektan** [comment]
Just my two cents. It may be Windows specific. I remember I encountered this issue a lot at that time when I was using Windows.
