### ISSUE TITLE
Prompt and command to install `languageserver`

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#754]
vscode-R now requires `languageserver` to be installed.

If the language server fails to start due to missing `languageserver` package, it would make sense to prompt to user and ask whether to install the package for the user.

**Comment by renkun-ken** [comment]
To be clear,

* R session watcher only requires `jsonlite` and `rlang` as before
* R language service requires `languageserver` which imports `jsonlite` and `rlang`.

**Comment by ManuelHentschel** [comment]
A related topic is `pandoc`/`rmarkdown` for the help-hover of the languageserver. Currently, the languageserver just serves the "old" layout if the required dependencies are not installed.
