### ISSUE TITLE
a problem in "plot viewer", when I use radian instead of R by set "r.rterm.linux:radian"

### ISSUE THREAD

**Issue by f-jx** [REditorSupport/vscode-R#760]
vscode version:1.59.0
conda version:4.10.3
R version:3.6.1
radian version:0.5.11
vscode-R version:v2.2.0

my workspace settings.json:
{
    "python.defaultInterpreterPath": "/opt/miniconda3/bin/python",
    "python.terminal.activateEnvironment": false,
    "r.rterm.linux": "/opt/miniconda3/bin/radian",
    "r.rterm.option": [
        "--r-binary=/opt/miniconda3/bin/R"
    ],
    "r.bracketedPaste": true
}

my R script test.r:
library("ggplot2")
plot(mtcars$wt,mtcars$mpg)

the problem is when I set {"r.rterm.option": ["--r-binary=/opt/miniconda3/bin/R"]} and run test.r by shortcut key "Ctrl+Enter"
the "plot viewer" show an picture: the coordinate scale is displayed as binary...
![image](https://user-images.githubusercontent.com/44256687/130311495-870b4f18-20f1-43d3-993b-4b058ed4bdef.png)

but the output picture of PDF file is correct:
![image](https://user-images.githubusercontent.com/44256687/130311566-9757728a-2289-4069-8cab-f9edd8de0c96.png)

I try to use R instead of radian again
workspace settings.json:
{
    "python.defaultInterpreterPath": "/opt/miniconda3/bin/python",
    "python.terminal.activateEnvironment": false
}

but it does'n work, the "plot viewer" still show an picture with binary coordinate scale...

Thanks for your answer!

**Comment by ManuelHentschel** [comment]
Does this also happen in the httpgd-based plot viewer?
(To check, install [httpgd](https://github.com/nx10/httpgd) and set `options(vsc.use_httpgd = TRUE)`)

**Comment by f-jx** [comment]
Thank you!
I installed httpgd, and the problem is gone.
but I don't know how to set options(vsc.use_httpgd = TRUE)

**Comment by renkun-ken** [comment]
With the latest release of vscode-R (v2.2.0), you could simply set `r.plot.useHttpgd` in vscode settings.

**Comment by f-jx** [comment]
Thanks！
I had set "r.plot.useHttpgd": true, and the picture automatically adapts to the window! It's so elegant!
