### ISSUE TITLE
Autocompletion of session variables in Rmd

### ISSUE THREAD

**Issue by roaldarbol** [REditorSupport/vscode-R#762]
**Describe the bug**
When writing the name of a data frame followed by `$` the column names should pop up; they do in a plain `R` script, but not in `R Markdown`. It might relate to #213 and be a `languageserver` issue, but (https://github.com/REditorSupport/languageserver/issues/424#issuecomment-868939350) suggests that it shoudl be working natively with vscode-R.

**To Reproduce**

1. Create dummy data frame in a fresh R/Rmd script (e.g. `df <- data.frame(x = c(1, 2, 3), y = c(4, 5, 6))`)
2. Start new line with `df$` - in the plain R script you'll see the column suggestions, in Rmd you won't.

## Do you want to fix by self? (We hope your help!)
No (sorry!)

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)
In case it's just because I've missed a setting or something similar, then a pointer - otherwise consider it a feature request. :-) 

(If related)setting.json

```json
{
    "editor.formatOnType": true,
    "workbench.colorTheme": "One Dark Pro",
    "r.rterm.mac": "/Users/myusername/opt/anaconda3/bin/radian",
    "r.bracketedPaste": true,
    "r.plot.useHttpgd": true,
}
```

**Expected behavior**
I would expect the same behaviour in `Rmd` as in plain `R`.

**Screenshots**
Data frame present in workspace:
![Screenshot 2021-08-24 at 12 19 39](https://user-images.githubusercontent.com/25629697/130607964-d34a495b-2c19-47e2-9e85-547ca3be0737.png)
Autocompletion in plain R:
![Screenshot 2021-08-24 at 12 19 25](https://user-images.githubusercontent.com/25629697/130607967-de377749-1778-4fd6-a53a-a217751a5f5e.png)
Autocompletion doesn't see the session variables in Rmd:
![Screenshot 2021-08-24 at 12 20 23](https://user-images.githubusercontent.com/25629697/130607960-e1238371-2022-4ee5-9c78-3b00ab46b649.png)
But autocomplete works for non-session objects:
![Screenshot 2021-08-24 at 12 23 44](https://user-images.githubusercontent.com/25629697/130608450-08c021f8-dd7a-4916-ab8a-4041e30d1433.png)

**Environment (please complete the following information):**

- OS: MacOS Big Sur
- VSCode Version: 1.60.0-insider
- R Version: 4.1.0
- vscode-R version: 2.2.0

**Comment by renkun-ken** [comment]
It is caused by `LiveCompletionItemProvider` only registered for `r`, not `rmd`. To make it also work with `rmd`, then the following needs to be done:

* Generalize the document selector by including both `r` and `rmd`
* Check if cursor is in an R code chunk if the document is `rmd`.

**Comment by roaldarbol** [comment]
Thanks for the quick reply, really appreciate it! Still being relatively new to VS, where do I do this?

**Comment by renkun-ken** [comment]
My comment above is just a note for development. It is not supported at the moment. I'll take a closer look this weekend.

**Comment by roaldarbol** [comment]
Ah, brilliant. Thanks for all the good work!

**Comment by roaldarbol** [comment]
Hey @renkun-ken, did you manage to take a look at this? :-)

**Comment by renkun-ken** [comment]
Didn't get a chance to look into this. Roughly speaking, we could extend both hover and completion to `rmd` by detecting if the cursor is in an R code chunk if the document language is `rmd`.

It would be much easier if we factor the rmd code chunk detection methods so that multiple places (hover, completion, code lens, run chunk commands) could share the data.

**Comment by renkun-ken** [comment]
@roaldarbol Would you like to try the [build](https://github.com/REditorSupport/vscode-R/suites/3755719482/artifacts/92226456) from #787 and see if works for you?
