### ISSUE TITLE
Use tab size etc. in `.Rproj` file

### ISSUE THREAD

**Issue by eitsupi** [REditorSupport/vscode-R#763]
It's useful to be able to use the settings in the `.Rproj` file within VSCode like we can use the settings we set in `.editorconfig` file with [editorconfig-vscode](https://github.com/editorconfig/editorconfig-vscode).

**Comment by ElianHugh** [comment]
Adding to this, I think it would be useful if .Rproj files could be used for setting workspace root, and further, if opening a .Rproj file would be synonymous with opening the folder.

I'm not sure if the latter is possible, but it would be neat!

**Comment by ElianHugh** [comment]
I think this is a good first issue, and (from my understanding) would likely require the following steps:

1. See if a .Rproj file exists at the workspace root
2. Read .Rproj lines in via `utils.readContent`, then parse lines as key:value pairs

The third step is potentially a little tricky and could be done in a couple ways:

- Apply changes when a new text document is opened (like how .editorconfig does it, but much more difficult)
- Write the parsed settings to the workspace settings.json file via the `update` method supplied by obtaining the configuration file, e.g.:
```ts
workspaceSettings = vscode.workspace.getConfiguration(
'settings', 
vscode.workspace.workspaceFolders[0].uri
);
workspaceSettings.update().....
```


Not all .Rproj settings are relevant to VSCode, but I think those with direct correlates should be straightforward to implement. A more complicated implementation would
