### ISSUE TITLE
Flextable not showing in viewer with v. 2.2.0

### ISSUE THREAD

**Issue by nsandau** [REditorSupport/vscode-R#770]
First of all, thank you so much for this excellent extension! 

I think I might have discovered a regression when using the flextable package with vscode-R v 2.2.0.

**Describe the bug**
I use the flextable package for outputting tables in rmd documents. 
With previous versions of vscode-R when printing the flextable object the viewer would show the table.
However, with version v. 2.2.0 the viewer just shows a blank canvas. 
When rolling back to 2.1.0 it works as expected. 
I have tried printing a table with the gtsummary package and it still works with 2.2.0.  

**To Reproduce**

flextable shows up blank in viewer:
`
flextable::flextable(as.data.frame(letters))
`

gtsummary table still works: 
`
gtsummary::tbl_summary(as.data.frame(letters[1:5]))
`

but when converting to flextable it shows up blank again:
`
gtsummary::as_flex_table(gtsummary::tbl_summary(as.data.frame(letters[1:5])))
`

## Do you want to fix by self? (We hope your help!)

Want to? Yes. Able to? Sadly no. 

**Expected behavior**
Flextable tables showing in viewer as in previous versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/12936029/131966351-eec31982-0f13-4456-8f64-c821772b43d0.png)

**Environment (please complete the following information):**

- OS: pop_os 21.04
- VSCode Version: 1.60.0
- R Version: 4.1.1
- vscode-R version: 2.2.2

**Comment by renkun-ken** [comment]
Thanks for reporting! I could reproduce the problem.

Looks like the content security policy is too strict for `flextable` to work. Relaxing it to `script-src https: data: filesystem: 'unsafe-inline'` seem to work.

**Comment by renkun-ken** [comment]
Please try installing the [test build](https://github.com/REditorSupport/vscode-R/suites/3673725738/artifacts/89390115) from <https://github.com/REditorSupport/vscode-R/pull/771/checks?check_run_id=3504364184> and see if it works for you.

**Comment by nsandau** [comment]
Thanks for the quick response. Installed the test build and flextable now shows in the viewer again. Thanks!
