### ISSUE TITLE
plot.gstatVariogram function not working

### ISSUE THREAD

**Issue by woidfeeee** [REditorSupport/vscode-R#772]
When I'm running the following R code in RStudio I get suitable results/plots:

```
# Load Libraries
library(maptools)
library(spatstat)
library(gstat)
library(rgdal)

# Define File Paths
path_data <- file.path(getwd(), "Data")
path_export <- file.path(getwd(), "Export")

# Read Data
file_oil <- file.path(path_data, "OilCont.shp")
points_oil <- readOGR(file_oil)

# Variograms
kwges_vgm <- variogram(log_Kwges~1, data = points_oil)
plot(kwges_vgm)

estimated_model <- vgm(1, "Sph", 80, 0.1)
plot(kwges_vgm, model = estimated_model)
```

But when I run the same code in VSCode with the R extension I get no output for the first `plot()` (without error message) and the following error message for the second `plot()`:

```
2: In plot.window(...) : "model" is no graphic parameter
3: In plot.xy(xy, type, ...) : "model" ist kein Grafikparameter
4: In axis(side = side, at = at, labels = labels, ...) :
  "model" ist kein Grafikparameter
5: In axis(side = side, at = at, labels = labels, ...) :
  "model" ist kein Grafikparameter
6: In box(...) : "model" ist kein Grafikparameter
7: In title(...) : "model" ist kein Grafikparameter
```

_it's in german so I translated the first line in english_

It seems like the **plot.gstatVariogram()** is not working properly in VSCode. I'm running VSCode with the R extension and all the suggested optional extensions.

Does anyone have the same issue or a solution for this?

**Comment by renkun-ken** [comment]
Could you provide a minimal reproducible example which only relies on publicly available data?

**Comment by renkun-ken** [comment]
Are you using httpgd plot viewer in R? You could take a look at `dev.cur()` and see what device you are using when the plot goes wrong.

**Comment by woidfeeee** [comment]
Yes, I'm using httpgd but also tried it already without. 

Here is the dataset I used in my code [OilCont.zip](https://github.com/REditorSupport/vscode-R/files/7105707/OilCont.zip). It's a small file with around 60 point shapes.

**Comment by ElianHugh** [comment]
I cannot replicate this with the supplied data, two plots show up successfully for me:

![image](https://user-images.githubusercontent.com/60372411/132013757-4260e4e4-82fd-4b58-869d-6da016ccfb89.png)

**Comment by woidfeeee** [comment]
Ok, now I got a solution for me: when I'm running the code in single lines (Ctrl + Enter) instead of Run Source (Ctrl + Shift + S) the plots are generated properly.
