### ISSUE TITLE
Inf is unable to be displayed in the vscode-r table window

### ISSUE THREAD

**Issue by mynanshan** [REditorSupport/vscode-R#776]
If you have a R dataframe `dat` in vscode-r, you can display the dataframe in an pop-up/separated window by typing `View(dat)`. However, I found that the table window is unable to display the infinity `Inf` normally.

![Figure 1. Inf not shown in displayed table](https://user-images.githubusercontent.com/80438694/132274342-aa94b785-ada1-440b-8739-4153c862f411.png)

![Figure 2. We can see the Inf in the terminal outputs](https://user-images.githubusercontent.com/80438694/132274381-7347a1f2-22a5-42ba-9899-a9b528e8fc1b.png)

**Environment:**

- OS: Windows 10 x64
- VSCode Version: 1.60.0
- R Version: 4.1.0
- vscode-R version: 2.2.0

**Comment by renkun-ken** [comment]
Thanks for reporting. It is caused by that we transform the data into JSON representation which does not support NaN, Inf. Let me see if we have a good walk around for this.
