### ISSUE TITLE
Document usage of `rmarkdown` and `pandoc` for prettier symbol documentation

### ISSUE THREAD

**Issue by mihaiconstantin** [REditorSupport/vscode-R#777]
**Is your feature request related to a problem? Please describe.**
Documentation improvement.

**Describe the solution you'd like**
Document the use of `languageserver` with `rmarkdown` and `pandoc` for prettier symbol documentation, as indicated by @ManuelHentschel in https://github.com/REditorSupport/vscode-R/issues/775#issuecomment-914263106.

**Comment by renkun-ken** [comment]
I'd like to enrich the content of the [R language service](https://github.com/REditorSupport/vscode-R/wiki/R-Language-Service) wiki page so that user could know more about the language service features.
