### ISSUE TITLE
Cross-reference does not work in preview when specify output as `bookdown::html_document2`

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#779]
Cross-referencing for images or tables via `\@ref(tab:xxx)` looks like working only under, say,  `bookdown::html_document2`. 
However, previewing the output by clicking "Open Preview to the Site" does not render cross-reference properly. 

For example:
```
---
title: "R Notebook"
output:
  bookdown::html_document2: default
---
{r table1}
knitr::kable(mtcars[1:5, 1:5], caption = "The mtcars data.")

`mtcar` data is shown in Table \@ref(tab:table1).

```
The vscode-R preview results in 
![image](https://user-images.githubusercontent.com/4111978/132522155-3907ba73-1bae-4989-bf4a-66633424d2a8.png)

The correct one with `rmarkdown::render` or `Ctrl + Shift + K` results in
![image](https://user-images.githubusercontent.com/4111978/132522645-fbdae440-5853-40c9-b988-770114dda340.png)

The current keybinding to open preview is `Ctrl + Shift + V`, is it possible to change it to render and open the preview with `Ctrl + Shift + K`, just like in RStudio?

**Comment by ElianHugh** [comment]
This is most likely because we ignore output specifications when previewing, as we require the guarantee of an html output

**Comment by Fred-Wu** [comment]
Thanks for the explanation. A work around for me now is to use newly published `Live Preview` extension for HTML by Microsoft. So that, I can generate `bookdown::html_document2` with correct cross-referencing and launch HTML preview. Once it is launched,  refresh for new contents would be shown in the preview just by Knitting again.
