### ISSUE TITLE
Consider storing background-process R commands in files

### ISSUE THREAD

**Issue by ElianHugh** [REditorSupport/vscode-R#781]
Many of VSCode-R's features use a background R process to perform tasks (e.g., help providers, previewing and knitting documents). We currently define the calls to R in-line, e.g.

```ts
      const cmd = (
            `knitr::opts_knit[['set']](root.dir = ${knitWorkingDirText});` +
            `cat('${lim}', rmarkdown::render(` +
            `'${filePath.replace(/\\/g, '/')}',` +
            `output_format = rmarkdown::html_document(),` +
            `output_file = '${outputFile.replace(/\\/g, '/')}',` +
            `intermediates_dir = '${tmpDir().replace(/\\/g, '/')}'), '${lim}',` +
            `sep='')`
        );
```

I think that long-term this could get hard to maintain. Also, it can be difficult to wrap your head around all the quoting!

**Describe the solution you'd like**

I think that it might be neater and easier to maintain if we instead stuck these calls in their own R files, and then sourced them. For instance:

```ts
cp.spawn(`R -f test.R`) 
```

We can use the [`commandArgs`](https://rdrr.io/r/base/commandArgs.html) method to pass values to a given file. E.g.

```r
# test.r
print(commandArgs(trailingOnly = TRUE))
```

```bash
R --silent --slave --no-save -f test.r --args "arg1" "arg2" "arg3"
#> [1] "arg1" "arg2" "arg3"
```

**Comment by renkun-ken** [comment]
That's true. If we want more simplicity and don't need to show up the arguments in the command line, we could even use environment variables to pass arguments into the scripts.
