### ISSUE TITLE
Syntax highlighting consistency

### ISSUE THREAD

**Issue by wkeahi** [REditorSupport/vscode-R#788]
**Is your feature request related to a problem? Please describe.**
I'm filing this as a feature request as it seems to be an issue with vanilla VS Code. However, I think vscode-R does some syntax highlighting improvements and I hope this can be added. **Request**: Make the syntax highlighting rules more consistent.

**Describe the solution you'd like**
All function calls should look the same, object references should look the same.

**Describe alternatives you've considered**
Perhaps this is more an issue with the particular theme. I'm not too sure the contributions between VS Code + vscode-R + theme. I've tried editing `editor.tokenColorCustomizations` with no success.

**Additional context**
VS Code using Monokai theme below (other themes have same issue including Abyss, Solarized Light). Note that the `mutate` function and `my_function` are not blue. `x,y,z` are styled differently depending on the surrounding punctuation, etc.
<img width="366" alt="Screen Shot 2021-09-14 at 1 29 58 PM" src="https://user-images.githubusercontent.com/27479446/133329701-56dc6b55-9286-4200-a936-ced0213a3c66.png">

Compare this with the same code in Sublime below for desired feature.
<img width="332" alt="Screen Shot 2021-09-14 at 1 30 03 PM" src="https://user-images.githubusercontent.com/27479446/133329697-c1075942-e03e-4220-8b80-5962885b4d1a.png">

**Comment by renkun-ken** [comment]
Thanks for reporting this issue! I observe this too. Looks like the syntax file needs some tuning for this.

**Comment by ElianHugh** [comment]
I have this issue as well. It might be worth taking a closer look at vscode-R's syntax definitions in general, as there are outstanding syntax issues (e.g. raw vectors)

---

It also might be worth looking into unit tests for syntax highlighting, as there appears to be edge cases that pop up unexpectedly when altering the syntax. I saw some libraries for this in passing, will update if I see them again.

**Comment by hongooi73** [comment]
Yep, same issue with the Github Light theme here.

**Comment by wkeahi** [comment]
Thanks! This seems to fix the variables/function parameters but the function calls are still highlighted like text/variables. However, I think this is the specific theme as the tokens appear okay (please confirm as this isn't my forte).

<img width="360" alt="Screen Shot 2022-01-21 at 3 17 08 PM" src="https://user-images.githubusercontent.com/27479446/150612130-2a970ffd-3de6-4a26-9321-7bc57be9b22d.png">

I add the following code to `settings.json` for the Monokai theme to achieve the result below.

```
    "editor.tokenColorCustomizations": {
        "[Monokai]": {
            "textMateRules": [
                {
                    "scope": [
                        "variable.function.r",
                    ],
                    "settings": {
                        "foreground": "#66D9EF",
                    }
                },
            ],
        }
    }
```

<img width="378" alt="Screen Shot 2022-01-21 at 3 15 09 PM" src="https://user-images.githubusercontent.com/27479446/150612037-25287f06-3e76-40c8-bb26-90e23ef367cb.png">

**Comment by renkun-ken** [comment]
@wkeahi Yes, the color is indeed theme-specific. If you use other themes, it is more likely that different colors are assigned to variables and function calls.

**Comment by JacobBumgarner** [comment]
@renkun-ken Would you mind sharing the theme that you use? I haven't been able to find this info.

Thanks!

**Comment by renkun-ken** [comment]
I'm using [GitHub Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme).
