### ISSUE TITLE
Enable Format R code in Rmd

### ISSUE THREAD

**Issue by taooceros** [REditorSupport/vscode-R#789]
**Describe the solution you'd like**
Recognize the part of R code in Rmd, and format them when formatting the Rmd file.

**Additional context**
It is currently not quite possible to format the R code in the Rmd file with the extension, which I think is quite reasonable to have one.

**Comment by renkun-ken** [comment]
Format R chunks in rmd is supported.

Could you provide an example where you find formatting not working properly?

**Comment by taooceros** [comment]
Hm it seems work fine now. Not sure what's causing it not working before. Thanks for responding.
