### ISSUE TITLE
Can't run r code from Rscripts

### ISSUE THREAD

**Issue by ChaoXu1997** [REditorSupport/vscode-R#790]
**Describe the bug**
I can't run r code from Rscripts. 
such as I run this code `print(1:10)` , and it doesn't work in the terminal
![image](https://user-images.githubusercontent.com/72029457/133880508-f32ab3be-105a-468d-af04-8e571e305e7c.png)
It seems to fail to activate ` R: create r terminal`
but how I can fix this

```json
// R path for Linux
"r.rterm.linux": "/home/xuchao/.local/bin/radian",



// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": true,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher
"r.sessionWatcher": true,


```

**Environment (please complete the following information):**

- OS: [e.g. Windows, macOS, Linux]
- VSCode Version: [ 1.61.0]
- R Version: [4.0.1]
- vscode-R version: [2.2.0]

**Comment by andycraig** [comment]
Hi @ChaoXu1997, try changing this setting

```json
"r.alwaysUseActiveTerminal": true,
```

to

```json
"r.alwaysUseActiveTerminal": false,
```

When that setting is `true`, it won't start the R session for you.

**Comment by renkun-ken** [comment]
As @andycraig pointed out, `"r.alwaysUseActiveTerminal": true` won't start an R session for you. It is only useful if you always start R by yourself (e.g. in a tmux/screen window).

**Comment by ChaoXu1997** [comment]
Thanks, it works.
