### ISSUE TITLE
Background knit process doesn't work for second instance

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#797]
## Issues

When current background knit processor is active (e.g., xaringan::inf_mr), the next custom knit doesn't work. It neither creates a new background instance nor kills the active one.

## Test File

`test.Rmd`:

````
---
output: html_document
knit: xaringan::inf_mr
# knit: pagedown::chrome_print
---

# Test

Para.
````

## Steps to Reproduce

1. Knit the `test.Rmd` with `xaringan::inf_mr` using the background process.

2. Re-knit `test.Rmd` with `pagedown::chrome_print`.

**Comment by ElianHugh** [comment]
This is related to #796. In particular, both issues occur because the knit process isn't set-up to handle non-file outputs or non-standard return values (e.g. returning an object rather than a path)

**Comment by ElianHugh** [comment]
unstale
