### ISSUE TITLE
cannot open table viewer for dataframe 

### ISSUE THREAD

**Issue by wangmengbo** [REditorSupport/vscode-R#798]
**Describe the bug**
After installation, I cannot view a data frame in a table tab with View().

**To Reproduce**
1. open my data frame from R workspace side bar or call ```View(my_data_frame)```
2. then the data frame file is always opened with a ```.txt``` postfix. (I guess it was opened as a text file)

## Do you want to fix by self? (We hope your help!)

Yes 

my r-related lines in setting.json

```json
"r.rterm.linux": "/home/wangmengbo/.pyenv/shims/radian",
"r.bracketedPaste": true,
```

**Expected behavior**
open a table-like viewer for my data frame

**Screenshots**
You can show the keybord contents by pressing `F1` and `Developer: toggle screencast mode`
![image](https://user-images.githubusercontent.com/23047431/134845719-d0088884-4d8f-4770-af49-28e03e508dce.png)

**Environment (please complete the following information):**

- OS: [WSL2]
- R Version: [4.1.1]
- vscode-R version: [2.3.0]

**Comment by renkun-ken** [comment]
Does `View(mtcars)` work?

Are you sure your object is a data.frame? You could check it with `is.data.frame(x)`. Looks like we check the object type, and it is neither `data.frame` nor `matrix` so it is treated as a `list`.

**Comment by wangmengbo** [comment]
> Does `View(mtcars)` work?

Yes it works. 
 
> Are you sure your object is a data.frame? You could check it with `is.data.frame(x)`. Looks like we check the object type, and it is neither `data.frame` nor `matrix` so it is treated as a `list`.

No. I'm sorry. The object is not a data frame. But can I view it like I in R studio? e.g.
![image](https://user-images.githubusercontent.com/23047431/134939948-0cdfbf37-65e1-496c-83ff-b50e24f7d06d.png)

**Comment by renkun-ken** [comment]
We don't support viewing list in the same way of RStudio at the moment. We could improve it somehow later.

**Comment by wangmengbo** [comment]
I see. Then I guess I'll move it to feature request. Thank you.
