### ISSUE TITLE
Run line using Ctrl + Enter and other R interactive commands don't work in Rmd files

### ISSUE THREAD

**Issue by bnicenboim** [REditorSupport/vscode-R#799]
**Describe the bug**
Run line and other R interactive commands don't work in Rmd files. Also hovering over a chunk doesn't produce "Run chunk" as in the example.

**To Reproduce**

1. Go inside an R chunk
2. Press Ctrl + Enter
3. I get a an empty line below the line of code.

**Some observations:**
- The weird thing is that if I do ctrl + shift + P. and I go to `>R: Run selection/line`, it does run the R code.
- Ctrl+Enter does work in files ending.R
- The files are detected as R Markdown

## Do you want to fix by self? (We hope your help!)

Maybe, I just started to use VS code, but if it's straightforward, I can try to fix it.

**Expected behavior**
Ctrl + Enter should run the line of code in an Rmd file (as it does it in an R file)

**Environment (please complete the following information):**

- OS: Linux, Ubuntu 20.04
- VSCode Version: 1.60.2
- R Version: 4.1.1
- vscode-R version: v2.3.0

**Comment by bnicenboim** [comment]
it was some clash with some other extension,I removed most of them, and now it works...

**Comment by andycraig** [comment]
Thanks for the update and glad to hear it's working properly now.
