### ISSUE TITLE
the operation of help pages in side bar ignore the vscode setting before I run a help command in R terminal

### ISSUE THREAD

**Issue by Yunuuuu** [REditorSupport/vscode-R#802]
Thanks for your all work in developing such good extension!

**Describe the bug**
I changed the  View column in vscode setting, and here is my setting.json concerned these setting:
```
    "r.session.viewers.viewColumn": {
        "plot": "Active",
        "helpPanel": "Active"
    }
```
when I opened a new vscode window and selected a R function (such as `options`), then I ran command `r.helpPanel.openForSelection` or click the command in the sidebar, the help page viewer didn't follow what I set in vscode. Only when I ran a help function in the R terminal, my setting in vscode could take effect.

**To Reproduce**

1. Change the R column view setting (`helpPanel`) to `"Active"`, if need , we can restart vscode,
2. Open a new vscode window and a editor
3. Input a R function in the editor and select it then Click `Open Help page for Seleccted Text` in sidebar.
5. Run `help` function with a random text (such as `help("options")`) in the R terminal then repeat 3, this time, the setting in vscode can function.

## Do you want to fix by self? (We hope your help!)

Yes, but I only learned R language. I guessed these may be caused by the delayed options read by vscode Command (`r.helpPanel.openForSelection`) until the `help` function in R terminal ? 

(If related)setting.json

```json
   "[r]": {
        "editor.rulers": [
            80 
        ],
        "editor.wordWrap": "bounded",
        "editor.wordSeparators": "`~!@#%$^&*()-=+[{]}\\|;:'\",<>/?",
        "rewrap.autoWrap.enabled": true,
        "rewrap.wrappingColumn": 80,
        "rewrap.doubleSentenceSpacing": true
    },
    "r.lsp.debug": true,
    "r.alwaysUseActiveTerminal": true,
    "r.bracketedPaste": true,
    "r.rterm.windows": "C:\\Users\\*****\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\radian.exe",
    "r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--r-binary=C:\\*****\\R\\R-4.1.1\\bin\\x64\\R.exe",
        "--local-history"
    ],
    "r.rpath.windows": "C:\\*****\\R\\R-4.1.1\\bin\\x64\\R.exe",
    "r.plot.useHttpgd": true,
    "r.session.levelOfObjectDetail": "Detailed",
    "r.session.objectLengthLimit": 100,
    "r.session.viewers.viewColumn": {
        "plot": "Active",
        "helpPanel": "Active"
    }
```

**Expected behavior**
All operation should follow the internal setting in vscode. 

**Environment (please complete the following information):**

- OS: Windows 19042.1237
- VSCode Version: 1.60.2
- R Version: 4.1.1
- vscode-R version: v2.3.0

**Comment by renkun-ken** [comment]
Thanks for reporting! I could reproduce this. Looks like the setting `r.session.viewers.viewColumn.helpPanel` is not used at all. 

Let me do a quick fix.

**Comment by Yunuuuu** [comment]
Thanks for your prompt reply and fixes! Especial appreciation for your blog which introduced the vscode-r and help me a lot in regulating the settings.
