### ISSUE TITLE
[Feature request] Don't close preview tab when failed to knit  `rmd` file

### ISSUE THREAD

**Issue by sukanka** [REditorSupport/vscode-R#806]
**Is your feature request related to a problem? Please describe.**

Rmarkdown preview tab crashes when fail to knit an rmd file.

I enable `R › Rmarkdown › Preview: Auto Refresh`. When I edit an `main.rmd` , which reads
```
---
output:
  pdf_document:
    latex_engine: xelatex
---

    ```{r}
    rnorm(5)
    rnorm(40)
    ```
```
It worked fine in general.
But if  I was too slow to type the second command, I just typed `rnorm(`, the preview tab would crash, and say
```
Quitting from lines 8-10 (main.rmd) 
Error in parse(text = x, srcfile = src) : 
  <text>:3:0: unexpected end of input
1: rnorm(5)
2: rnorm(
  ^
Calls: cat ... <Anonymous> -> parse_all -> parse_all.character -> parse
```

**Describe the solution you'd like**

It is better to  keep the previous preview and wait for next auto refresh. Anyway, it maybe better to keep that window open.

Or add an option, `R › Rmarkdown › Preview: Refresh On Save`, only refresh when the file is (manually) saved.

**Comment by ElianHugh** [comment]
Just to be clear, is the refresh triggering without you saving the file?

**Comment by sukanka** [comment]
No, I notice that I enabled `auto save` with a 1000ms delay. After I turned it off, when I didn't save manually,  the preview tab would not refresh, thus would not crash either.
