### ISSUE TITLE
`r.session.objectLengthLimit` seems not working well

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#811]
The delay after calling other objects in the terminal is still significant even setting `r.session.objectLengthLimit` to 100. 
As long as the workspace can show the information from `str()` for a `data.frame`, the issue is still there. 

Although I have not checked for the setting smaller than 100, the only time the issue is gone after loading 9 years data (reported in #174)  was to set `objectLengthLimit` to 0 or 1. This time, `str()` information won't appear at all.

**Comment by renkun-ken** [comment]
Could you provide a reproducible example?

It looks like calling `str()` on your object might have significant overhead. Could you run

```r
system.time(str(ED))
```

and see if the timing is significant?

**Comment by Fred-Wu** [comment]
Thanks for the investigation. I did set `r.session.levelOfObjectDetail` to `Minimal`.
I will be waiting for the next update then.

**Comment by renkun-ken** [comment]
You might want to try the [build](https://github.com/REditorSupport/vscode-R/suites/4010861100/artifacts/101258832) of #815. Using `"r.session.levelOfObjectDetail": "Normal"` should be a better option.

**Comment by renkun-ken** [comment]
Thanks for the testing of `max.level = 1` which still has notable overhead in your case. Would you like to paste the output of `str(ED, max.level = 1)` so that I could make an example that is more similar with your data?

**Comment by renkun-ken** [comment]
A setting of `r.session.objectTimeout` is added (default 50ms) so that each call of `capture.output(str(obj, max.level=))` takes at most 50ms or otherwise it will fallback to `max.level=0` which takes minimal time.

Would you like to try the latest build of the #815?

**Comment by renkun-ken** [comment]
It requires a two-way communication between vscode-R and user R session. And the click is only responsive when R is not busy. Currently we only rely on a mostly one-way communication approach.

**Comment by Fred-Wu** [comment]
What about disabling the hover for data.frame, just showing in the workspace? 
Will it make a difference?
