### ISSUE TITLE
`browseURL()` doesn't work with `file://` URLs

### ISSUE THREAD

**Issue by cmrnp** [REditorSupport/vscode-R#812]
The vscode-R hook for `browseURL()` doesn't work with `file://` URLs. Instead it prints the error message: `File not exists`.

**To Reproduce:**

Run the code below in an R terminal with the *R: Session Watcher* option enabled in vscode-R:

```r
# create a temporary local HTML file to test with
test_file <- file.path(tempdir(), "bug_test.html")
cat("<h1>test file</h1>\n", file = test_file)

# doesn't work in vscode-R; does work in plain R or RStudio
browseURL(paste0("file://", test_file))

# works if the built-in R browseURL() implementation is used
options(browser = NULL)
browseURL(paste0("file://", test_file))
```

This was triggered in real life by trying to fit an RStan model in multi-core mode. See <https://github.com/stan-dev/rstan/blob/da2fc9c079534a82d3d26adda51ad17bf22f5e2b/rstan/rstan/R/stanmodel-class.R> line 642-643; they have some RStudio-specific logic too, but for now I'd be happy with vscode-R being compatible with the plain R behaviour.

**Do you want to fix by self? (We hope your help!)**

I could try to fix this if your time is limited, though I suspect it would take me longer than someone more familiar with the vscode-R code base.

**(If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)**

Looks like the error message is generated in `R/session/vsc.R` line 576.

**Expected behavior:**

When given a valid URL, `browseURL()` should open either an external web browser, or a VSCode web view. The latter is probably preferred for `file://` URLs, unless there's some VSCode limitation I'm not aware of.

I would argue that `browseURL()` calling `stop()` is always a bug; the built-in implementation fails silently when given an invalid URL.

**Environment:**

- OS: Windows 10
- VSCode Version: 1.6.1
- R Version: 4.1.1
- vscode-R version: 2.3.7

**Comment by cmrnp** [comment]
That would be an easy fix, except the code that's adding the `file://` is not mine - it's in a commonly used R package, and this works everywhere except with vscode-R.

Moreover, the documentation for `utils::browseURL()` says "Some platforms also accept file paths." while explicitly listing `http://`, `https://`, `ftp://` and `file://` URL schemes as being supported (depending on browser and OS). There is even an example provided in the help with a `file://` URL.

**Comment by renkun-ken** [comment]
Would you like the try the [build](https://github.com/REditorSupport/vscode-R/suites/4011011341/artifacts/101263787) from #817 and see if it works for you?
