### ISSUE TITLE
[Feature Request] support for conda

### ISSUE THREAD

**Issue by TTTPOB** [REditorSupport/vscode-R#826]
**Is your feature request related to a problem? Please describe.**

if i am using a conda managed R, some shared libraries may rely on the conda env to be activated. but when i hit ctrl + enter in r file or select R: Create New R Terminal from command palette, it wont auto activate conda environment, or to say, vscode-r dont have a proper conda environment support like vscode-python.
if i write my R path and radian path in config file, and the specified R are managed by conda, it ends up like
![image](https://user-images.githubusercontent.com/19909103/138021807-9d8dd335-ba8b-4e3f-bedf-90afb23b4ac3.png)

**Describe the solution you'd like**

scan user conda environments and let user choose which R binary to use, and auto activate the env/if the binary is not a conda R installation, do nothing

**Describe alternatives you've considered**

allow user to add an alternative console start up script

**Comment by renkun-ken** [comment]
This might be helpful: https://github.com/REditorSupport/vscode-R/issues/723#issuecomment-837942021.

**Comment by TTTPOB** [comment]
> This might be helpful: [#723 (comment)](https://github.com/REditorSupport/vscode-R/issues/723#issuecomment-837942021).

I want to know where this extension get environment variable from, because I am using nix to manage my envrionment now, I can confirm that the vscode session has been configure to find the right `$PATH` 
![image](https://user-images.githubusercontent.com/19909103/138325682-b41ab4ab-1cf1-4889-81d4-98b717a9b585.png)
but this extension still find R in original system path, and do not respect my nix environment.

I want to know what causes this and maybe I can have a look at it.

**Comment by TTTPOB** [comment]
update:
after R was launched(even the wrong, original R), `Sys.getenv("PATH")` shows right path, but `Sys.getenv("R_LIBS_USER")` shows `~/R/.../libs` (which was wrong)
