### ISSUE TITLE
[Question] Where does this extension gets Environment Variable from?

### ISSUE THREAD

**Issue by TTTPOB** [REditorSupport/vscode-R#831]
recently i tried to use anaconda and nix to manage my workflow, so I have some findings below:
Information:
1. I have:
    - system installed R 3.5.1 in `/usr/local/bin/R`
    - system installed R 4.1.1 in `/opt/R/4.1.1/bin/R` linked to `~/.local/bin/R`
    - anaconda installed R 4.1.0 in `~/anaconda/bin/R` (real location `~/anaconda/lib/R/bin/exec/R`)
    - nix installed R 4.1.1 in `/nix/store/xxxxx-R-xxx/bin/R`
 2. when not activating any nix/anaconda environment, my `$PATH` looks like
 ```
/home/xxxx/anaconda/condabin
/home/xxxx/.autojump/bin
/home/xxxx/bin
/home/xxxx/.cargo/bin
/home/xxxx/.local/bin
/home/xxxx/.local/bin/ucsc
/home/xxxx/.nvm/versions/node/v14.15.2/bin
/home/xxxx/perl5/bin
/usr/bin
/usr/lib64/qt-3.3/bin
/usr/local/bin
/usr/local/sbin
/usr/sbin
```
3. If I don't override the option `rterm.linux`, despite whether I activated any environment via nix/anaconda or not, R language server uses R from anaconda, this is extremely strange because I prevented anaconda auto activation in `~/.{bash,zsh}rc`, `Create R Terminal` from vscode command palette also uses this R.
4. there is a [plugin](https://marketplace.visualstudio.com/items?itemName=arrterian.nix-env-selector) that can relaunch vscode in a nix environment specified, if I used that, I can see whether the main process and the extension host of vscode reads environment variable of that nix environment
5. in this circumstances, `Create R terminal` and languageserver still launches from the anaconda R.
6. evaluate `Sys.getenv("PATH")` in the created r terminal as discribed above will show the desired, nix included `$PATH`
7. I dont have may knowledge of {java,type}script but I think this snippet from `repo/src/utils.ts` should return the firse R present in system `PATH`:
```typescript
function getRfromEnvPath(platform: string) {
    let splitChar = ':';
    let fileExtension = '';

    if (platform === 'win32') {
        splitChar = ';';
        fileExtension = '.exe';
    }

    const os_paths: string[] | string = process.env.PATH.split(splitChar);
    for (const os_path of os_paths) {
        const os_r_path: string = path.join(os_path, 'R' + fileExtension);
        if (fs.existsSync(os_r_path)) {
            return os_r_path;
        }
    }
    return '';
}
```
8. but apparently it didn't, so, where this plugin get environment variable from, will it open a login shell before launches the language server/creates the r terminal, and where did the anaconda R come from if I have never activated the environment?

**Comment by l-d-s** [comment]
@TTTPOB Is this workaround still the best solution here?
