### ISSUE TITLE
[Feature request] R Markdown: Choose templates

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#839]
It would be so great if we had an interactive command showing all the available Rmd skeleton templates that users can choose from.

Currently, RStudio IDE has this feature. As you know, all the Rmd templates path has the following structure:

`[pkg_name]/rmarkdown/templates/`

**Comment by renkun-ken** [comment]
We could scan the user library about existing templates by looking at each package folder and see if `{package}/rmarkdown/templates` folder exists. If so, read all `{package}/rmarkdown/templates/*/template.yaml` to get all templates from installed packages.
