### ISSUE TITLE
R workspace is not working.

### ISSUE THREAD

**Issue by qlife1146** [REditorSupport/vscode-R#840]
I know that workspace is a window where you can see RStudio's Environment. the screenshot in the [workspace Viewer description](https://github.com/REditorSupport/vscode-R/wiki/Sidebar-user-interface#workspace-viewer), I also saw that the variable I entered was in the workspace. However, it keeps saying 'Rworkspace is empty.' Is there anything I need to check?

**Comment by qlife1146** [comment]
> Does the vscode-R attach to any R session and the status bar item shows the pid like "R: 12345"?
> 
> In you R session, you might print and see if the session watcher is correctly inited?`ls.str(.vsc)`

Oh, I solved it thanks to your solution. thank you so much.

**Comment by qlife1146** [comment]
> Does the vscode-R attach to any R session and the status bar item shows the pid like "R: 12345"?
> 
> In you R session, you might print `ls.str(.vsc)` and see if the session watcher is correctly inited?

I'm sorry. I solved it before, but it's the same situation again. The code you gave me doesn't work.
`Error in ls.str(.vsc) : object '.vsc' not found`

**Comment by renkun-ken** [comment]
How do you start your R session? Does it work when you execute command "R: Create R terminal"?

**Comment by qlife1146** [comment]
> How do you start your R session? Does it work when you execute command "R: Create R terminal"?

Oh, that question was to be asked in a different development environment, but I gave up the development environment. I'm sorry.
