### ISSUE TITLE
The link to knit output path not easy to open

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#858]
Knitting any rmd document will result in showing a link to the file surrounded by vsc delim `---vsc---`, making the link not easy to open.

```

Output created: _book/test.html

---vsc---/Users/ken/Workspaces/test/rbook/_book/test.html---vsc---
[VSC-R] main.Rmd process exited with exit code 0
```

<img width="590" alt="image" src="https://user-images.githubusercontent.com/4662568/140237249-d5d3f47b-2f4c-446e-b043-c19df6560e9d.png">

Follow link will try to open the incorrect path:

```
/Users/ken/Workspaces/test/rbook/_book/test.html---vsc---
```

**Comment by ElianHugh** [comment]
A related issue is where the output ends up as:

```
---vsc---
/Users/ken/Workspaces/test/rbook/_book/test.html
---vsc---
```

causing the progress bar to never close. Might need to rethink how to display this for both cases.
