### ISSUE TITLE
Rmarkdown Background Process Failure

### ISSUE THREAD

**Issue by AndrewCSQ** [REditorSupport/vscode-R#860]
System: Fedora 35 (but also failed with Fedora 34)

What happens: Knitting a file in the current R terminal (radian) works fine. When I try to use the extension to preview the resulting file (or if I use the background process i.e., _smart knitting_) to knit my rmarkdown file, I instead get the following error

```
Error in cat(lim, eval(parse(text = knit_command)), lim, sep = "") : 
  object 'lim' not found
```

Which I deduce from ` vscode-R/R/rmarkdown/knit.R` has to do with the line

```
lim <- Sys.getenv("VSCR_LIM")
```

The same also occurs with a "fresh" install of VSCode (deleting all config / extensions, loading the vscode-R extension only). Maybe some explanation of the logic in the `knit.R` file can assist in debugging.

EDIT: The extension was previously working fine for me. Possibly [this recent PR #784](https://github.com/REditorSupport/vscode-R/pull/784) broke functionality for me. Confirmed that reverting to extension version 2.2.0 fixed this functionality regression for me.

**Comment by ElianHugh** [comment]
That PR shouldn't have affected the knitting delimiter, so my gut feeling is that it may have been a coincidence. Are you still running into this issue?

**Comment by AndrewCSQ** [comment]
Hi Elian, thank you for responding to my issue. My bisect could be wrong, but I have just confirmed that I am still running into this issue with the latest version 2.3.2, and that downgrading to 2.2.0 restores previous functionality.

**Comment by ElianHugh** [comment]
No worries! Hmm, it's very weird given that 'VSCR_LIM' is explicitly set prior to launching the knitting process. Just to be clear, when using the knit button, are you using the background knit functionality, or is it sending a knit command to the R terminal? IIRC, background knitting wasn't added until 2.3.0

**Comment by AndrewCSQ** [comment]
Bug is only encountered when using the background knit functionality. Unfortunately, the "Preview Rmd" function seems to ignore the setting (i.e., bug is encountered when trying to preview the Rmd regardless of whether the "use background process" box is checked in the settings).

One possible fix (which sidesteps the breakage of the background knit, but I don't really care for it personally) is to make the preview Rmd function respect that setting.

**Comment by ElianHugh** [comment]
Right - the preview button ignores the setting as it is intended for the knit button (currently, it is isn't possible to preview documents knit in the R Terminal). The intended behaviour is that if the user wants to opt out of smart knitting/revert to older behaviour, they can toggle that setting. 

The main issue is figuring out why the knit variables aren't being set appropriately, causing the preview to crash.

**Comment by AndrewCSQ** [comment]
Sorry I wasn't able to look at this again. Is there anything else I can do to help figure out why the knit variables aren't being set appropriately? Am not familiar with how to write VSCode extensions, but happy to provide any logs that are needed (properly anonymized).

**Comment by ElianHugh** [comment]
No worries at all! There are 2 places with useful error information - the R Markdown output stream (which you've sent some of), and the developer console. 

Developer tools can be accessed by the default shortcut `Ctrl+Shift+I` or the 'Toggle Developer Tools' command in the command palette. If there are any errors in the console there, they may be useful!


------

As an aside, here is some background on the knit process if it is at all helpful.

Environment values are set in knit.ts:

```ts
const lim = '<<<vsc>>>';		
const re = new RegExp(`.*${lim}(.*)${lim}.*`, 'gms');		
const scriptValues = {			
'VSCR_KNIT_DIR': knitWorkingDirText,			
'VSCR_LIM': lim,			
'VSCR_KNIT_COMMAND': knitCommand		
};
```

These are passed to the knit process during its creation in rmarkdown/manager.ts:

```ts
const processOptions: cp.SpawnOptions = {					env: {						
...process.env,						
...scriptArgs					
},					
cwd: args.workingDirectory,				
};
```

Which is then accessed via Sys.getenv(...) in R.

**Comment by Albatrosses-reply** [comment]
HI, i had a similar issue.

`Error in cat(lim, rmarkdown::render(file_path, output_format = set_html,  : 
  object 'lim' not found`

Likewise, when I downgraded to 2.2.0, it worked normally. Will it be able to be fixed through an upgrade in the future?

**Comment by ElianHugh** [comment]
> HI, i had a similar issue.
> 
> `Error in cat(lim, rmarkdown::render(file_path, output_format = set_html,  : 
>   object 'lim' not found`
> 
> Likewise, when I downgraded to 2.2.0, it worked normally. Will it be able to be fixed through an upgrade in the future?

Hi there! Could you please post your developer tools logs? Developer tools can be accessed by the default shortcut Ctrl+Shift+I or the 'Toggle Developer Tools' command in the command palette.

**Comment by AndrewCSQ** [comment]
Hi Elian, thanks for engaging us on this. The 2.2.0 workaround is going to fail for me because I'm shifting towards Quarto (which requires the latest version of this extension) but still have some `.Rmd` files for historical purposes. I haven't been able to get the developer logs to properly show, but I have identified the issue.

A common practice in scripts is to clear the environment using `rm(list = ls())` and it is the inclusion of this line at the start of my `.Rmd` scripts that creates the issue. Removing it solves the problem. One solution is simply not to clear the environment (or maybe I can detect when the extension is calling the script and only trigger the cleanup if the extension is not the one calling the script) - but I think this is a fairly common use-case (to clear the environment to ensure reproducibility).

Hopefully this will help the team triage the issue and decide whether to fix it. A simple "hello world" Rmd with the `rm(list = ls())` command will trigger the error. I can completely understand if the issue is marked WONTFIX (though that would be unfortunate).

**Comment by ElianHugh** [comment]
Hi Andrew,

Thanks for the information -- super useful! If rm is the issue, I think this is relatively straight forward to implement. Looks like we need to hide away the rmarkdown variables in a new environment so it isn't touched by `rm`

**Comment by ElianHugh** [comment]
Hi again @AndrewCSQ  and @Albatrosses-reply, the latest push to the repo should have fixed this issue. If you find you still run into it, please feel free to open!

**Comment by urmzd** [comment]
It took a little bit of searching to figure out how to install the correct version of R extension for vs-code.

It should also be noted that as of latest commit https://github.com/REditorSupport/vscode-R/commit/8f5f78172e4bade335a52778e0759fb319b46aaf, there exists a module interpolation issue that requires fixing prior to being able to install the extension.

The solution below does not have this problem and works for both the preview + knit feature.

```bash
git clone https://github.com/REditorSupport/vscode-R.git # or ssh alternatively
git checkout 3ed84833d4deffc381259757e85628aff8c878bd #1117 fix
# npm install -g yarn (if you don't have it already)
yarn install
vsce package
code --install-extension r-2.5.0.vsix
```
