### ISSUE TITLE
Ikuyadeu.r formatter is 

### ISSUE THREAD

**Issue by Yemoloh** [REditorSupport/vscode-R#862]
Hi, I've installed R on VScode, but when I try to format my code, I have this message :
"There is no formatter for 'r' files installed"
This is my settings.json

{
"tabnine.experimentalAutoImports": true,
"workbench.colorTheme": "Cobalt2",
"r.alwaysUseActiveTerminal": true,
"r.rpath.windows": "C:\Program Files\R\R-4.1.2\bin",
"r.rterm.windows": "C:\Program Files\R\R-4.1.2\bin\R.exe",
"files.associations": {
"*.rmd": "markdown"
},
"r.dependencyChecks": true,
"editor.formatOnPaste": true,
"editor.formatOnType": true,
"r.lsp.debug": true,
"[r]": {
"editor.defaultFormatter": "Ikuyadeu.r"
},
}

Does anybody had this issue before ?

Yemoloh

To Reproduce

1. Install languageserver
2. Install r.extension
3. Add : "[r]": {
"editor.defaultFormatter": "Ikuyadeu.r"
}, in settings.json
4. Open an r.file, type unformatted code and hit shift+alt+f

- OS: [Windows 10]
- VSCode Version: [1.62.0]
- R Version: [4.1.2]
- vscode-R version: [2.3.2]

**Comment by renkun-ken** [comment]
Looks like the R language client does not correctly start and thus not registered as a valid R formatter. Could you go to `Output -> R Language Server` and take a look at the log of language server. Does it start correctly?

**Comment by robokamran** [comment]
I have the same problem with pretty much the same configuration.
how should I go to `Output -> R Language Server` ??

**Comment by renkun-ken** [comment]
Go to the Output pane and choose "R Language Server" and view the log:

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/4662568/143675112-42e3730f-0f32-44f9-8a39-c97b05f6f9aa.png">

**Comment by robokamran** [comment]
Thank you for your quit reply.
Here is my screenshot, the code runs correctly, but when I hit `ALT+Shift+F` I get that error.
And the output looks like this:

![Screenshot 2021-11-27 191819](https://user-images.githubusercontent.com/8957516/143677254-f73c01cf-49bf-4d2e-a2d0-1a7833f843fe.jpg)

**Comment by renkun-ken** [comment]
Looks like the language server does not start at all.

@ManuelHentschel Does the value of `r.rpath.windows` looks correct?

**Comment by robokamran** [comment]
I can use `R.exe` address for `r.rpath.windows` with/without the double quotations, or even remove the whole `r.rpath.windows` entry. The result is the same. The install address of my R executable instance is correct though. Also I when I install `languageserver` this is the output:
```
> install.packages("languageserver")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.ism.ac.jp/bin/windows/contrib/4.1/languageserver_0.3.12.zip'
Content type 'application/zip' length 808148 bytes (789 KB)
downloaded 789 KB

package 'languageserver' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Kamran\AppData\Local\Temp\RtmpqmtkCP\downloaded_packages
>
```

**Comment by ManuelHentschel** [comment]
> @ManuelHentschel Does the value of `r.rpath.windows` looks correct?

With the quotes, I get the same error, removing the quotes fixes the error for me.

**Comment by robokamran** [comment]
I removed the quotes and did multiple restarts. Still, there was no success. But I did this once in my R terminal and it was fixed:
```
> library(languageserver)
> languageserver::run
function (debug = FALSE, host = "localhost", port = NULL)
{
    tools::Rd2txt_options(underline_titles = FALSE)
    tools::Rd2txt_options(itemBullet = "* ")
    lsp_settings$update_from_options()
    if (isTRUE(debug)) {
        lsp_settings$set("debug", TRUE)
        lsp_settings$set("log_file", NULL)
    }
    else if (is.character(debug)) {
        lsp_settings$set("debug", TRUE)
        lsp_settings$set("log_file", debug)
    }
    langserver <- LanguageServer$new(host, port)
    langserver$run()
}
<bytecode: 0x000000001da7bbc0>
<environment: namespace:languageserver>
>
```

**Comment by renkun-ken** [comment]
Would you like to confirm that you are using the following setting:

```
"r.rpath.windows": "C:\\Program Files\\R\\R-4.1.2\\bin\\x64\\R.exe"
```

but the language server still cannot start like

```
R Language Server (undefined) started
```

**Comment by robokamran** [comment]
Yes, it was like that. With the following setting:
`"r.rpath.windows": "C:\\Program Files\\R\\R-4.1.2\\bin\\x64\\R.exe"`
I also got this error:
`R Language Server (undefined) started`
But I ran these commands in my R terminal and the problem was fixed (I ran the commands only one time and it was fixed):
```
> library(languageserver)
> languageserver::run
```
My current config (which is working) is still like this:
`"r.rpath.windows": "C:\\Program Files\\R\\R-4.1.2\\bin\\x64\\R.exe"`

**Comment by yxb-cn** [comment]
I wonder if this problem is solved? I meet the same error.

**Comment by robokamran** [comment]
Yes, the issue was solved for me using the procedure I mentioned. However, I've not been using R for months. So I hope the same procedure still works with the newer updates.

**Comment by hhilbig** [comment]
In case someone has this issue: language server also did not start for me, as discussed earlier.  I got "R Language Server (-1) started". It turned out that `r.rpath.mac` was pointing to an older R version. I changed `r.rpath.mac` to the most recent R version, which fixed the issue.
