### ISSUE TITLE
After new VSCode update R extension does not work in combination with Remote - SSH anymore

### ISSUE THREAD

**Issue by jnnsbrr** [REditorSupport/vscode-R#865]
See also https://github.com/microsoft/vscode-remote-release/issues/5852

1. having the [Remote - SSH extension](https://github.com/microsoft/vscode-remote-release) installed
2. having the **R extension** installed
3. update VSCode to version 1.62.1

After the update of VSCode I could not use the R extension in combination with **Remote - SSH** anymore (on my local machine it does still work though). Somehow my `settings.json` file on the remote machine is overwritten by the entries of the local machine (I cannot reproduce the state of how it was set before the update)

A colleague on another machine ran into the same bug with basically the same setup. 

The following errors are thrown when starting an interactive R session in VSCode ...
`Failed to get list of R functions. Make sure that `jsonlite` is installed and r.rpath.linux points to a valid R executable.`  
`Command failed: undefined --silent --no-save --no-restore --slave -f "<path-to-extension>/ikuyadeu.r-2.3.2/R/help/getAliases.R" > "/tmp/vscode-R-aliases-GMTylO/aliases.json"
/bin/sh: undefined: command not found
`

I think that the problem also relies in the Remote - SSH extension (see link above) but I just wanted to make sure that this is also not a bug on your side since the problem was induced by the VSCode Update to 1.62.1

## Do you want to fix by self? (We hope your help!)

 No

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

Maybe check why the settings.json is overwritten with the values from the local machine. I think before the paths for the remote machine were set correctly.

**Expected behavior**
Also within the Remote - SSH connection, the R extension did and should work properly and should find the location of R. Or at least it did and did work as does locally on the remote machine.

**Environment (please complete the following information):**

VSCode Version: 1.62.1
Local OS Version: Windows 10
Remote OS Version: SUSE Linux Enterprise Server 12 SP3
Remote Extension/Connection Type: SSH
R Version: 3.6.3

**Comment by renkun-ken** [comment]
It should be fixed in [VS Code 1.62.2](https://github.com/microsoft/vscode/releases/tag/1.62.2).

**Comment by renkun-ken** [comment]
Feel free to reopen if the problem still persists. Closing.
