### ISSUE TITLE
Rmd preview fails if chunk-background setting is empty

### ISSUE THREAD

**Issue by ManuelHentschel** [REditorSupport/vscode-R#866]
With the setting `"r.rmarkdown.chunkBackgroundColor": ""`, the Rmd live preview fails in dark mode.

This can be solved by adding `const regOut = chunkCol.match(colReg) || [];` in [rmarkdown/preview.ts](https://github.com/ManuelHentschel/vscode-R/blob/b47e93b751896b743e269fd9a95189ae74af9f5e/src/rmarkdown/preview.ts#L89-L92), but then the code blocks are rendered with a white background and somewhat difficult to read.

**Comment by renkun-ken** [comment]
If `r.rmarkdown.chunkBackgroundColor` is empty, I think the `outCol` should fallback to an editor css style to match the theme.

**Comment by ManuelHentschel** [comment]
@ElianHugh since you wrote this component, do you have a specific fix in mind? Or should I just give it a shot myself?

**Comment by ElianHugh** [comment]
I think this should be relatively simple to fix/future-proof, so I should be able to get to it tonight unless you're eager!
