### ISSUE TITLE
Problem with R console on VS Code

### ISSUE THREAD

**Issue by trdunsworth** [REditorSupport/vscode-R#870]
I'm trying to use vscode-R on Visual Studio Code 1.62.2 (details from help below)
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

I tried to use the terminal to install the languageServer package. Currently, I don't get an error when opening an R file, but the terminal output is as follows. 

[chooseTerminal] A. There are 2 terminals: Terminal 0: pwsh Terminal 1: cmd B. There are 2 terminals: Terminal 0: pwsh Terminal 1: cmd C. There are 2 terminals: Terminal 0: pwsh Terminal 1: cmd

**Comment by ElianHugh** [comment]
Similar to #864, which *should* have been resolved with vscode 1.62.2.

**Comment by ElianHugh** [comment]
I've begun running into this too recently. For me, it seems to occur when the terminal state is 'restored'. E.g., opening a new workspace, and then reopening a previous one that had an R terminal running
