### ISSUE TITLE
`R Markdown: Open in External Browser` doesn't work in Remote Development

### ISSUE THREAD

**Issue by eitsupi** [REditorSupport/vscode-R#874]
**Describe the bug**

In Remote-Containers, selecting "Open in External Browser" from the RMarkdown preview menu does not work. (The OS will note that there is no app to open the vscode-remote link.)
This is in contrast to the httpgd plot, where the button with the same icon works fine.

**Expected behavior**

It would be great if it also worked when using the remote extension.
Or,  if this is technically difficult (perhaps currently just opening the temp file from a browser and not starting the server), it might be easier for users to understand if you put a warning that it will not work on remote extensions.

**Screenshots**

![image](https://user-images.githubusercontent.com/50911393/142731784-7feaad38-c86a-4a45-9a6e-b3c4aaeffa17.png)
![image](https://user-images.githubusercontent.com/50911393/142731852-45d958e0-e613-4258-baee-85a2afb842c8.png)

**Environment (please complete the following information):**

- OS: Windows Docker Desktop (WSL2 back end)
- VSCode Version: 1.62.3
- R Version: 
- vscode-R version: 4.1.2

**Comment by jooyoungseo** [comment]
Maybe duplicate of [#838](https://github.com/REditorSupport/vscode-R/issues/838).

**Comment by eitsupi** [comment]
@jooyoungseo I think this has nothing to do with that issue.

**Comment by ElianHugh** [comment]
The 'open in external browser' name is perhaps a misnomer, as it is actually attempting to *open* the file (which, generally, is opened via browser). We could potentially serve the file via Live Preview, but it would also mean an added dependency to this extension

**Comment by eitsupi** [comment]
unstale
