### ISSUE TITLE
Help Server: support CRAN like repositories e.g. RSPM

### ISSUE THREAD

**Issue by eitsupi** [REditorSupport/vscode-R#876]
**Is your feature request related to a problem? Please describe.**

The "Install CRAN Package" button shown in the help panel will not work if we have set up a CRAN-like repository such as RStudio Package Manager ([RStudio Public Package Manger](https://packagemanager.rstudio.com/client/)).

![image](https://user-images.githubusercontent.com/50911393/142872049-85395278-2254-4098-bfd4-f7e9533920e2.png)

**Describe the solution you'd like**

[As implemented in The R-universe system](https://ropensci.r-universe.dev/man), it may be desirable to get the information from the URL of `/src/contrib/PACKAGES` instead of the current `/web/packages/available_packages_by_date.html`.

https://cran.r-project.org/src/contrib/PACKAGES
https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/PACKAGES
https://ropensci.r-universe.dev/src/contrib/PACKAGES

**Comment by ManuelHentschel** [comment]
Makes sense.

Apparently, the file `/src/contrib/PACKAGES` does not include the title (or description) field, and `/stats/descriptions` does not seem to work with normal CRAN mirrors. Do you know a clean way to get these fields from other repos?

**Comment by eitsupi** [comment]
I did some research, but unfortunately I couldn't find a unified method to get the Title or Discription.

The `utils::available.packages` function seems to get and use `/src/contrib/PACKAGES` (or `/bin/windows/contrib/PACKAGES` or `/bin/macosx/contrib/PACKAGES`) by the `utils::contrib.url` function, so RSPM and R-universe seem to implement these (and specialized APIs).

Reference

- https://stackoverflow.com/questions/11560865/list-and-description-of-all-packages-in-cran-from-within-r
- https://github.com/r-universe-org/cranlike-server
- https://github.com/r-hub/pkgsearch (The `pkgsearch` package seems to use R-hub instead of CRAN for searching infomation.)

**Comment by ManuelHentschel** [comment]
I guess then we can just try all three URLs `/web/packages/available_packages_by_date.html`, `/stats/descriptions`, and `/src/contrib/PACKAGES`, and see how much information we get.

I'll try to implement this in the next couple of days!
