### ISSUE TITLE
Workspace always empty

### ISSUE THREAD

**Issue by maillot-jaune** [REditorSupport/vscode-R#879]
For some time now my **workspace is always empty**. I think (but I'm not sure) that this behavior started when Visual Code started to show "Session contents restored from [...]" whenever I start it up. If I remember correctly, R did not start until I submitted the first line of code. Now, R starts when I start VS Code with this "Session Contents restored from [...]". Screenshot:

![code](https://user-images.githubusercontent.com/4822979/143200265-9d9dd4ca-9d77-4da3-8622-c092315b66a9.png)

I'm using the latest development build of [version is 2.3.3](https://github.com/REditorSupport/vscode-R/releases/tag/latest). This is because my plot window didn't update correctly [#640](https://github.com/REditorSupport/vscode-R/issues?q=640) 

This is my session:

    > sessionInfo()
    R version 4.1.2 (2021-11-01)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Linux Mint 20.1
    
    Matrix products: default
    BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
    LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
    
    locale:
    [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    [5] LC_MONETARY=sv_SE.UTF-8    LC_MESSAGES=en_US.UTF-8   
    [7] LC_PAPER=sv_SE.UTF-8       LC_NAME=C                 
    [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    loaded via a namespace (and not attached):
    [1] compiler_4.1.2

**Comment by renkun-ken** [comment]
Does it work if you click the status bar item to attach to the R session?

**Comment by maillot-jaune** [comment]
The status bar says "R: (not attached)", and when I click that, i get this in my R terminal window:

    Error in .vsc.attach() : could not find function ".vsc.attach"

**Comment by renkun-ken** [comment]
If the session is created via "R: Create R terminal", does attach work properly?

Looks like the *recovered* session did not source the session watcher init script at all.

**Comment by maillot-jaune** [comment]
Yes. I closed the current terminal and used the command palette to start a new. Then the workspace populated correctly. And it still does after restarting VS Code. So that's good! 

I still get the "Session contents restored from [...]" in the terminal though. When I start VS Code. But maybe that's intended behavior?

**Comment by renkun-ken** [comment]
You might want to turn off `terminal.integrated.enablePersistentSessions` in vscode settings.
