### ISSUE TITLE
Workspace follow environment (e.g. `browse`, `debug`)

### ISSUE THREAD

**Issue by kklot** [REditorSupport/vscode-R#881]
**Is your feature request related to a problem? Please describe.**

- Workspace and object pop up show that in the global environment, not where the code is at.

**Describe the solution you'd like**

When user use debugging functions, such as `browse`, `debugonce`,... the workspace should show what objects exist in that environment.

**Comment by renkun-ken** [comment]
This is debugger features. Already supported by [https://github.com/ManuelHentschel/VSCode-R-Debugger] in a debugger session.

**Comment by kklot** [comment]
may be my debug workflow is different/incorrect, but `VSCode-R-Debugger` is really inconvenient (I don't want to run the whole file, new terminal, no code highlight).
