### ISSUE TITLE
Code excecution in radian terminal randomly stops

### ISSUE THREAD

**Issue by martinottmann** [REditorSupport/vscode-R#882]
Hello there,

I have set up radian to run R code - and I did so successfully as R generally works in VSCode. However, fairly regularly some code snippets do not get executed when I hit 'control enter' or - when working with a RMarkdown document - I press the "Run Chunk" button. The code is sent to radian but then it appears to not get executed. The terminal doesn't even show the next line. Sometimes it helps to send the next command (or just even some random letter sequence plus hitting enter) and then the code gets executed. But sometimes even that doesn't help and I have to kill the terminal and start a new one. There is no error message of any sort.

It's not a code issue as it is never the same code snippet that causes this problem. The issue appears with any kind of code (e.g., loading data, plotting, basic data transformations). Also, when working on a RMarkdown document, I have no issues knitting it - even if I just encountered the problem described above with some code block contained therein.

Below are my relevant R settings in VSCode:
```
"r.sessionWatcher": true,
"r.rterm.windows": "C:\\\\Users\\\\XXXXX\\\\AppData\\\\Roaming\\\\Python\\\\Python37\\\\Scripts\\\\radian.exe",
"r.lsp.path": "C:\\Program Files\\R\\R-4.1.0\\bin\\R.exe",
"r.lsp.debug": false,
"r.rterm.option": [],
"r.plot.useHttpgd": true,
"r.session.viewers.viewColumn": {
        "viewer": "Active",
        "pageViewer": "Two",
        "view": "Active"
    },
"r.alwaysUseActiveTerminal": true,
"r.bracketedPaste": true
```

I searched far and wide for a solution but wasn't able to get to the bottom of this (or even solve it). Any help or pointers of how to fix is very much welcome.

I'm using:
- Windows 10
- VSCode 1.62.3
- R 4.1.0
- vscode-R 2.3.3

**Comment by randy3k** [comment]
I just realize that it could be a trailing new line issue: see [this](https://github.com/randy3k/radian/issues/324#issuecomment-987025410) for discussion.
