### ISSUE TITLE
Rmarkdown failed to preview and knit : pandoc was not found

### ISSUE THREAD

**Issue by LeiGuo0812** [REditorSupport/vscode-R#886]
**Describe the bug**
1. The same rmd file knit and preview worked well in Rstudio, but not in vscode.  After pressing vscode Open Preview, an error was thrown : 

����: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).

ִֹͣ��

[VSC-R] Untitled-1.rmd process exited with exit code 1

2. When cliking knit r, nothing happend. The Ctrl + Shift + k shortcut also didn't work. 

## Do you want to fix by self? (We hope your help!)

No, I don't know how vscode works.

(If related)setting.json

```json
// R.exe path for windows
"r.rterm.windows": "D:\Softwares\Anaconda3\Scripts\radian.exe",

// R path for Mac OS X
"r.rterm.mac": "",

// R path for Linux
"r.rterm.linux": "",

// R command line options (i.e: --vanilla)
"r.rterm.option": [--no-save --no-restore],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": false,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Screenshots**
![image](https://user-images.githubusercontent.com/50766698/143685284-45f5a634-7103-4616-b874-ddd0a3acdcc8.png)

**Environment (please complete the following information):**

 
- VSCode Version: 1.62.3 (user setup)
   Electron: 13.5.2
   Chrome: 91.0.4472.164
   Node.js: 14.16.0
   V8: 9.1.269.39-electron.0
   OS: Windows_NT x64 10.0.22000
- R Version: 4.1.1
- vscode-R version: 2.3.3

**Comment by renkun-ken** [comment]
pandoc is bundled with RStudio installation.

You need to go to <https://github.com/jgm/pandoc/releases>, download the pandoc installer for your OS and install it on your machine. Make sure `pandoc` is in your `PATH` environment variable so that `rmarkdown::pandoc_version()` could find it.

**Comment by LeiGuo0812** [comment]
Thanks for your rapid reply. I installed pandoc, but It seems that it still doesn't work. I'm not sure if I have configured it correctly.
![image](https://user-images.githubusercontent.com/50766698/143686300-849313e5-1f64-4b30-943f-50cc918033ee.png)

**Comment by renkun-ken** [comment]
Do you restart vscode to update the terminal environment variables?

Could you type pandoc in vscode terminal and see if the command works?

**Comment by LeiGuo0812** [comment]
Oh, thanks. After restarting vscode, the environment variable had taken effect. 
However, I believe I encountered the same problem as described in #830 : After clicking "open preview to side", the HTML was successfully knitted, but the side window was blank.  
And still, clicking "knit rmd" or using shortcuts doesn't cause any reaction.
![image](https://user-images.githubusercontent.com/50766698/143690488-08a26c43-9055-41be-bb70-1f23ef0defa5.png)

**Comment by renkun-ken** [comment]
Does `rmarkdown::render()` or `rmarkdown::run()` work and properly produce a document or preview?

**Comment by LeiGuo0812** [comment]
Yes, I tried `rmarkdown::render()` in R terminal and it knitted properly. (The parameters have to be set manually).

**Comment by renkun-ken** [comment]
Would you like to go to the Output pane and check out the log of "R Markdown" and see if the knitting process works properly?

**Comment by LeiGuo0812** [comment]
![image](https://user-images.githubusercontent.com/50766698/143733834-0ed86a9e-7f82-4a14-879b-cea99792523c.png)
Yes, I opened the terminal and Output panel, and it seems that the knitting process is only presented in the terminal but not the Output pane. I'm not sure if I checked this correctly.

**Comment by renkun-ken** [comment]
Are you sure you open the preview by clicking the "Open Preview to the Side" button?

<img width="169" alt="image" src="https://user-images.githubusercontent.com/4662568/143734855-fe56c921-2e77-49e6-95f1-94273860120c.png">

It uses a background process instead of sending code to terminal.

**Comment by LeiGuo0812** [comment]
![image](https://user-images.githubusercontent.com/50766698/143735642-e1620f67-59a6-4e56-90d9-da03f21cb9eb.png)
Oh, sorry! I clicked the Preview button and there was information output in the Output panel. It seems that the document was properly knitted.

**Comment by renkun-ken** [comment]
When I tried the same, the output looks normal:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4662568/143762951-fe694db8-180a-48ba-9ec9-fd657a6407f5.png">

Would you like to open the file that appears in the log between `---vsc---` in an external web browser and see if it is rendered properly?

If so, would you like to execute "Developer: Open WebView Developer Tools" and see if the empty WebView has anything wrong on initialization?

**Comment by LeiGuo0812** [comment]
Yes,  the temporal file could be open and is rendered properly. And as you expected, the Consele panel in WebView Developer Tools listed a bunch of errors, haha:
![image](https://user-images.githubusercontent.com/50766698/143767679-fc05bbc3-e96c-43bf-8eed-5975eca906d6.png)
![image](https://user-images.githubusercontent.com/50766698/143767684-e426d9cf-cc4d-432c-bc28-7db76fe77a8a.png)

**Comment by renkun-ken** [comment]
It is weired that from the "R Markdown" log in the Output pane, the output file is `C:/Users/.../4525...84a.html` but the log in the WebView developer panel shows that it was trying to open `D:/Users/.../4525...84a.html`. The inconsistency should explain why the webview is blank.

**Comment by LeiGuo0812** [comment]
Oh yes, I totally agree. I tried in another computer with the same configuration (by account synchrony), and repeated the error. Is it possible that my R and Vscode are both installed in D:/ ?

**Comment by ManuelHentschel** [comment]
> Is it possible that my R and Vscode are both installed in D:/ ?

Vscode usually installs into the user directory (seems to be C: in your setup) and your R installation seems to be on in D:\software. In principle, this should not be a problem for the preview, but it can sometimes be hard to find these bugs.

Have you tried previewing a file that is saved somewhere on your D: drive?

**Comment by LeiGuo0812** [comment]
Well, actually my vscode and R are both in D:\Softwares. I tried to create a new rmd file under D:\ and it produced exactly the same error.

**Comment by renkun-ken** [comment]
I think I found the problem. The use of `Uri.parse()` does not automatically handles Windows path. We should use `Uri.file()` instead.

```
vscode.Uri.parse('C:/Users/ken/test.rmd')
w {scheme: 'C', authority: '', path: '/Users/ken/test.rmd', query: '', fragment: '', …}
_formatted:null
_fsPath:null
authority:''
fragment:''
path:'/Users/ken/test.rmd'
query:''
scheme:'C'
```

**Comment by renkun-ken** [comment]
@LeiGuo0812 Would you like to try [the test build](https://github.com/REditorSupport/vscode-R/suites/4485538898/artifacts/119481956) from #888?

**Comment by LeiGuo0812** [comment]
> @LeiGuo0812 Would you like to try [the test build](https://github.com/REditorSupport/vscode-R/suites/4485538898/artifacts/119481956) from #888?

Oh, sure. Happy to help. But I don't know what to do after downloading the file.

**Comment by renkun-ken** [comment]
Just extract the vsix file from the zip, and in VS Code, run command "Extensions: Install from VSIX" and choose the vsix file, the test build will be installed. Now restart your vscode, retry, and see if the problem still persists.

**Comment by LeiGuo0812** [comment]
Brilliant!  The preview problem is solved! Now my rmd file can be correctly previewed. The auto-refresh also worked well.
![image](https://user-images.githubusercontent.com/50766698/143773544-1ebcc38f-ac9d-4b4b-8719-70ec663f7741.png)

**Comment by LeiGuo0812** [comment]
Thank you very much for your effort. yyds!
