### ISSUE TITLE
Dataset object remains in `promise` class in Workspace unless it gets called

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#889]
I've found that dataset object remains in `promise` status in Workspace when loaded with `data()` function until it explicitly gets called.

1. Run the following code in a clean R session:

``` r
library(ggplot2)
data(mpg)
```

2. Execute `R: Focus on Workspace View`

3. Check the class of `mpg`. It is displayed as `mpg (promise)`.

* Note: At this point, `mpg$` doesn't trigger column-name auto-suggestion.

4. Run the following in R console:

``` r
class(mpg)
#> [1] "tbl_df"     "tbl"        "data.frame"
```

5. Execute `R: Focus on Workspace View`

6. Check the class of `mpg`. It is displayed as `mpg (tbl_df)`.

* Note: This time, `mpg$` triggers column-name auto-suggestion.

**Comment by ElianHugh** [comment]
Promise objects are intentionally kept as promises until evaluated by the user. It looks like when loading mpg, it is lazy loaded until interacted with. Is this unexpected behaviour?

**Comment by jooyoungseo** [comment]
Yes, I think any dataset when loaded with `data()` (e.g., `data(airquality)` is kept as promises until evaluated. For end-user who uses auto-suggestion for dataset column names, however, this is inconvenient. Because the users will have to evaluate the object to benefit from the auto-suggestion.

As you know, you can trigger column name suggestion in `RStudio` quite lazily. I was wondering if we could come up with any workaround.

**Comment by ElianHugh** [comment]
Hmmm, we used to grab the names of promise objects, but this meant that they were effectively never lazy loaded. This was especially annoying for stuff like delayedAssign, which would essentially have no effect

**Comment by renkun-ken** [comment]
The workspace viewer respects the evaluation status of objects in the global environment, i.e. if the object is a promise, we won't force it. Maybe we could allow user to opt-in to force evaluation?
