### ISSUE TITLE
Support Cairo as graphics backend

### ISSUE THREAD

**Issue by ShixiangWang** [REditorSupport/vscode-R#891]
**Is your feature request related to a problem? Please describe.**

I cannot plot due to no X11 available:

```r
unable to start device PNGwarning messages from top-level task callback 'vsc.plot'
Warning message:
In (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
  unable to open connection to X11 display ''
```

**Describe the solution you'd like**

In RStudio, we can set the backend.

![image](https://user-images.githubusercontent.com/25057508/143843156-258c566b-6f3a-4909-9073-df535abf11ce.png)

Is it possible to add such support in VSCode R plugin?

**Comment by renkun-ken** [comment]
I recommend that you use the [httpgd plot viewer](https://github.com/REditorSupport/vscode-R/wiki/Plot-viewer#svg-in-plot-viewer).

**Comment by ShixiangWang** [comment]
@renkun-ken Thank you, Kun. I'll take a try.

**Comment by ShixiangWang** [comment]
It works.
