### ISSUE TITLE
R markdown: Knit button and keyboard knit shortcut doesn't work

### ISSUE THREAD

**Issue by LeiGuo0812** [REditorSupport/vscode-R#895]
**Describe the bug**
I use the same rmd file as in #886 in this report. (The preview problem has been fixed.) When the setting "Knit: Use Background Process" is on, the knit button and keyboard shortcut (Ctrl + Shift + k) don't work. The output panel of R markdown showed nothing. But after turning off the "Knit: Use Background Process", the rmd file can be knitted correctly.

**To Reproduce**

1. turn on "Knit: Use Background Process"
2. Click on 'Knit'

## Do you want to fix by self? (We hope your help!)

No, I don't know how vscode works.

```jsonc
// R.exe path for windows
"r.rterm.windows": "D:\Softwares\Anaconda3\Scripts\radian.exe",

// R path for Mac OS X
"r.rterm.mac": "",

// R path for Linux
"r.rterm.linux": "",

// R command line options (i.e: --vanilla)
"r.rterm.option": [--no-save --no-restore],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": false,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**
The rmd file can be knitted correctly when "Knit: Use Background Process" is on.

**Screenshots**
"Knit: Use Background Process" is on:
![image](https://user-images.githubusercontent.com/50766698/144170907-4359a4cc-64ac-4b20-8641-63be31e24648.png)

"Knit: Use Background Process" is off:
![image](https://user-images.githubusercontent.com/50766698/144170971-ec8c0485-0fb7-4ba6-a915-b953c46a476a.png)

**Environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.62.3 (user setup)
- R Version: 4.1.1
- vscode-R version: v2.3.4

**Comment by Matt17BR** [comment]
Came here to see if anybody had the same issue. I can fully reproduce this, but on a different setup.

**Environment (please complete the following information):**
- OS: Manjaro Linux
- VSCode Version: 1.62.3
- R Version: 4.1.2
- vscode-R version: v2.3.4

**Comment by renkun-ken** [comment]
I cannot reproduce this problem.

Do you mean that when you turn on `r.rmarkdown.knit.useBackgroundProcess`, the "Knit" button still sends code to terminal rather than renders the document with a background process?

**Comment by LeiGuo0812** [comment]
Not really. If turning on `r.rmarkdown.knit.useBackgroundProcess`, clicking the "Knit" button or using the keyboard shortcut doesn't do anything (Not sending code to terminal, nor print information on Output panel or knit the file). 
If turning off  `r.rmarkdown.knit.useBackgroundProcess`, the "Knit" button and shortcuts work well (Sending codes to terminal and knit the file correctly).

**Comment by ElianHugh** [comment]
Interesting, I can't replicate this on Manjaro Linux. 

Could you please post any relevant logs when knitting (i.e. R Markdown output stream, developer console)? Developer console can be accessed via the default shortcut Ctrl + Shift + I

**Comment by Matt17BR** [comment]
> Could you please post any relevant logs when knitting (i.e. R Markdown output stream, developer console)? Developer console can be accessed via the default shortcut Ctrl + Shift + I

The output stream for R Markdown is completely empty, but I've attached the dev console log below:
[vscode-app-1638644003826.log](https://github.com/REditorSupport/vscode-R/files/7654469/vscode-app-1638644003826.log)

**Comment by ElianHugh** [comment]
Thank you for the log! It looks like the issue is with the knit command detection. Out of curiosity, are you opening a workspace to knit these files, or are you opening the file on its own?

**Comment by LeiGuo0812** [comment]
> Thank you for the log! It looks like the issue is with the knit command detection. Out of curiosity, are you opening a workspace to knit these files, or are you opening the file on its own?

Thanks, I think I understand the problem. This issue only occurs when I open the file on its own. When I have set a workspace, the knit button and shortcut worked well.

**Comment by Matt17BR** [comment]
> Thank you for the log! It looks like the issue is with the knit command detection. Out of curiosity, are you opening a workspace to knit these files, or are you opening the file on its own?

Before reporting the bug, I'd only ever tried to knit after opening an R markdown file. I've tried to load a workspace induced by the file I'm working on, but that seems to do nothing either unlike for @LeiGuo0812. The workspace is correctly loaded by vscode-R and all objects are loaded, but CTRL+Shift+K and the graphical shortcut seem to be unresponsive.

**Comment by LeiGuo0812** [comment]
> Before reporting the bug, I'd only ever tried to knit after opening an R markdown file. I've tried to load a workspace induced by the file I'm working on, but that seems to do nothing either unlike for @LeiGuo0812. The workspace is correctly saved and loaded by vscode-R and all objects are present, but CTRL+Shift+K to knit and the graphical shortcut seem to be unresponsive.

I believe that it's just a misunderstanding. The workspace Elian is talking about is the working path set by the explorer in the sidebar, not the .rdata file. After setting the directory in explorer, the button should work.

**Comment by renkun-ken** [comment]
@ElianHugh Looks like we should check the usage of workspace folder in the rmarkdown part of code.

**Comment by Matt17BR** [comment]
> > Before reporting the bug, I'd only ever tried to knit after opening an R markdown file. I've tried to load a workspace induced by the file I'm working on, but that seems to do nothing either unlike for @LeiGuo0812. The workspace is correctly saved and loaded by vscode-R and all objects are present, but CTRL+Shift+K to knit and the graphical shortcut seem to be unresponsive.
> 
> I believe that it's just a misunderstanding. The workspace Elian is talking about is the working path set by the explorer in the sidebar, not the .rdata file. After setting the directory in explorer, the button should work.

Ah, sorry for the misunderstanding, you're exactly correct. Setting a directory on the sidebar indeed does the trick!
