### ISSUE TITLE
Wrong closing brackets on selected text

### ISSUE THREAD

**Issue by kklot** [REditorSupport/vscode-R#900]
**Describe the bug**
Select a `word` and press `(`, it appears as `(wor)d)`

**To Reproduce**
File types tested are `.R` and `.Rmd`

**Expected behavior**
the result should be `(word)`

**Environment (please complete the following information):**

- OS: macOS,
- VSCode Version: 1.62.3
- R Version: 4.0.1
- vscode-R version: v2.3.4

**Comment by renkun-ken** [comment]
I cannot reproduce it. Does it happen with other files?

**Comment by kklot** [comment]
Found out the reason, because I have vscodevim + `.vimrc` that contains some unusual keyboard shortcuts. Disable using `.vimrc` fixed this.
