### ISSUE TITLE
use plotly can't not download png

### ISSUE THREAD

**Issue by Achuan-2** [REditorSupport/vscode-R#904]
it reported
> sorry there was a problem downloading your snapshot!

![image](https://user-images.githubusercontent.com/60436214/144952717-bdc8818f-eaa0-4d40-b907-9102da4a68ea.png)

**Comment by renkun-ken** [comment]
The error is

>Refused to load the image 'blob:vscode-webview://c15349f8-4fc2-46c7-92bd-8a579babbe0c/41bc9abb-07de-4a7f-9d49-bf1c159ac03f' because it violates the following Content Security Policy directive: "default-src https: data: filesystem:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

I add the following to the Content Security Policy to the WebView

```
img-src 'self' blob: data:;
```

"take snapshot" now seems to work without signaling an error, but it does not trigger a file save dialog anyway.

@ElianHugh @ManuelHentschel Do you know if it is possible for the WebView to capture the request to download a file on the client?

**Comment by renkun-ken** [comment]
Might be useful: https://github.com/microsoft/vscode/issues/98101

**Comment by KatlehoJordan** [comment]
I have just seen this same issue.

In VS Code dev container, using `R`, run the following:
```R
library(plotly)
plot_ly(midwest, x = ~percollege, color = ~state, type = "box")
```

Get the error in the screenshot below:
![Screenshot 2022-12-11 104639](https://user-images.githubusercontent.com/89082001/206896822-ffc4a314-fbf2-459d-b4a1-32fc40fb084e.png)

**Comment by kiarashFarzad** [comment]
I am also having the same problem; any solutions yet?
