### ISSUE TITLE
Cannot install vscode-R extension in MacOS Mojave

### ISSUE THREAD

**Issue by emezir** [REditorSupport/vscode-R#906]
Install R (>= 3.4.0) = OK
Install languageserver in R = OK
Install the R extension for Visual Studio Code = NOK!!!
nothing cones up

**Comment by renkun-ken** [comment]
Is there an error message?

**Comment by renkun-ken** [comment]
> tried from chrome from safari...

Are you trying to install it in vscode in web browser? It is not supported.
