### ISSUE TITLE
Open in the browser when shiny.launch.browser is TRUE

### ISSUE THREAD

**Issue by ColinFay** [REditorSupport/vscode-R#907]
**Is your feature request related to a problem? Please describe.**

One current point of friction when using R with VSCode is that the `options(shiny.launch.browser = TRUE)` doesn't open the shiny app in the default web browser — the default behavior in the RStudio IDE. https://shiny.rstudio.com/reference/shiny/0.14/shiny-options.html

Right now it opens in a VSCode tab, and you have to pop it out to get in the browser. That's kind of not complex per se, but you end up doing that a lot __and__ with a lot of useless tabs in VSCode you have to manually close. 

**Describe the solution you'd like**

I'd love the shiny app to be opened in the web browser whenever `shiny.launch.browser` is TRUE.

**Describe alternatives you've considered**

I don't think there are any alternatives so far.

**Comment by renkun-ken** [comment]
Thanks for reporting this. I didn't know such an option. Will take a look at this. If we can identify if a browser request is from a shiny app, we could read this option so that it will be open externally.

**Comment by renkun-ken** [comment]
From the documentation at <https://shiny.rstudio.com/reference/shiny/0.14/runApp.html>, the definition of `shiny.launch.browser` seems to be open browser in general rather than toggling open in external browser or open in RStudio, i.e. if it is `FALSE` then it will not try to open any window to show the shiny app.

**Comment by renkun-ken** [comment]
Looks like inside the `browser` call, we could check if `environmentName(parent.env(parent.frame(2))) == "shiny") to identify a shiny app calling browser.

**Comment by renkun-ken** [comment]
In you case, you might want to put the following in your VS Code settings:

```json
"r.session.viewers.viewColumn": {
        "browser": "Disable"
    }
```

Then all browser requests will open web browser.

**Comment by ColinFay** [comment]
> From the documentation at shiny.rstudio.com/reference/shiny/0.14/runApp.html, the definition of shiny.launch.browser seems to be open browser in general rather than toggling open in external browser or open in RStudio, i.e. if it is FALSE then it will not try to open any window to show the shiny app.

Yes, shiny.launch.browser = TRUE opens the default web browser, shiny.launch.browser = FALSE will not open anything (it currently works as expected), and you can also do `options(shiny.launch.browser = rstudioapi::viewer)` to force the view in the RStudio viewer. Not sure if this last should be supported or not, and how? 

 > In you case, you might want to put the following in your VS Code settings:

Awesome, thanks a lot !! 

> Looks like inside the browser call, we could check if environmentName(parent.env(parent.frame(2))) == "shiny") to identify a shiny app calling browser.

In case it can help, what shiny does for displaying the app is : 

+ `launch.browser = getOption('shiny.launch.browser', interactive()),` => if the option is not set, it defaults to TRUE in interactive sessions https://github.com/rstudio/shiny/blob/main/R/runapp.R#L89

+ if it's a function (when `options(shiny.launch.browser = rstudioapi::viewer)` ), it uses this function, otherwise it calls `browseURL` https://github.com/rstudio/shiny/blob/main/R/runapp.R#L364

+ `browseURL()` in VSCode will open the local content in itself, otherwise in the browser

```r
> utils::browseURL("https://google.com")
VSCode WebView only supports showing local http content.
Opening in external browser...
Browsing https://google.com
```

Whereas opening a local html will render inside VSCode (hence the opening of the local shiny app inside VSCode).

**Comment by renkun-ken** [comment]
You could use `options(shiny.launch.browser = function(...) .vsc.browser(...))` to force viewing it inside VS Code.

**Comment by renkun-ken** [comment]
Also, you could use 

```r
options(shiny.launch.browser = function(...) .vsc.browser(..., viewer = FALSE))
```

to force opening shiny apps in external web browser.
