### ISSUE TITLE
htmlwidget with media elements not working in WebView

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#908]
Some htmlwidgets might contain multimedia elements. They are currently not working properly in WebView.

For example, `{gm}` can be used to generate music scores and playable audio with the following demo code:

```r
library(gm)

m <- 
  # initialize a Music object
  Music() +
  # add a 4/4 time signature
  Meter(4, 4) +
  # add a musical line of four quarter notes
  Line(list("C5", "D5", "E5", "F5"), list(1, 1, 1, 1))

show(m, to = c("score", "audio"))  
```

Its HTML is simple:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<div>
  <p>
    <img src="file12eef7447e4b9.png" style="max-width: 100%;"/>
  </p>
  <p>
    <audio controls>
      <source src="file12eef7447e4b9.mp3" type="audio/mp3"/>
    </audio>
  </p>
</div>
</body>
</html>
```

From the developer tools, the URIs seems to be correctly replaced with `vscode-resource` scheme but still not working.

**Comment by ElianHugh** [comment]
Without testing, it looks like we might need to expand the watched tags in `observer.js`. 

```
 ​const​ ​watchedTags​ ​=​ ​[ 
 ​  ​"IMG"​, 
 ​  ​"A"​, 
 ​  ​"LINK"​, 
 ​  ​"SCRIPT" 
 ​]​;
```

**Comment by renkun-ken** [comment]
I tried adding `"SOURCE"` to `watchedTags` but it does not work. Looks like it is a known limitation (https://github.com/microsoft/vscode/issues/54097). There are some other notebook-related issues regarding video/audio: https://github.com/microsoft/vscode/issues/118275, https://github.com/microsoft/vscode/issues/119127.

**Comment by ElianHugh** [comment]
Perhaps it would be useful to show a vscode notification stating that opening in a browser is required (if a multimedia element is found)?

**Comment by renkun-ken** [comment]
`<media>` element has been supported since 1.72. Closing.
