### ISSUE TITLE
Self-managed R session will not attach 

### ISSUE THREAD

**Issue by wcerfgba** [REditorSupport/vscode-R#909]
**Describe the bug**
I have a subdirectory in my project containing an renv and I would like to start a radian session in that directory and attach it to vscode-R. I have followed the instructions in the wiki and appended the relevant line to the `.Rprofile` created by `renv::init()`. I then run `r` in a terminal in vscode, and I can see that the status bar updates and has detected the R session. However, when I click the R widget in the status bar, instead of attaching to my running R session in my subdirectory, it is creating a new R session in the project directory instead. The following output is observed in the new terminal:

```
^[[200~.vsc.attach()^[[201~
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Platform: x86_64-pc-linux-gnu (64-bit)

r$> .vsc.attach()                          
Error in .vsc.attach() : could not find function ".vsc.attach"

r$> getwd()                                
[1] "/home/jpreston/Sync/work/phd"   # this is the project root

r$>  
``` 

**To Reproduce**

1. Open terminal
2. Navigate to subdirectory in project directory
3. Start R
4. Initialise an renv
5. Exit R
6. Amend the renv .Rprofile as per wiki instructions
7. Start R again
8. Observe that renv is loaded, and the VSCode R status bar widget updates to detect the R process
9. Click the R widget in status bar
10. Observe a new terminal is started but this is starting a new R process, not attaching to existing process

## Do you want to fix by self? (We hope your help!)

Yes

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

Not sure

**Expected behavior**
Expected R terminal to attach to existing R process in subdirectory.

**Environment (please complete the following information):**

- OS: Linux
- VSCode Version: 1.62.3
- R Version: 4.1.2
- vscode-R version: 2.3.4

**Comment by renkun-ken** [comment]
In your case, you need to turn on `r.alwaysUseActiveTerminal` so that you could use the R terminal you started manually.

**Comment by renkun-ken** [comment]
Since the renv is in a subdirectory, then it is only effective if you start your R terminal from that subdirectory. If you don't have `r.alwaysUseActiveTerminal` enabled, vscode-R will start an R terminal from the workspace folder rather than the subdirectory, then the renv will not effect.

**Comment by wcerfgba** [comment]
Aha that's it! Thank you :) I'd suggest adding a note about this to the [R Session watcher wiki page](https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher) :)
