### ISSUE TITLE
Plot viewer shows 404

### ISSUE THREAD

**Issue by lboller** [REditorSupport/vscode-R#916]
**Describe the bug**
The httpgd plot viewer in VSCode shows a 404 error. Opening the URL in a browser shows the viewer without any issues.

**Screenshots**

![](https://user-images.githubusercontent.com/1630748/146041136-ecb78d36-e406-4143-b412-4608343183cc.png)

**Environment (please complete the following information):**

- OS: macOS
- VSCode Version: 1.64.0-insider
- R Version: 4.1.2 (ARM)
- vscode-R version: 2.3.4

**Comment by psobolewskiPhD** [comment]
Hmm. I'm also arm64, Insider 1.64, vscode-R 2.3.4, and see no issues
```
library(ggplot2)
ggplot(mtcars) +
      geom_point(aes(x = wt, y = mpg, colour = factor(gear)))
```
My `httpgd` version is 1.2.1

**Comment by lboller** [comment]
Upgrading `httpgd` from 1.1.1 resolved this for me.
