### ISSUE TITLE
Merge request for vscode-R wiki

### ISSUE THREAD

**Issue by 18kimn** [REditorSupport/vscode-R#917]
I've made some updates to docs in responses to #910 and #777, and filled out the R language server page with more detail and a table a contents. I've cloned the wiki and edited the docs on my own machine, but it seems I can't open a PR to file the suggested changes. Would an admin be able to take a look and provide feedback / revise and merge? 

The forked wiki can be found at https://github.com/18kimn/vscode-R/wiki

Summary of changes
- added markdown linting configuration; linted/formatted files 
- added comment suggesting pandoc/rmarkdown installation
- expanded notes on rlanguageservice
- added a few recommendations to the recommended extensions page
- moved "keyboard shortcuts" to the "configuration" section on the sidebar

**Comment by renkun-ken** [comment]
Thanks for working on the wiki!

I disabled "Restrict editing to users in teams with push access only" in the repo settings, and the wiki should be editable now. Would you like to merge your changes?

**Comment by 18kimn** [comment]
thank you! I've just tried to push up my changes to the wiki, but got a 403:

```
remote: Permission to REditorSupport/vscode-R.wiki.git denied to 18kimn.
fatal: unable to access 'https://github.com/REditorSupport/vscode-R.wiki.git/': The requested URL returned error: 403
```

I see the "Edit" and "New" buttons on the wiki now, but I still don't seem to have push access. Would you be able to check if there is a setting that can allow this? I'm not really sure how this works; if there is no such setting I can just copy and paste the content

**Comment by renkun-ken** [comment]
Can you edit the wiki pages directly on the web pages?

**Comment by 18kimn** [comment]
yep, I'll do that!

**Comment by 18kimn** [comment]
finished updating! closing this issue --
