### ISSUE TITLE
can  not view pciture

### ISSUE THREAD

**Issue by xiachenrui** [REditorSupport/vscode-R#919]
**Describe the bug**
I can not see the picture when I plot in remote server

**To Reproduce**
When I press 'Enter & Ctrl', R code can be run in R terminal, but when I try plotting, I can not see the picture
Instead , a 'Rplots.pdf' occur in my workspace but it is empty

## Do you want to fix by self? (We hope your help!)
No, I check it for long time 

(If related)setting.json

```jsonc
// R.exe path for windows


// R path for Mac OS X


// R path for Linux
"r.rterm.linux": "/home/xiacr/software/R/R-4.1.1/bin/R",

// R command line options (i.e: --vanilla)
"r.rterm.option": --no-restore

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**
pop a picture windows 

**Screenshots**
![image-20211216201424778](https://gitee.com/huhansan666666/picture/raw/master/img/image-20211216201424778.png)

**Environment (please complete the following information):**

- OS: ubuntu
- VSCode Version: 1.63.1
- R Version: 4.1.1
- vscode-R version: 2.3.4

**Additional context**

**Comment by xiachenrui** [comment]
And when I checked the settings.json. I find "terminalPath":"/home/xiacr/miniconda3/envs/R41/bin/R","interpreterPath":"/home/xiacr/miniconda3/envs/R41/bin/R"}, This R path was not usable now ,how can I change them? I tryed to modify settings.json, but it would change back again.

**Comment by renkun-ken** [comment]
>I find "terminalPath":"/home/xiacr/miniconda3/envs/R41/bin/R","interpreterPath":"/home/xiacr/miniconda3/envs/R41/bin/R"}, 

These settings are not for R extension.

You could install `httpgd` package and enable `r.plot.useHttpgd`.

**Comment by xiachenrui** [comment]
Thanks, I found annother problem,
- R interactive terminal in VSCODE is alyways choose systerm R(3.6.3) as its kernel even I specify "r.rterm.linux": "/home/xiacr/software/R/R-4.1.1/bin/R",
- When I use 'Always Use Active Terminal' option , it can not plot as which I discribed before

**Comment by xiachenrui** [comment]
![image-20211216224326302](https://gitee.com/huhansan666666/picture/raw/master/img/20211216224326.png)

**Comment by renkun-ken** [comment]
In your image, it is not `R` but `radian`, then you have to set the following settings:

```json
"r.rpath.linux": "/home/xiacr/software/R/R-4.1.1/bin/R",
"r.rterm.linux": "/home/xiacr/path/to/your/radian",
"r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--r-binary=/home/xiacr/software/R/R-4.1.1/bin/R"
    ]
```

You need to adjust the path to your `radian`.

**Comment by xiachenrui** [comment]
OK, thanks a lot for your kind reply

**Comment by xiachenrui** [comment]
One more question, I read your [wonderful blog](https://renkun.me/2019/12/26/writing-r-in-vscode-interacting-with-an-r-session/), You can use a tmux to keep the R session even you leave R studio, but when I follow yout tutorial and set  "r.alwaysUseActiveTerminal": true. I open a tmux shell and then open R terminal. Then I find I can run code in the terminal, but can not plot or use `View()`
![image-20211216234918879](https://gitee.com/huhansan666666/picture/raw/master/img/20211216234918.png)

**Comment by renkun-ken** [comment]
To work with self-managed R terminals, please follow the instructions at <https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions>.

**Comment by xiachenrui** [comment]
Thanks a lot !!! I can plot with my new R session in tmux now! But I find 'R workspace' show nothing about this R session. Could you please tell me how to fix this? Sorry for bother you again.
![image-20211217110932269](https://gitee.com/huhansan666666/picture/raw/master/img/image-20211217110932269.png)

**Comment by renkun-ken** [comment]
Did you evaluate `a = 1` lines? "R workspace" viewer shows the current global variables in the attached R session, while "Outline" shows the variable defined in the R document (not necessarily evaluated).

**Comment by xiachenrui** [comment]
oh！I think I get your point, when I run `.vsc.attach() ` in R terminal in tmux, I find  'R workspace' work correctly. Thanks again for your kind help !!!
