### ISSUE TITLE
Dot `.` will be duplicated if suggestions are allowed for words beginning with a dot `.` in RMarkdown R code chunks

### ISSUE THREAD

**Issue by eitsupi** [REditorSupport/vscode-R#926]
**Describe the bug**

For example, if I want to enter the option `.groups` for the function `dplyr::summarise()`, and I select the suggested candidate on a `.Rmd` file, I will get `..groups`, which has a duplicated dot.

In `.R` file (works fine)

![Rfile](https://user-images.githubusercontent.com/50911393/147637164-18d2862f-d38b-4837-8ef2-afeaf122b0b6.gif)

In `.Rmd` file

![Rmdfile](https://user-images.githubusercontent.com/50911393/147637251-a4cd3d33-1f8b-4f6b-9e63-71766e3f3545.gif)

**To Reproduce**

See the videos above.

setting.json

```jsonc
"editor.tabCompletion": "on"
```

**Environment (please complete the following information):**

- OS: Windows + Remote Ubuntu (Docker Container)
- VSCode Version: 1.63.2
- R Version: 4.1.2
- vscode-R version: 2.3.5

**Comment by andycraig** [comment]
I wonder if this is related to #821, which is also has strange extra characters appearing autocompletions in Rmd files.

**Comment by eitsupi** [comment]
Thank you for pointing this out.
This seems to be a duplicate of #821.
