### ISSUE TITLE
Arguments section is empty in hover view for some functions

### ISSUE THREAD

**Issue by eitsupi** [REditorSupport/vscode-R#927]
**Describe the bug**

Hover the cursor over a function to display the function's help.
For some functions, the Arguments section does not seem to be displayed.

I first found this behavior with `shiny::fluidPage()`, but when I checked other functions, the same phenomenon seems to occur with `ggplot2::geom_bar()`, etc.

`shiny::fluidPage()`'s hover (Arguments section is empty)

<img width="521" alt="fluidpage" src="https://user-images.githubusercontent.com/50911393/147643620-1adf3909-141c-46fd-8950-9c16d156af5b.png">

`shiny::sidebarPanel()`'s hover (Correct display)

<img width="521" alt="sidebarpanel" src="https://user-images.githubusercontent.com/50911393/147643700-09aff432-faca-4761-af7b-270112728741.png">

`shiny::fluidPage()`'s help page (Correct display)

<img width="749" alt="fluidpage_help" src="https://user-images.githubusercontent.com/50911393/147643783-1ab31cd2-aa9a-4eaf-989b-c2fe56fdc499.png">

`ggplot2::geom_bar()`'s hover (Arguments section is empty)

<img width="523" alt="geom_bar" src="https://user-images.githubusercontent.com/50911393/147643915-65dc08d8-1cac-40fe-8867-2f04207782f9.png">

**Environment (please complete the following information):**

- OS: Windows + Remote Ubuntu (Docker Container)
- VSCode Version: 1.63.2
- R Version: 4.1.2
- vscode-R version: 2.3.5

**Comment by atusy** [comment]
This is a limitation of REditorSupport/languageserver , which converts the help content to GitHub-flavored markdown (gfm).

Before the conversion by Pandoc, the content of Arguments is an HTML table.
The table can be converted to gfm table iff each cells of the table contains a single paragraph.
However, some documents describes the arguments with multiple paragraphs or other block elements such as a bullet list.
In such a case, the HTML table is kept as is in the output gfm.
Then, VS code ignores the HTML table.

I will try convert table to other format by Lua filter and will open a PR to the **languageserver** package.

https://github.com/REditorSupport/languageserver/blob/97e1cbbbc98b914e2fde44fdbaa69b9fd3578102/R/utils.R#L730

**Comment by eitsupi** [comment]
Is there any chance that REditorSupport/languageserver#534 will be merged?

**Comment by renkun-ken** [comment]
Merged. Thanks!
