### ISSUE TITLE
Links in R Help panel fail intermittently

### ISSUE THREAD

**Issue by HVoltBb** [REditorSupport/vscode-R#929]
**Describe the bug**
The links in R help page in VS code only work sometimes. When it breaks, none of the links work, and the navigation button also does nothing.

If I close the help page, and reopen the help page, the links will work fine. Obviously, there is a bug somewhere. 

**To Reproduce**
As of now, I can't provide a reproducible case. It happens intermitently. When I have more info, I'll try to update this issue report.

I am using the Insiders version of VS code on Win10.

## Do you want to fix by self? (We hope your help!)

No

**Comment by gowerc** [comment]
When you say the don't work, as in they do nothing when you click them or you get a 404 or what happens sorry? I'm wondering if it's a sort of timeout issue, does the problem occour if you haven't touched the help file for a while ?

**Comment by HVoltBb** [comment]
When I click on them, nothing happens, just like clicking on plain text, no 404.

I am reporting back here. I left out an important piece in the original post. Those cases happened only in the Insider edition of vscode. When I switched back to the stable version, everything worked fine.
