### ISSUE TITLE
Rmarkdown inside the VSCode-R cannot render Chinese character in figure/table caption correctly

### ISSUE THREAD

**Issue by milanglacier** [REditorSupport/vscode-R#933]
**Describe the bug**

The rmarkdown within the VSCode cannot render Chinese character correctly.
(after clicking the `knit rmd` button, the corresponding pdf renders UTF8 codes instead of correct Chinese character).

However, the same document can be rendered correctly if I open an terminal and type

```bash
R
rmarkdown::render("file.rmd")
```
So I think there's nothing to do with the encoding of my source file. The `render()` function takes "UTF8" encoding as default option.

**To Reproduce**

Suppose we have the following rmd file `file.rmd`:

~~~text
---
title: "minimal example"
author: "Kobe Bryant"
output: html_document    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, eval = T)
```


Chinese character in the main article can be rendered normally.
(正文区的中文可以正确的渲染)

Figure legends cannot be rendered normally.

```{r, fig.cap = "科比"}

plot(1:5, 1:5)

```
~~~

```jsonc


// R path for Mac OS X
"r.rterm.mac": "/usr/local/bin/R",

// R command line options (i.e: --vanilla)
"r.rterm.option": ["--no-save", "--no-restore"],

// An optional encoding to pass to R when executing the file, i.e. 'source(FILE, encoding=ENCODING)'
"r.source.encoding": "UTF-8",

// Keeping focus when running
"r.source.focus": "editor",

// Use active terminal for all commands, rather than creating a new R terminal
"r.alwaysUseActiveTerminal": false,

// Use bracketed paste mode
"r.bracketedPaste": true,

// Enable R session watcher
"r.sessionWatcher": true,

// Delay in milliseconds before sending each line to rterm (only applies if r.bracketedPaste is false)
"r.rtermSendDelay": 8,
```

**Expected behavior**

The Chinese character within a figure caption can be rendered correctly.

**Screenshots**
The **correct** html document (via calling rmarkdown in terminal) should be:

<img width="600" alt="Screen Shot 2022-01-05 at 11 45 51 PM" src="https://user-images.githubusercontent.com/45728125/148329773-5de229da-df56-4584-9f2f-4f4f9f3cf5f0.png">

What rendered by VSCode-R extension  `knit rmd` button (**wrong**) is:

<img width="600" alt="Screen Shot 2022-01-05 at 11 47 05 PM" src="https://user-images.githubusercontent.com/45728125/148329869-643ee965-a0b8-4670-b0f6-f396e69b40e3.png">

**Environment (please complete the following information):**

- OS: [macOS 12.0.1, Apple M1 MacBook Air]
- VSCode Version: [1.63.2(universal)]
- R Version: [4.1.2(aarch64)]
- vscode-R version: [2.3.5]

**Comment by achey2016** [comment]
I believe I have the same problem with French accents.

My system uses the following locale in the terminal : 

```
$ locale
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL=
```

In the interactive R console, I have 

```
> Sys.getlocale()
[1] "fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8"
```

But for some reason, vscode-R knit and preview don't inherit this setting, and a R chunk 
with `Sys.getlocale()` will output

```
[1] "C"
```

As a workaround, adding `Sys.setlocale(category = "LC_ALL", locale = "fr_FR.UTF-8")` in the setup chunk of my Rmd 
file solved my accent problem.
