### ISSUE TITLE
Is it possible to just preview RMarkdown's text sections without actually knitting the whole file?

### ISSUE THREAD

**Issue by MrJGao** [REditorSupport/vscode-R#935]
I always find myself working on a large RMarkdown file that knitting the whole thing will take a long time. But, sometimes, I just want to preview the Math equations and some text to see if they are looking good. Currently, seems every time I click "Open Preview to Side", it has to knit everything. I can set `eval=FALSE` in the knit option to prevent that, but I wonder if there's some feature that already has been done. Thank you!

**Comment by milanglacier** [comment]
You already know you can simply change the knife::options to eval = F.
I think it is already a very convenient way.

**Comment by MrJGao** [comment]
Ok, thank you, I just wonder if there's any button or something, haha, never mind, I'll close this issue.
