### ISSUE TITLE
I cannot change the workspace of R

### ISSUE THREAD

**Issue by fabiolexcastro** [REditorSupport/vscode-R#937]
Hi, 

I have installed the plugging, but I need to use the lastest R version (now 4.1.2), but Visual Studio Code just recognize the 4.0.4 version. I have tried in the config sesion to change it, but it's not working. 

Right now I have these features: 

- Microsoft windows 10
- R version 4.1.2
- RStudio lastest version 

![image](https://user-images.githubusercontent.com/20421819/148797265-cad216ca-eb7f-4ee7-a4cd-c13a9b95749b.png)

Thanks a lot. 

¡Happy new year!

Best regards, 
Fabio Castro
@ambarja

**Comment by renkun-ken** [comment]
Did you "Save version number in registry" when you install the latest version of R?

If not, then you might want to reinstall R 4.1.2 with version number saved to registry as suggested in the [wiki](https://github.com/REditorSupport/vscode-R/wiki/Installation:-Windows#vscode-r).

**Comment by fabiolexcastro** [comment]
Thanks for the quick reply. 

I have r installed R and restarted R and Visual Studio Code, but it's not work. 

![image](https://user-images.githubusercontent.com/20421819/148805553-1df8ad6c-3995-4b8a-a6ba-606b62a7b276.png)

I appreciate any comment about it. 

Best regards, 
Fabio Castro

**Comment by fabiolexcastro** [comment]
![image](https://user-images.githubusercontent.com/20421819/148805755-da6690e7-e0b3-4c9b-b617-bc60a867310d.png)

**Comment by renkun-ken** [comment]
Would you like to check your `PATH` environment variable and see if the old R's directory is included in it?

**Comment by fabiolexcastro** [comment]
Hi Renkun-Ken, 

Thanks a lot for you quick reply. 

Yes, the path environments is ok. But it did'nt work. 

![image](https://user-images.githubusercontent.com/20421819/148943948-107fe6bc-0e4a-4770-a83b-a1368a4a566d.png)

Best regards, 
F

**Comment by renkun-ken** [comment]
You could show the `PATH` environment variable by running the following in R:

```r
Sys.getenv("PATH")
```
