### ISSUE TITLE
Keep output pane hidden when knitting .rmd documents.

### ISSUE THREAD

**Issue by BerriJ** [REditorSupport/vscode-R#940]
When knitting .rmd Documents the "output" pane always pops up. This is annoying since it steals screen real estate. Most of the time (successful compilations) the progress popup which comes up is sufficient to track the knitting progress. The following gif demonstrates what I mean:

![Peek 2022-01-11 11-24](https://user-images.githubusercontent.com/37799358/148925744-0c320815-5652-4910-951f-8c7baf5a6957.gif)

It would be nice to have an option to disable the popup of the output pane or disable that popup completely (one can still use CTRL+K CTRL + H to toggle output visibility).

Btw, thanks so much for this extension. I use it every day and it's awesome!

**Comment by renkun-ken** [comment]
`r.rmarkdown.knit.focusOutputChannel` should be what you are looking for.

**Comment by BerriJ** [comment]
Thank you so much, Ken. And sorry for not digging deep enough myself.
