### ISSUE TITLE
tibble objects and pillar/cli formatting lead to terminal formatting/line wrap problems 

### ISSUE THREAD

**Issue by mkoohafkan** [REditorSupport/vscode-R#942]
**Describe the bug**

printing `tibble` objects results in weird formatting, timestamps (see #878). Changing option `width` (e.g., `options(width = 150)` does not have consistent results and generally does not resolve issue, nor does the `Alt+Z` terminal word wrap toggle. Printing of timings has also been observed in e.g., printed outputs from the `targets` package, so this may also be an interaction with formatting produced by the `cli` package.

**To Reproduce**
R code to reproduce the behavior:

```{r}
library(tibble)

print(mtcars)

print(as_tibble(mtcars))
```

**Expected behavior**
`tibble` objects should not cause timings to print or introduce line wrapping independent of terminal settings.

**Screenshots**

![image](https://user-images.githubusercontent.com/4790348/149224275-26e6185b-97b5-4f22-a2d4-49e26ba91322.png)
![image](https://user-images.githubusercontent.com/4790348/149224320-d184eb68-1ee9-4ad1-8e93-b05972f57afa.png)

**Environment (please complete the following information):**

- OS: Windows 10
- VSCode Version: 1.63.2
- R Version: 4.1.2
- vscode-R version: 2.3.5

**Comment by renkun-ken** [comment]
You are using the official R terminal. It is not smart enough to update its terminal width automatically. Therefore, the table will only print according to `getOption("width")` which is fixed on startup.

I recommend that you use [radian](https://github.com/randy3k/radian#features) which "automatically adjust to terminal width", or otherwise you have to manually adjust the terminal width via e.g. `options(width = 200)`.

**Comment by mkoohafkan** [comment]
setting `options()` appears to work for normal R objects but does not seem to work with objects formatted by `pillar` or statements printed using `cli` (which is most of the tidyverse as well as a variety of utility packages including `devtools`, `usethis`, and `targets`). This also does not explain the printing of timings.

radian is not a great solution for me as I routinely use `reticulate` and conda environments, my understanding is that I would need to install radian on every conda  environment.

**Comment by mkoohafkan** [comment]
> These are ANSI colors, which your terminal apparently cannot interpret. I am not sure why they are turned on, but nevertheless you can turn them off by setting an R option or an env var: https://cli.r-lib.org/reference/num_ansi_colors.html

_Originally posted by @gaborcsardi in https://github.com/r-lib/cli/issues/412#issuecomment-1033057602_

This fix works, and for now I have put `Sys.setenv(NO_COLOR = 1L)` in my .Rprofile. Would it be possible for vscode-R to set this automatically if the official R terminal is detected?

**Comment by renkun-ken** [comment]
You could try adding the following in your R profile:

```r
addTaskCallback(function(...) {
  width <- Sys.getenv("COLUMNS")
  if (nzchar(width)) {
    options(width = as.integer(width))
  }
  TRUE
}, name = "auto.width")
```

After each top-level expression is evaluated, the width option will be adjusted to terminal width.

**Comment by mkoohafkan** [comment]
Thanks @renkun-ken I am not that concerned about the width issue. The ANSI color code printing is a big issue though as it makes printing `tibble` objects and reading any messages from packages that use `cli` very difficult.

**Comment by renkun-ken** [comment]
You could put the following in your `.Rprofile`:

```r
if (interactive() && Sys.getenv("RADIAN_VERSION") == "") {
  Sys.setenv(NO_COLOR = 1L)
  addTaskCallback(function(...) {
    width <- Sys.getenv("COLUMNS")
    if (nzchar(width)) {
      options(width = as.integer(width))
    }
    TRUE
  }, name = "auto.width")
  invisible()
}
```

**Comment by mkoohafkan** [comment]
Thanks, I'll try that out. Note that `cli` already has logic for detecting the console, but perhaps something about the way vscode interacts with the terminal causes `cli` to think it's not a "dumb" terminal. I wonder if that could be fixed to allow `cli` to correctly detect the terminal type.

**Comment by eitsupi** [comment]
FYI, I cannot reproduce this problem in my environment (Windows or Linux).

![image](https://user-images.githubusercontent.com/50911393/153162721-3d5e7cd1-b913-4279-abab-f43e1d7985e9.png)

**Comment by mkoohafkan** [comment]
Thanks, I can reproduce it on Windows Server 2016 and a virtual Windows 10 machine, but not on my standard Win10 laptop. I will investigate further.

`Sys.getenv("COLUMNS")` is always `""` on my server, VM, and standard laptop. However, setting the `width` option manually is working as expected now that I have turned off  `cli` ANSI colors.

**Comment by gaborcsardi** [comment]
FYI, I will not follow this thread any more, but if it turns out that the cli ANSI detection should be improved, please ping me in the cli repo. Thanks!

**Comment by mz-bayer** [comment]
I have the same problem with ANSI color codes when I use `Rterm`. It appeared somewhere in between November and December 2021 and goes away when adding `Sys.setenv(NO_COLOR = 1L)` to `.Rprofile`.

Here is a reprex along with a screenshot:

``` r
library("cli")

sessionInfo()
ansi_palette_show()
ansi_palette_show()
```
![cli_3 2 0](https://user-images.githubusercontent.com/93116954/154236158-6476b67d-7a27-4281-b7a1-17cf682a345b.png)

Note that the palette looks different for each call and the spacing is garbled.

**Comment by mz-bayer** [comment]
I have to correct myself: setting `Sys.setenv(NO_COLOR = 1L)` only resolved some of the problems. When I read a large file using `readr::read_tsv`, the output is still garbled:

![r_ansi_read_tsv](https://user-images.githubusercontent.com/93116954/154243324-7dee718a-3855-4324-8f70-6eec2e8fa10c.png)

I have only obfuscated the filename and the number of rows and columns. See how parts of the ANSI codes (`[`, numbers and `m`) as well as blank lines appear at random places. This looks different every time - sometimes I even get black characters on a black background (or white on white).

**Comment by mz-bayer** [comment]
Interestingly, this problem only occurs when I work on the virtual Windows 10 machine of a customer. On my local system (Windows 10 as well) it works fine.

On both system, I removed all R libraries, installed only the package `cli` before testing:

``` text
      Package Version
          cli   3.2.0
         glue   1.6.1
 translations   4.1.2
```

I also used a minimal set of VS Code settings :

``` json
{
    "workbench.colorTheme": "Default Dark+",
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "editor.wordWrap": "wordWrapColumn",
    "editor.wrappingIndent": "indent",
    "telemetry.telemetryLevel": "off"
}
```

**Comment by mkoohafkan** [comment]
@mz-bayer Are you accessing the virtual machine via Windows Remote Desktop Connection? I encounter the issue when accessing a Windows Server 2016 VM via Remote Desktop Connection, I'm wondering if that's the commonality here.

**Comment by mz-bayer** [comment]
@mkoohafkan I share your thoughts. In my case, I connect via Citrix Workspace, and I suspect VMware plays a role too (there is an icon for VMware Tools in my toolbar).

Unfortunately, the whole setup is all a bit intransparent.
