### ISSUE TITLE
Provide a option to set the `Rscript` path running the R package development task

### ISSUE THREAD

**Issue by Yunuuuu** [REditorSupport/vscode-R#948]
**Describe the solution you'd like**
Sometimes we used different R version to develop a R package, it's better to provide a option (such as `r.rscript.mac`,  `r.rscript.linux` and  `r.rscript.windows` like `r.rpath` and `r.rterm`) to run the vscode task concerning R development in specific R version. Such as following R development task:
```
`Rscript -e "devtools::build()`
`Rscript -e "devtools::check()`
`Rscript -e "devtools::document()`
`Rscript -e "devtools::test()`
```

**Comment by Yunuuuu** [comment]
whether it's better to only provide a option to set `r version` like what rstudio do ?

**Comment by gowerc** [comment]
What would you expect the UI of this to be ? I'm wondering if it would make sense to handle this like the python extensions do where it shows the selected interpretor in the bar at the bottom and you can click on that to change the current interpretor?

That being said, unlike python the vast vast majority of people only run a single version of R. Do you definitely need an interactive selection. Vscode supports you writing your own project specific tasks which can inherit other tasks and change the config slightly, i.e. you can pre-specify new tasks to run using different versions of R.

@renkun-ken apologies I was trying to look through the code but am really struggling to see where the "r build" tasks are actually defined. Any pointers would be appreciated

**Comment by Yunuuuu** [comment]
Hi, gowerc, sorry for the delay reply. I don't have any idea about the UI but just want a option to configure this setting in the same way of `r.rpath.windows` or `r.rterm.windows`, as the vscode-r task would  come into a failure in this condition where we sometimes never put the `R bin path` into our `PATH`. I don't know it's necessary to make a interactive selection for the convenience of the change of the the interpreter of `R task`. In my view, I prefer what `RStudio` do, which provide a option to set whole `R folder path` like this:
![image](https://user-images.githubusercontent.com/19575010/152780382-161c4093-a94e-4c6e-a107-fc9235be3708.png)

I may not take this in a complete view, I don't know whether it's necessary to split the `R execute path` of `rpath` and `rscript` into different `R version`, any idea about these?

**Comment by renkun-ken** [comment]
#994 now uses R path specified via `r.rpath.*` settings. Now you can put your settings per workspace to customize the R path to run tasks. In fact, all rscripts now consistently respect the `r.rpath` settings.
