### ISSUE TITLE
Allow multiple different R terminals to be defined

### ISSUE THREAD

**Issue by hongooi73** [REditorSupport/vscode-R#953]
It would be nice if we could have more than one type of terminal that could be opened, eg

- Windows native
- WSL
- Remote (SSH or container)

The use case is that when developing packages, I often get tripped up by differences in behaviour in R between Windows and Linux. In particular, `file.path` will strip off a trailing slash on the former, but not the latter. This has led to bugs creeping in.

To avoid this, I'd like to be able to run my package tests in both the Windows and Linux environments. VSCode goes halfway there by letting you do remote development in WSL, SSH and a container. From what I can tell, however, the R extension only lets you have one type of terminal: whatever is defined by the environment you're in. So if I want to work in WSL, for example, I can't use the regular Ctrl-Enter shortcut to submit code; instead I have to copy-and-paste with Ctrl-C and Ctrl-V like a barbarian.

 If I could tell VScode-R to open up a terminal in WSL, or in a container, and have that treated the same as how the terminal currently works, that would be awesome.

**Comment by eitsupi** [comment]
I think this use case is already possible by opening the same folder on different VSCode instances on a Windows machine with commands such as "Open Folder in WSL", "Reopen Folders in Windows" and "Reopen in Container".

**Comment by hongooi73** [comment]
Ah, I didn't know about that feature. It seems to do the job pretty well. Thanks!

**Comment by gowerc** [comment]
@hongooi73  can this be closed then ?

**Comment by hongooi73** [comment]
Yeah, I'll close it.
