### ISSUE TITLE
Autocomplete variable names within ggplot2 aes() calls

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#966]
Would there be any plan for the following support in VSCode R as well?

> Given the code:

``` r
library(ggplot2)
ggplot(mtcars, aes(...))
```

> It would be useful if we provided autocompletion results for the column names from mtcars within the aesthetic mapping.

* Retrieved from [rstudio/rstudio#8444](https://github.com/rstudio/rstudio/issues/8444)

**Comment by renkun-ken** [comment]
unstale
