### ISSUE TITLE
Errors after setup .lintr in the HOME directory

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#967]
Here is the error after setup .lintr file in the HOME directory on MacBook. 
The error highlight always on the first character of the first line. 
```
Failed to run diagnostics: callr subprocess failed: Malformed config file, ensure it ends in a newline
  Invalid DCF format.
Regular lines must have a tag.
Offending lines start with:
  )lintr
```

**Comment by eitsupi** [comment]
The format of the .lintr file may be incorrect, as described in the error. Can you upload the .lintr file?

**Comment by Fred-Wu** [comment]
> The format of the .lintr file may be incorrect, as described in the error. Can you upload the .lintr file?

I just copied the one from Wiki. 

```
linters: with_defaults(
  object_usage_linter = NULL,
  commented_code_linter = NULL
)
```

**Comment by eitsupi** [comment]
That format is not correct. (That is, the wiki description is not correct.)
It is in the form of a dcf, which is correctly written as follows:

```dcf
linters: with_defaults(
  object_usage_linter = NULL,
  commented_code_linter = NULL
  )

```

See if you can read the file with R's `read.dcf()` function.

```R
read.dcf(".lintr")                                                                 
#> Error in read.dcf(".lintr") : Line starting ') ...' is malformed!
```

**Comment by Fred-Wu** [comment]
> That format is not correct. (That is, the wiki description is not correct.) It is in the form of a dcf, which is correctly written as follows:
> 
> ```
> linters: with_defaults(
>   object_usage_linter = NULL,
>   commented_code_linter = NULL
>   )
> ```
> 
> or
> 
> ```
> linters: with_defaults(
>   object_usage_linter = NULL,
>   commented_code_linter = NULL)
> ```
> 
> See if you can read the file with R's `read.dcf()` function.
> 
> ```r
> read.dcf(".lintr")                                                                 
> #> Error in read.dcf(".lintr") : Line starting ') ...' is malformed!
> ```

Thank you. It works now.

**Comment by py9mrg** [comment]
Hello @Fred-Wu  I have just spent an hour trying to get a .lintr file to work and finally managed it after reading this issue - thanks! But I think you should re-open this issue for a couple of reasons.

1. I couldn't get the above correct examples to work at first:
````r
linters: with_defaults(
  object_usage_linter = NULL,
  commented_code_linter = NULL)
````

would not give me an error with `read.dcf` but still wouldn't work, I had to actually add an explicit new line:
````r
linters: with_defaults(
  object_usage_linter = NULL,
  commented_code_linter = NULL)


````
I only realised this because, even though a manual run of `read.dcf` was error free, I'd still get the error message over at the problems tab of vs code. Also, you may have included the explicit new line in your example, but in writing this comment I had to use 2 new lines to get github to actually show the final new line!

2. This should be added to the documentation? Probably here in the vscode-r documentation, but also at https://github.com/REditorSupport/languageserver#linters

**Comment by mcmuffin6o** [comment]
> That format is not correct. (That is, the wiki description is not correct.) It is in the form of a dcf, which is correctly written as follows:
> 
> ```
> linters: with_defaults(
>   object_usage_linter = NULL,
>   commented_code_linter = NULL
>   )
> ```
> 
> or
> 
> ```
> linters: with_defaults(
>   object_usage_linter = NULL,
>   commented_code_linter = NULL)
> ```
> 
> See if you can read the file with R's `read.dcf()` function.
> 
> ```r
> read.dcf(".lintr")                                                                 
> #> Error in read.dcf(".lintr") : Line starting ') ...' is malformed!
> ```

Good lord, who came up with such a terrible syntax???

**Comment by victorhartman** [comment]
To anyone (on windows) running into this issue. Make sure the document is set to LF (unix) instead of CR LF (windows). Only this fixed it for me.

**Comment by francisbarton** [comment]
For anyone else finding this problem, it might be your DESCRIPTION file (if you're authoring a package) or any other config file that uses the dcf format.

I was thrown off scent by the fact I was getting this error when I tried to run `lintr` - but it wasn't the .lintr file that was the issue (it was my DESCRIPTION)
