### ISSUE TITLE
R Plot shows Status: 404 Reason: Not Found

### ISSUE THREAD

**Issue by EvoLandEco** [REditorSupport/vscode-R#971]
I have installed and enabled httpgd in extension settings:
![image](https://user-images.githubusercontent.com/57348932/152639983-6b37df0b-9649-4b9f-b841-5df2e0f40786.png)
Then I tried to plot something, the R Plot panel appeared but cannot show any plot:
![image](https://user-images.githubusercontent.com/57348932/152640037-a8d0763f-7d06-4095-9d53-23a4331828c7.png)

**Comment by eitsupi** [comment]
Duplicate of  #916, #923, #947.

**Comment by EvoLandEco** [comment]
Thx for the quick reply, it solved the issue
