### ISSUE TITLE
Plot viewer not working with radian.

### ISSUE THREAD

**Issue by postylem** [REditorSupport/vscode-R#973]
**The issue**
When I use radian as my default R Plots stubbornly use X11, rather than showing up in VSCode.

**To Reproduce**

1. Install languageserver package, then, vscode-R.
2. Install radian (with `pip install -U radian`).  
3. Set to use radian as R to use`"r.rterm.mac": "/usr/local/bin/radian"`
4. Run "R: Create R terminal" to attach an R (radian) session.
5. Make a plot, e.g. `plot(c(1, 2, 3), c(1, 3, 2))`
6. The plot opens in X11 viewer, not inside VSCode.

If I repeat these steps from 3 on, but without setting radian as the rterm, then it works as expected (I get the PNG plot in the VSCode pane).  How can I make this happen with radian too?

all my r `setting.json` settings:
```jsonc
"r.alwaysUseActiveTerminal": true,
"r.bracketedPaste": true,
"r.rterm.mac": "/usr/local/bin/radian",
"r.sessionWatcher": true,
```

my `~/.Rprofile` is empty.

I have tried setting `options(vsc.plot = TRUE)` or "Two" in `~/.Rprofile`, and also tried using httpgd (which is installed), by setting vsc.plot to FALSE, and adding  `"r.plot.useHttpgd": true,` to the settings json.  In both cases it seems to work fine with vanilla R (I can use httpgd with the latter setting), but with radian, I just get the X11 window for plots.

**Expected behavior**
I expect the plot to appear as a PNG (or SVG with httpgd) in VSCode.

**Environment**

- OS: macOS 12.1 (x86)
- VSCode Version: Version: 1.64.0
- R Version: 4.1.0 
- vscode-R version: 2.3.6

Thanks for the really great extension!  I just want to get the plots working (ideally with httpgd and radian).

**Comment by renkun-ken** [comment]
If you use `"r.alwaysUseActiveTerminal": true`, then you need to put the following code in your `.Rprofile` to load vscode-R init script:

```r
 source(file.path(Sys.getenv(
   if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"
 ), ".vscode-R", "init.R"))
```

as suggested at <https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions>.

**Comment by renkun-ken** [comment]
Looks like vscode-R does not manage to attach to your R session. Would you like to see the output of `ls.str(.vsc)`?

**Comment by postylem** [comment]
I think it's attaching fine.
- If I start R (radian) using "R: Create R terminal", then I see that there is an environment loaded called `.vsc` (and running `ls.str(.vsc)` gives a whole lot of stuff... would it be helpful to share it?)
- if I start radian at the command line (in a terminal in VSCode), then `ls.str(.vsc)` results in the error _"Error in ls.str(.vsc) : object '.vsc' not found"_

**Comment by renkun-ken** [comment]
If you start R from vscode terminal, then you need to following <https://github.com/REditorSupport/vscode-R/wiki/R-Session-watcher#advanced-usage-for-self-managed-r-sessions> and put the following in your `~/.Rprofile`:

```r
source(file.path(Sys.getenv(
   if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"
 ), ".vscode-R", "init.R"))
```

**Comment by postylem** [comment]
Thanks. I understand that if I start R from vscode terminal I need to set it up to run the init script as you point out, but this shouldn't affect when I'm starting R using "R: Create R terminal", should it (and in any case, this doesn't seem to change anything with respect to the plots using X11)?

**Comment by alexkyllo** [comment]
I was having this issue--plots were rendering in an external X11 window--and it turned out that what I had to do was click on the R: (not attached) in the lower right tray. Once I did that, it started rendering plots inside VS Code.

Before:
![image](https://user-images.githubusercontent.com/2609312/193355496-cecd9b51-10d0-49de-811c-9e52aaacd70b.png)

After:
![image](https://user-images.githubusercontent.com/2609312/193355327-7e03840e-5cc8-4262-9485-2ff0763308a7.png)

**Comment by postylem** [comment]
I have moved to a new computer, with the following setup, and I do not have this problem anymore.  The plots are now rendered in vscode, not X11, without me having to do anything.

- OS: macOS 12.4 (Apple silicon)
- VSCode Version: Version: 1.72.0-insider
- R Version: 4.1.2
- REditorSupport version: 2.5.3
