### ISSUE TITLE
Not able to trigger Web Help Page when there's no R file opened

### ISSUE THREAD

**Issue by shrektan** [REditorSupport/vscode-R#976]
## Reproducible Steps

1. Open any project in VSCode
2. Close all the R files and Web viewers
3. Reload the Window
4. Open a regular terminal, type `radian` or `R` to launch the R terminal
5. Type `?print`, you will find no response. Only after an R script is opened (probably only so it can trigger the R extension), then `?print` can open the help webpage. 

I know it's a very trivial issue but it confuses users when it occurs, as there's no webpage help or the terminal help shown. 

Is it possible to fix this?

Thanks.

**Comment by renkun-ken** [comment]
It is caused by that the vscode-R extension is not activated.

**Comment by shrektan** [comment]
I see. The root folder of my workplace doesn't contain those files. Those files are in the sub-folder. I think that would be the case. Is there any option to enable the vscode-R extension when only sub-folder R-related files exist?

**Comment by renkun-ken** [comment]
Then we might also need 

```
workspaceContains:*/*.{rproj,Rproj,r,R,rd,Rd,rmd,Rmd}
```
