### ISSUE TITLE
Migrating to REditorSupport

### ISSUE THREAD

**Issue by randy3k** [REditorSupport/vscode-R#98]
It’s pity that you are no longer supporting it. Are you interested in moving it to REditorSuport? 

I will see what can be done with the lsp and this package.

**Comment by Ikuyadeu** [comment]
Sorry, about stopping support.
I am considering just send commit authority to you.
Because the current issues and pull requests are not solved.

**Comment by randy3k** [comment]
If you don’t want to migrate it to REditorSupport, we could also crest a fork at REditorSupport and point users to there.

**Comment by randy3k** [comment]
I am writing to see your decision on migrating the repo to REditorSupport. You are already an owner of REditorSupport, so you should be able to transfer it if you want to. On top of that, you may also need to contact Microsoft to change the `publisher` to `REditorSupport`.

**Comment by randy3k** [comment]
@Ikuyadeu 

I just want to reinitiate the discussion on migrating the repo to REditorSupport. 
A similar issue was created for the debugger related packages developed by @ManuelHentschel
https://github.com/ManuelHentschel/vscDebugger/issues/33

By moving the repo to a centralized place, I am sure users will be benefited and get less confused.

**Comment by randy3k** [comment]
By the way, it is impressive to see that @renkun-ken has contributions all around the places.

**Comment by qinwf** [comment]
Unified VS Code R plugin will provide a much better experience. 

You do not need to teach the new users to install A and then B and the C. 

Just get one Plugin and then it will automatically download the `languageserver` R package for you to get all the functionality going. That's it. It is simple.

I simplified some descriptions about how to set up R with VS Code before.

For example:

[old introduction](https://github.com/qinwf/awesome-R/tree/6872431bb731e1ec29c7f6ecdeef8832a2a831ac#2020):


* [VSCode <img class="emoji" alt="heart" src="https://cdn.jsdelivr.net/gh/qinwf/awesome-R@3c66da6e291bcc0520b1649125b0bed750896a9a/heart.png" height="20" align="absmiddle" width="20">](https://code.visualstudio.com/) + [vscode-R](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r) + [vscode-r-lsp](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp) + [languageserver](https://github.com/REditorSupport/languageserver) - VSCode R Langauage Support

[now](https://github.com/qinwf/awesome-R#2020)

* [VSCode](https://code.visualstudio.com/) - [vscode-R](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r) + [vscode-r-lsp](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp) VSCode R Langauage Support

[futuer](https://code.visualstudio.com/)


* [VSCode](https://code.visualstudio.com/) - VSCode R Langauage Support

People are lazy. If there is an easy way to get things done, it will be much easier for them to adopt new technology.

**Comment by renkun-ken** [comment]
As [VSCode-R-Debugger](https://github.com/ManuelHentschel/VSCode-R-Debugger) and [httpgd](https://github.com/nx10/httpgd) are working better, my recommended tools of VSCode R support will become the following:

[VSCode](https://code.visualstudio.com/) + [vscode-R](https://github.com/Ikuyadeu/vscode-R) + [vscode-r-lsp](https://github.com/REditorSupport/vscode-r-lsp) + [languageserver](https://github.com/REditorSupport/languageserver) + [radian](https://github.com/randy3k/radian) + [VSCode-R-Debugger](https://github.com/ManuelHentschel/VSCode-R-Debugger) + [vscDebugger](https://github.com/ManuelHentschel/vscDebugger) + [httpgd](https://github.com/nx10/httpgd).

I can already feel the confusion from the future users.

However, combining them into much fewer projects may not look necessary to me. I think if the VSCode extensions could install their external R package dependencies automatically, e.g. vscode-r-lsp installs languageserver automatically, VSCode-R-Debugger installs vscDebugger automatically. Then a [VSCode R Extension Pack](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r-pack) could make it much simpler.

**Comment by qinwf** [comment]
If there are many plugins, it will be harder for users to do bug reports.

Some users in the past talked about they do not know if a issue is a `vscode-R` issue or `languageserver` issue and do not know where to report the bug for VS Code support for R.

**Comment by renkun-ken** [comment]
@qinwf, Yes, that's the main issue here.

**Comment by renkun-ken** [comment]
Sometimes, however, we are not sure where to put a certain issue. For example, it might first appear to be a bug in radian, but turns out to be a bug in vscode-R sending code to radian. But there's no point to combine radian and vscode-R.

But if it is only for bug reporting confusion, I think we could make a central place for all bug reporting if user is not sure where to put it.

**Comment by randy3k** [comment]
By the way, I fully support merging vscode-R and vscode-r-lsp. Originally I approach @Ikuyadeu to see they wants to add support of languageserver but for some reasons, they created a new project rather to add the feature to vscode-R.

**Comment by renkun-ken** [comment]
If possible, I support merging all vscode-R, vscode-r-lsp, and VSCode-R-Debugger together.

**Comment by Ikuyadeu** [comment]
OK, we can do the following steps like [Java extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack).

1. Move `Ikuyadeu/vscode-r` and `Ikuyadeu/r-extension-pack` to `REditor`.
2. Integrate `vscode-lsp` into `vscode-R`.
3. Add `VSCode-R-Debugger` into `r-extension-pack`.

@renkun-ken , @andycraig Is It OK?

**Comment by renkun-ken** [comment]
@Ikuyadeu Sounds good to me.

VSCode-R-Debugger is still at an early stage, very experimental, and not published to vscode marketplace yet. When it is published at some point, we could put it into r-extension-pack.

@ManuelHentschel do you think if makes sense to integrate the R debugger with vscode-R at some point? We already have a lot of confusion going on here.

**Comment by randy3k** [comment]
Do we also want to change the publishId of `vscode-R` and `r-extension-pack`? As far as I understand, if we change the publishId to REditorSupport, existing users won't be able to update `vscode-R` automatically. Of course, having them under REditorSupport will be less confusing for future users. (I am open to this).

**Comment by Ikuyadeu** [comment]
I don't think it makes much sense to change the publisher.
GitHub's authority movement function changes old repository links to new repository link shortcuts.
Moreover, the change of the link of the repository and the issue described in package.json leads the user to the new repository and the issue.

**Comment by randy3k** [comment]
There is also an administrative consideration. With the current publishId, @Ikuyadeu is the only person who has control of the releases. 

In my opinion, I think it is better to have a least two admins taking charge of the package. (I don't mean @Ikuyadeu is not doing your job adequately, nor I am trying to take away the credits from @Ikuyadeu). From a management perspective, it is always good to have a backup plan. That's also why I have invited @renkun-ken to REditorSupport. In case, I am out of town or for whatever reasons not able to reply, there is always another person to do the job. (It also reminds myself that I should add @renkun-ken as a maintainer of `languageserver`).

**Comment by randy3k** [comment]
Sadly, CRAN only allows one maintainer.

```
Invalid DESCRIPTION:
Authors@R field gives more than one person with maintainer role:
  Randy Lai <randy.cs.lai@gmail.com> [aut, cre]
  Kun Ren <mail@renkun.me> [aut, cre]
```

**Comment by Ikuyadeu** [comment]
So, how are these fixed works?

Quick work
* Move Ikuyadeu/r-extension-pack repo to REditor.
* Move Ikuyadeu/vscode-r repo to REditor.

Small change
* Add vscode-lsp as the vscode-R dependencies

Feature work (Looks large works)
* Integrate vscode-lsp into vscode-R and remove from dependencies

If VSCode-R-Debugger will be published
* Add VSCode-R-Debugger into r-extension-pack

If @Ikuyadeu stoped to replying the new version request
* Publish insider version r-extension-pack and vscode-r as the new publisher

**Comment by renkun-ken** [comment]
I think integrating vscode-r-lsp into vscode-r is fairly easy. I'm interested in putting the two together quickly if nobody is more interested?

**Comment by randy3k** [comment]
@Ikuyadeu Thank you. I agree that moving `r-extension-pack` and `vscode-r` can be done immediately, especially you have already `write` permission to the org. 

> If @Ikuyadeu stoped to replying the new version request
Publish insider version r-extension-pack and vscode-r as the new publisher

Ha, but I guess we'll need your approval in order to change the publishId. Not sure how we could approach you if you were not replying...

@renkun-ken please work on the integration. By the way, there is always one thing that I notice, the [title](https://github.com/Ikuyadeu/vscode-R/blob/master/package.json#L455) in settings in `r` instead of the convention "R". I always wanted to submit a PR to fix it. Perhaps you could fix it while working on the merge.

**Comment by ManuelHentschel** [comment]
> VSCode-R-Debugger is still at an early stage, very experimental, and not published to vscode marketplace yet. When it is published at some point, we could put it into r-extension-pack.
> 
> @ManuelHentschel do you think if makes sense to integrate the R debugger with vscode-R at some point? We already have a lot of confusion going on here.

Once the debugger is as stable as vscode-R, I think this would make sense, since the two extensions don't really have any conflicting overlap and users would profit from having everything inside one extension.

**Comment by Ikuyadeu** [comment]
> Ha, but I guess we'll need your approval in order to change the publishId. Not sure how we could approach you if you were not replying...
My email address is on my profile.

I agree that extension integration benefits both users and extension developers like us.
However, I feel that revoking the copyright has no benefit to me or the user.
Because I have already passed the commit privilege to the key collaborators.
Also, unlike last year, I continue to work on checking really bad code, and continue to publish a new version once a month when features are added to the extension.

**Comment by renkun-ken** [comment]
@Ikuyadeu @randy3k 

I've done the integration of the language client from vscode-r-lsp at https://github.com/renkun-ken/vscode-R/tree/lsp and it works quite well. Looking forward to the migration to REditorSupport and then I could send a PR.

It's obvious that the two codebases has own licenses and copyright. I'm not sure if there's anything I should do to reflect that, merging the licenses or add some statement somewhere?

**Comment by assignUser** [comment]
@Ikuyadeu @renkun-ken I would like to refresh this discussion in view of #405 . As renkun-len has already done the job of integrating vscode-lsp into vscode-R the move should be pretty straight forward?

**Comment by gvelasq** [comment]
Speaking as a supportive user of the VS Code ecosystem of R extensions and related R packages, I wanted to raise attention to this issue again. I recently co-authored a blog [post](https://ivelasq.rbind.io/blog/vscode-live-share/) and @ivelasq [tweeted](https://twitter.com/ivelasq3/status/1357136366568689664) about our tutorial trialing VS Code and VS Live Share for remote pair programming in R.

However, as the blog post and similar tutorials have outlined, there is a complex set of extensions, packages, and configurations required and these can be daunting for new users. In the spirit of drawing in more R users (novices and experts alike) to try VS Code, and to foster the visibility and longevity of this effort, I support minimizing the number of extensions/packages and separate configurations involved. One step would be to merge this extension into a single organization such as REditorSupport.

Related: https://github.com/Ikuyadeu/vscode-R/issues/496

**Comment by nx10** [comment]
First of all: Thank you all for your amazing work you put in the R/vscode ecosystem. All the packages have matured quite a bit compared to when I first looked at them a couple of years ago.

I just wanted to add to the conversation: If there is anything I can help with to make the httpgd integration in vscode easier for users (maybe as an experimental feature flag), let me know.

If there is interest I am also open to the idea of adding another maintainer to httpgd in the future.

**Comment by eitsupi** [comment]
The other day, when I tried using httpgd as introduced in [this article](https://renkun.me/2020/06/16/using-httpgd-in-vscode-a-web-based-svg-graphics-device/) (by @renkun-ken ), I was surprised at how good the experience was.
But as the article says, I have to edit multiple config files, so I thought it would be great if httpgd worked well without having to edit the config files.

**Comment by randy3k** [comment]
@Ikuyadeu 
Do you have any update about your thoughts in combining some of the tools here?

**Comment by Ikuyadeu** [comment]
I am still in discussions with several companies.
If everything seems difficult, I think one option is to move to REditor.
However, I think it's best to leave it to a commercial organization or a large community as much as possible to keep this repository going for a long time.

I want you to wait another month for new information.

**Comment by randy3k** [comment]
Generally speaking, projects housed by large companies are often killed because of changes in interests.  Say for example Atom. The best way to keep a project alive is to have a group of people who are willing to maintain the project (for free).

**Comment by Ikuyadeu** [comment]
It's been a month, so I'll report on the progress. Our discussion is going in the right direction for the entire community, especially for collaborators.
I'm sorry for the lack of transparency, but please wait for a while.
At the longest, it's likely that my management will be hard from April next year, so I'll handle this as soon as possible.

**Comment by Ikuyadeu** [comment]
After much consideration, I've decided to move this repo to the REditorSupport organization. I have been discussing this matter closely with a few organizations and individuals, both in the private sector and  in the open-source community.
In particular with current collaborators & Randy Lai from REditorSupport & Don Jayamanne (author of the Python and Jupyter extensions in VS Code).
I believe moving this repo under a Github org managed by the R community would benefit the extension.

I plan to start the migration in July.
By then, I will resolve issues with engineering tags and organize the documentation.

**Comment by Ikuyadeu** [comment]
I believe source code will continue to be released under MIT. Also, would it be possible to add Don Jayamanne as a member to the REditorSupport (I believe his expertise in VS Code will prove invaluable for the extension)?

**Comment by randy3k** [comment]
@Ikuyadeu you could go ahead to add him as a member of REditorSupport. (In case you didn't notice, you are one of the owners of the org.)

**Comment by randy3k** [comment]
@Ikuyadeu Additionally I believe that you'll need to contact Vscode marketplace support to change the publisherId to REditorSupport.

**Comment by Ikuyadeu** [comment]
@randy3k That's right, thank you for reminding me.
But since I haven't been involved recently, I felt that approval was necessary.
Anyway, I just invited you.

**Comment by benz0li** [comment]
@Ikuyadeu When moving this repository to the [REditorSupport](https://github.com/REditorSupport) organization, please make sure that the R extension is sill allowed to be [published on OpenVSX](https://open-vsx.org/extension/Ikuyadeu/r) in the future.

[Don Jayamanne](https://github.com/donjayamanne/)'s [Python extension has been stuck at version 2020.10.332292344 on OpenVSX](https://github.com/eclipse/openvsx/issues/241) for months due to its dependency on the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) and the [runtime license](https://github.com/microsoft/vscode-jupyter/blob/e6e8961a9dba5e5929d53c6c943bc17d1e00de5b/extension_license.txt)¹ of the latter.  
ℹ️ ¹This issue has only been resolved recently by https://github.com/microsoft/vscode-jupyter/pull/5812, which may allow updating both Python and Jupyter extensions on OpenVSX.

This is important for all users of [VSCodium](https://github.com/VSCodium/vscodium), [Eclipse Theia](https://github.com/eclipse-theia/theia) and [code-server](https://github.com/cdr/code-server).

**Comment by gvelasq** [comment]
@benz0li, thank you for raising this here. There is an open issue re: verifying this extension in the OpenVSX registry: #524 

The good news is that REditorSupport/vscode-r-lsp#55 is already verified [here](https://open-vsx.org/extension/REditorSupport/r-lsp).

Thank you as well for the update on microsoft/vscode-jupyter#5812. The Jupyter data viewer is one of several solutions being considered in #506, so it's good to see the MIT license.

**Comment by Ikuyadeu** [comment]
Now, I move the vscode-r to the REditor.

In the vscode discussion, I cannot rename the Marketplace owner for current user experience as same as ESLint and TSLint.
However, we can publish this extension via GitHub Actions.

I will only rename the GitHub owner and contents of the LICENCE file to REditor at a later date.

**Comment by randy3k** [comment]
Thanks @Ikuyadeu for initiating the work. Awesome.

I believe that you could contact Microsoft marketplace support to change the publishId (remember that we have done it before for https://github.com/REditorSupport/vscode-r-lsp?)

**Comment by renkun-ken** [comment]
Looks like there are plentiful examples where publishId is changed (e.g. https://github.com/microsoft/vscode/issues/3670). There are also examples of quite popular projects (e.g. https://github.com/prettier/prettier-vscode/issues/41, https://github.com/prettier/prettier/issues/2577). I guess if we are to change it, the earlier, the better.

We could update README to notify what should be done on the user side.

**Comment by renkun-ken** [comment]
I'll raise separate issues to track post-migration issues such as change publishId and integrate vscode-r-lsp into vscode-R.

**Comment by renkun-ken** [comment]
@Ikuyadeu I released the `v2.1.0` to the marketplace via github actions. It looks like the changes in `packages.json` does not have effect on the publisher name on the [marketplace webpage](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r).

Would you like to take a look and see if there are some places to update the publisher name?

**Comment by Ikuyadeu** [comment]
@renkun-ken Thank you for releasing.
It means all of the members can publish our extension at any time.

Looking at the previous discussion, I didn't send an email because I thought it could be reflected without changing the publisher.

OK, I will send you an email again. I will write "I'm going to remove my name because other members mainly maintain it".
Should I write another motivation to change the publisher?

**Comment by renkun-ken** [comment]
>OK, I will send you an email again. I will write "I'm going to remove my name because other members mainly maintain it".
Should I write another motivation to change the publisher?

I think the reason is enough. It is now maintained by REditorSupport and it is thus reasonable to use it as the publisher.

**Comment by Ikuyadeu** [comment]
@renkun-ken Thannk you, I'll send an email to the marketplace, and add cc your outlook address.

**Comment by Ikuyadeu** [comment]
@renkun-ken I submit the issue on https://github.com/microsoft/vsmarketplace/issues/133
Please check here.

**Comment by renkun-ken** [comment]
Thanks for raising the issue!
