### ISSUE TITLE
cannot detect language server

### ISSUE THREAD

**Issue by MrJGao** [REditorSupport/vscode-R#980]
**Describe the bug**
I think it's probably from today's update. So, suddenly, my VSCode cannot detect R language server, and it keeps asking me to install it, although I have done so many times.

![image](https://user-images.githubusercontent.com/7261090/152844600-8b7cd84a-93d8-4526-9f4a-8ba7c78a492f.png)

I'm on my Windows machine. 

Any ideas? Thanks.

**Comment by MrJGao** [comment]
FYI, I just checked, my MacBook works fine.

**Comment by jooyoungseo** [comment]
I have the same issue on my Windows machine. FYI, I use the dev version of `languageserver`.

**Comment by jmwingenroth** [comment]
I have the same issue (also Windows).

**Comment by renkun-ken** [comment]
It is a Windows-specific issue. Should be fixed via 1efd2d4.
