### ISSUE TITLE
[Windows] Stuck with Error: Previewing documents requires the {rmarkdown} package. after following install guide

### ISSUE THREAD

**Issue by MTRNord** [REditorSupport/vscode-R#983]
**Describe the bug**
When I try to preview a r notebook with a fresh R install on windows I cant get the preview to run.

`rmarkdown::run()` works flawless. Using vscode-r previews keeps failing with:

```
[VSC-R] d.matrix_fosdem2022.Rmd process started
Error: Previewing documents requires the {rmarkdown} package.
Execution halted

[VSC-R] d.matrix_fosdem2022.Rmd process exited with exit code 1
```

**To Reproduce**
Steps to reproduce the behaviour:

I am not sure exactly. I simply did a fresh install.

## Do you want to fix by self? (We hope your help!)

No

**Expected behavior**

It should run just fine

**Screenshots**
You can show the keybord contents by pressing `F1` and `Developer: toggle screencast mode`

**Environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.64.1
- R Version: 4.1.2 (2021-11-01)
- vscode-R version: 2.3.8

**Additional context**
My R knowledge is limited, so there is a possibility I am missing something obvious.

**Comment by sergeizv** [comment]
```install.packages("rmarkdown")``` in the R console solves the issue
