### ISSUE TITLE
Using "recently used" tasks launches the wrong task

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#991]
This might be an issue with my local setup as I've been messing around with task settings a lot but it would help if someone else could test if they are getting the same issue or not. 

Essentially if I run the "R: document" task and then re-run it by selecting the "recently used" tasks it launches the wrong task (the build task instead).  I've added a video below to highlight the issue:

https://user-images.githubusercontent.com/8447209/153753282-f81a5c93-69f7-4d2f-81ae-22913380be84.mp4

If the issue isn't repeatable feel free to close as it probably means I've just borked my local config :)

**Comment by renkun-ken** [comment]
When I put `.vscode/tasks.json` with the following content:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "R",
			"label": "R: Build",
			"problemMatcher": []
		},
		{
			"type": "R",
			"label": "R: Document",
			"problemMatcher": []
		}
	]
}
```

then the R tasks will become all identical

<img width="608" alt="image" src="https://user-images.githubusercontent.com/4662568/153765435-f11506e8-99d4-4a81-a904-2a185be363d2.png">

but choosing each will still work properly.

**Comment by renkun-ken** [comment]
And the "recently used" item actually comes from `task.json`:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "R",
			"label": "Test1"
		}
	]
}
```

and the recently used item becomes

<img width="613" alt="image" src="https://user-images.githubusercontent.com/4662568/153765541-e579d07e-a4f3-49af-b545-21abf7fc44e0.png">

**Comment by renkun-ken** [comment]
From the [TaskProvider](https://code.visualstudio.com/api/extension-guides/task-provider#task-provider) documentation, it says 

> resolveTask requires that the same definition object be used.

I tried the following code:

```typescript
public resolveTask(task: vscode.Task): vscode.Task {
        return new vscode.Task(
            task.definition,
            vscode.TaskScope.Workspace,
            'Install',
            'R',
            new vscode.ShellExecution(
                'Rscript',
                [
                    '-e',
                    {
                        value: 'devtools::install()',
                        quoting: vscode.ShellQuoting.Strong
                    }
                ]
            )
        );
    }
```

where the returned `Task` has to use the intput `task.definition` and it works. Looks like we shoud properly implement `resolveTask` to make it work with user customized R tasks in `tasks.json`.
