### ISSUE TITLE
How to manage abandoned issues

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/vscode-R#993]
I am conscious that quite a few of the issues here require user feedback and have been left lingering as the original reporter has not responded.  I am wondering if its worth setting up some form of auto-close bot to handle legacy issues (i.e. if marked as waiting-for-information and the owner doesn't respond within 14 days then close, or something like that) ?

**Comment by eitsupi** [comment]
FYI https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by ElianHugh** [comment]
Coming back to this, I think this would be super helpful in keeping on top of issues

Any thoughts @renkun-ken ?

**Comment by renkun-ken** [comment]
It would be nice to have only active issues open. PR to set up a bot is welcome.

**Comment by benz0li** [comment]
> FYI https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

https://drewdevault.com/2021/10/26/stalebot.html: GitHub stale bot [...] a terrible, horrible, no good, very bad idea.
