### ISSUE TITLE
R Markdown: Insert an R Code Chunk

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#995]
It'd be nice if VSCode-R could provide a feature to quickly insert an R code chunk in Rmd files.

**Comment by jooyoungseo** [comment]
I am closing this one because I found insert an R chunk using code snippet.

**Comment by renkun-ken** [comment]
Yes, pressing `r` will show the snippet.

**Comment by shmuhammad2004** [comment]
Oh, Thank you for mentioning how to add by pressing r.
