### ISSUE TITLE
Insert quoted text only works for the first selected line

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#996]
## Reprex

1. Make `test.Rmd`.
2. Write two lines and select.

    ```
    line1
    line2
    ```

3. Do `Insert Snippet` -> `quote, Insert quoted text`
4. See if the two lines are quoted: only the first line is quoted.

    ```
    > line1
    line2
    ```

**Comment by renkun-ken** [comment]
I doubt if it is supported by snippets? Do you know any snippet that insert characters before each line of selected text?

**Comment by jooyoungseo** [comment]
I think [this issue](https://github.com/microsoft/vscode/issues/92987#issuecomment-601576876) is exactly the same as this request, but it seems tricky.
