### ISSUE TITLE
Insert R code chunk snippet does not work for selected text.

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#997]
## Reprex

1. Make `test.Rmd`.
2. Write two lines and select.

    ```
    x <- 1
    (y <- x + 2)
    ```

3. Do `Insert Snippet` -> `r code chunk, Insert R code chunk`
4. See if the two lines are surrounded with R code chunk fence:  the two lines are completely replaced with R code snippet.

    ````
    ```{r}
    
    ```
    ````

**Comment by Yunuuuu** [comment]
@renkun-ken, sorry, I'm not very familiar with git operation for collaborative work, I'm still studying it. , It may be better to use `"${TM_SELECTED_TEXT}$0"` in [this](https://github.com/REditorSupport/vscode-R/blob/f5d857e2739b1106f059bf8f982cf212ecdda05a/snippets/rmarkdown.json#L84) .
